### ISSUE TITLE
Unable to import wallet/send btc due to encrypted password

### ISSUE THREAD

**Issue by Lenny309** [bitpay/copay#10038]
Hello everyone,

thank you in advance for your help. Any input is greatly appreciated.

In May 2018 I created a Copy wallet with some bitcoins. I have the passphrase (it's correct, I always triple check stuff like that) and I can't remember setting up an encrypted password. I have some changing "password-patterns" that I usually use and none of those (admittedly many) versions works. 

I've already tried pretty much anything I could find to access my bitcoins. I'm currently logged in on my laptop (Win 10 if that's important) but need to move to a new device.

I tried:
- creating a wallet on my new device to just import it -> Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
The derivation path
The wallet service URL
I tried that with Copay and BitPay. I don't know where to go from here.
- sending my bitcoins to a new wallet -> also requires the enrcrypted password
- finding die wallet file to delete it (I've read the encrypted password is saved locally and could be removed this way) but for the love of god I could not find any wallet.dat, .wallet or .key file or anything described online

I have the option to update Copay to the newest version. So far I haven't done it in case anything goes lost or the old version is for some reason better suited for my problem. I have no clue if what I'm saying here even makes sense. (: 

I have googled for like 2 hours and haven't found a solution so far. Maybe you can help me?

Thank you!

**Comment by BGalliotti** [comment]
Hello @Lenny309 

> creating a wallet on my new device to just import it -> Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
>The derivation path
The wallet service URL
I tried that with Copay and BitPay. I don't know where to go from here.

This error is due to:
- Any of the reasons mentioned
- Importing a wallet that was not created with the Copay/BitPay app

A recommendation for this error is to [create the wallet (instead of importing it) specifying the recovery phrase](https://github.com/bitpay/copay/issues/9916#issue-464712495).

In regards to the recovery phrase, any version of the wallet (later to 4.8.1) should work properly.
You might be misspelling a word, please check the [import recommendations](https://github.com/bitpay/copay/issues/8532#issue-319277251).

Please let us know if you have any additional questions.
Kind regards.

**Comment by walletrescue** [comment]
@Lenny309 
did you restore your lost bitcoin, if you couldn't drop me a message, I can help to recover the lost coins i have done such recoveries in the past:  : anywalletrecovery@gmail.com
