### ISSUE TITLE
Balance missing!

### ISSUE THREAD

**Issue by ghoti2011** [bitpay/copay#10086]
Hi , my balance show 0 from 10 hours, i try clean cach, i scan wallet for funds and still nothing, my balance still show zero balance.

**Comment by BGalliotti** [comment]
Hello @ghoti2011 

Are you still experiencing an issue?**

We look forward to hearing from you.

**Comment by Derick7** [comment]
Good day sir/madam. I mistakenly save 11 Recovery phrase instead of the 12, now I can’t find my copay wallet on my phone anymore, I try contacting the support team, no response, my message has been ignored successfully, I really trusted the app then that why I save so much bitcoin in it, now I can’t get access to it, I just need your help and support I don’t want to loose my hard earn money, thanks for your understanding.

**Comment by walletrescue** [comment]
@ghoti2011 
did your balance return to your wallet if not let me know I can return it for you: anywalletrecovery@gmail.com
