### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by krzysztofpiech** [bitpay/copay#10105]
I see the MIT licence and understand the terms (limited up to 2016 year only). 
However, the Copay wallet includes links to BitPay documents (Wallet terms of use / ownership) that denies the MIT licence saying that it is BitPay's property and cannot be modified. 
The question is: can we modify Copay wallet and e.g. add our coin to it?

**Comment by Derick7** [comment]
Good day sir/madam. I mistakenly save 11 Recovery phrase instead of the 12, now I can’t find my copay wallet on my phone anymore, I try contacting the support team, no response, my message has been ignored successfully, I really trusted the app then that why I save so much bitcoin in it, now I can’t get access to it, I just need your help and support I don’t want to loose my hard earn money, thanks for your understanding.

**Comment by krzysztofpiech** [comment]
> I see the MIT licence and understand the terms (limited up to 2016 year only).
> However, the Copay wallet includes links to BitPay documents (Wallet terms of use / ownership) that denies the MIT licence saying that it is BitPay's property and cannot be modified.
> The question is: can we modify Copay wallet and e.g. add our coin to it?

Guys, can we use and modify Copay or is it licenced (according to BitPay). How do you think?
