### ISSUE TITLE
Cant import wallet, found problem with 12 words phrase

### ISSUE THREAD

**Issue by Alecampo86** [bitpay/copay#10114]
Just got my phone stolen a coouple of weeks ago so I bought a new one, downloaded Copay, entered the 12 words phrase I got written down and to my surprise they didnt work! I started looking for help and found the list of spanish words on the github website. So I doublechecked everything was fine until I found one difference. I was given the word "activar" but on the list it doesnt exist. Instead, you get "activo" between many others. How can this be?? I tried that one also but didnt work... I am absolutly sure the order is correct so what is going on??? Is there any other way to recover my wallet?? Please help with this, I cant lose this money. I am extremely worried.

Alejandro

**Comment by BGalliotti** [comment]
Hola @Alecampo86 
Gracias por ponerse en contacto con nosotros.

Desafortunadamente no hay otra forma de recuperar la billetera.  
De todas maneras, en base a nuestra experiencia, siempre que esto ocurre es debido a que el usuario está ingresando alguna palabra incorrectamente o no está incluyendo acentos (cosa que sucede en Español).

Le recomendamos lo siguiente

- Corrobore que las palabras de su frase están correctamente escritas incluidas las que llevan acento escrito.
- Reemplace la palabra "activo" por las palabras  parecidas de la lista (acoger, acoso, activo, acto, actriz,..)

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by Derick7** [comment]
This copay support contact is really not helping their users at all, I wrote here long time ago, that I have some bitcoin inside my wallet I mistakenly save 11 Recovery phrase instead of 12, no response ever since, is this app not really the best app for saving bitcoin, you don’t really have customer in your heart, ever sis Ec I wrote my message they keep ignoring me here

**Comment by Derick7** [comment]
This copay support contact is really not helping their users at all, I wrote here long time ago, that I have some bitcoin inside my wallet I mistakenly save 11 Recovery phrase instead of 12, no response ever since, is this app not really the best app for saving bitcoin, you don’t really have customer in your heart, ever since I wrote my message they keep ignoring me here

**Comment by Derick7** [comment]
Good day sir/madam. I mistakenly save 11 Recovery phrase instead of the 12, now I can’t find my copay wallet on my phone anymore, I try contacting the support team, no response, my message has been ignored successfully, I really trusted the app then that why I save so much bitcoin in it, now I can’t get access to it, I just need your help and support I don’t want to loose my hard earn money, thanks for your understanding.

**Comment by walletrescue** [comment]
@Alecampo86 
could you recover your wallet??
