### ISSUE TITLE
Marchent fee is too high, transaction rejected. 

### ISSUE THREAD

**Issue by ibkarchev** [bitpay/copay#10127]
Hello all day I'm trying to transfer funds to my neteller account by copay wallet but every time I try I get this massage "Marchent fee is too high, transaction rejected.". I've made a lots of transfers to neteller but didn't remember for a problem like this before. Can you help me whit this issue?

**Comment by Derick7** [comment]
Good day sir/madam. I mistakenly save 11 Recovery phrase instead of the 12, now I can’t find my copay wallet on my phone anymore, I try contacting the support team, no response, my message has been ignored successfully, I really trusted the app then that why I save so much bitcoin in it, now I can’t get access to it, I just need your help and support I don’t want to loose my hard earn money, thanks for your understanding.

**Comment by BGalliotti** [comment]
Hello @ibkarchev 

The app detects when the fee is too high in relation to the whole transaction amount and depending on that might prevent you from making the payment.
Usually, you should retry later when the fees are lower.

Kind regards.
