### ISSUE TITLE
Copay.io not work

### ISSUE THREAD

**Issue by shans22** [bitpay/copay#10131]
Hi Copay Team. 
Please tell me what happened to the Copay project. Request to copay.io is redirected to github. There is no app in Google Play.

**Comment by BGalliotti** [comment]
Hello @shans22 

Copay is no longer on Google Play Store, it has to be removed due to Google policies, therefore, it is published on [Github](https://github.com/bitpay/copay/releases).

Not all releases are published to be downloaded, only the major ones or those that include critical fixes.

Kind regards.
