### ISSUE TITLE
Error 500 missing inputs

### ISSUE THREAD

**Issue by kashif04444** [bitpay/copay#10365]
Unable to send bit coins error 500 missing input please check

**Comment by kashif04444** [comment]
Please check why this issue is occurred

**Comment by mrgilbbs** [comment]
I have being experiencing this issue for the past 48hours now ..
Each time I want to send btc it reads “500 missing inputs”
Please can someone tell me what is going on?

**Comment by BGalliotti** [comment]
Hello @kashif04444 @mrgilbbs 

This issue is usually related to inconsistencies on one or more wallet inputs that are shown as having funds when they actually do not have funds anymore. When the server tries to create the transaction finds the problem and retrieves this error.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Their representatives can address your inquiry there.

We appreciate your patience.

Kind regards.
