### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by TBUSA** [bitpay/copay#10456]
Hi!

I tried to deposit money from my copay to neteller as usual but kept getting error message when I pasted BTC address that I have insufficient funds.. I kinda know that this means the funds in my wallet are lower then the recommended bitcoin miner fee lever for getting a transaction added to the Bitcoin blockchain ("confirmed") . But I dont know what to do in practice to be able to deposit my funds onto neteller now.. Im also a noob when it comes to stuff like this.. Could anyone help me step by ste what to do?

**Comment by BGalliotti** [comment]
Hello @TBUSA 

If you are getting the error "insufficient funds for fee" it means just that, if you have 2.3 BTC (for example) you cannot 2.3 BTC as that transaction includes a fee so lets say you will be able to send 2.2984 BTC as a maximum (this is an example), because you have to pay the transaction fees.

In order to send the maximum amount available, try the *Send Max* feature.

To send Bitcoin or Bitcoin Cash from the BitPay Wallet, please follow the steps below:

1. Navigate to the wallet you wish to send funds from the BitPay App and click **Send** at the bottom.
2. Paste or scan the address you want to send funds to. You can scan QR codes by tapping on the scan icon on the right side of the **Recipient** field.
3. When on the **Send** tab, there will be a screen where you put the amount you want to send. Click on the **Send Max** option below the number 8 if you want to send the maximum amount available. Sending the max amount also includes the mining fee.
4. Slide the Bitcoin ‘₿’ from left all the way to the right to confirm on mobile. Click the **Click to send** button on the desktop app.

Kind regards.
