### ISSUE TITLE
Cannot Create Wallet

### ISSUE THREAD

**Issue by ivanetra** [bitpay/copay#10578]
**Error creating wallet: Network error.** This happened at my first start

**Comment by BGalliotti** [comment]
Hello 

**Unfortunately, this error is usually due to your internet connection.** Your device may be using a proxy server or VPN, which may be rejected by BitPay’s server. 

We suggest you try the below to troubleshoot:

- Access the internet through a different network connection.
- Use mobile broadband connections (such as 3G/4G/5G) instead of wifi, or use wifi instead of mobile broadband. 
- Reach out to your internet service provider’s technical support.
- Make sure that any internet traffic filtering software (such as antivirus, firewall, or internet suites) is not blocking your connection.


Kind regards.

**Comment by ivanetra** [comment]
I have tried all of your suggestions, but they still didn't work. Is there another way to solve it?

**Comment by BGalliotti** [comment]
Hello @ivanetra 

What country are you in?

Kind regards.
