### ISSUE TITLE
Funds received confirmed, But not available.

### ISSUE THREAD

**Issue by cmoleka** [bitpay/copay#10598]
Here is an interesting bug. 
This is the first time I'm running into this issue with Copay.

A recent transaction that was received and confirmed does not appear to be available for use on the Copay app. 
At the time of writing, the transaction has 5 confirmations on the Blockchain.
**Transaction Hash:** a2fc59c99d23dbbbb54518660b4f6438c35cd1bb4d38a6abbb3c40fc64d21832

I made a test transaction of 36.88 EUR that did go through for unknown reasons, leaving a balance currently equivalent to 207.55 EUR (current value) "available" on the wallet. The following transaction is currently unconfirmed at the time of writing.
**Transaction Hash** d733d154843b7de527cb8a0d3b5f0fb8c2c24d76b24a6202a41eca00874d0fd1 

Now, back on the Copay App within the Personal Wallet window under activity. The "available" amount on the wallet is displayed at the top in BTC and in a smaller font right underneath in EUR. 
Below it is displayed a mistirouse transaction of 0.14EUR or 0.000015 BTC that appears to be unconfirmed. What it is? I don't know.  

So to continue, I am trying to initiate a transaction for testing purposes of 5 EUR. Copay states that the wallet does not have that amount available. Interesting. 

Any idea what this is?

Current solution:
Exporting wallet to electrum BIP39 with address type P2PKH m/44'/0'/0'

**Comment by BGalliotti** [comment]
Hello @cmoleka 

We assume you are using some of the latest versions of Copay.

Basically the issue is Copay even when showing Total funds for X amount tells you have no funds (or not enough funds, when the amount is actually enough) to make a transaction, right?

We think that may be a synchronization issue, thanks for reporting it.
We would recommend you refresh the wallet and see what changes.

Please let us know if you were still having this issue.








Kind regards.
