### ISSUE TITLE
allow using simple passwords if length is big

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#2305]
passwords of this style: "aim google 9 crown disrespect" are very secure but rejected by copay.

**Comment by eordano** [comment]
Yes please, this is anti-security, I normally use these kinds of passwords and I've seen other users (like @slezica) complain about this as well.

**Comment by thoatbk** [comment]
There are other issues with the password check.

It simply doesn´t work for passwords in non-latin words.

If you insert something chinese there for example the regexp is never hit and the password strange isnt set higher it seems, (chinese has no lower upercase etc).

**Comment by seweso** [comment]
Upvote. You would think developers know better than to add arbitrary constraints to passwords. Very annoying.

**Comment by thoatbk** [comment]
To be fair coplay is pretty complex, took me weeks to get a more or less good understanding of the code etc and it´s beta software and those small problems or better edge cases you typically only notice later :)

http://danpalmer.me/jquery-complexify/

Something like this seems pretty useable for coplay, because it supports Unicode.

"For example, as there are 96 Hiragana characters defined in the Unicode specification, including one of these will increase the brute-force complexity by 96."

the minified version is around 2kb - https://github.com/danpalmer/jquery.complexify.js/blob/master/jquery.complexify.min.js
Heres the node-wrapper version: https://github.com/kislyuk/node-complexify - 2kb is the minified version

so that would add around 4kb more to the app, should be not too much overhead.

Ich took the time to check other password strength libs for js, complexify was the only one i found that has full unicode support and gets regular updates.

**Comment by matiu** [comment]
Re: developers know better: password strength check can be dissabled at
config.js

On Wednesday, January 14, 2015, thoatbk <notifications@github.com> wrote:

> To be fair coplay is pretty complex, took me weeks to get a more or less
> good understanding of the code etc and it´s beta software and those small
> problems or better edge cases you typically only notice later :)
>
> http://danpalmer.me/jquery-complexify/
>
> Something like this seems pretty useable for coplay, because it supports
> Unicode.
>
> "For example, as there are 96 Hiragana characters defined in the Unicode
> specification, including one of these will increase the brute-force
> complexity by 96."
>
> the minified version is around 2kb -
> https://github.com/danpalmer/jquery.complexify.js/blob/master/jquery.complexify.min.js
> Heres the node-wrapper version: https://github.com/kislyuk/node-complexify
> - 2kb is the minified version
>
> so that would add around 4kb more to the app, should be not too much
> overhead.
>
> Ich took the time to check other password strength libs for js, complexify
> was the only one i found that has full unicode support and gets regular
> updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2305#issuecomment-69951598>.
>


-- 
BitPay.com

**Comment by thoatbk** [comment]
Well you can set the passworth min strength to be less, but 

1) It gives back wrong messages for chinese, russian, japanese, thai etc. words; 
for example it will say to use mixed case for chinese, but there is no upper and lowercase in chinese.

2) If you download it at the playstore, windows store etc you can´t edit the config file

**Comment by jaimenm** [comment]
Agree with OP, password constrains force the user to use a different password tactics, resulting in lost passwords or forcing to write them down. Will be better to use a reminder tip, suggesting the user to use an strong password. This is not cold storage.

**Comment by matiu** [comment]
Closing this one. Wallet is not password encrypted by default on v0.10 since the priv keys are never sent to a centralised storage, only private key can be encrypted, and no strength check is performed on the user's input. Also encryption is performed on wallet backup.
