### ISSUE TITLE
UX Suggestion

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#2355]
Hi,

1- I think the current copay mobile buttons ( Home, Receive, Send and History) should disappear. I think the way it´s now is visual pollution.
2- I like more the coinbase design. I think Copay should clone it. 
3- I think Copay mobile should show the last transactions on main window.

![screenshot_2015-01-27-08-26-28](https://cloud.githubusercontent.com/assets/1178856/5917159/f8d6f526-a600-11e4-80ca-c2f33e6fac3e.png)

![screenshot_2015-01-27-08-23-12](https://cloud.githubusercontent.com/assets/1178856/5917161/04742b38-a601-11e4-8c74-625be27033dc.png)

**Comment by bitcoinuser** [comment]
Even my bank mobile app use the + button. See:

![screenshot_2015-01-27-10-35-00](https://cloud.githubusercontent.com/assets/1178856/5918576/53a3d1f8-a611-11e4-8c8f-f5a33655c77e.png)

**Comment by thoatbk** [comment]
That is an extra click for nothing, if you want to use a payment app in real life it should be FAST to use/navigate with as little clicks as possible.

**Comment by bechi** [comment]
Hi @bitcoinuser  , thanks for your feedback.
1- We can't remove tabs nav because it's the navegation for the different section.
2- Now we're working on the new styles for copay, I hope you like it.
3- In the new design, we're thinking put the last transactions on the main windows, we don't know if the correct option but we're thinking.

**Comment by matiu** [comment]
the next UX iteration of copay will consider some this suggestions. Thanks a lot!
