### ISSUE TITLE
Error broadcasting tx

### ISSUE THREAD

**Issue by ripper234** [bitpay/copay#2441]
Someone initiated a tx 4 days ago, and I tried to sign it now (2-out-of-3 wallet).
I got this error, and the funds were not sent.

The error persisted a few times + after reloading copay (I'm using the web interface).

> {"statusText":"Not Found","status":404,"responseURL":"https://insight.bitpay.com/api/tx/4c2a9be1000a9a935fc03336828fb78f0d30d13d6951c34907902fceb1f3cd69","response":"Not found","responseType":"","responseXML":null,"responseText":"Not found","upload":{"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null},"withCredentials":false,"readyState":4,"timeout":0,"ontimeout":null,"onprogress":null,"onloadstart":null,"onloadend":null,"onload":null,"onerror":null,"onabort":null,"seq_id":13,"id":"13: GET https://insight.bitpay.com:443/api/tx/4c2a9be1000a9a935fc03336828fb78f0d30d13d6951c34907902fceb1f3cd69","_id":"13: GET https://insight.bitpay.com:443/api/tx/4c2a9be1000a9a935fc03336828fb78f0d30d13d6951c34907902fceb1f3cd69","timeoutTimer":4417,"statusCode":404,"body":"Not found"}

**Comment by ripper234** [comment]
Conjecture: this tx was trying to send all remaining funds from the wallet to a different copay wallet. Is it possible the problem was caused by tx fees? (not enough funds to move everything out)

**Comment by MeniRosenfeld** [comment]
I have a theory that this is about dust change. I can't see the tx details in the interface, but based on the amount the tx should result in a change output of 212 satoshis, below the dust limit.

That's understandable, but if this is indeed the case then I would appreciate:
1. A more informative error message.
2. The tx creation being refused in the first place, rather than waiting for everyone to sign and then refusing to broadcast it.

**Comment by matiu** [comment]
this should be fixed (error displayed) in current version.
