### ISSUE TITLE
Inviting copayers 

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2561]
The idea of sharing a secret is kind of intimidating and as a casual user you might be concerned with sharing "secrets" via email etc.  recommend this be relabeled to something like "Invite users" or "Invite copayers" or similar.  Remove word "secret" from screen.

**Comment by dabura667** [comment]
+1

My wife actually just asked me that:

"ok, I signed up, but do I send you the secret or do I keep it secret???"

I was about to go into the difference between asymmetric and symmetric keys... but then just decided to say "it's our secret, so gimme :-P"

**Comment by martindale** [comment]
+1 on this as well.  I always move through this stage really quickly when showing people how Copay works, because it's where people get stuck.

Maybe there's also an opportunity here to do local discovery on a LAN, or something – other Copayers can turn on "discovery mode", and when creating a wallet, you can see a list of these people and add them directly.
