### ISSUE TITLE
Move translations to crowdin

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2576]
crowdin uses po files natively to manage translations, has amazing string management functions, AND offer their services for FREE to open source projects.

After seeing how different the template.po is from the po I translated into Japanese, it would take me many hours to take the diff of just the english and figure out which ones are similar etc. but crowdin would do that for me automatically, every time the english strings changed.

The best action for the templates file as is would be for me to just translate it from scratch.

https://crowdin.com/page/open-source-project-setup-request

Some recommendations:

1. Set it so that anyone can participate without invite.
2. Set it so that anyone can add glossary terms.

Then all you need to do is click on the 100% translated languages and download their respective po files. Since Copay deals with po files directly, it should be easy.

**Comment by cmgustavo** [comment]
Good solution to have Copay in the majority of languages as posible! 

Regarding your work in the `ja.po`, note that the new `template.pot` has less words than old Copay. Only a few words are repeated. Open the ja.po file and `Update from template POT file`.
Anyway, we are planning to include the translation again when having all words inside the template.pot (right now, only have the words from the html, not javascript files). This issue is related to enable again the automatic translation of Copay: https://github.com/bitpay/copay/issues/2575

Thanks for your suggestion!
