### ISSUE TITLE
[Feature] Is it possible to support BIP39 wordlists for backups?

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2698]
Hi :)
It can avoid the need to add an extra password for encryption if the user is asked to write the words on a paper.
Maybe users will be more motivated to do a backup with simple words than an incomprehensible encrypted password?
In addition, you have Spanish, Japanese and Chinese wordlists (and french soon).
What do you think?

**Comment by matiu** [comment]
The problem is that to restore funds from a  multisig HD wallet, with
quorom copayers (eg: 2 copayers from a 2-4 wallet) you need 2 private keys
+ 2 extended public keys of the other copayers) (ie, the private keys alone
are not enough for quorum recovery).

So, we are afraid that users storing only the bip39 menomic of the private
key will have a false sense of security.



On Mon, May 11, 2015 at 12:36 PM, Kirvx <notifications@github.com> wrote:

> Hi :)
> It can avoid the need to add an extra password for encryption if the user
> is asked to write the words on a paper.
> Maybe users will be more motivated to do a backup with simple words than
> an incomprehensible encrypted password?
> In addition, you have Spanish, Japanese and Chinese wordlists (and french
> soon).
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2698>.
>



-- 
BitPay.com

**Comment by Kirvx** [comment]
Thanks :)
Simply, the idea to control the money with words sounds magic to me (and certainly for other people).
So maybe you should develop your own BIP in the futur to integrate this :)

**Comment by Kirvx** [comment]
Greenbits do that with a seed of 24 words.

**Comment by matiu** [comment]
just for future searchs:

see also:
https://github.com/bitpay/copay/issues/2546
and
https://github.com/bitpay/copay/pull/2246
