### ISSUE TITLE
Access to shared wallet lost by some copayers if multiple copayers are in same application instance

### ISSUE THREAD

**Issue by tab00** [bitpay/copay#2812]
To reproduce the error, either in Android or Chrome extension:
Create a new 2-of-2 wallet with wallet name "Shared 2-of-2" nickname "user 1".
Copy the invitation code.
In the same application, join the shared wallet by pasting the invitation code and with nickname "user 2".
You will notice 2 wallets named "Shared 2-of-2".
Select the first "Shared 2-of-2" as the active wallet.
Have some bitcoin deposited into the wallet.
Send some bitcoin out of the wallet.
A message appears that says "Payment proposal created".
Select the second "Shared 2-of-2" wallet in order to add the other signature.
If you were able to do so, press on "Multisignature wallet" in the center of the Home screen. You'll notice "user 1 (Me)" is bolded. It should instead be "user 2 (Me)". The transaction cannot be signed because you are not "user 2".
If you were not able to select the second "Shared 2-of-2" wallet, it may have disappeared from the list (it happens in the Android app), and therefore cannot be selected as the active wallet. Hence transaction cannot be signed as "user 2".

The funds are thus stuck forever in the shared wallet and can no longer be spent.

The "user 2" wallet should not disappear, and it should be selectable as the active wallet so that the transaction can have all required signatures and then allowed to be broadcast.

Some people are going to test multisignature transactions in copay on a single device, just as I did, and may find their bitcoin stuck as described. This can cause some grief if this test is done using a significant amount of real bitcoins.

Please fix this problem as soon as possible.

**Comment by matiu** [comment]
Thanks for the detailed report. I was able to reproduce it. This is purely an UI issue: we are indexing the available wallets be `walletId`, we should do it by `walletId:copayerId`.

**Comment by chaosgrid** [comment]
It would be really useful to have this fixed. I just wanted to setup a multi sig wallet from within the same app instance and because of this bug I had to revert to using multiple devices / app instances.

**Comment by matiu** [comment]
What would be the use case of having multiple keys of the same wallet on the same device?

**Comment by chaosgrid** [comment]
Say you want to create a backup wallet for emergencies where you are no longer available (as a person i.e. you die) to access funds. You have some people that you trust but they are not into BTC yet for whatever reasons. As of now, you can only create a multi-sig wallet when every other participating person has a copay wallet and so on. This would allow to create a multi-sig wallet on one device and then distribute the encrypted backup files for the individual wallets via i.e. e-mail to your trusted peers that do not have copay yet. After all this is done, you can then delete all the wallets you created and just need to let the others know the passwords for their wallet backups that you sent out (should be a seperate communication channel). This way, in an emergency, your trusted peers can come together and access funds when the time has come rather than to explain them copay and bitcoin etc. right when creating the backup wallet.

Of course this is kind of a work around and a dedicated "create emergency wallet" functionality would probably be better and more clear. But in any way, also for testing purposes, I think it makes sense to support having multiple keys in the same app instance.

**Comment by dabura667** [comment]
This backup scheme seems unnecessary.

If you are going to trust them with m keys so that they could come together at any time to spend your funds, should they take the time to figure it out, then why not just give them a copy of your keys.

ie. Instead of creating 2 of 4, creating 2 dead keys and giving them to relatives, then using the other two on your devices... just give copies of the 2 backups of a 2 of 2 to them.

Same exact thing, except your transaction fees will be a LOT smaller.

**Comment by chaosgrid** [comment]
Ya, I'm no expert and maybe the example is bad but I was just saying that there is a use case for initially creating a multi-sig wallet on one device and then distributing the backups to other people :)

**Comment by dabura667** [comment]
bitcore-wallet-client can create as many wallets as you want on the same device.
It's like Copay but without the UI.

Not the most user friendly thing in the world, but you could generate the wallets on bwc and then send the files to friends via mail or something. Those can then be recovered in Copay app.

**Comment by tab00** [comment]
Is this problem fixed yet?

Any situation in which a user can have their bitcoin stuck and therefore no longer spendable (possibly forever) is a very serious problem, as users can potentially have a large amount get stuck.

**Comment by dan-da** [comment]
another use case:   testing and evaluating Copay.   without requiring 5 different devices.

another:  two people share the same physical device.   phone.  laptop.  tablet.   whatever.

another:  setting up spare keys in case somebody leaves the company since Copay has no way to revoke keys or add new payers.

But let's ask a different question:  is there any reason NOT to enable multiple copayers using the same Copay instance?

**Comment by matiu** [comment]
in the upcomming version 1.1.3 this is prevented: If the user tries to join
a wallet from the same instance of Copay more than once an error is
displayed (before the join is performed). There no wallet is created, no
address can be generated.

We dont want to support this feature since allowing more that one key of
the same wallet on the same installation  breaks one of  multisig main
features: distributing the keys for better security.



On Wed, Aug 12, 2015 at 4:28 AM, dan-da <notifications@github.com> wrote:

> another use case: testing and evaluating Copay. without requiring 5
> different devices.
>
> another: two people share the same physical device. phone. laptop. tablet.
> whatever.
>
> another: setting up spare keys in case somebody leaves the company since
> Copay has no way to revoke keys or add new payers.
>
> But let's ask a different question: is there any reason NOT to enable
> multiple copayers using the same Copay instance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2812#issuecomment-130199946>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by chaosgrid** [comment]
Why don't you display a simple warning that describes and communicates this to the user, but allows to do it anyways? 
As dan-da also explained, I think there are a few use cases. I think the most important one is to actually test the wallet functionality.

**Comment by matiu** [comment]
For testing & developing we recommend using `npm start` and point to `http://localhost:3001`
you can open that on a browser and browser + private mode for multisig.

For testing & not-developing, you can use the Chrome App + the deskop version + phone versions,  for multisig.

**Comment by chaosgrid** [comment]
> For testing & not-developing, you can use the Chrome App + the deskop version + phone versions, for multisig.

Fair enough, I still think it'd be more convenient to allow this in the same app instance with a warning message.
