### ISSUE TITLE
Suggestion: Make 1-of-1 wallet adhere to BIP44 as normal p2pkh addresses

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2866]
So the pubkey stored in the wallet will be the node at `m/44'/0'/0'` instead of `m/45'`

This coincides with the Enhanced backups and lowering dependency on BWS in areas that it can.

Bonus points for BIP39 with optional password support.

See also:
#2722 
#2863

**Comment by matiu** [comment]
Currently Copay only uses the 'shared' addresses of BIP45 (since address
are assigned in BWS, so there is not synchronisation problem), so we are
not using the realy advanjes of BIP45.

Given the advantages you mentioned, we are thing of completely migrate to
BIP44, do not support BIP45 anymore (only for address fund scanning, for
backwards compatibility).  If it not a difficult change to do, given how
copay is now coded. The only drawback is that we wont be able to support
generating addresses for the wallet without BWS (it is from an offline
client), at least wit the same 'elegance' that BIP45 do.

What are you thought about that?




On Sat, Jun 6, 2015 at 10:43 AM, dabura667 <notifications@github.com> wrote:

> So the pubkey stored in the wallet will be the node at m/44'/0'/0'
> instead of m/45'
>
> This coincides with the Enhanced backups and lowering dependency on BWS in
> areas that it can.
>
> Bonus points for BIP39 with optional password support.
>
> See also:
> #2722 <https://github.com/bitpay/copay/issues/2722>
> #2863 <https://github.com/bitpay/copay/issues/2863>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2866>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
ping @isocolsky

**Comment by dabura667** [comment]
I think BIP44 for 1-of-2 and above is not good.

But for 1-of-1 (or rather, Pay2PubKeyHash addresses beginning with '1') I think it is great.

As far as your other comments, I am sorry I don't think I understand you.

You are saying Copay is not BIP45 currently? Are you talking about 1-of-1 or everything?

Or maybe do you mean that Copay does not use the cosigner_index and only puts 0 in it and never 1,2,3,4,5 etc?

I think if you are staying on 0 because address generation is based on BWS and needs to request to it anyways, then sure it would be ok to switch to BIP44 in that situation.

However, I think that staying with BIP45 will allow us to do more in the future, as I hope that all multi-sig wallets will use BIP45 to remove the race conditions.

It just so happens that Copay is the first REAL multisig wallet.

So I think YES for (BIP44 + P2PKH ('1'))
and a NO for (BIP44 + P2SH ('3') + multisig) I think it should stay BIP45 just in case, for future updates... (also, to avoid exposing pubkeys if people reuse their xprvs in other wallets... the pubkeys would already be on the blockchain, but checking the p2pkh address would lead them to think it isn't.)

**Comment by matiu** [comment]
done!
