### ISSUE TITLE
Better backups

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2955]
- bip39
- printable, bip38, QR
- downloadable encrypted file

**Comment by Kirvx** [comment]
Nice :)
Will you also integrate french, spanish, chinese and japanese wordlist for BIP39 ?
https://github.com/bitcoin/bips/tree/master/bip-0039

**Comment by isocolsky** [comment]
@Kirvx that is the plan. We will be implementing all languages available in https://github.com/bitpay/bitcore-mnemonic/tree/master/lib/words. French is not listed yet but will work on adding it to Bitcore.

**Comment by Kirvx** [comment]
Ok thanks :)

**Comment by dabura667** [comment]
Since this is related, I thought I'd post here too.

https://github.com/bitpay/bitcore-mnemonic/pull/27

Please merge. bitcore-mnemonic was non-BIP39 compliant. (English words are all NFKD normalized to begin with, so no one ever noticed, I think) wallets generated with bitcore-mnemonic using Spanish wordlist up until now are not BIP39 compliant.

**Comment by XBTdev** [comment]
> bip39
> printable, bip38, QR
> downloadable encrypted file

bip39 sounds awesome. bip38 sounds really awesome (I like a paper backup that still requires a password)! But I haven't seen bip38 used for HD wallets. I think its only for encrypting individual private keys. Are you going to use scrypt in a modified version of bip38?
