### ISSUE TITLE
Spec: Shared Wallet User Management

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#2971]
It would be valuable to make modifying the signature requirements in a shared wallet more intuitive.

If a quorum of users in a shared wallet want to add or remove one or more users from the wallet, it should be possible to sweep the "old" wallet to a "new" wallet in a way similar to signing a transaction. When this is done, it should be possible to maintain the wallet's transaction history.

**Comment by bitjson** [comment]
[Requested on reddit](https://www.reddit.com/r/Bitcoin/comments/3cszc4/new_features_for_copay_users_in_version_11/csyt2i4)

**Comment by dan-da** [comment]
This seems like progress, thx!   So here I'll provide some food for thought.  Sorry if its a bit rambly, but it was basically my thought process as I was first evaluating CoPay and hopefully you will get the gist.

Here's my present day situation that I'm wanting to replicate in a bitcoin environment.  So far, CoPay seems closest of all the wallets out there.

My secretary prepares bill payments and payroll payments using our bank's website.  She is able to prepare payments only.  When I login, I am notified if there are any pending payments awaiting authorization.  I can then review them and either authorize them invidually or en masse.

Important:  as the authorizer, I can also unilaterally send a payment on my own.

If the secretary ever leaves the company, the replacement will receive a new login account on the bank's website and will be given the same role/permissions.  I will remove permissions from the first account.  Everything then continues as normal.  easy peasy.

So this is basically a 1 preparer : 1 approver model.    There could theoretically also be n preparer : 1 approver or y preparer : m of n approver.

Now I do not know if an arbitrary number of preparer/signer is possible with bitcoin's multisig.  If one could create a transaction that says:   
    2 of 5 signers are needed and one of them must be X
then that would be getting pretty close.

Without the "one of them must be X" capability, that leaves us with something like:
   2 of 5 signers.   where preparer hold one key and authorizer holds 2 keys plus 2 backup keys.
( authorizer holds 2 keys to enable unilateral spending. )

So that all works fine until the preparer leaves employment or changes roles.

At that point, what do I do?
  The old key should be revoked, but bitcoin doesn't support that.  Can we at least remove or disable/blacklist that person from our CoPay wallet for future transactions?
   The replacement preparer needs a key, but where from?  Should I give them one of my 2 backup keys?  doesn't seem like a good idea.

If I had created a 2 of 10 wallet initially instead of 2 of 5, then I would have 5 spare keys available for replacement staff.   Which is much better, but still there is a fixed limit that I'm leery about someday bumping into.

I can create a new wallet and transfer the funds, but that is a hassle and coordination effort for everyone involved and I really really do not want to lose or split up transaction history in the process.   This is needed for the company accountant.  So that's basically a showstopper.

Now if new wallet creation can somehow be streamlined so that the new wallet keeps the existing wallet members (without having to reconfirm) except for members X,Y and adding N new members, and keeps the transaction history available,  then I think we are getting to something usable.

Stated another way:  The desired feature is "Add/Remove wallet participates to existing wallet".  But if that is technically impossible, then perhaps the feature could exist, but under the covers new wallets are created, keeping as much of the old wallets as possible.

**Comment by thecrm** [comment]
You're referring to a 'preparer' as someone who has non-signing rights. It seems like there would actually be three different types of users:

1. View only: could monitor wallet
2. Non-signing user: could create transaction proposals
3. Copayer: A signing user with a private key

**Comment by dan-da** [comment]
Yes, ideally the wallet would support the following workflow:

1) non-signing user creates transaction proposals.
2) Copayer(s) receive some type of message upon login that there are pending transactions to review.
3) Copayer(s) can either approve or disapprove.    If not enough approve, the transaction is moved to some sort of declined state.

I wasn't aware that this non-signing user is really an option, so was trying to shoehorn the workflow into an m of n signing model.

**Comment by matiu** [comment]
JFYI, we just merged a PR  about 'non signing backups'.

See https://github.com/bitpay/copay/pull/2998 for details.

On Thu, Jul 16, 2015 at 4:34 PM, dan-da <notifications@github.com> wrote:

> Yes, ideally the wallet would support the following workflow:
>
> 1) non-signing user creates transaction proposals.
> 2) Copayer(s) receive some type of message upon login that there are
> pending transactions to review.
> 3) Copayer(s) can either approve or disapprove. If not enough approve, the
> transaction is moved to some sort of declined state.
>
> I wasn't aware that this non-signing user is really an option, so was
> trying to shoehorn the workflow into an m of n signing model.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2971#issuecomment-122062083>.
>



-- 
BitPay.com
