### ISSUE TITLE
Hidden Balance

### ISSUE THREAD

**Issue by gehlm** [bitpay/copay#2975]
Include an option to require a pin to view balance or "lock wallet". If phone is lost or computer is left logged in, anyone can view wallet balances. If option is set, after a timeout period, balance is hidden.

**Comment by zachdoty** [comment]
+1 

Question: would the data be encrypted on the local filesystem? 

Would this be a global option, or a wallet setting?

**Comment by gehlm** [comment]
Global option would be most user-friendly. Not sure if the data is encrypted. The feature should be similar to Mycelium's "Require PIN on Start".

**Comment by matiu** [comment]
There is no plan to include this feature yet, we tend to prefer to trust your device locking mechanism (phone or pc) to prevent access to the app.

Regarding encryption, we have two layers:
1- In phones, localData is encrypted with a hash of DeviceID + salt.
2- Per wallet, it is possible to encrypt the private key with a user defined passphrase (settings -> encrypt private key).

Finally, all backups are encrypted with a user defined passphrase.

**Comment by sironitomas** [comment]
So if someone copied the contents of my device's memory, they wouldn't be
able to unencrypt the private keys, right?

**Comment by dabura667** [comment]
Now that we support Trezor... This function is something I wish existed.

1. I want to be able to deposit to my Trezor.
2. But I don't want to advertise my whole balance to anyone in the vacinity when I am depositing.

Sure it can be fixed by finding a nice quiet place with no people to deposit to my Trezor... but for in person LocalBitcoin sales, it'd be nice to have my no-key watch only wallet on my phone, be able to see incoming transactions, but still have the option to have hidden balance display and hidden transaction display.

I think breadwallet's approach is good. (by default their wallet requires a PIN or TouchID to show balance. This means you can open up to send or receive without people nearby seeing your balance.

Especially when paying, the other person usually looks at your screen (maybe they think you're trying to do something fishy or idk... but usually when I send bitcoin we both look at each other's screens until the reaction appears on the receivers screen.

This is why I feel comfortable holding larger amounts on breadwallet, and Copay is just for multisig and an emergency wallet (for when breadwallet was crapping out a lot recently)

**Comment by XBTdev** [comment]
Other than copay, there aren't any other sensitive apps on my phone. It would be nice not to have to have a pass-code on my phone just to protect my copay balance & tx history.

(1) App pin code #3061, (1) hidden balances #2975, or (1) stealth wallets #3030 have all been suggested as good solutions. I really hope one of these is adopted soon, so I can disable the annoying swipe code on my phone.

Besides, all of these options listed above provide stronger privacy than a phone passcode, because my phone is unlocked countless times per day and anyone who shadowed me could [shoulder-surf](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security)) and observe my unlock code.

Personally, I would like to see all three of these options adopted in Copay. But at least one of them would be nice.

**Comment by matiu** [comment]
done on the upcoming Copay 2.0
