### ISSUE TITLE
Path derivation for external hardware wallet implementation

### ISSUE THREAD

**Issue by EricLarch** [bitpay/copay#2999]
We (Ledger) are in the process of finalizing the integration of the Ledger hardware wallet to Copay. In order to provide the best implementation possible, I have a question regarding BIP45.

Right now, each time a Copay wallet is created (single or multisig), a new HD wallet is generated and BIP45 is applied to build the addresses path. With the Ledger implementation, there is the possibility to select an external xpub to seed the new wallet. This xpub is given by the Ledger hardware wallet.

The problem is the following: each time you will create a new copay wallet and source the xpub on the Ledger device, you will get the same xpubkey (the derivation being m/45' from the master).

What would be the most elegant solution to this?
* do nothing, and accept that all wallets based on the Ledger HW will have the same set of addresses
* derive the xpub on something like m/sha32(wallet_name)/45'
* something else?

(right now we are going to the first option)

**Comment by matiu** [comment]
Hi Eric,

Great news you are moving ahead. 

So, IIUC, the ledger device can hold only one master extended private key, is that correct?

The first approach (do nothing) would mean that all Copay's wallets related to a ledger device will have the same extended master key. This could be OK if users only use 1-1 wallet, but see the following example:

 * Alice create a 1-1 wallet
 * then join a 2-2 wallet with Bob

Since the key Alice used for the 2-2 wallet is the same than the one she used for the 1-1 wallet, and given that Bob of the 2-2 wallet have access to all the extended public key, Bob will be able to derive all address of the 1-1 wallet of Alice, and see her TX history, which is unacceptable.

The approach `m/toNumber(walletName)'/45'` or `m/toNumber(walletId)'/45'` is interesting, the problem would be that if you need to restore a Copay wallet from your ledger device you will need to know the walletName or walletId, correct? Are you planning of storing that somewhere on ledger? 

Optionally you could use a simpler, small integer, like `m/smallInt'/45'``, and store the mapping of smallInt <-> walletId. In case everything is lost, it would be possible to restore all ledger's device wallet by scanning `m/X/45'`. Not sure is a good idea though. May be is simple for the user to remember the wallet name.

**Comment by EricLarch** [comment]
When creating a new wallet, we can ask the user to pick a number between 0 and 19 (should be enough) and this number will be stored in the wallet backup. In case of total loss, the user would have at maximum 20 tries to recover access to his copay wallet.

**Comment by matiu** [comment]
sounds good.
