### ISSUE TITLE
Unconfirmed transaction for more time than expected

### ISSUE THREAD

**Issue by Duobit** [bitpay/copay#3388]
Hello,

We have a Multisignature wallet (2-of-2) in copay.

We sent 4.886 Bitcoins today at mid-day, but it still says Unconfirmed.

The transaction does not even appear in Blockchain, it only shows sign of life in insight.bitpay.com

The transaction ID is: 7e1be321942a9773c862840a30de7602f237a459cc01345e66202c712640404b

Could you please let us know what to do?, this is the first time that this happen to us.

Please if you could help us that would be really appreciated.

Sincerely,
Richard Vasquez

**Comment by matiu** [comment]
Hi,

The transaction also shows on other block explorers:
https://www.blocktrail.com/BTC/tx/7e1be321942a9773c862840a30de7602f237a459cc01345e66202c712640404b

It seems you just need more time so it gets confirmed. To speed up that
process you can rise the fee level in the transaction creation tab, in
future transactions.





On Tue, Nov 3, 2015 at 9:09 PM, Duobit <notifications@github.com> wrote:

> Hello,
>
> We have a Multisignature wallet (2-of-2) in copay.
>
> We sent 4.886 Bitcoins today at mid-day, but it still says Unconfirmed.
>
> The transaction does not even appear in Blockchain, it only shows sign of
> life in insight.bitpay.com
>
> The transaction ID is:
> 7e1be321942a9773c862840a30de7602f237a459cc01345e66202c712640404b
>
> Could you please let us know what to do?, this is the first time that this
> happen to us.
>
> Please if you could help us that would be really appreciated.
>
> Sincerely,
> Richard Vasquez
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3388>.
>



-- 
BitPay.com

**Comment by Duobit** [comment]
Hello Matias,

Yes, but it been more tan 8 hours by now, I dont think that is normal.

Richard Vasquez

2015-11-03 19:59 GMT-04:30 Matias Alejo Garcia <notifications@github.com>:

> Hi,
>
> The transaction also shows on other block explorers:
>
> https://www.blocktrail.com/BTC/tx/7e1be321942a9773c862840a30de7602f237a459cc01345e66202c712640404b
>
> It seems you just need more time so it gets confirmed. To speed up that
> process you can rise the fee level in the transaction creation tab, in
> future transactions.
>
>
>
>
>

**Comment by Duobit** [comment]
Hello Matias,

Yes, but it has been more than 8 hours by now, I don't think that is normal.

I used some unconfirmed funds when sending the Bitcoins, I dont know is
that affect.

Richard Vasquez

2015-11-03 20:01 GMT-04:30 shmokii smufu <ventas.sys.ca@gmail.com>:

> Hello Matias,
>
> Yes, but it been more tan 8 hours by now, I dont think that is normal.
>
> Richard Vasquez
>
> 2015-11-03 19:59 GMT-04:30 Matias Alejo Garcia <notifications@github.com>:
>
>> Hi,
>>
>> The transaction also shows on other block explorers:
>>
>> https://www.blocktrail.com/BTC/tx/7e1be321942a9773c862840a30de7602f237a459cc01345e66202c712640404b
>>
>> It seems you just need more time so it gets confirmed. To speed up that
>> process you can rise the fee level in the transaction creation tab, in
>> future transactions.
>>
>>
>>
>>
>>

**Comment by matiu** [comment]
it is confirmed already.

**Comment by Duobit** [comment]
Hello,

 We have a Multisignature wallet (2-of-2) in copay.

 We sent 9.36868301 Bitcoins on Monday 13th, but it still says Unconfirmed.

 The transaction does not even appear in Blockchain, it says:

"Transaction rejected by our node. Reason: Transaction was previously
accepted but has been pruned from our database."

 The transaction TX is:
 a91c883580d9c1c67f0b26d71ef12ee77fc204b05fbc03dfcaa4db2486790e33

 Could you please let us know what to do? We are really worried, we are
talking about almost 7000$

 Please if you could help us that would be really appreciated.

 Sincerely,
 Richard Vasquez

**Comment by matiu** [comment]
this is a new issue, right?

Please check the transacion at insight.bitpay.com.

it shows there. the unusual delay could be related to some inputs no yet
been confirmed. if that is the case, even if you have a OK fee in your TX,
it cannot be confirmed until the.inputs are confirmed.

to prevent this in the future,  uncheck the "use uncorfirmed inputs" in
global settings.  (see attachment)

Hello,

We have a Multisignature wallet (2-of-2) in copay.

We sent 9.36868301 Bitcoins on Monday 13th, but it still says Unconfirmed.

The transaction does not even appear in Blockchain, it says:

"Transaction rejected by our node. Reason: Transaction was previously
accepted but has been pruned from our database."

The transaction TX is:
a91c883580d9c1c67f0b26d71ef12ee77fc204b05fbc03dfcaa4db2486790e33

Could you please let us know what to do? We are really worried, we are
talking about almost 7000$

Please if you could help us that would be really appreciated.

Sincerely,
Richard Vasquez

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/3388#issuecomment-226944600>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAGCHD17lWLaifXKcJEAn2I1JivmyTSiks5qM_y5gaJpZM4GbX6t>
.
