### ISSUE TITLE
n-of-n multisig trancsction signing fails. "Could not accept payment: Server response could not be vefified."

### ISSUE THREAD

**Issue by ihqtzup** [bitpay/copay#3397]
Model: Samsung Galaxy Xcover 3
Platform: Android 4.4.4
Wallet servive URL: https://bws.bitpay.com/bws/api

Problem: Can't sign n-of-n transaction proposals with recently restored backups. I tried with both LTE and Wlan connection.

Error message: "Could not accept payment: Server response could not be vefified."

However this happens only with one specific wallet. Not with an another n-of-n wallet.

**Comment by ihqtzup** [comment]
Further investigations shows that this happens only with one parcticular signer transaction proposals and only if I'm signing that transaction.

**Comment by matiu** [comment]
Could you check that all copayers are using the latest copayer version?

**Comment by ihqtzup** [comment]
All copayers are using 1.4.3 version.

**Comment by Sabbe** [comment]
I'm one of to copayers. This bug is really strange. It only happens when our third copayer is signing transactions and when ihqtzup tries to co-sign. If transactions are created & signed in *any other way*, it works.

**Comment by matiu** [comment]
You mentioned that the some of the wallets were restored from a backup.
Would it be possible to you to create a new multisig wallet, and move the
funds to that new wallet? If one of the backup of the original wallet was
too old, it could be possible that there is some incompatibility with the
current wallet-service version.

On Tue, Nov 10, 2015 at 2:51 PM, Sabbe <notifications@github.com> wrote:

> I'm one of to copayers. This bug is really strange. It only happens when
> our third copayer is signing transactions and when ihqtzup tries to
> co-sign. If transactions are created & signed in *any other way*, it
> works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3397#issuecomment-155512455>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by Sabbe** [comment]
I think that is a good guess for the source of the problem. We will do some more tests and if the bug still persists, we will make new wallets.

I remember that when ihqtzup migrated to the new major revision of Copay a while back, there was a problem. Me and the third copayer were able to migrate without problems but he needed to manually use backups to migrate.

I think that is where it already went wrong. It just took us a long time to find the bug out because it requires a very specific scenario where one of us creates the tx, and a particular other co-signs. Otherwise it doesn't happen. I think this has been present since the major revision of Copay.

**Comment by matiu** [comment]
Thanks for the update, and the details.

While in Copay you can always recover access to the wallet and funds having only the extended private key (present in all the backups), I think it would be better you to migrate to a new wallet, to avoid inconveniences.

Closing this ticket now, let us know if you have further problems.
