### ISSUE TITLE
Access to wallets denied. Error message: "Could not decrypt storage: device ID mismatch"

### ISSUE THREAD

**Issue by tab00** [bitpay/copay#3523]
Whenever opening the Copay android app in android I receive the above error message with an OK button. Pressing the OK button closes the app. There are a number of wallets, one real and others testnet, with positive balances which I can no longer access.

I had been tinkering previously with the phone settings, e.g. I changed the IMEI. Thinking that this may have caused the problem, I changed the IMEI back to the original value, however the problem remains.

What caused this problem and what are the options to fix it?

Can any changes be made in the app to prevent this problem from ever occurring? Every possibility of users permanently losing access to wallets should be prevented. I've already encountered two possibilities so far since I started using Copay.

**Comment by matiu** [comment]
I am sorry you are having problems with Copay.

Because some users reported DeviceID problems on Android, we disabled DeviceID encryption in v1.5. If you are using v1.5.x, Copay will migrate your storage, but to do that, it needs the right device ID. So, answering your question, for new users, this will not longer be an issue.

For you wallets, the simplest approach would be to recover your livenet wallet from backup. For what you need to uninstall Copay, reinstall it, and then import the backup. As mentioned above, DeviceID will no longer be used (is you install v.1.5).

**Comment by tab00** [comment]
What exactly caused the problem? Did Copay use the IMEI value to identify a Copay installation?

I upgraded to the latest version of Copay for Android but I still can't access the wallets.

Is there any way to restore access without uninstalling Copay and reinstalling?

**Comment by matiu** [comment]
On Mon, Nov 30, 2015 at 2:08 AM, tab00 <notifications@github.com> wrote:

> What exactly caused the problem? Did Copay use the IMEI value to identify
> a Copay installation?
>
Copay used to use unique device ID to encrypt. Here is the code: (
https://github.com/Paldom/UniqueDeviceID). It seems that in Android Device
Id is composed by:

uuid = androidID + deviceID + simID;


> I upgraded to the latest version of Copay for Android but I still can't
> access the wallets.
>

Because your data is still encrypted. One unencrypted, data can be
migrated, but first the correct deviceID is necessary.


> Is there any way to restore access without uninstalling Copay and
> reinstalling?
>

I dont think so. If you cannot restore the original deviceID, the easiest
way would be to uninstall, and install and restore the wallet backups.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3523#issuecomment-160516742>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
