### ISSUE TITLE
Cannot import breadwallet seed due to "invalid derivation path"

### ISSUE THREAD

**Issue by snakecharmer1024** [bitpay/copay#3564]
Breadwallet says their derivation path is 

m/0'/0/0

but when I enter this into the derivation path when importing into copay, I get 

"invalid derivation path"

I'm trying to import my breadwallet so I can sign messages with my private keys...

**Comment by matiu** [comment]
For the moment, only BIP44 paths are supported.

**Comment by koalalorenzo** [comment]
I am running into the same problem as reported here:
https://www.reddit.com/r/btc/comments/48sg13/move_from_breadwallet_to_copay/

Any Idea? Should I create a new wallet from a new seed? I would like to avoid that!

**Comment by matiu** [comment]
Breadwallet does not use BIP44 address derivation standard, but uses a custom schema (https://github.com/voisine/breadwallet/issues/131), therefore you can not directly import your Breadwallet seed into Copay. You will need to create a new wallet and move your funds there.

**Comment by dabura667** [comment]
Note: breadwallet has stated multiple times that one of the main reasons they don't switch over to BIP44 is because they believe using the same private keys on multiple devices and apps spreads your exposure surface leading to less security.

With crypto, you can only degrade your security, you can never restore the security of a degraded key.

Recent revelations on specific attack vectors on iOS and Android proves that you want as small an attack surface as possible.

**Comment by dan-da** [comment]
or in other words, customer lockin.

**Comment by snakecharmer1024** [comment]
I was able to load it with multibit, fyi

**Comment by nmarley** [comment]
Just for clarification, BreadWallet doesn't use a custom schema, but the "Default Wallet Layout" defined in BIP0032: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#the-default-wallet-layout

There's no lock-in at all.

**Comment by bitcreatenow** [comment]
Use derivation path m/44'/60'/0'/0. This works fine.
