### ISSUE TITLE
SPV mode for more decentralization

### ISSUE THREAD

**Issue by caveman1973** [bitpay/copay#3601]
Copay uses a centralized validation. According to bitcoin.org "Copay wallet relies on a centralized service by default. This means a third party must be trusted to not hide or simulate payments."

Is it possible to use SPV mode similar to Bread Wallet? According to bitcoin.org "Bread Wallet uses SPV and the Bitcoin network. This means very little trust in third parties is required when verifying payments. However, it is not as secure as a full node like Bitcoin Core."

Using SPV won't make Copay more secure and trustworthy? Why Copay doesn't use it?

**Comment by matiu** [comment]
> Is it possible to use SPV mode similar to Bread Wallet? 
No

> Why Copay doesn't use it?

There are several reasons, some that I can think now are:
 - Because Copay is a  multisignature wallet, it already needs a coordination server to handle the transactions proposals. 
 - Wallets that relies on a block explorer API can be faster to use / sync, and can use less network traffic. This is more notable in mobile devices and in places with network speed is not great.
 - Extra services can be provided by the server (like having an encrypted backup of the addressbook)
 - Notifications (like emails) can be send when incoming transactions are detected.

We tried to mitigate the 'centralized dependency' problem with:
 - The wallet service does not hold, not even encrypted, the copayer's private keys 
 - The wallet service is open source, and anyone can be setup one, and use it from Copay, not relaying on Bitpay
 - Migrating a wallet from a server to other is just a one-click procedure in copay.
