### ISSUE TITLE
Does Copay really use BIP45 ?

### ISSUE THREAD

**Issue by NicolasDorier** [bitpay/copay#3729]
I've tried get back my private key from my copay backup.

I had no luck generating the same address than expected using BIP45:

So here are my questions:

* Why does the xPrivKey and xPubKey of the JSON does not match ?

I tried to generate several path in the tree, I could not find a xPubKey matching a derived HD pubkey from the xPrivKey.

* My key ring is : "derivationStrategy":"BIP45","account":0,"addressType":"P2SH", so I tried to generate 1-1 multi sig P2SH using the path m/45'/0/0/* by using both xPrivKey and xPubKey... why don't I find the same address than those derived by my copay wallet ?

**Comment by dabura667** [comment]
Depends on when you made the wallet.

Copay abandoned BIP45 a while back.

I can explain tomorrow, message me, I have some tools.

**Comment by NicolasDorier** [comment]
xPubKey is 45'. Don't manage to derive the addresses though.

My wallet is old version so it still use 45' P2SH 1-1. (The first generated address was P2SH 1-1 multi)

**Comment by NicolasDorier** [comment]
Hooray, I found it, using key path 0x7fffffff !

**Comment by kost123** [comment]
Could you help me to get mine too? what do I need to do?

**Comment by dabura667** [comment]
https://bitpay.github.io/copay-recovery/

**Comment by joemphilips** [comment]
I would like to know why copay have abandoned bip45. @dabura667 what was the problem?

**Comment by dabura667** [comment]
1. BIP45 solves the problem duplicate address generation. ie. A B and C make a multisig, but if they all generate the same path for receive address generation the A and B might send the same address to two different customers and if the invoice amounts are the same, both will think they have received when only one has sent.
2. Therefore, BIP45 is only usefull when copayers can not communicate before generating every address.
3. Since Copay started using BWS, everytime someone generates an address, it asks the BWS server, “which index should I generate?” So you are always communicating. (This is why Copay can not generate addresses offline)
4. Since there is communication always, BIP45 only add extra overhead, and gives no benefit.

**Comment by Keensyst** [comment]
I don't understand why I have not been able to collect my bitpay on my wallet

**Comment by joemphilips** [comment]
perfect! thanks.
