### ISSUE TITLE
Show only the icons of (Receive, activity, send)

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3927]
Hi,

I think the height of buttons bar is high. I think Copay should only show the icons and not the names of receive, activity and send. Something like twitter app.

Please consider it. Thanks

**Comment by Jacobbubble** [comment]
I would prefer collapsible text. This is seen in a lot of material design. 

Copay has a single UI that runs on large screens so I don't think it makes sense to get rid of the text altogether since I believe the text adds to the UX.

Not against the idea of collapsing the text on very small screens (less than 3.5" or so).

**Comment by matiu** [comment]
The names are replaced for address book entries, TX descriptions (if given) and TX comments (if set), so I think the do add value to the user.
