### ISSUE TITLE
API question/suggestion

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3928]
Hi,

I would like to know if is possible an android app request to spend bitcoins from copay. And if is possible to setup copay to automatically do this. So a specific app could automatically spend bitcoins from a specific wallet of copay without any user action on copay app.

Thanks

**Comment by dabura667** [comment]
> without any user action on copay app.

This is extremely insecure.

**Comment by matiu** [comment]
Check bitcore wallet client and bitcore wallet service. Copay use both.

**Comment by lucaszanella** [comment]
We had this idea because of services like shakepay.co. By having a channel open with them, we could pay something via NFC through their app, the money would get discounted from the copay's wallet if I pressed ok, the money would be sent to shake or bitpay without any fees, and them shake/bitpay would credit me with dollars to be spent via NFC, all of this at the same time. In this way I could trust all my funds to be used by third party apps without having to make them hold my bitcoins. Security measures like only making it possible to pull from a specific wallet, and limit by purchase, for example, could be added. I don't see this as insecure.

**Comment by matiu** [comment]
answering the OP, it is not possible due to security reasons. 

You can use `bitcoin:`  URL to trigger copay from other apps.
