### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by maxguzenski** [bitpay/copay#3960]
On OSX Copay don't update himself automatically, is this some kind of limitation or just not implemented yet?

**Comment by dabura667** [comment]
Chrome version updates automatically (this is forced by Chrome Store, you can't NOT update automatically) but in general, you don't want financial software to update automatically, which is why the standalone versions don't.

If you would like auto-updates, use the Chrome extension version.

Chrome is a great browser imo. Sorry if you don't like it.

**Comment by maxguzenski** [comment]
I didnt say nothing about chrome ;)

**Comment by matiu** [comment]
We have a planned feature to notify new version on desktop versions: https://github.com/bitpay/copay/issues/3548

but it wont autoupdate.
