### ISSUE TITLE
Copay added to mac homebrew cask system

### ISSUE THREAD

**Issue by bektar** [bitpay/copay#4007]
I've added copay to the homebrew cask system on mac os x. It is now possible to install it using

    brew cask install copay

if homebrew is installed. Maybe this should be added to the installation instructions, at least on the github page?

**Comment by martindale** [comment]
Great idea!  Thanks for making this happen.  You should submit a pull request by [editing README.md directly on GitHub](https://github.com/bitpay/copay/edit/master/README.md), which will guide you through the process of submitting a modification.

**Comment by matiu** [comment]
Thanks a lot for this.

I am not familiar with brew cask, I see: https://github.com/caskroom/homebrew-cask/blob/master/Casks/copay.rb

How is the procedure to update it? Given that a modified Cask pointing to a wrong repo could
stole bitcoins from users, we need to understand in detail how the updates are done, and how will have the right to modify that file.

thanks.

**Comment by bektar** [comment]
Tbh I don't fully understand how it works, but as far as I can tell it's automatic. It's reading from your github releases feed. I'll have a chat with the homebrew people to make sure.

If you are curious for yourself the relevant can be found in [appcast.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) and [adding_a_cask.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) on the brew github page.

**Comment by bektar** [comment]
There is a script that needs to be run after a new version has been released. It doesn't have to be run by you specifically, but someone has to do it.

Instructions can be found on: [updating a cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)

**Comment by kleetus** [comment]
Not knowing everything about Homebrew and the Cask system, can we include a PGP signature with the distribution and can Homebrew check the signature?

**Comment by bektar** [comment]
I can see that there is a field for a gpg at least, don't know about pgp. I don't know the specifics on how it's used either. I'll have another chat with the brew people and get back to you (hopefully tomorrow).

**Comment by bektar** [comment]
Hmm, i didn't know that pgp and gpg were compatible… TIL (never used either one).

As far as i can tell there should be no problem including a pgp key. When you run the script i mentioned above i would assume that you just include the pgp signature in the gpg field. See [cask_language_reference](https://github.com/caskroom/homebrew-cask/tree/master/doc/cask_language_reference).

**Comment by kleetus** [comment]
I just attempted to install copay using:

`brew cask install copay`

the sub shell returned 0, success, but:

`Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3548, done.
remote: Compressing objects: 100% (3492/3492), done.
remote: Total 3548 (delta 57), reused 757 (delta 34), pack-reused 0
Receiving objects: 100% (3548/3548), 5.92 MiB | 3.75 MiB/s, done.
Resolving deltas: 100% (57/57), done.
Checking connectivity... done.
Tapped 1 formula (3513 files, 25M)
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
==> Downloading https://github.com/bitpay/copay/releases/download/v1.9.4/Copay-osx.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask copay
==> Symlinking App 'Copay.app' to '/Users/myuser/Applications/Copay.app'
🍺  copay staged at '/opt/homebrew-cask/Caskroom/copay/1.9.4' (249 files, 96M)`



there is no symlink to 'Copay.app' to '/Users/myuser/Applications/Copay.app'. Granted I had a previous install of Copay in Applications.


I am pretty sure we can get caskroom to preform the signature checking using the DSL (thanks @bektar for checking into that), but I would REALLY like the user performing the brew install to have the Copay key already imported in order to check the signature: 

https://pgp.mit.edu/pks/lookup?op=get&search=0x5CD600A61112CFA1

So maybe the end result is to first check for a suitable key on the keyring. Remind the user to perform a manual check that the Copay key is a legit key (as much as possible using web of trust). Only then, will a brew install function. The user should review the output of the brew install as well.

**Comment by bektar** [comment]
I checked brew for the new 1.9.7 version and it is already there. I can see that it is downloading from the correct url, but I don't really understand the pgp stuff, so I'll leave you guys to figure that out :)

**Comment by bektar** [comment]
oh, and I actually tried running the upgrade script (but aborted when i saw that the new version was already there) and i got the following output (don't know if it is useful for anything):

    $ cask-repair --pull origin --push $github_user $outdated_cask
    -------------------------------------------------------------------------------------
    cask 'copay' do
      version '1.9.7'
      sha256 '1325eb34c9c5244a9551f27a314c13537043141d09ef86b7c3fd0fb21c50a4bd'

      # github.com/bitpay/copay was verified as official when first introduced to the cask
      url "https://github.com/bitpay/copay/releases/download/v#{version}/Copay-osx.dmg"
      appcast 'https://github.com/bitpay/copay/releases.atom',
          checkpoint: 'aad77ea2cf8e892b9820d586fa33264b55c3e8fad61923ae1c7b5dd58b18472e'
      name 'Copay'
      homepage 'https://copay.io'
      license :oss

      app 'Copay.app'
    end
    -------------------------------------------------------------------------------------
    Type the new version (or leave blank to use the current one)
    > ^C
    You aborted

**Comment by kleetus** [comment]
I just realized that I was mistaken on the caskroom not symlinking, it does symlink, except to ~/Applications and not /Applications. 
$ which Copay.app  
yields the one in ~/Applications

**Comment by kleetus** [comment]
Ok, so I think once:

https://github.com/caskroom/homebrew-cask/pull/16090

is merged, we can revisit this issue.

**Comment by matiu** [comment]
Closed until caskroom/homebrew-cask#16090 is implemented
