### ISSUE TITLE
Signature rejected by server/ Response could not be verfied 

### ISSUE THREAD

**Issue by mc25** [bitpay/copay#4116]
I am unable to sign transaction in a 2/2 multisig wallet, no matter who created the transaction. 

https://goo.gl/photos/BJzdwhk8U1TviLqGA
https://goo.gl/photos/cuRLGQsY4uQUxHMr7

**Comment by matiu** [comment]
What Copay version are you using? Can you send us your wallet id in private (matias@bitpay.com).

You can get the wallet id from:  Settings -> Advanced -> Wallet Info

**Comment by matiu** [comment]
Fixed offline. thanks.

**Comment by abishekk92** [comment]
i am having the same problem with a 1/1 wallet.

**Comment by mc25** [comment]
I restored from seed…

**Comment by najmina** [comment]
I cannot send transaction since 18 hours ago.
Signature rejected by server.
I need help.

**Comment by matiu** [comment]
@abishekk92 Please see https://github.com/bitpay/copay/wiki/Signature-Rejected-by-the-Server-or-Cannot-verify-Server-Response

Provide the required information and we will try to help you.

**Comment by abishekk92** [comment]
@matiu I recovered the wallet from the recovery seed. For what it is worth, I was using the latest version(< 1.11.0 unless this was released few days ago) on One Plus Two running Oxygen OS 2.2.1, another thing worth mentioning is that I couldn't recover the wallet using the same app, I had to use the Mac App to recover it, looks like the problem is specific to Android.

**Comment by matiu** [comment]
Thanks a lot for the comments. The issue seems to be related to Android 6.x

We will try to reproduce it.
