### ISSUE TITLE
sent money from glidera but accidentally used the bitcoin address in my wallet

### ISSUE THREAD

**Issue by ashleyt79** [bitpay/copay#4122]
I have a deposit coming to Glidera next week- it was a new account so it is taking several days- the issue is I set it up to go directly to a Copay bitcoin address which I accidentally used already & I know they refresh once used. What can I do? I have emailed Glidera & have been unable to get a response for 2 days. I just want to know what will happen to my money.

**Comment by matiu** [comment]
While address reuse is not recommended due to privacy concerns, there is no
other problem on reusing and address. Your copay wallet still manage old
addresses and if funds are transferred to it, you will see then on your
balance and you can operate with them with no problem.

Pro Tip: you can see all your wallet addresses at: settings > advanced >
wallet info
