### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#4162]
Can you add the possibility to work on the italian translation on Crowdin?

**Comment by cmgustavo** [comment]
Hi @HostFat , I just added the italian language to the list. 

We were considering to add languages that have more than 95% of the completed translation. So, many languages were removed because they ceased to maintain. But we can add it again if the translators can return to work.

We appreciate your effort and we hope that you can keep up to date the translation.

Thanks!

**Comment by HostFat** [comment]
It's good to add languages only when they are nearly complete, but removing them from Crowdin make it even less probable that someone will complete them :D

**Comment by dabura667** [comment]
@HostFat I agree with you, but apparently some site scouring crowdin data will penalize us for having non-translated languages available...

Or something like that. I still don't quite understand.

**Comment by HostFat** [comment]
With the help of some people the italian community, the translation is completed! :D
