### ISSUE TITLE
Doesn't rotate to landscape orientation on Android

### ISSUE THREAD

**Issue by shrugal** [bitpay/copay#4210]
The Android app forces portrait orientation and doesn't autorotate to landscape. This is especially bad on tablets!

It actually works well with an app that forces landscape on all apps, so I guess fixing it should be as easy as changing the manifest file.

**Comment by cmgustavo** [comment]
Hi @niggo372, 

Copay was designed to use in small screens (mobile), so autorotate to *landscape* is not allowed (by manifest file). In order to support *landscape* is needed some modification to layout (for example, show menu in landscape and hide menu in portrait orientation). We think that probably it will be ready in next versions.

Thanks.

**Comment by niggo372** [comment]
@cmgustavo I agree that there is some more work to be done before larger screens are properly supported, but as I stated in my first post: If you use another app to force landscape orientation on all apps, then the current Copay version works just fine. It's not as great as a properly tablet-optimized app, but it's far better than rotating to portrait mode on a tablet, especially if you have a keyboard attached. The current state is just infuriating to use.

So what I would ask from you is to just remove the flag that forces portrait mode, even before further optimizations for landscape mode arrive. I guess (by your use of "versions" instead of "version") that these modifications could take a while until they are ready, so why not make the app usable on tablets now, and then improve the experience later?
