### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by hoghip** [bitpay/copay#4260]
I need help, if you can, recovering some 50,000 Bits. 
  The bits were sent to my copay account.  However, I made a mistake setting up my copay account and downloaded a android version of copay onto a windows phone.  This made it inoperable.  I uninstalled copay from the phone, reinstalled the correct version and used the correct 12 word wallet seed to reinstate the account.  However, this did not work. What if anything can I do.
Thanks
 Randy

**Comment by dabura667** [comment]
> used the correct 12 word wallet seed to reinstate the account.

When you tried to reinstate the account... did you choose "create wallet" or "import wallet"?

"Import wallet" is the correct one.

**Comment by JDonadio** [comment]
Hi @hoghip, in order to restore your wallet correctly, follow dabura's comment and try to import your wallet. If you have the _seed_ don't worry about the uninstall or migrations error. Just use [this tool](https://bitpay.github.io/copay-recovery/) and send that funds to another **safe wallet**. 

To clarify: your wallets are stored in the server, so the fact to uninstall Copay doesn't means that your wallets are gone, but you remove the way to handle them. You can also try the [chrome](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=es-419) version.

**Comment by hoghip** [comment]
Yes I used import wallet and it said my seed was not valid. Thanks for your help 

-----Original Message-----

**Comment by matiu** [comment]
Thanks @hoghip we enhanced the error display in Copay 2.0
