### ISSUE TITLE
Click on a  bitcoin: link, if Copay is already open does not work as expected

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4277]
on IOS, it does not show the list of wallets to select where to pay from. (Only if Copay is already open)

**Comment by gabrielbazan7** [comment]
I reproduce the error. When copay wallet is minimized, works as expected, the problem is when copay is closed. Copay start with the list of wallets to select, then the app refresh automatically and change the route to activity screen.

**Comment by gezman** [comment]
I have very similar problem. Could you please look at this?

Introduction:
I'm creating application with option to pay bills using bitcoins. When I got everything what is needed to bitcoin transaction I try to open inside my iOS app an URL: "bitcoin:<address>?amount=<amount>", then your App is coming to live and there I have two cases:

Case - 1:
When your App Copay is totally closed, then you app is launching and everything works perfect. It means that I'm able to choose wallet and pay my bill with bitcoins.

Case - 2:
When your App Copay is in background, then app is taken to the foreground and screen for choosing wallet is come only for an "one second" and automatically main screen with all transactions is opened. The result is that I lost my possibility to quick payment, because my predefined payment is gone.

In addition:
I use testnet wallet maybe this is the matter.

**Comment by matiu** [comment]
We should consider migrating to https://github.com/phonegap/phonegap-plugin-barcodescanner/commits/master

instead of 
https://github.com/JrontEnd/phonegap-plugin-barcodescanner/commits/master

and check on a Nexus 5x device.

**Comment by matiu** [comment]
Add info to this issue: Tested on Android 6, and work as expected, both with Copay closed and in background.
