### ISSUE TITLE
Improve backup process for new users

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4403]
I introduce new people to Bitcoin with CoPay on a daily basis. A HUGE impediment to the process, and distraction from the discussion, is the forced backup once the Receive button is pressed.

I would like to see the forced backup process be turned into a persistent nag AFTER the wallet has 50,000 bits.

**Comment by matiu** [comment]
I see you point, we used to have it that way before but nothing prevents a user to deposit a large amount on a new wallet on the first transaction. 

Given that we had *many* cases of people losing money because they didn't have the backup, we decided to force it before showing the first address. While it has obvious disadvantages, we prefer to be on the safe side in this case. 

Forced backup is only disabled on testnet wallets.

**Comment by Derrick-** [comment]
This is an issue for me too. I don't mind writing down seed words eventually, but my primary and preferred backup method is Export to Email. The ability to create a new account without pen and paper would be more pleasant.

**Comment by JulianTosh** [comment]
Given that I had a wallet that was backed up with ~ $170 and is still not able to be recovered (#4182), your defense has no weight.

The likelihood of a new user depositing more than $50 their first time is not likely and an experienced user depositing more than $50 without a backup kinda needs to get what they deserve.

**Comment by JulianTosh** [comment]
How about we meet in the middle.

If the wallet has not been backed up, then the receive tab will only show the "Request a specific amount" page where you have to enter in an amount. The interface will only allow an amount up to 50,000 bits when the wallet has not been backed up.

That would be a perfect compromise.
