### ISSUE TITLE
I cant see my bitcoin wallet balance

### ISSUE THREAD

**Issue by michaelbest6** [bitpay/copay#4479]
Please i dont know whats happening to m wallet..
i have about $500 worth of bits in my btc wallet..
in my phone i cant see the balance.. but in my pc i do see the balance..
recently.. the copay wallet in my pc is still updating wallet ffor 5 hours now..
Is my btc safe????

**Comment by matiu** [comment]
Can you send a screenshot?

You can refresh the balance on you phone by tapping it.

**Comment by michaelbest6** [comment]
![my pc](https://cloud.githubusercontent.com/assets/20089748/16266352/46dc09d4-3839-11e6-9b4c-2e902718a51b.jpeg)
i uploaded 2 pics now.. 1 is my pc the second is the wallet in my phone.. the one i personally imported to my phones now seems like a new wallet after the backup i did and recovered.. 
i am not just happy..  i can send my transaction details if u want..
![my phone](https://cloud.githubusercontent.com/assets/20089748/16266380/71520cea-3839-11e6-9cc5-e2905c7dda47.png)

**Comment by michaelbest6** [comment]
i have not had issues with copay before.. why now i have saved alot of money.. am i scammed??

**Comment by matiu** [comment]
could.you send me your wallet Id to matias@bitpay.com? you can find it at
settings > advanced > wallet info

if you need inmediate access to your funds please try the Copay Recovery
Tool.
On Jun 22, 2016 09:25, "michaelbest6" <notifications@github.com> wrote:

[image: my pc]
<https://cloud.githubusercontent.com/assets/20089748/16266352/46dc09d4-3839-11e6-9b4c-2e902718a51b.jpeg>
i uploaded 2 pics now.. 1 is my pc the second is the wallet in my phone..
the one i personally imported to my phones now seems like a new wallet
after the backup i did and recovered..
i am not just happy.. i can send my transaction details if u want..
[image: my phone]
<https://cloud.githubusercontent.com/assets/20089748/16266380/71520cea-3839-11e6-9cc5-e2905c7dda47.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/4479#issuecomment-227727022>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAGCHHx67pE6EFxEPNfIEfJa46aC9L3xks5qOSmggaJpZM4I7tJd>
.

**Comment by michaelbest6** [comment]
done...

**Comment by matiu** [comment]
fixed offline.
