### ISSUE TITLE
How to get HD PubKey

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitpay/copay#4500]
How to I export my pub key so that someone can pay me via HD addresses?

**Comment by dabura667** [comment]
This can not be done through Copay, you will need to use an external tool.

However, I highly recommend NOT to do that.

The only reason I could see for it is if you are sure you won't be able to contact that person for a long time.

But in that case, what if you lose your wallet and you can't contact the other party? They will continue sending money to a lost wallet.

Send an address to them every time you need them to send to you.

**Comment by bitcoinbrisbane** [comment]
The reason is we have built a service, to automatically send payments to a user each week / month etc.  User are also asking for increased privacy.  A HD wallet makes sense.

**Comment by matiu** [comment]
You can see that HD key on Settings > Advanced > wallet info
Please note that if you are using multisig, you need the HD key of all the copayers. Also if you will be receiving payments, the recipient will probably need to trigger an address scan from the same window, periodically (to detect new payments). But, I agree with @dabura667 that unless you know very well what you are doing it is not a good idea, since there is no standard way to do it.

On that note, we wrote a proposal for this sometime ago: https://docs.google.com/document/d/1_ZMnFXLvsWIc-MFh6bCUFfjT_ptR_Lmvda1Jgyi1DlI/edit?usp=sharing

would love to know you feedback (+ @dabura667's)

**Comment by bitcoinbrisbane** [comment]
Thanks, but if i follow your instructions:

1. The pub key is truncated
2.  There is no way to cut and paste it

**Comment by matiu** [comment]
Are you on mobile? That could be a bug.

As a workaround: 
1) import you wallet on desktop and you can copy it there. (the ... will be expended when it copied)
2) OR regenerate the xpub from the mnemonic using any tool like: https://dcpos.github.io/bip39/

**Comment by dabura667** [comment]
@matiu 

> The wallet software must decide how to determine a suitable value for x, but it must be scannable from the root node, so funds can be recovered without other information.

This is glazed over like it's a small problem, but this is THE biggest problem to these types of address schemes.

BIP47 has to run around in circles using bloom filters or "notification addresses" in order to accomplish that one seemingly simple task.

Also, I think BIP47 comes up short in the one fact that there is no way to revoke a code.

1. People should not reuse addresses for many reasons, one most important one is that unless you are in constant contact with the user, you have no idea whether they lost their private key or not. Also, Bitstamp got hacked, and everyone decided to deposit to their bitstamp addresses (so they could sell) from their "contact books" on Electrum etc. and just ended up sending the hacker more money.
2. Reusable payment codes are necessary to generate new addresses each time.
3. However, generating them in such a way that the receiver always knows how many payments they have received without using a method that leaks pubkeys from one sender to the other (ie. making x consecutive, if I'm x = 56, I can look at x = 55 and x = 54 and see payments.) is extremely difficult.
4. Out of band solutions are the cheapest, but then the guarantee of recover-ability is gone. On-chain solutions are recoverable but cost a ton.

Also, I think that base58 with a simple 4 byte checksum is not so good. using base64 or base32 with some sort of error correction algorithm would be better. Since reusable codes are way too long to read anyways, so it will likely only be in QR code.
