### ISSUE TITLE
CSV compatible with LibraTax

### ISSUE THREAD

**Issue by BitGive** [bitpay/copay#4530]
Hey Guys! I am looking to upload a CSV file into our LibraTax account (or even better have a direct integration). The CoPay CSV wasn't accepted by LibraTax. I have also sent LibraTax a help/support question. Any suggestions? Thanks! Connie

**Comment by matiu** [comment]
Hi Connie.

Libratax CSV import is very strict. Since we need to include more information in our exports, we decided to break compatibility.

In order to import a CSV from Copay in Libra Tax you need to edit it manually. 2 simple changes need to be done:
 1- rename de column 'Decription' to 'Note'
 2- delete the entire column 'Comment'

thanks!

**Comment by BitGive** [comment]
Thanks, Matiu!! I'll try this. Hope you're doing well!

**Comment by BitGive** [comment]
It worked! Thanks!

**Comment by cmgustavo** [comment]
@BitGive , 

The Libratax team has recently updated their system to be compatible with Copay. So, it isn't necessary to do any changes in the CSV.

Thanks!

**Comment by BitGive** [comment]
Thanks!
