### ISSUE TITLE
Bitcoind 0.12 seems to return -1 always for nbBlocks=1 estimatefee

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4618]
move fee levels to:
2: prio
3: normal
6: low
24: extra low

**Comment by dabura667** [comment]
The reason for this:

nBlocks will only return a value if over a certain percentage of new transactions confirm within that window.

As we get more and more congested, 2 will also return -1... Then 3 will as well, and so on.

Perhaps patching the estimatefee function to not return a -1 with insufficient data, and attempt to give the best estimate possible would be a good idea?
Because of recent transa

**Comment by KeyJockey** [comment]
Or... also, hey... howza bout, maybe let advanced users manually edit their fee value too!
😃 😃 😃 😃 😃  (ducking and running away now from objects being thrown at me...)

**Comment by isocolsky** [comment]
Fixed by https://github.com/bitpay/bitcore-wallet-service/pull/596
