### ISSUE TITLE
Cannot Import Ledger Hardware Wallet

### ISSUE THREAD

**Issue by crwatkins** [bitpay/copay#4670]
Chrome app v2.4.1 on Mac with Ledger app and Nano S

1) IMPORT WALLET
2) HARDWARE WALLET
3) WALLET RECOVERY PHRASE:  Ledger Hardware Wallet
4) Account Number: 1

I get asked by Ledger to confirm release of the xpub and I allow that.

Result:  Error message on Copay wallet:
`Could not import: Wallet not registered at the wallet service.  Recreate it from
  "Create Wallet" using "Advanced Options" to set your recovery phrase
`

Expected Result:  New wallet created

Note:  If I try to use "Create Wallet" as the error message suggests, there is no Ledger listed under the recovery phrase option (just Trezor).

Note:  If I try the above procedure but use "Account Number 0"  Copay displays "Waiting for Ledger..." forever.  Ledger never asks about releasing the xpub.  There seems to be something strange about Account 0.

**Comment by matiu** [comment]
Hi Craig.

Some fields levels are wrong (Recovery phrase should be read a 'wallet seed' in some places, we will fix it on the next release.

Regarding the problem:

In Copay, Importing mean importing a wallet in your Copay instance, that already exists on the wallet service.

If the wallet is not on the wallet service, you need to go to "Create" as the message tries to explain.

Legder is only supported for multisig wallets . We discussed that a the implementation time with the ledger guys, because some API limitations. It seemed to make sense for 1-1 wallets to use the Ledger Chrome App directly, and for multisig, Copay. This is why the option is not available on Create (if you are on the "Personal Wallet" tab). 

See https://github.com/bitpay/copay#hardware-wallet-support

**Comment by crwatkins** [comment]
Thanks! Out of pure curiosity (not a feature request) do you recall why you decided against P2PKH (what the limitation was -- it seems like P2SH would be much harder)? (I've asked the same of Ledger.)

On a very related topic (let me know if you would prefer a new issue created) Copay will not allow account 0 (only account 1 or above) in the multisig Create process with Ledger that you describe above (It displays an error message about the account being invalid.  By the way, the error message is often scrolled off the top of the window and it is not obvious anything has happened.  Why is 0 illegal?

Also, I believe there is something strange going on in Copay once it displays that error.  It doesn't seem to be able to use any other accounts.  If I switch to account 1, I get a grayed "Waiting for Ledger..." display.  However, my Ledger app seems fine, and it even takes API calls from other "wallets" (https://www.ledgerwallet.com/api/demo.html) just fine.

**Comment by JDonadio** [comment]
Wording solved. Please feel free to open a new issue with your doubts.
