### ISSUE TITLE
Duplicated Transaction

### ISSUE THREAD

**Issue by bijeebuss** [bitpay/copay#4694]
Not sure if this is the right place for this but the support link on copay.io leads here. Also I'm not sure if this is repeatable but someone should be aware that it's possible. 

I scanned an invoice qr code to send 494,184.40 bits to 1Kp2dXVX98HWnjxpgBD61VpZD41bv4WMYd then tapped send and confirm. The screen froze on the confirmation page so I force closed the app. Then when I reopened the app I saw two transactions with the same fee, to address, and amount.

d71009204e3ff9a45b99ad5e1cb2c32eb351bf662c616ad08fc426feb2788c2e
f86f5fea97c03eb32106a1eb9bebcd1913e966e7f576b4d1c393c7269d3e444c  

Im using the iOS version.

**Comment by matiu** [comment]
Copay has a confirmation popup between transaction. The inputs signatures are created after that confirmation. Given that the inputs of both transactions are different, it does not seems the signatures can be produced  "automatically" due to a UX problem.

**Comment by bijeebuss** [comment]
Is it possible that two confirmation pop ups were loaded onto the ui stack at the same time and I clicked confirm on both thinking nothing happened when confirm on the first one actually popped the second confirm into view?

**Comment by casascius** [comment]
Hi, I think I'm having the exact same problem.  I had 2 recent double payments go out - same fee, same destination - and I'm absolutely certain I didn't confirm them twice.

Both of them were to Coinbase's web merchant dialog where I had sent a payment with a normal (non multisig) wallet after having scanned the address via a QR code.  So, some exacerbating factor could be present there.

In my case, the two addresses that received duplicate payment are as follows:
https://blockchain.info/address/1KCCtQpVchK9wfNcYNK5yb7kNXLMSpNMNN
https://blockchain.info/address/15hQYSoxsq7buyWUtKmC4o5rxXTaLHpnco

I'm also using the iOS version.

Unlike the OP, the app didn't crash on me.  It gave me no warning I had sent two payments.  They went out so close in time (judging by blockchain.info timestamp) there's no way I could have done them somehow forgotten having done so.  I just discovered it today as I was going through my transaction history within the app, wondering why my wallet balance was lower than expected.

**Comment by casascius** [comment]
Just to follow up for testing purposes (to test the hypothesis that this only happens when you scan a QR code meeting some sort of criteria) I went to the same Coinbase merchant and did the same workflow to get a QR code, the same way I got QR code for the two previous transactions that got duplicated.  Then instead of making a payment, I just used a normal QR reader to decode the following plain text:

bitcoin:19BX7y7hEvjB81jR5c1MCKz4jiEBUJLxRS?amount=0.153306&r=https://www.coinbase.com/r/57f934ed5de12c7194184d80

(and here's the QR image, if this worked properly)

<img width="422" alt="screen shot 2016-10-08 at 12 08 27 pm" src="https://cloud.githubusercontent.com/assets/957584/19215044/01212688-8d50-11e6-837d-49524c47150e.png">
