### ISSUE TITLE
Make Amazon gift cards menu optional, like Glidera and Coinbase

### ISSUE THREAD

**Issue by franamati** [bitpay/copay#4712]
It would be nice to have an option to remove the gift card menu, similar to what we already have with Glidera and Coinbase.

It is an option even less related to Bitcoin than Glidera and Coinbase, and with no use for most of the world. Thanks.

**Comment by KeyJockey** [comment]
Agree +100

Seems to me like the nice clean simple Copay we all know and love is getting a mite cluttered up these last few days.  Are these features really more important to do first? Than, say, oh I don't know... maybe better MINER FEE control for *advanced* users??

In fact I posted THIS a while back on Reddit... 

https://www.reddit.com/r/btc/comments/4yju6l/copay_wallet_fork_anyone_interested/ 

...thinking maybe it's time for someone to fork this and return to simple clean elegant design.

The reddit post got a little attention and some positive comments but then unfortunately sort of faded.  Nobody piped up about IF they'd be willing to spend any money with me on the project, even if I fronted most of the cost and/or just managed it via some crowdfund site project.

Maybe that's still possible...?  

Anyone around HERE feel like they'd be WITH ME on something like this?

**Comment by dan-da** [comment]
I have no use for glidera or coinbase.   In fact I haven't upgraded since about 6 months ago.

I would love to see the Copay team focus on the core functionality that attracted to me in the first place:  namely multi-signer functionality.    In particular:

* it should be easy to add a view-only participant that can propose payments but not sign.
* there should also be a view-only participant that cannot propose payments, eg for auditing/accountant.
* there should be a way to handle the case when a signer leaves the company, or a new signer is added.  If key revocation is not possible then there should at least be a process for m-of-n signers to agree to a new x of y wallet and sweep the funds into it, while preserving tx history.

These two features would make the wallet much more usable for organizations.

All of this is possible and I have brought it up several times, but the team has prioritized features that I find non-compelling instead.

If a fork were created that implemented the above features, I would certainly switch to it.

**Comment by KeyJockey** [comment]
>>> the team has prioritized features that I find non-compelling instead

That's the heart of the matter here, frankly.

Now, we probably can't entirely *blame* them, as the order to do so probably came down from above, i.e. BitPay's management who probably needed to at least somewhat monetize this project in order to keep supporting it.  I'm assuming that Coinbase, Glidera, Amazon etc probably paid something for what they're getting here.  

Nothing wrong with that IF it's your cup of tea but for a general open-source FOSS project, maybe a different team can do better?

As I've said elsewhere (repeatedly LOL) I'm not a programmer myself and couldn't code my way out of a paper bag if my life depended on it -- a little raw HTML and (even less) JavaScript from time to time is all I can manage.

However I *am* a fairly good UI designer and "human interface" theorist, I think... FWIW the bug report issue to merge Copay's initial four tabs into the current, nicer and more streamlined, THREE simpler tabs was my issue at first, I believe, and I was very happy when the Copay team accepted my suggestion for that and implemented it (very well).

OTOH I've been more than a little frustrated that my own major personal huge pet peeve issue about MINER FEE CONTROL has gone absolutely nowhere, after a year here, even with more than a little user support.  Getting THAT done if it's at all possible will be my Number ONE main motivation to directly manage or at least just SUPPORT a fork project.

Who else is with me here on this?

P.S. If it's not appropriate to discuss here, my apologies and we can move the topic off to one of a few forums that I have available for other businesses, or maybe just another GitHub...?

**Comment by matiu** [comment]
@dan-da @KeyJockey we will be more that happy to see Copay forks to support specific use cases that are not supported on the original Copay.  Please do not troll Copay tickets with comments that are not related with the OP.

**Comment by Endogen** [comment]
I would also like to see this as a optional thing

**Comment by bitjson** [comment]
@franamati – We definitely hear you – we've been busy working on the new UI and [BitPay distribution](https://blog.bitpay.com/introducing-bitpay-app/).

With the new BitPay app available, by default, Copay will return to being that "nice clean simple Copay we all know and love" (-@KeyJockey) 😄 

The BitPay app will be tightly-integrated with services that make getting started with and using bitcoin easier, and the Copay app will contain only core wallet functionality out-of-the-box.

I think it's safe to say this issue was solved here: https://github.com/bitpay/copay/pull/4810, and will be deployed in the next update. 🚀

**Comment by raizlin** [comment]
#!/usr/bin/env ruby

module WDF

  class WFGet
    def self.current_quarter
      yr = Date.today.year
      if yr >=10
        4
      elsif yr >= 7
        3
      elsif yr >= 4
        2
      else
        1
      end
    end

    def self.todays_edgar_url
      # Current quarter, 1 - 4
      qtr_num = self.current_quarter
      # Current year 2016 format
      yr = Date.today.year
      # Filename from date
      filename = Date.today.strftime("%Y%m%d") + ".nc.tar.gz"
      "https://www.sec.gov/Archives/edgar/Feed/#{yr}/QTR#{qtr_num}/#{filename}"
    end
  end

  class Filing
    attr_accessor :primary_doc_url, :index_url, :company, :cik, :date_filed
    def initialize(company, cik, date_filed, filing_path)
      self.index_url = "http://www.sec.gov/Archives/#{filing_path}"
      self.primary_doc_url = self.index_url.gsub("-","").gsub(".txt","/primary_doc.xml")
      self.company = company
      self.cik = cik
      self.date_filed = date_filed
    end
  end

  class FilingIndex
    attr_accessor :filings
    def initialize(filename)
      self.filings = []
      parse_filing(filename)
    end
    def parse_filing(filename)
      out = ""
      text = File.open(filename).read
      text.gsub!(/\r\n?/, "\n")
      text.each_line do |line|
        parts = line.split("  ").uniq
        if parts[0] == "D"
          self.filings << Filing.new(parts[2], parts[3], parts[4], parts[5])
        end
      end
      puts "Added #{self.filings.length} Form D filings"
      puts "First filing url: #{self.filings[0].primary_doc_url}"
      puts "First filing name: #{self.filings[0].company}"
    end
  end

end

WDF::FilingIndex.new('form.20161216.idx')
