### ISSUE TITLE
(not issue) Newbie Question: about copay address generation

### ISSUE THREAD

**Issue by haries18** [bitpay/copay#4741]
Hello all,
sorry for the stupid question, I am new in bitcoin :-)  I didnt find forum for copay and it redirects me to github... so I hope this is the right place to ask.
Reading from
http://bitzuma.com/posts/five-ways-to-lose-money-with-bitcoin-change-addresses/

As written there, my concern is about the max addresses generated by copay. Is there any ?
If I generated millions of addresses since my last seed backup, would I be able to import it safely with all wallet funds intact ?
My assumption is yes, seems from the article this does not apply for blockchain base (I think copay is based on blockchain no?)
But I am not that fully certain nor understand, thats why I asked.
Please enlighten.

thanks & best regards.
haries

**Comment by matiu** [comment]
The max address GAP is 20, as stated on BIP32. (ie Copay will scan up to 20 *empty* address before stopping).

**Comment by haries18** [comment]
thanks for the reply.
Do you mean only 20 wallet addresses are possible with copay ?
Or do you mean 20 empty addresses (empty == no fund?) ?

Or do you mean if copay generated 20 addresses and all are empty, then it will stop generating and just loop back into existing empty wallet address ?

**Comment by isocolsky** [comment]
Only 20 consecutive empty addresses are allowed. After that, no new addresses will be generated and the last one will be shown in the Receive tab. However, if you receive funds on any of the last 20 addresses, it restarts the process and new addresses can be generated (how many depends on which address got the funds).

**Comment by haries18** [comment]
thanks. So basically if the generated addresses all have funds, then practically many-many wallet addresses are possible (if not unlimited), and all can be restored back using the seed, correct ?

If so, could you pls elaborate again why in the article I posted before showing concern of maximum generated addresses ?

**Comment by isocolsky** [comment]
Every single address in a Copay wallet (including change addresses) is deterministically derived from a single Master Extended Private Key (which is obtained from the 12 words). So as long as you keep these words, your funds will be safe regardless of how many addresses you have generated.
The issue is with the discoverability of the funds. The algorithm used by Copay and described in the BIP32 will generate all addresses one by one in order querying the blockchain for activity (transactions) until 20 consecutive addresses are generated with no transactions associated. If this arbitrary limit was lifted, you could in keep generating millions of addresses. So the limit is just there for practical reasons. It just works fine for 99% of the use-cases.

**Comment by haries18** [comment]
thank you. It is clear now :)
