### ISSUE TITLE
Can't create a second wallet with m/44'/0'/0'/1

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#4760]
On Copay 2.7

I've created a wallet named "Checking" with a mnemonic and derivation path m/44'/0'/0'/0 successfully.
No I'm trying to create a second wallet named "Funds" with same mnemonic but derivation path m/44'/0'/0'/1, either as a creating or importing operation, but it fails saying "wallet already in Copay" or "key already associated with existing wallet".

I believe I'm following BIP44 rules and I was expecting to create wallets like this. Am I misunderstanding BIP44? Or is it a bug?

I also noted that Copay presents a default m/44'/0'/0'/\* while BIP44 says m/44'/0'/0'/0/*. This is a bit confusing for users.

**Comment by avibrazil** [comment]
I also noted that on Advanced ➡ Wallet Information ➡ Extended Public Keys it shows the xpub and a wrong derivation path: m/44'/0'/0'. But the generated addresses are correct m/44'/0'/0'/0/* (confirmed with https://github.com/dcpos/bip39).

So I think Copay considers the xprv and xpub keys of a wallet as the BIP32 root key. While I was expecting it to consider the extended prv and pub keys.

**Comment by avibrazil** [comment]
Again, comparing Wallet Information on Copay and https://github.com/dcpos/bip39, Copay says the "Extended Public Key" is different from what dcpos/bip39 says, even if generated addresses match.

On a wallet which I deleted the recovery phrase, exporting it shows the BIP32 root private key and not the extended private key. I'm not sure if this is the right behavior. If so, there should be an easier way to import an extended private key to work with an, say, m/44'/0'/0'/1 or 2 or 3 path only, without knowing the root seed.

**Comment by dabura667** [comment]
> https://github.com/dcpos/bip39

This site is wrong, it was based off of the iOS version of Mycelium which had a bug that would export xpubs from the change index rather than the account index.

Here's a quote directly from BIP44:

`m / purpose' / coin_type' / account' / change / address_index`

So:

```
m / purpose' / coin_type' / account' / change / address_index
m /   44'    /     0'     /    0'
```

This is the xpub you want to generate keys for your account. As the change (0 or 1) and address index are both non-hardened (no `'` added)

All wallets give the xpub of the last hardened level, which makes sense.

The site you were looking at is based off a wallet that had a bug in it a while back (which has since been fixed)

**Comment by avibrazil** [comment]
Thanks for quick reply. So what is "hardened"? Can't find an explanation on BIP32 about it. Also, dcpos shows xpubs for both root and extended keys. The root key matches what Copay shows.

Also, I can't find a way to use Copay in the following scenarios:

1. Create a second wallet using same mnemonic words but with different derivation path. End result would be 2 wallets with same mnemonics, one on m/44'/0'/0'/0 and other on m/44'/0'/0'/1. First would be for everyday use and the second for investments or higher values or offline storage. According to BIP44, the change defines trees that intended for internal use (1) or external use (0).

2. Create a watch only wallet, probably from the xpub extended key of m/44'/0'/0'/1, so I can see movements or send coins to the investment subtree but not spend them. Obviously without knowing the mnemonic words.

3. Create or import a sub-wallet, say m/44'/0'/3'/0, without knowing the root mnemonic words but knowing the m/44'/0'/3'/0 xprv extended key, to be used as a slave account monitored by who actually has the root key or mnemonic words. This use case is cited as an example on BIP32.

Do you know of any other offline tool to inspect BIP32 things similar to dcpos? Maybe the code behind bip32.org ?

Thank you

**Comment by dabura667** [comment]
I made https://bip32jp.github.io/english/ a while back... kinda shitty though.

1. That would be a separate account. Use derivations m/44'/0'/0' , m/44'/0'/1' , m/44'/0'/2' so on. "Internal" "External" is a complicated way for saying "change address (for internal use of the wallet software)" and "receiving address (for giving out to people externally)" so you don't want to put down the /0 like you are trying to.
2. You can only do this with the bitcore-wallet-client library by instanciating your credentials with the xpub and some entropy (to seed the encryption keys for the server) and syncing that with the BWS server... then you could import it into Copay... unfortunately, there is no way to start a wallet like this in Copay UI.
3. This can be done by giving someone the m/44'/0'/3' xprv key and they can create a new wallet from xprv key instead of mnemonic in the advanced options on wallet creation.

**Comment by avibrazil** [comment]
1. Didn't understand. I guess I don't fully understand this last index number. I'll assume your good practice and move on.
2. Didn't understand a word of what you said. Which server? https://bws.bitpay.com/bws/api? Thats too complicated. But it is a nice feature to have in the UI, to watch cold wallets.
3. Its not working. If I paste a xprv extended (not root) key in the Wallet Recovery Phrase field along with its derivation path and no password, Copay throws the error "Key already associated with and existing wallet". If I do the same on the Import Wallet form, it says the wallet doesn't exist on the server.

All of this is way too complicated and non intuitive for regular human beings, even the ones that have read the BIPs, as me.

**Comment by avibrazil** [comment]
For example, the mnemonic "veteran dream detect ivory march breeze hurdle kangaroo dizzy pause height salt" apparently has xprv9xmMSQ55EhTJUENnfSLLhUsLKZKKW4hkVpUC7hKZMts1Ay6FCB5RoXAeygfA3aVXSonRxtf6FkqRfrrKosUX2pwNtjXjhzv73EVBu5xGMtL for m/44'/0'/1'. I say "apparently" because even developers seem to disagree about this, when comparing that tool you said is buggy with bip32.org with your bip32jp fork and with Copay itself.

But there is no way to create or import this wallet. It says key already exists (when trying to create) or wallet doesn't exist (when trying to import).

EXTREMELY CONFUSING !

Also, if I create/import m/44'/0'/0' and m/44'/0'/1' with mnemonic in Copay, both accounts/wallets get exported with root private key, while I was expecting they would get exported with extended key only.

Either the UI needs to be improved or something is buggy or documentation for users (not for crypto developers) is needed.

**Comment by dabura667** [comment]
> All of this is way too complicated and non intuitive for regular human beings, even the ones that have read the BIPs, as me.

You are trying to use Copay in a way that is not intended by the developers... so I would not be surprised if it is not intuitive.

> when comparing that tool you said is buggy with bip32.org

bip32.org does not support BIP39. the "passphrase" it refers to is merely hashed with a method distinct to bip32.org... which makes sense because the site was created BEFORE BIP39 was even thought of.

My crappy site was made for BIP39, and all the bugs are convenience ones (like, the "wrong phrase" warning check is too fast, so if you try to type in the phrase, it will pop up with alert every character you type until you actually type a valid phrase), it will generate valid keys from valid BIP39 phrases, I have tested it against many other libraries.

1. If you want to share a watch only wallet with a user, export your wallet from the Export screen with the "Do Not Include Private Key" option in "Advanced options" checked.
2. If you want to create a brand new Copay wallet directly from an xpub without ever having to create one with the private key, I made a script showing how to do it. https://gist.github.com/dabura667/0813f8a8856c963c456245be854178eb

> Either the UI needs to be improved

UI is something for features that are implemented. What you are trying to do is not a feature, so it is irrelevant to UI of Copay.

> something is buggy

As far as Copay is concerned, all features are working as intended.

> documentation for users (not for crypto developers) is needed.

I agree with this in some part, but it is much better to have an app that works intuitively.

However, your use case of generating multiple wallets from the same mnemonic is an "Advanced feature" and requires knowledge of BIP44... when you said "tried to make a wallet from m/44'/0'/0'/1" that shows that you don't understand that you are putting "1" where the wallet logic for change address goes... and thus you do not understand BIP44.

Note: I am not related to bitpay, but I have created 5 different for-hire projects based off of bitcore-wallet-client and worked on the localization for Japanese as well as implementation issues for BIP39 dealing with non-English languages, so I am pretty comfortable with the library.

**Comment by avibrazil** [comment]
Dabura, thanks for explanations and patience with me. I'll move on with what is possible right now. The only thing that still doesn't make sense to me is the export of a m/44'/0'/0' wallet to include a root key in a way that this export might be used to create a full featured m/44'/0'/1' wallet. I was expecting more separation between accounts.

Thank you

**Comment by dabura667** [comment]
Yes. Currently Copay exports and manages xprv and mnemonic data as root (m) but manages watch-only xpub data as account level. (m/44'/0'/a') which is very confusing when you try to mix copay with automation.

The compartmentalization of HD wallets is still something that is not well explored in normal user facing wallet software... primarily because those types of use cases are very complicated to begin with... so it would be extremely difficult to make that easy to use UI for my grandma.

However, there are ways around it. (I have been paid to find them, like the one I showed you, which is based on the premise of the client throwing an error etc) And any pull requests / suggestions are always welcome.

**Comment by avibrazil** [comment]
So I would suggest, on the export screen, an additional option to let the user chose which level of keys to export: the root or the current leaf. For private and for pub keys. I've tryied to find the right key through that bip39 or your bip32jp tools but that was EXTREMELY confusing. (I'd love to have a 30min conf call with you so you can teach me some things, if you can)

It's bizarre that the exported data of a m/44'/0'/5' gives you access to whole m/44'/0'/*. It kind of breaks most benefits of BIP32.

Also, on a multi-wallet tool (as Copay) which works in a context where wallets are inter-related (BIP32) it would be nice to have some visuals to represent this relationships, such as a folder of wallets. Then you'd be able to import/export each wallet (leaf keys) or the folder (root keys).

For me, the strength of Copay is on BIP32/44 wallet management, which are the closest thing to make cryptocurrencies usable by my mother. So I think wallet management must be the field that must receive the most attention by developers. All the rest is kind of ready in Copay.

**Comment by dabura667** [comment]
I think that would be a good feature to add to the advanced options on the export screen.

@matiu What do you think about the ability to export a wallet with only the m/44'/0'/x' xprv key?

The exported backup would need to delete the mnemonic, and minor changes would be needed to allow BWC to work, but I understand the use case (I want to export one of my accounts as a separate wallet for someone else to use, but not show them any of my other accounts... Like a parent giving a wallet to their kid etc.) and think it would be a good addition.
