### ISSUE TITLE
What if Bitpay servers are hacked ?

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#4761]
I'm sure this was answered before...

Since Copay uses the Bitpay services to talk to the blockchain, what if Bitpay gets hacked? Are my private keys visible to the Bitpay server at any given time? Are they visible when I'm not using Copay? Is this architecture explained somewhere ?

Thank you in advance

**Comment by isocolsky** [comment]
Private keys never leave your device so a compromised server would not be able to steal funds. Copay does share the Extended Public Key with the server. This means the server is able to tell your balance and all incoming and outgoing transactions associated with your wallet.

**Comment by avibrazil** [comment]
What if I want to make a transaction? Then Copay goes directly to the Blockchain without the help of Bitpay ?

**Comment by isocolsky** [comment]
Well no, it goes something like this:

![image](https://cloud.githubusercontent.com/assets/2073468/18633620/8e60d32e-7e53-11e6-856a-7a5727545c71.png)

Where BWS is the Bitcore Wallet Service (Copay's server). And Insight is BitPay's open source block explorer which communicates directly with a bitcoind node.

**Comment by dabura667** [comment]
The only part of your wallet that is "compromised" by the model above is "maybe" privacy.

However, a similar model is used by Electrum, but with one exception.

In Electrum, anyone running a server (it's open source) joins a pool, and every wallet user connects to a random server in the pool.

You could look at it one of two ways:

1. FBI or NSA is running most of the Electrum servers, and is monitoring your transactions.
2. Electrum servers are more private because every query could be potentially to different servers (which are probably not all NSA and FBI) and Electrum servers don't hold any private data on you.

The same way you could look at Bitpay:

1. They are friends with the FBI and NSA and are giving away all your transaction metadata.
2. Bitpay is a bitcoin company dedicated to your privacy, so they will never track you or give away your data to third parties.

But to be honest, with both Electrum and Copay, I can run my own server and set up my client to only connect to my server... so that's what I do...

And Copay has a better UI than Electrum with more platforms supported, plus an easy (-er than Electrum) to use backend library that makes automation much easier... so I chose to switch to bitcore for all my projects, and I occasionally help people running Electrum based solutions and bitcoind based solutions.

If I couldn't run my own server, I would go with Copay, personally... because I think the likelyhood that NSA is running a bunch of Electrum servers is much higher than Bitpay being the NSA's best friend.

**Comment by avibrazil** [comment]
Thank you folks for the explanation. I don't fully understand isocolsky's drawing or how private keys do not travel to these servers, but I'm happy that you say they don't. I also don't currently care about transaction privacy, so I'm good for now.

Thank you again

**Comment by rosdi** [comment]
Hi sorry to 'reopen' this issue, I want to understand something... this happened before https://www.google.com/search?q=bitpay+hacked

It happened once, not impossible to happen again, what happens to our coins in this scenario?

**Comment by junderw** [comment]
@rosdi Bitpay doesn't hold any bitcoins of customers.

"Bitpay hacked" articles are talking about the CEO of Bitpay getting the company's Bitcoin stolen, not their users' Bitcoins. Since Bitpay doesn't hold any Bitcoins for its users, but it does hold a lot of its own money in Bitcoin.

**Comment by rosdi** [comment]
Ah ok... I thought as much... I was just trying to make sure I understand it correctly... finally I can put this lingering doubt to rest.... thanks for the clarification... greatly appreciate it!
