### ISSUE TITLE
Sign-0ut

### ISSUE THREAD

**Issue by TradZAllDay** [bitpay/copay#4762]
Hello,
            when The C0Pay wallet first came out it allowed users to sign-0ut, but now I see that this feature has been removed🤔
When I open up the wallet I'm automatically signed in, is this safe?

**Comment by dabura667** [comment]
There is no "login" information stored on bitpay's servers.

All of your sensitive data is stored on your phone. If you have a password set for sending, it is encrypted. Otherwise the only thing protecting your private keys is the OS sandbox security.

This means that if your device is jailbroken or rooted, you should definitely have a strong password set to encrypt your wallet.

**Comment by dabura667** [comment]
This changed after version 0.9.0, I think it makes users' funds safer.  If Bitpay gets hacked, now there is no leaked private keys.

**Comment by bitjson** [comment]
I think it's safe to close this issue. Hopefully the new onboarding process makes this much clearer too.
