### ISSUE TITLE
Where is the Copay documentation?

### ISSUE THREAD

**Issue by quinncomendant** [bitpay/copay#4777]
The “Help & Support” link at copay.io goes to this github new issue form. If nobody has raised this issue before, I'd like to suggest that copay create some real documentation, or at least expand the wiki here on github (yes, I found the [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ) page, but it doesn't answer my questions).

For example, I'd like to know:
- On the _Activity_ screen, what does `🔒` or `Auditable` mean?
- What does `Delete recovery phrase` do? Should I do that?
- What is `Sweep paper wallet`?
- What does `Enable Glidera Service` do? 

Google isn't much help in discovering these answers. E.g., googling for `"copay" "Delete recovery phrase"` returns nothing but links to Copay's source code. It's not friendly.

**Comment by JDonadio** [comment]
@quinncomendant I'm agree, there is some question that we need to consider and implement in the FAQ guide. Actually that section needs a lot of work in order to clarify this kind of scenarios.

About your questions:

* 🔒 > Means you have spending password
* Delete recovery phrase > Is completely optional. It's recommended for security, but isn't necessary for use Copay at all.
* Sweep paper wallet > If you have a paper wallet, you can sweep it scanning the QR code (private key) and move the funds to your Copay Wallet.
* Enable Glidera/Coinbase Services > Shows the options in your side bar.

**Comment by quinncomendant** [comment]
Thanks for the answers @JDonadio .

I found [this article](https://bitcoinhelp.net/know/more/private-key-import-vs-sweep-difference) explains the difference between *sweeping* and *importing* from a paper wallet. It might be useful for others or when writing the docs.

**Comment by JDonadio** [comment]
@quinncomendant great info, thanks!

**Comment by xelawafs** [comment]
@quinncomendant thanks for opening this issue. Building up on it, I can find little to no in-line code comments. I've also looked around but can't find any docs on customizing Copay code for custom wallets. The only docs available are on this project's README and that only covers setup and builds.

Are there any docs specifically for doing stuff with Copay's code? If not, are there plans to make some? I think it would greatly reduce the learning curve for new users(devs)/contributors. I just started working on a custom wallet based off copay. I got into this project along the way and I'm currently doing catchup on the codebase, with no docs, it's taking a bit longer to figure things out. I'd love to help start or get involved in any plans around writing developer documentation for Copay. @JDonadio any place you can point me to for this?

**Comment by JDonadio** [comment]
@xelawafs unfortunately there is not documentations about the customization of Copay. As you mentioned, README file have an extended information about build, integrations, etc, but not about "how to customize".

However, [bwc](https://github.com/bitpay/bitcore-wallet-client) and [bws](https://github.com/bitpay/bitcore-wallet-service) has the complete documentation, so you can take a look there in order to understand the architecture of the Copay platform.
