### ISSUE TITLE
Should “Delete recovery phrase” be part of the backup process?

### ISSUE THREAD

**Issue by quinncomendant** [bitpay/copay#4778]
On the wallet backup screen (_“Write your wallet recovery phrase …”_) there is no instructions that you should delete your recovery phrase after writing it down. Isn't that recommended? (Under the “Delete Recovery Phrase” screen, it says _“Once you have copied your wallet recovery phrase down, it is recommended to delete it from this device.”_)

**Comment by JDonadio** [comment]
Delete recovery phrase option was removed.

**Comment by mr-j0nes** [comment]
Why was this feature removed ? I am suppose to store my 12 words phrase in a secure place but since I don't delete it, it is there for everybody having access to my phone, to be seen.. (If I didn't setup a password they could recreate it very easy)

By the way, I can still delete the recovery phrase in CoPay but not anymore in BitPay (android)...
