### ISSUE TITLE
Broadcasted

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4878]
_From @ajp8164 on October 24, 2016 12:31_

We should use "Broadcast".  Although "broadcasted" does seem to be a word (ugh) - it is much less common and quite frankly should not be a word; the dictionary people are wrong.

<img width="400" alt="screen shot 2016-10-24 at 8 28 45 am" src="https://cloud.githubusercontent.com/assets/1063765/19645701/165fa7ec-99c4-11e6-8d27-be26f5cecbf1.png">

_Copied from original issue: bitpay/bitpay-wallet#660_

**Comment by bitjson** [comment]
Maybe there's a more descriptive term for that item anyways? Need to review it, but the screenshot at #4907 seems to imply that it's a (very) separate event from the last "Accepted"? Any idea why that would be?

**Comment by ajp8164** [comment]
"Accepted" (I think) means "signed" so maybe we should use "Signed".

Instead of "Broadcast" what about "Complete".  "Broadcast" sort of implies that something comes next.  This being a timeline should have a resolved state.

I think the whole timeline (names) should be re-looked at.  It's really a transaction timeline, right?

Ideas:

"Timeline" > "Transaction Timeline" ?(header)
"Proposal created" > "Created by Jason"
"Accepted" > "Signed by Houston"
"Rejected" should be a final state (?)
"Broadcasted" > "Complete"

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854

**Comment by bitjson** [comment]
Merging here: https://github.com/bitpay/copay/issues/4907
