### ISSUE TITLE
Unconfirmed transaction copay

### ISSUE THREAD

**Issue by bnkprc** [bitpay/copay#4912]
Had .536138 BTC sent to address of 19kgpqdtWXkN1Nk7oHpX4p75Hx6mECykK9 Almost 3 hours ago and still have unconfirmed transaction appearing .

Info is telling me this: https://blockchain.info/address/19kgpqdtWXkN1Nk7oHpX4p75Hx6mECykK9

Any help is greatly appreciated!

**Comment by bitjson** [comment]
Hi @bnkprc – is there an issue happening in Copay that you weren't expecting? There's a fairly large backlog on the Bitcoin network right now, and the linked transaction hasn't confirmed yet. The funds should be available in your wallet after the transaction has confirmed.

Since this seems like a network issue rather than a bug in Copay, I'll keep this issue closed for now. If you're noticing a bug in Copay, please provide a little more info, and we'll reopen.
