### ISSUE TITLE
unconfirmed

### ISSUE THREAD

**Issue by moneymaka** [bitpay/copay#4920]
hey there i have sent 2 payments for over 2hrs now and it still says unconfirmed what is the problem??please get back to me asap.

**Comment by dabura667** [comment]
What was your fee set as?

Currently the network is very crowded, so any fee not set to "priority" can take up to 12-24 hours. If you have "spent unconfirmed funds" turned on, it will allow you to use unconfirmed funds, which should relieve most problems.

If you are relying on a speedy confirmation right now, the bitcoin network can't make any guarantees for you due to the random nature of block discovery as well as the instability of the fee market.

My recommendation is to set fees to priority, and turn on "spend unconfirmed."

**Comment by moneymaka** [comment]
what do you mean by that?
the fee charged was .0002442 for a transaction of $15.00
and .0002443 for a transaction of $1.00

**Comment by moneymaka** [comment]
ok i just changed the settings so the transaction will be confirmed by tomorrow right??

**Comment by matiu** [comment]
> ok i just changed the settings so the transaction will be confirmed by tomorrow right??

Please check the current backlog of the bitcoin network. It is pretty congested at the moment. the confirmation times depends on that and the fee.
