### ISSUE TITLE
Can't backup my wallet due to visualization error

### ISSUE THREAD

**Issue by frz-dev** [bitpay/copay#4991]
The backup page in the Copay webapp, is not shown correctly.
This prevents me to backup my wallet.

Here's the screenshot: http://storage8.static.itmages.com/i/16/1108/h_1478619310_9346377_b0458fed14.png

I'm using Firefox 49.0

**Comment by JDonadio** [comment]
Please use Chrome instead Firefox

**Comment by matiu** [comment]
We dont support Copay running as a web page, it is not secure.

**Comment by frz-dev** [comment]
@JDonadio I tried, but the app starts from scratch (it asks for creating a new wallet), so I cannot use it to export my current wallet...

@matiu I understand that this is for developing purposes (which is my case anyway),
but since you provide it, maybe it would be nice to have it working ;-)
(Furthermore, the web page is automatically opened as soon as the I run 'npm start', so... )

Now I'm trying to install the desktop app (which is not working, but I will open a new issue for that),
 but what about my current wallets? Will they be automatically retrieved?
If not, how can I backup/export them? I'm using my own local wallet service.
I guess it's possible through the command line, but didn't find info about that.

**Comment by JDonadio** [comment]
@frz-dev you are trying to back up a testnet wallet but in any case you must to use chrome instead of firefox. As matiu says Copay is not supported as web page, it's just only for developers mode. If you are building Copay and need to export a wallet try printing your extended private key (or mnemonic words) in the console and import it from Import > Recovery phrase.

**Comment by frz-dev** [comment]
Ok, I'll try it. Thanks

**Comment by bitjson** [comment]
Merging to here: https://github.com/bitpay/copay/issues/4997

**Comment by sid64** [comment]
You are receiving this because you are subscribed to this topic.
Reply to this e-mail, view it on GitHub, or mute the thread.
mute thread.
You forget dicks Email: zcoufal@volny.cz
Log off me from GitHub
______________________________________________________________
> Od: Jason Dreyzehner <notifications@github.com>
> Komu: bitpay/copay <copay@noreply.github.com>
> Datum: 09.11.2016 18:32
> Předmět: Re: [bitpay/copay] Can't backup my wallet due to visualization error
>
Merging to here: #4997 <https://github.com/bitpay/copay/issues/4997>

**Comment by bitjson** [comment]
@sid64 no one else can do that for you. https://help.github.com/articles/about-notification-emails/
