### ISSUE TITLE
Some Android devices are pushing parts of views off the screen

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4997]
Some instances:

<table><tr>
<td><img src="https://cloud.githubusercontent.com/assets/904007/20147857/e9b74658-a677-11e6-962e-cad669eb4dc9.png" width="200"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/20147855/e9b644f6-a677-11e6-9a9e-f159b415524a.png" width="200"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/20147856/e9b70bd4-a677-11e6-8093-1ea29a1c4e0c.png" width="200"></td>
</tr></table>

**Comment by bitjson** [comment]
Happening on these devices:
- `Samsung Galaxy Note 3 and use Cyanogenmod 11, Android 4.4.4`
- `Z3c, Android 4.4.4`

So maybe an issue on that Android version?

**Comment by bitjson** [comment]
Also happening on Firefox here: https://github.com/bitpay/copay/issues/4991

Image mirrored for GitHub:
<img src="https://cloud.githubusercontent.com/assets/904007/20147978/75f67e04-a678-11e6-9f3e-d5b6541b9840.png" width="200">

**Comment by bitjson** [comment]
If this is due to inconsistent implementations of flexbox, we might need this: https://github.com/bitpay/copay/issues/4965

**Comment by sid64** [comment]
You are receiving this because you are subscribed to this topic.
Reply to this e-mail, view it on GitHub, or mute the thread.
mute thread.
You forget dicks Email: zcoufal@volny.cz
Log off me from GitHub
______________________________________________________________
> Od: Jason Dreyzehner <notifications@github.com>
> Komu: bitpay/copay <copay@noreply.github.com>
> Datum: 09.11.2016 18:32
> Předmět: Re: [bitpay/copay] Some Android devices are pushing parts of views
>
Also happening on Firefox here: #4991 <https://github.com/bitpay/copay/issues/4991>
Image mirrored for GitHub:
  <https://cloud.githubusercontent.com/assets/904007/20147978/75f67e04-a678-11e6-9f3e-d5b6541b9840.png>

**Comment by sid64** [comment]
You are receiving this because you are subscribed to this topic.
Reply to this e-mail, view it on GitHub, or mute the thread.
mute thread.
You forget dicks Email: zcoufal@volny.cz
Log off me from GitHub
______________________________________________________________
> Od: Jason Dreyzehner <notifications@github.com>
> Komu: bitpay/copay <copay@noreply.github.com>
> Datum: 09.11.2016 18:31
> Předmět: Re: [bitpay/copay] Some Android devices are pushing parts of views
>
Happening on these devices:
Samsung Galaxy Note 3 and use Cyanogenmod 11, Android 4.4.4Z3c, Android 4.4.4So maybe an issue on that Android version?

**Comment by bitjson** [comment]
@unusualbob is able to reproduce on a `Z3c` device.

**Comment by bitjson** [comment]
Maybe reproduced – I suspect that these devices are not handling the `-webkit-transform: translate(-50%, -50%)` properly. Not been able to confirm on a real device yet. Even the Android stock browser is supposed to support this properly ([caniuse](http://caniuse.com/#search=transform) reports full support with the `-webkit-` prefix).

![screen shot 2016-11-14 at 4 00 49 pm](https://cloud.githubusercontent.com/assets/904007/20282682/c8a15200-aa83-11e6-8093-e4834e539890.png)

**Comment by gabrielbazan7** [comment]
fixed here https://github.com/bitpay/copay/pull/5950
