### ISSUE TITLE
NW.js sometimes makes call to clients.l.google.com upon launch

### ISSUE THREAD

**Issue by davidlatapie** [bitpay/copay#5067]
BitPay.app/Contents/MacOS/nwjs want to conntect to clients.l.google.com on TCP port 443

Found thanks to Little Snitch

I blocked the query because I cannot get why Google is in the loop here. Explain please.

**Comment by bitjson** [comment]
Hey @davidlatapie – this is an issue with NW.js: https://github.com/nwjs/nw.js/issues/5206. It's because NW.js is a fork of Chromium, which means your local copy of NW.js could be logged into Google. (Since we never log in, this is basically just dead code.)

It's annoying that we can't disable this by default, but we're already migrating to Electron in this [pull request](https://github.com/bitpay/copay/pull/5023), so hopefully this will be an historical issue by the next release.

I'm going to merge this issue into https://github.com/bitpay/copay/issues/4890 for now, please let me know if I should re-open.

**Comment by davidlatapie** [comment]
Thanks @bitjson . The main issue I see with the current behaviour is that it raises suspicion about security. Someone not knowledgeable about the inner working of copay but paranoid enough to use an application firewall (or for using bitcoin, by the way) could falsely believe that CoPay is working hand on hand with the dreadful privacy-unfriendly GAFAM. So, mostly an advocacy / PR issue.

But since moving the code is on the way, this is a minor annoyance.

Thanks again

**Comment by bitjson** [comment]
Definitely agree. Hopefully we'll be able to get switched over to Electron soon. 🚀
