### ISSUE TITLE
Card Pairing Success Email and Pairing Note on Dashboard Sent Even If Device Not Fully Paired

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5087]
If I select "Go Back" in the last step before pairing my Card and the app, I still receive a success email from BitPay saying that my card was connected to the app. I can also see the card paired in my BitPay Card dashboard under "Add Wallet to Card." Something is wrong with the events/triggers here.

**Comment by ajp8164** [comment]
I noticed this during testing.  The problem is that bitpay.com is sending all the emails and it sends the "device paired" email without a confirmation from the device that the pairing actually completed.  My opinion is that the device should make a final api call to the bitpay server using the account credentials that says it completed the pairing process.  Only then should the bitpay server send the "device paired" email.
