### ISSUE TITLE
Missing Bitcoins

### ISSUE THREAD

**Issue by davidxproctor** [bitpay/copay#5144]
Hi All

I bought $400 worth of bitcoins today through bitcoin.com.au, and they have sent me the successful transaction details. 

The blockchain reference is:  https://blockchain.info/tx/a8fa543ab1c2b033ec7f291bff42e3adfe865543cf034346bdefc2f1802dba85 

These coins have not appeared in my Copay wallet. Can you please help me track where they are?

Kind Regards
Dave

**Comment by dabura667** [comment]
1. Open the wallet
2. Tap the cog on the upper right
3. Tap Advanced (5th from top, last option before Security settings section)
4. Tap "Wallet Details"
5. Scroll down to "Recent Addresses"
6. Check to see if 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj is listed.

If it is not listed, there are two common causes:

1. You are looking at the wrong wallet. From the wallet main screen tap the menu on the upper left and select a different wallet and try 2-6 again.
2. You have malware or virus on your computer / phone which caused you to THINK you copied the address from Copay, but actually the malware immediately copies an address for the malware author. So when you paste it, unless you double check the address, you won't notice that the address was replaced on the clipboard by a virus.

If it is listed:

Scroll to the bottom of the list of addresses, there is a button saying "Check balance" and tap it.

**Comment by davidxproctor** [comment]
Hi Dabura667

Thanks for the information. I don't have anything called 'Wallet Details',
I do however have 'Wallet Information'. When I go there, there is no
'Recent Addresses', only 'Last Wallet Addresses', and I can't see anything
related to 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj. Am I doing something wrong
here? This was done using my mobile phone and not a computer.

Regards
Dave

**Comment by dabura667** [comment]
If the wallet you had opened doesn't say 'Last Wallet Addresses' with that address in the list, then that address is not a part of your Copay wallet.

Try choosing the check balance button below the 'Last Wallet Addresses' list.

Also, explain how exactly is the process to buy bitcoin from that site, and what actions you took in Copay app to complete that process?

**Comment by davidxproctor** [comment]
No, I can't see that address anywhere. I suppose you're now wondering where
I got that address from in the first place. I did a transaction 6 days ago
to that address and the coins turned up immediately into my Copay wallet.
Was this the wrong thing to do? I've now used that adders twice in the past
with 2 separate transactions and it worked fine previously, I thought I
could use it again for this transaction. Moving forward, how will I know
which address to use? Will I be able to recover my coins? Who know owns
that address if I don't?

The bitpay.com.au process is very simple.

1. Visit the site
2. Select Buy bitcoin
3. Enter the amount in Australian dollars or the amount of bitcoin wanted
4. Fill in the details - name, bitcoin address, mobile number
5. Print out the QR code and take that to one of the available outlets
(news-agency)
6. Scan in the QR code at the outlet and pay cash over the counter
7. Bitcoins on then transferred into the bitcoin wallet (this never
happened for me this time round)

Below is the proof of the transaction:

[image: Inline images 1]

Previous transactions to that address:

[image: Inline images 1]

Regards
Dave

**Comment by dabura667** [comment]
looking at that address, it says you received 0.36272 BTC at 2016-12-04 01:08:12

Then you sent all that money you received ($400 AUD) to 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu at 2016-12-04 02:16:10

If you look at 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu, there are a lot of varying amounts of inputs being bundled together into smaller transactions.

Two possibilities:

1. 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu is the address of some hacker who stole your Copay wallet.
2. 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu is the address of some service that you forgot existed.

Did you send any bitcoins from your wallet with 1 hour and 8 minutes after seeing the transaction from that  bitpay.com.au place

**Comment by davidxproctor** [comment]
No, I didn't send any money anywhere. I should've received that money at
that time as it's when I paid for the bitcoin, but it never showed up at
all in my wallet, which is why it would've been impossible to send it
anywhere as it didn't exist. I'm pretty new to this whole bitcoin thing,
and the transactions that you see are the only ones I've ever done. I have
a very safe PC at home, VPN's running etc.. and have never been hacked. I
use my phone to do the transactions, and have never heard of anyone's phone
been hacked before.

How would I have the confidence to buy more coins after this? What should
my wallet address be? I used 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu in the past
and thought it was the right thing to do?

**Comment by dabura667** [comment]
If 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu is not in the Wallet Information screen, it is not your address!!!

Again, please answer my questions:

1. Where did you download Copay on your Android Phone? Google Play store? Some other store? Some website directly?
2. What phone are you using, where did you buy it, what is the android version number?

Smartphone hacks are VERY common. These two questions will help identify where you were likely attacked.

**Comment by davidxproctor** [comment]
Again, it's not in my wallet information. I downloaded Copay from Google
Play Store. Yes, it's an Android that was bought on a plan from Telstra
(Australia's largest telecommunications company). The software is up to
date. If Androids are very common to hacks I'd be surprised as not one
person I know in Australia has ever been hacked.

To be honest, I don't care about the $400. My question is "How do I move
forward?" *Where is the address* in my Copay wallet that I should be giving
out?

*Mobile details*:
Android version: 6.0.1
Baseband Version: G935FXXU1BPJH
Kernal Version: 3.18.14-9519568
Build Number: MMB29K.G935FXXU1BPJH
SE for Android status: Enforcing
Security software version: MDF v2.0 Release 7; VPN v1.4 release 6.1; ASKS
v1.2_161011
KNOX version: 2.6
Android Security Patch Level - 1 November 2016

In Copay I have a Wallet ID, but I know this is not the same as the
address. I can also see 'Last Wallet Addresses', *but what should I use* if
I want to buy Bitcoins again? The last Wallet Address, or do I somehow have
to obtain a new Wallet Address from somewhere? I can see 'Balance by
Address', is that my current address? Should I be using that address moving
forward?

Thanks for your time.

**Comment by dabura667** [comment]
If you bought your Android from a reputable store, brand new, and downloaded Copay from the official Google Play store, and you don't do things like install side-loaded apps via apk files by disabling security features on your phone, then you should be fine for the most part hack-wise.

The problem seems to be in the address 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj, because it is obviously not your address (you claim to not have ever received the bitcoin, but the blockchain states that the $400 DID arrive to 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj and within 1 hour and 10 minutes was immediately sent to 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu.)

This commonly means that 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj is a compromised address. (meaning, someone tricked you into copy pasting this address even though it doesn't exist in your wallet.)

It looks like a lot of other people also were tricked into using addresses that immediately sent all their money to 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu. If you check 1FwtDqXXxJqEPX7egocyTbRv7Jxo7Nb8zu history, all of the addresses that sent to it received money 1 hour beforehand.

You need to figure out how you were tricked into copy pasting 14KDGr5kP76dN31MRu8ozmfLqzeEL7KQbj when it is not your address.

Since a lot of other people are being tricked, perhaps it is a problem with the website itself. How do you know that bitpay.com.au is a reputable website?

I tried http://bitpay.com.au/ and https://bitpay.com.au/ and neither of them work for me. A google search also produces 0 results.

**Comment by dabura667** [comment]
As far as "next steps," if it were me, I would:

1. try to figure out how I was tricked
2. if I can't figure it out, I would completely wipe my Android phone, and only reinstall the apps I really need by directly downloading them fresh from Google Play (If I use some backup tool, I'd be afraid to backup a virus infected app)
3. make sure that I double check any address I send to someone (exchange or otherwise) before I click OK. I would make sure the address on my Copay was definitely the address in the text box before I click the send button.

But tbh, after google searching bitpay.com.au and not finding anything, I am thinking maybe it was that site tricked you into paying money.

**Comment by davidxproctor** [comment]
Hi

Where\How do I find my legitimate address in Copay? If I want someone to
deposit bitcoins into my wallet ie. myself, what address do I use?

**Comment by JDonadio** [comment]
@davidxproctor any address generated by Copay are safe. Just make sure (as dabura mentioned) to copy, paste or share correctly before transfer any funds there.

>make sure that I double check any address I send to someone (exchange or otherwise) before I click OK. I would make sure the address on my Copay was definitely the address in the text box before I click the send button. 

👍 

Note: every time a transaction arrives to Copay a fresh address is generated, so in a common scenario you'll have many addresses. However, you can create a wallet without this functionality switching on the "Single address walllet (for audit purposes)" in advanced options.
