### ISSUE TITLE
Copay "Could not update wallet: 403" - Problem trying to import on PC

### ISSUE THREAD

**Issue by aladinsane60** [bitpay/copay#5197]
I have no problem importing my wallet on my smatphone using mnemonic phrase (12 words), but I have been trying almost a week with the desktop app, and all I have is this message: Could not update wallet: 403
Some idea, please? Could be something wrong in my pc or network settings?

**Comment by JDonadio** [comment]
Are you trying with the latest version? Please check if you are updated

Download BitPay app from [here](https://bitpay.com/wallet)

**Comment by aladinsane60** [comment]
Solved. Thank you!

**Comment by knocte** [comment]
I'm having this problem with the latest version downloaded today. Can someone reopen this issue?

**Comment by gabrielbazan7** [comment]
@knocte what's your problem ?

**Comment by knocte** [comment]
Apparently the servers had a problem last night, it works now. But the error message was not helpful at all: "403 error, tap to retry", or something like that.

**Comment by CurrencyInvestors** [comment]
Copay has many errors in particular 403, people distrust COPAY could miss the Bitcoin.
Error 403 is presented in: Tablet, Windows phone, Android and Windows PC.

Luckily I only use test in BTCT otherwise my btc could be lost.

I recommend COPAY to solve these problems otherwise the user will not give continuity to Copay..

**Comment by mandotolas** [comment]
I have the same problem and I am worried about my stored bitcoins, for days I can not connect or make transactions, someone can help me please

**Comment by JDonadio** [comment]
Please follow #7053

**Comment by CurrencyInvestors** [comment]
Hi, what can I do with bitcoin testnet 3 ... some trick I must learn with
COPAY.
It would be interesting to transform bitcoin testnet 3 into real bitcoin
and market ...

2017-11-06 11:22 GMT-05:00 Javier Donadío <notifications@github.com>:

**Comment by blinov02** [comment]
Hello have the same problem.I can't import my wallet.

**Comment by blinov02** [comment]
if I want to import my wallet there is an error:failed to import the wallet it is not registered in Bitcore

**Comment by RLdiamond1** [comment]
Has anyone tackled this issue? obviously people are facing this issue then suddenly dropping the subject. I am currently facing the same issue and suddenly, I was no t able to access my bitpay wallet anymore through mobile app. I uninstalled and reinstalled the app, and was not able to restore wallet giving same 403 error. 

Tried the restore on different mobile, when i restore i get the same error however it continues to attempt to import and remains on *importing wallet* stuck with no progress.

Kindly assist or provide a solution for this problem!

**Comment by BGalliotti** [comment]
Hello @RLdiamond1 

We are sorry you have had this bad experience.
We understand your situation, unfortunately, this error is due to the **Internet connection** you are using, it has nothing to do with us.

Depending on which country you are, **CloudFlare,** our Content Delivery Network provider might be blocking your request.

Please check out the following links for a list of countries that ban/prohibit/limit the use of cryptocurrencies:

- [Countries where the cryptocurrencies are banned](https://bitnewstoday.com/market/bitcoin/countries-where-the-cryptocurrencies-are-banned-busted-for-bitcoin/)
- [Bitcoin bans](http://bitcoinbans.com/).

*Note: these links are external resources not related to Bitpay and we are not responsible nor for the content neither for its accuracy.*

In case you are not located in any of the countries which ban cryptocurrencies, the only thing you can do is try a different connection. You might be behind a proxy server, or accessing through an IP that is somehow being rejected by the server.

**We can suggest you try:**

- Accessing the internet through a different network connection (friends, neighbors, work..).
- Using your mobile broadband connection (3G/4G/5G/..) instead of Wifi
- If you did not experience this issue before, please think about what might have changed (you changed your Internet service provider/connection, your mobile/cable company, etc).
- Reach your internet service provider/phone/cable company technical support, and tell them about your problem, they should give you a solution.

We hope this helps and that you will be able to resolve this situation.

**If you cannot access your wallet, you can still recover your funds by moving them to another wallet.**

Here is our recovery tool https://bitpay.github.io/copay-recovery/

Read this [article](https://blog.bitpay.com/bitcoin-cash-recovery/) to know how to use it.

Feel free to get back to us in case you have any questions or concerns.
Thank you for your interest and support.

**Comment by BGalliotti** [comment]
Hello @corn91791 
Thanks for reaching out to us.

As you requested 

>Kindly assist or provide a solution for this problem!

We are trying to help you.

Please try the steps on our answer and let us know what is your situation to see if there is something we can do.

Anyways, if you have your 12-word backup, you can restore the wallet on any wallet app of your preference.

> Then do it somebody putting a different address to where I want to going

Sincerely we do not understand your answer.

Please let us know if you have any additional questions.
Kind regards.

**Comment by corn91791** [comment]
Yes
