### ISSUE TITLE
Make desktop wallet download links less confusing 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5272]
I just worked with a user who was confused about verifying our Window download file's PGP signature and whether he should download the .sig or the .exe file for the Windows app. The large number of links/files we show on each release is a contributor to this.

Can we make the interface for downloading these desktop apps significantly simpler for people who don't normally download from GitHub. A simple Windows icon with the .exe file would be way easier for a non-techie, for instance.

![screen shot 2016-12-16 at 12 57 17 pm](https://cloud.githubusercontent.com/assets/9257396/21272947/4293b5f2-c38f-11e6-8752-776af3e1afc8.png)

**Comment by bitjson** [comment]
These boxes are actually download links: ![screen shot 2016-12-16 at 1 45 33 pm](https://cloud.githubusercontent.com/assets/904007/21274379/ef942ea2-c395-11e6-892b-0d3bd94608d6.png)

That's good to know though – maybe we can make it clearer somehow. I'll try right now.

**Comment by bitjson** [comment]
I imagine people are ignoring the images because they look a little like advertisements. I duplicated the grid to the bottom and made some language clearer. hopefully that solves the issue for now (until we provide a simpler option for pre-selecting OS and sending people to the proper download from https://bitpay.com/wallet)

https://github.com/bitpay/copay/releases/tag/bitpay
