### ISSUE TITLE
Amazon gift card missing from UI

### ISSUE THREAD

**Issue by shibley** [bitpay/copay#5277]
Hello,
I purchased an Amazon gift card via my Copay wallet and it showed up under the "Gift Cards" section of my Copay app.  Now when I check, there is no reference to the gift card, and no way to redeem it.  Is there any way I can get it back, I can provide proof I purchased the $50 card.

**Comment by shibley** [comment]
How long is the Amazon gift card visible in the app before going away?

**Comment by matiu** [comment]
Hi @shibley. I am very sorry we missed this issue.

Where you were able to redeem the card? I will be happy to assist you if this is still an issue.

**Comment by shibley** [comment]
Hi @matiu,
I still am not able to view the gift card via the Copay app ( Mac ).  Have there been other occurances of gift cards disappearing from the UI.  It did show up initially, then when I checked back at a later time, it was not there.
Thanks for any help you can provide.

**Comment by shibley** [comment]
<img width="563" alt="screen shot 2017-04-11 at 2 46 37 pm" src="https://cloud.githubusercontent.com/assets/402991/24932303/bf48e05e-1ec5-11e7-85cb-5c231165867d.png">

**Comment by matiu** [comment]
could you please set me the address(es) you use to paid the invoices to
matias@bitpay.com so I can check the codes for you? thanks.

On Apr 11, 2017 6:47 PM, "Shibley Burnett" <notifications@github.com> wrote:

[image: screen shot 2017-04-11 at 2 46 37 pm]
<https://cloud.githubusercontent.com/assets/402991/24932303/bf48e05e-1ec5-11e7-85cb-5c231165867d.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/5277#issuecomment-293410303>, or mute
the thread
