### ISSUE TITLE
[bitpay app only] Review app refresh when a tx is received

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#5325]
Sometimes Balance is updated, but tx history is not.

**Comment by JDonadio** [comment]
I think it's working well now. I'll re-open this personally if the problem remains.

**Comment by Asher0451** [comment]
> Sometimes Balance is updated, but tx history is not.
Okay this is a long shot but.....
I'm trying to get a hold of matiu... You created an issue in 2016 #451 that has my Bitcoin address in it. I see that the user was chrisk  Chris is actually the person I need to get a hold of... or he get a hold of me... I believe he was the person I met in 2011 at Lake Las Vegas in the casino montelago and pitched Bitcoin to me. I believe he must have been the one paying into my wallet account with the initial 1500 and smaller payouts for several years thereafter. All as part of my signing up through him and helping fund his mining btc back in 2011. I need help accessing my Bitcoin wallet. I purchased 1500 btc and 1500 btc-cash. I don't remember which platform I used to create my wallet. Maybe his payout records will have record of it. Because If I know which one I used to create my wallet then I can hopefully back track correctly and find my priv keys. I wrote them down and I may or may not have sent them to him along with my wallet address for the deposits. I need to ask that question too.  I, of course don't have anything other than maybe my hard drive if it's the correct device I used, I had several at that time. I've searched it but can't find anything related to Bitcoin. I'm not even sure if I actually finished the whole setup process and received prv keys...alot has happened since then and memory is not serving me. What I do remember is my wallet address due to word association while writing it down back then. I found it on the Blockchain as well. Which was not that hard since I knew how many I purchased and all are already in order of balance. So out of the few that holds 1500 I recognized it right away. That is what led me to your post on GitHub, I googled my address and realized that this site (GitHub) is used by miners/coders. I have spent years trying to figure this out and see if all is lost or if I have other resources unknown to me. I realize I am not the only person that got into Bitcoin through this person however I'm hoping that he remembers something anything that may help me. My email is myguyandi@gmail.com which is not the same one I used back then. Google purged my original email account due to inactivity so all emails received at that time are gone. however I was able to obtain the same email afterwards so I should be able to get new verification emails if it's an online platform I used. I've tried to sign in to several that were used in 2011 using my old email address but most emails come through saying to finish setting up my account click here... I haven't clicked cause I'm not sure I want to set up new accounts with that email for fear I may lose the original one. I was hoping to get to the next stage and enter my password but I don't feel comfortable with clicking to just see if I get there or set up another account. Please contact me. If you can help me let's get started... Or to only to say you can't help me. Either way please reach out I'm feeling a little hopeless. So much has happened to me since then I've gone from living at Lake Las Vegas to losing everything and moving back to my dad's house. No job no car no house and about $11 in my bank account. Knowing I invested in btc and have a huge fortune I can't yet touch is driving me crazy. I need help. If you know anyone who can help (I'm very skeptical though) more so I'm afraid to lose it for good to someone more savvy than I. Which is pretty much anyone. My computer skills are receptionist at best. I do have my old cell phone still it's a slide phone that has worn out the screen ribbon due to excessive sliding so the screen doesn't come on. It used to if I held it tight in a certain spot but I did that so long that it won't do it anymore. The last time I powered it up the screen did show for about 2 seconds but hasn't worked again (2months ago) I've tried four more times since. I'm thinking that it may still hold my emails in the memory. But don't know how to get it to work long enough to search it. After trying four more times I figured I better not break it for good and have just sat it aside. Any advice on that would be great too. Well hope to hear from you or anyone who has read this message and is willing to help. Thank you.
