### ISSUE TITLE
Ability to delete recovery phrase 

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#5361]
Copay has the ability to delete a recovery phrase. Are there plans to bring this to the BitPay wallet? In the unlikely scenario where someone gets into my phone, I'd rather the most they get access to is the amount of BTC I currently have in my wallet. I'd rather eliminate the scenario where they copy down my recovery seed and wait for a time where a larger amount of funds is passing through my wallet in the future.

**Comment by bitjson** [comment]
Thanks for opening an issue!

Just to note – the same problem also occurs if someone gets access to the xprivkey, which must be available to the app anyways. So usually, deleting the words doesn't really provide anything past "UI security." It only inconveniences attackers with device storage access, while significantly complicating recovery for casual users.

If we're primarily concerned about a thief getting access to the logged-in device (like if you let someone else use your phone) do you think something like https://github.com/bitpay/copay/issues/4555 would solve this use case? (Already on the roadmap for a near-term release.)

(As an aside, are you using a spending password for the wallet?)

**Comment by JDonadio** [comment]
We currently have enough of security capabilities in the app, recently added PIN/Fingerprint to lock/unlock the app. In the meantime the spending password encrypt your privkey and make a password request for any access to your sensitive information. So basically you don't need to delete your recovery phrase anymore.

**Comment by avibrazil** [comment]
The macOS version of Copay 3.2 doesn't have the "Lock App" feature. Hence the need to handle security to the core and allow to delete recovery phrase.

I don't get it why an existing feature gets removed just because it doesn't improve security enough. **The app architects have to decide if Copay is going to be clean and easy (and limited) or full of features.** It isn't currently in neither space: doesn't leverage BIP44 usefulness and possible use cases and can't be used in more advanced ways by entry users as my wife.

The clean and easy space is apparently occupied by Mycelium (which I just tried but I don't use because it is limited).

I wish Copay to be full of features.

Thank you
