### ISSUE TITLE
Add PIN code or password for viewing backup phrase after initial backup

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5497]
We need to add password protection or PIN code protection on the backup phrase viewing screen (in Settings > Wallet > Backup Wallet) if we want to keep it. Right now anyone with access to a phone (unlocked) could open a BitPay wallet and view its backup phrase. 

@cmgustavo says that users with spending passwords already enabled will be prompted to provide those passwords when trying to view this screen. The problem is that users are not told that they need to set spending passwords in order to protect this information within the app. It's not clear that "Spending Passwords" are also "Passwords for Protecting Sensitive Info from Prying Eyes."

One solution is to prompt **all** users to create spending password for their new wallets in the wallet creation flow so as to include this security by default. Other solution is PIN code for accessing the app interface. Finally, you could just

**Comment by matiu** [comment]
This was discussed before at:
https://github.com/bitpay/copay/issues/4555
and
https://github.com/bitpay/copay/issues/4617

**Comment by JDonadio** [comment]
> @cmgustavo says that users with spending passwords already enabled will be prompted to provide those passwords when trying to view this screen. The problem is that users are not told that they need to set spending passwords in order to protect this information within the app. It's not clear that "Spending Passwords" are also "Passwords for Protecting Sensitive Info from Prying Eyes."

Maybe we should add some description to clarify it, like:

<img width="414" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22375357/71f1a39e-e488-11e6-9f36-7f2db40d107f.png">

**Comment by darakaye** [comment]
Can someone help me?  I did not set a spending password.  I cannot access my btc.

**Comment by BGalliotti** [comment]
Hello @darakaye ,

Thanks for reaching out to us.

If you are being prompted for a password, that means you set up a password. 
Very likely you did it on the app onboarding and do not remember. Certainly the app cannot generate a password and lock wallets with random passwords.

Since the password is stored locally on your device, there is nothing we can do to restore it.

There are two ways to solve this situation:

1. Remember the password. Keep in mind there are no special requirements for the password such as numbers, symbols, uppercase letters, etc.

2. Restore the wallet with the 12-word recovery phrase.

For option 2:

**What you can do is restore the wallet.**

**A)** First, make sure the recovery phrase you have, corresponds to the wallet you want to restore.

i) **IF YOU HAVE ONLY ONE WALLET IN THE APP**

- If you have only one wallet, import the wallet with the instructions below (**C**).
You should get an error saying the wallet is already in the app. 

- In such case, you can safely proceed to delete the wallet and restore it (remember, only in case you have only one wallet). Proceed to (**B**)
- If you do not get an error (and you have only one wallet), then the recovery phrase that you have does not belong to the wallet you want to restore. Proceed to (**D**)

ii) **IF YOU HAVE MORE THAN ONE WALLET IN THE APP**

- Install Copay app

Install the Copay app from the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the Copay wallet [here](https://bitpay.com/wallet).

- Import the wallet ( follow steps on **C**)
- Check the wallet imported is the one you want to restore. In case it is, you can safely proceed to (**B**), if not, proceed to (**D**).

**B)** Delete the wallet

- Open the BitPay wallet
- Select the wallet 
- Tap the upper right corner icon (Preferences)
- Scroll down and tap **Delete Wallet** > **Delete**

Then proceed to **C**

**C) Import/Restore**

Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115003028346
wallet-from-Copay-to-BitPay-) for steps on how to restore the wallet from a backup.

Here is a [video](https://www.youtube.com/watch?v=U23E-dZEuYs&t=1s) from our support channel for a clearer explanation.

To import the wallet on another device, you can click the **+** next to Wallets and then choose **Import wallet**. Enter the 12-word recovery phrase and you will now have access to the wallet from both devices.

Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-) for steps on restoring your wallet using the recovery phrase.

**If you are experiencing an issue, here are some things that you can check:**

- Are you sure that the recovery phrase was written in the correct order?
- Did you use all lowercase letters and no punctuation?
- Did you add a password to your recovery phrase?
- [Do you have the QR code or text/file backup?](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-)
- Did you separate each word with a single space (no commas or any other punctuation)?

Also make sure:
**- Your phone is not using capitals for the first letter of the words**

**- You are not typing spaces:**

- before the first word
- more than one space between words
- After the last word

Please also ensure that your words are all contained in the following [list of possible words](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) (in English).

For other languages click [here](https://github.com/bitcoin/bips/blob/master/bip-0039)

**D)** We recommend you look for other recovery phrases (12-word recovery phrases) that you might have and try to restore the wallet.
If you do not have the recovery phrase for that wallet, unfortunately, there is no way to recover it, however, we recommend not to uninstall the wallet nor to delete the wallet, so in case you find the recovery phrase, you can restore it.

**Bear in mind**

**There is no account or password for the BitPay wallet. Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115002989283-Why-don-t-I-have-an-online-account-for-my-BitPay-wallet-).**

**BitPay does not store your private keys or have access to your funds. The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device. To restore your wallet if your device is lost or stolen, you must save the 12-word backup phrase that you receive when you create a wallet. BitPay will not be able to recover your funds.**

**If you are still having issues after checking all of the above, please let us know.**

Please let us know if you have any additional questions.
