### ISSUE TITLE
How to hide bitcoin as i share laptop with colleagues

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#5503]
i share my laptop with colleagues and i want to be able to hide how much bitcoin i have when they open up copay application. How do i remove the data file to run from external drive or hidden volume so that when they open up Copay app they can not see the Bitcoin there?!

**Comment by JDonadio** [comment]
@themovement919 you already open [this ticket](https://github.com/bitpay/copay/issues/5498) with the external drive question.

On: There is a feature request ticket about lock/unlock the app [here](https://github.com/bitpay/copay/issues/4555). However, in order to avoid a first look of your balance you can tap and hold for a second to hide it, and same process to show it again.

Hope this help for now.

**Comment by dabura667** [comment]
> i share my laptop with colleagues

use different login names.

Any modern OS can support multiple users logging on at the same time.

In Windows, click "change user" and you're done in a few seconds.

**Comment by themovement919** [comment]
@JDonadio @dabura667  so is there a way to move the data file to an external hard drive so that it can only be accessed from the external drive? 

is there a lock/unlock feature on copay?

**Comment by JDonadio** [comment]
Please continue your externa drive discussion [here](https://github.com/bitpay/copay/issues/5498)

**Comment by matiu** [comment]
I highly recommend not using Copay is you are sharing the computer with untrusted people. It was definitely not designed for that use case.
