### ISSUE TITLE
Please help. I'm new

### ISSUE THREAD

**Issue by charlieasvp** [bitpay/copay#5504]
So I have the app on my phone and I believe someone sent me bits to my wallet. I went into it today to check and they just made me back up my wallet. But I looked at the addresses and they are not the same. I still have the phrase for my old adress but how can I get back to that one?

**Comment by bitjson** [comment]
Your wallet has a nearly unlimited number of bitcoin addresses which are all generated from your backup phrase. You don't need to worry about keeping track of addresses, any payments made to any of the addresses in your wallet will show up in your balance. The wallet simply tries to use a new address each time to improve your privacy and security.

You may want to use the [BitPay app](https://bitpay.com/wallet), since it really makes these things clearer. (You can see all your addresses by choosing the wallet in the 'Receive' tab.)

Until the next release of Copay comes out, you'll have to open the wallets advanced settings, and check the "more info" view for a full list of your addresses.

Hope that helps – I'll close this for now, but please let me know if I should reopen.
