### ISSUE TITLE
Adding Funds to Bitpay Visa Card

### ISSUE THREAD

**Issue by mybitpay** [bitpay/copay#5523]
Ok this is king of ridiculous. I just connected my Bitpay visa card using Windows Desktop Bitpay Wallet App.
I am just testing it and can't even add a simple $1 to my Bitpay Visa Card??? My personal wallet has $4.50. Can you tell me if this a ptoblem or how do i fix this so i can add funds to my card?
![addfunds](https://cloud.githubusercontent.com/assets/25313357/22268009/b705fd7c-e23a-11e6-93e3-84f80cb03cc6.JPG)

**Comment by JDonadio** [comment]
Please take a look at [this](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send)

**Comment by mybitpay** [comment]
I already saw this and still don't work st all. Again this is ridiculous. Other payment processor sending to a BTC wallet never have no problems. Yes I try send max to my BTC wallet and still says not enough funds for fee. Again so confused and can't even send $1 only.
![wp_ss_20170131_0001](https://cloud.githubusercontent.com/assets/25313357/22476526/9abb592a-e797-11e6-8cc2-eca1bf1ae6ca.png)
![wp_ss_20170131_0002](https://cloud.githubusercontent.com/assets/25313357/22476527/9abca618-e797-11e6-8

**Comment by JDonadio** [comment]
This happens just because you have many small inputs and the tx size claims a "big fee" to build it so you are not able to send that funds. Maybe (and it's just a suggestion) selecting **economy** as fee level can build it, but maybe not. If isn't the case we are very sorry about that but unfortunately there is nothing we can do. This is not a Copay problem, but how the bitcoin protocol works.

**Comment by mybitpay** [comment]
So I have no way to withdraw all my BTC out. I can't even send at least $.50 and still won't send due to fee.
