### ISSUE TITLE
Testnet in Copay

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5534]
I could learn that Copay supports Testnet. Can someone share more light on how I can use Testnet for developmental and testing purposes within Copay. Like send/receive Testnet using multiple Copay wallets while testing some features?

**Comment by JDonadio** [comment]
Just display the advanced options at creation, and you will see something like this:

<img width="413" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22336191/1fcc5f3c-e3c0-11e6-9d71-9d049f7c674c.png">

<img width="412" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22336222/3cf51e0a-e3c0-11e6-93cd-8098312dc3b7.png">

In order to fund your wallet you must use some web faucet and provide an address. All the process (receive, send, etc) are the same as a livenet wallet.

**Comment by rakeshgn31** [comment]
ohh yaa I missed out during creation of wallet and looking for option in settings after creation of wallet. Thanks!

**Comment by JikkuJose** [comment]
Will I be able to **send** testnet BTC? It seems the app keeps trying to send from mainnet wallet?

**Comment by JDonadio** [comment]
Yes, your recipient should be testnet as well in order to display your testnet wallets in the confirm view.

**Comment by JikkuJose** [comment]
Aaah! Thats why, but whats the difference between the two wallets? Is it just a security aspect that CoPay does to ensure that BTC will not be spent by mistake?

**Comment by gabrielbazan7** [comment]
It's done to avoid future errors. It's not possible to send bitcoins from a livenet wallet to a testnet wallet.

**Comment by JikkuJose** [comment]
Cool, perhaps its better to specify it explicitly like:

*Mainet BTC* Addresses:
<address1>
<address2>

**Comment by tbrannt** [comment]
Could you add a testnet feature for Bitcoin Cash too?
