### ISSUE TITLE
Unspent UTXOs not included

### ISSUE THREAD

**Issue by tycoonlover1359** [bitpay/copay#5558]
I'm just testing around with the Copay / BitPay app and am wondering why occasionally, Copay / Bitpay will not let me use some of the money in my wallet. This is annoying when I'm trying to transfer wallets and it won't let me spend a little bit of bitcoin.

**Comment by gabrielbazan7** [comment]
Could you provide more info to us ? Maybe an screenshot ?

**Comment by JDonadio** [comment]
@tycoonlover1359 that's because these UTXOs are smaller than the normal (or maybe economy) fee rate, so basically are excluded (if there are bigger UTXOs available) at the building transaction time. The tx size depends on the inputs count, if you have many small UTXOs your tx size becames bigger and your fee will be also higher than normal.
