### ISSUE TITLE
Bitpay vs Copay

### ISSUE THREAD

**Issue by TAiS46** [bitpay/copay#5563]
Can someone please explain the difference?
I thought this is an copay repository but in the releases I see a bitpay client.
Why are there two different software releases of bitpay and copay?
As I can see both have a different UI. (Copay seems to be the better solution)

Will there be also a new version of copay and is copay still supported?

**Comment by dabura667** [comment]
Yes, it is very confusing... chromium doesn't do chrome releases on github...

Imo it should be a separate repo

**Comment by ivanrojasorg** [comment]
I cant install bitpay walley with the Command ./Bitpay, how install bitpay wallet in Ubuntu?

**Comment by dabura667** [comment]
https://github.com/bitpay/copay/releases/download/bitpay/BitPay-linux.zip

Download this, unzip it, and run the executable from the terminal.

chmod if necessary

**Comment by tab00** [comment]
Please make a separate repository for BitPay. I've been wanting an updated Copay version but all I see is a Bitpay release, which I don't want because I don't want Bitpay-specific things like the debit card integration.

**Comment by JDonadio** [comment]
During the BitPay app development Copay *releases were* delayed for a while. The new UI-UX was introduced in  *Copay v3* merging the code for both apps. Basically the differences, for now, are:

1- Bitpay branding for Bitpay app
2- No BitPay Card integration in Copay
3- Copay  supports  Chrome-extension

We use the same repo because BitPay app was built from the Copay base-code.

**Comment by chrisrico** [comment]
>No BitPay Card integration in Copay

>Only Copay supports Trezor and Ledger HW wallets

Why is this? I've got a Bitpay card and use a Trezor. This means I can't top up my card on my desktop, which is really dumb.
