### ISSUE TITLE
Can the process of multisig wallet recovery be done manually with only backup phrases?

### ISSUE THREAD

**Issue by insiderq** [bitpay/copay#5607]
Copay wallet says that i will need an access to coordination server in order to recover multi-signature wallet, can this process be done without a coordination server manually, using some self-written script or with 3rd party service like coinb.in? So the question is can it be done if copay servers go away? I have found copay recovery tool, but it is also unclear for me if it uses copay servers or not.

**Comment by dabura667** [comment]
Yes. But you will need m phrases and at least one exported wallet backup (json file on computer, or the mobile app I think exports to email client so you can email it to yourself or something)...

OR if you have ALL n PHRASES then you could also recover your funds.

The Copay recovery tool does not use Copay servers, it uses Insight though... which is also run by bitpay...

BUT you can actually run your own Copay server, as everything is open source.

The reason why it says you need access to the server is because that's the only way to EASILY restore... restoring without the server requires managing an encrypted json file along with your m phrases... very hard to explain to a noobie, so the app just says "write down this phrase and be sure to connect to the same server" to make things simple.

**Comment by insiderq** [comment]
Ok, thank you for an answer. What about usual wallets? Am i able to recover funds if everything goes wrong for example with this script having only 12 word seed phrase? https://iancoleman.github.io/bip39/

**Comment by dabura667** [comment]
Yes, but you don't even need that.

For single sig, just enter your 12 word phrase into almost any other wallet.

Electrum, Mycelium, MultibitHD, etc

**Comment by insiderq** [comment]
Thank you for the answers, i really appreciate your team responsiveness. Wish you all the luck!
