### ISSUE TITLE
(CRITICAL) Wrong key derivation for specific mnemonics, BIP39/BIP44 issue?

### ISSUE THREAD

**Issue by a49q258k** [bitpay/copay#5667]
TEST CASE:

Mnemonic `fruit wave dwarf banana earth journey tattoo true farm silk olive fence`
Passphrase `banana`

BitPay
m/44'/0'/0'/0/0 `13EuKhffWkBE2KUwcbkbELZb1MpzbimJ3Y`

Electrum, [iancoleman.github.io/BIP39/](https://iancoleman.github.io/bip39/)
m/44'/0'/0'/0/0 `17rxURoF96VhmkcEGCj5LNQkmN9HVhWb7F`

Also see https://github.com/iancoleman/bip39/issues/58, I am not sure which clients are deriving properly / improperly, but we have a BIP39 mnemonic and passphrase that derives different addresses on different clients

@slush0 @prusnak

**Comment by prusnak** [comment]
It is an issue with wrong private BIP32 derivation that has already been
reported and patch submitted.


https://github.com/bitpay/bitcore-lib/pull/97



Why it has not been merged and fix released is really beyond me.



HD wallets (including HW HD wallets) that do not use bitcore-lib private
derivation are not affected.

**Comment by prusnak** [comment]
@BGalliotti care to explain why you closed the issue?

**Comment by BGalliotti** [comment]
@prusnak Sorry, I tracked the pull request you mentioned and I ended up in this merged PR (https://github.com/bitpay/bitcore-lib/pull/116#issue-96833473) and this comment (https://github.com/bitpay/bitcore-lib/pull/116#issuecomment-289306738) that has a similar example as above working good. Could you tell me what's the issue here? Anyway, I will contact the wallet team today.
