### ISSUE TITLE
Beta Issue: white screen, home screen not loading after splash screen 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5709]
Using beta 3.0 on Android 7.1.1, Nexus 6P. I've tried closing and reopening the app with the same results.

**Comment by JDonadio** [comment]
## **[ANDROID]**

This is an issue caused by an error during the building. Please, if you are subscribed as beta tester, please follow this:

**To upgrade the app**

1) click here: https://t.co/mS3sm5kUX0
2) click on: "Download it on Google Play first"
3) see if the 'upgrade' option is available

Thanks

**Comment by JDonadio** [comment]
Please reopen if the problem persist.
