### ISSUE TITLE
transaction id and mBTC

### ISSUE THREAD

**Issue by Gibmireinenusername** [bitpay/copay#5783]
Cant find the transaction ids inside the app or i have to open the blockexplorer. I would like to have the option to put it to mBTC, not only BTC and Bits. Thank you very much and greetings

**Comment by JDonadio** [comment]
Hi there, 

In order to simplify your suggestion and the features request you should create separated issues.

> Cant find the transaction ids inside the app or i have to open the blockexplorer

Definitely we'll review this and try to get a good design for it.

> I would like to have the option to put it to mBTC, not only BTC and Bits

Please see [this thread](https://github.com/bitpay/copay/issues/4438), specially to [this comment](https://github.com/bitpay/copay/issues/4438#issuecomment-227844494).

**Comment by gabrielbazan7** [comment]
I will close this one in order to https://github.com/bitpay/copay/issues/3999. Thanks for the comment!

**Comment by Gibmireinenusername** [comment]
Hi,
Thank you very much. Keep on the amazing work. Im looking forward for
further progress. Have a nice day, greetings

Am 16.03.2017 2:07 nachm. schrieb "Javier Donadío" <notifications@github.com
