### ISSUE TITLE
Hard Fork

### ISSUE THREAD

**Issue by tommyquite** [bitpay/copay#5792]
Hello,

I really enjoy using the Copay wallet, I have a slight concern tho.

In the unlikely hypothetical case of a hard fork of Bitcoin, will storing coins in my Copay wallet allow me to have both coins? So will my current amount of coins be doubled and evenly spread over both coins? Read somewhere this would be the case if a fork would actually occur. And money on exchanges wouldn't necessarily be "doubled".

Thanks in advance.

Best Regards,

Tom

**Comment by dabura667** [comment]
Storing your bitcoin in ANY wallet will mean you have coins that can be spent both once on each fork.

However, whether that means "double your coins" or not is up to interpretation.

In regards to Copay, Copay's backed is currently running Bitcoin Core, so in the event of a hard fork, the first expended utxo before the point of fork will be sent and broadcasted to the network (assuming no replay protection is implemented in BU) and likely will confirm on both forks. Then, when you try to send the change from that transaction, Copay as it is right now will only be able to send the change that is confirmed on the Bitcoin Core blockchain.

However, that is only a matter of "ability to send" and not "owning coins." You will still have ownership of the coins on the BU chain, you just need to import your BIP39 phrase into a wallet that supports BU and BIP39/BIP44 and you will be "able to send" your BU coin balance as well.

This all assumes that Copay's backend stays on Bitcoin Core throughout the hard fork. Seeing as Bitcore has stopped updating past Bitcoin Core 0.12.0, it is unlikely that they will move to any new fork quickly. (seeing as their decision to stop supporting bitcore-node was likely due to priorities... and Copay doesn't make them any money to begin with.)

However, I would also be interested to hear if the Bitpay dev team has made any decisions on how they would handle a hard fork.

**Comment by frenchfaso** [comment]
Yes, I would also like to know which is their official position towards a hard fork...

**Comment by matiu** [comment]
As a wallet, Copay will support whatever the Bitcoin community decides and make sense for our users, to transact and retain their stored values.

**Comment by sushilraghav** [comment]
@tommyquite @dabura667 @frenchfaso @matiu @kleetus  For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
