### ISSUE TITLE
Private keys and security

### ISSUE THREAD

**Issue by tommyquite** [bitpay/copay#5816]
Hello,

I apologize in advance but I'm not very technical and was wondering about something that might seem very obvious to some of you. From what I understand your private key is the key you use for spending, and therefore the key to your bitcoin funds. With Copay I do not own my own private key from what I understand. Who does? Does Copay own the key? And if so, what is to keep them from hypothetically stealing bitcoins from users? 

To clarify, I fully trust Copay, and in no way fear they would do any such thing. But I just want to understand how secure my wallet is. And the bitcoin wallets security system in general, as I feel I must be missing something. 

Thanks in advance for explaining.

Best Regards,

Tom

**Comment by isocolsky** [comment]
You do own the private key. With Copay you are the only one in control of your funds. As long as you keep the 12 words you are safe.

**Comment by dabura667** [comment]
Copay generates your private keys on your device, and merely sends the corresponding public keys to the server so the server can watch the blockchain for you and send you email notifications and push notifications and the like.

We know this is true, because the code that makes Copay work and the backend server work are all up here on Github.
