### ISSUE TITLE
balance fix pls

### ISSUE THREAD

**Issue by zakkum1** [bitpay/copay#5940]
![balance](https://cloud.githubusercontent.com/assets/28070128/25458556/0571ef7a-2ae3-11e7-982c-be85e03b702e.png)
send problems 
insufficient funds error fix pls

**Comment by gabrielbazan7** [comment]
This happens when you have insufficient funds to pay the fee amount of the transaction you are trying to send. It could be possible that you have a ton of very small inputs that are no economical worthy to send. You can get an idea of your "usable" balance by trying to send all (using the send all feature) funds to other wallet.

**Comment by gabrielbazan7** [comment]
If you have more questions, please re open the issue. Also, if you want, take a look to the Copay/BiPay FAQ http://help.bitpay.com/bitpay-secure-bitcoin-wallet.
