### ISSUE TITLE
I didnt recieve my btc on copay

### ISSUE THREAD

**Issue by Wizawt** [bitpay/copay#5965]
My copay Adress: 1Nge4Rvg77ZNsLuoxFNF2NxqmcPF11Bz4c
Transaction: https://blockchain.info/tx/15aedf47582561cc52f04ca0c0b26b64c836950fa5a5b5368785913b28e59ae1
![screenshot_20170506-015059](https://cloud.githubusercontent.com/assets/12194672/25759929/c3a722fe-31fe-11e7-8d66-029ff46c2f09.png)

My first and only problem after using copay, what's wrong?

**Comment by gabrielbazan7** [comment]
Click on the address and try "Scan addresses for funds"

**Comment by Wizawt** [comment]
Not working mate. maybe it's on the bitcoin side since its still unconfirmed after 1+ day. Gonna try to follow up the result later on if anything changes. thanks for the response!

**Comment by dabura667** [comment]
The person sending to you has an unconfirmed chain of transactions about 3 transactions long and has double spent the root utxo 3 times to different addresses.

There is a high chance that the money will never arrive to your wallet ever.

If this is a website/service. Please tell me the name so I can warn them to stop doing dangerous things that endanger their customer's funds... but perhaps they are doing it on purpose to steal something from their customers.

**Comment by dabura667** [comment]
Wow... either they have 5 year olds for engineers, or they made a web of double spends depending on each other in order to make it difficult to find out what they're doing.

Blockchain.info shows all double spends, so it's good for spotting anomalies. But it doesn't mention when an unconfirmed parent is double spent... (it probably should).

The site probably was using this fact to make it look like they paid you and then pull the rug out from under you later.......... (or they hired a 5 year old to code for them)

**Comment by Wizawt** [comment]
it is indeed a web for exchanging my local currency to bitcoin, this is my first problem on the site and i've never been on any problem before. 

i am not really technical and i don't really understand how is this happening. but the site was http://triv.co.id
you should probably give technical advice to them...
