### ISSUE TITLE
Feedback and concerns about the UI 

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5977]
From @toomim : 

_Hey guys, do you do any user testing on desktop?
The "swiping a card" at the bottom for accounts is not intuitive on desktop, and displays the wrong cursor.
In order to change accounts, you have to drag and drop a card with the mouse. But drag and drop is not an easy operation with a mouse. And if you DO need drag and drop, you should use a "grab" ![76b543d8-2144-11e7-862b-c3d118218012](https://cloud.githubusercontent.com/assets/10999037/25807595/c7d136b8-33dd-11e7-9ec1-ea04ef4333b8.png) cursor image or a "pointer" ![808c870e-2144-11e7-8151-c0bd5e41d61a 1](https://cloud.githubusercontent.com/assets/10999037/25807572/b44bc3d8-33dd-11e7-809d-e4ca17708fa7.png) but right now it's using a default arrow cursor:  ![89e5856c-2144-11e7-8521-00fd3dda08b5](https://cloud.githubusercontent.com/assets/10999037/25807589/c13ef1f0-33dd-11e7-91e3-b03ee708dc36.png). That gives no suggestion to the user that you can even drag and drop, and thus that you can change accounts.
If you didn't run into the problem selecting a wallet in your user testing, it sounds a lot like you didn't test with any desktop users. I recommend you give it a shot.
Also, ask them to try copying the bitcoin receive
 address to the clipboard. I bet they will find it confusing. You are making them click on the QR code right now! That doesn't make sense when you have a mouse cursor_

_Also, when something is clickable you should use the pointer icon:  ![808c870e-2144-11e7-8151-c0bd5e41d61a](https://cloud.githubusercontent.com/assets/10999037/25807659/f93f7ba6-33dd-11e7-9b98-3786b6698bd1.png) 
But none of the cards are showing up as clickable. It displays no pointer icon. So changing accounts is not discoverable on desktop. 
Finally, it would be way better if you reversed the order and put the account selection on TOP. Users need to select their account before they grab its bitcoin address, and actions in a user-interface should proceed top-to-bottom, left-to-right, in the same order that western people read.
Thanks for reading! I hope the UI gets better._

**Comment by JulianTosh** [comment]
The current UI is very confusing and non-intuitive for new users. Users tend to want to browse their account list and select an account interact with (to send/receive), which is counter to the current requirement to select a function (receive, scan, send) first, the select the account. 

If they select an account first, there should be a means to select an operation (receive, send) on that account.

When selecting the send function, it is difficult for users to make decisions on to/from accounts because there is no balance information shown. Continuing on to the amount page, there is again no balance information. Users will have to guess/remember an amount to enter that is less than what's actually available. Further, the ability to "Send All/Max" is not intuitive. No new user I train can ever find this on their own.

Perhaps simply changing the order of these screens may help: From/To first, then placing the amount screen last.

Having to choose the settings function to get to wallet details is annoying and non-intuitive. This should be accessible from viewing the wallet from the lists.
