### ISSUE TITLE
Purchasing BTC on BitPay using the Glidera integration and who sets the transaction fee policy

### ISSUE THREAD

**Issue by letitbegood** [bitpay/copay#6015]
Hello, 

Several days ago I made a purchase through my BitPay wallet using the Glidera integration.  The transaction was completed about 2 hours ago and the BTC shows in my wallet, but has not yet been confirmed.  In my BitPay wallet, it says “This transaction could take a long time to confirm or could be dropped due to low fees set by the sender”.  My Fee Policy was set to ‘normal’ and have always had quick confirmations in the past using this setting, so it's strange to get this message.

My question is:  When I purchase through my BitPay wallet, is it using the transaction fee I set on the wallet, or a transaction fee that is set by Glidera?  I am happy to change the Fee Policy to 'urgent' in the future, but first want to understand who is setting the fee when I use the Glidera integration.

Thanks.

**Comment by gabrielbazan7** [comment]
Hi, Glidera set the fee. But I think is not configurable. Maybe you should ask them

**Comment by letitbegood** [comment]
Yes, I wasn't sure who handled the fee but I've also reached out to Glidera but have not heard back yet.  You are correct that it is not configurable on their end.  

Question: Since the BTC shows in my BitPay wallet, can I send a spend a small fraction of it to another wallet I have and set the BitPay network fee policy to 'urgent' in order to pay the highest transaction fee possible?  If so, do you think this will help to confirm both transactions together? 

Also, is there a way to set my own transaction fee in BitPay, or do I have to use one of the 5 options available?

Thanks.

**Comment by amycv3** [comment]
I started the "please help" thread.  My transaction is now showing in my wallet, but it is not a true balance.  My true balance is 0.00.
And I have the exact same message: "...transaction could take a long time or be dropped"...
What is really frustrating is that I used a Bitcoin ATM and those transactions should be instantaneous.
I've done plenty before and they all deposited immediately using a different wallet.
Set up this wallet, made the transaction, and now I'm being told I have to get a refund from the ATM because the transaction was dropped due to low fee.
Something isn't right here.....

**Comment by dabura667** [comment]
> those transactions should be instantaneous.

Tell that to the Bitcoin ATM company. The receiving wallet has 0 to do with the confirmation speed in Bitcoin. Only the sending wallet can affect confirmation by adding a proper fee.

**Comment by gabrielbazan7** [comment]
@letitbegood mmm I don't recommend you to do that. I'm not sure that Copay will use those utxos to send the other transaction. You could not set your own transaction fee (to avoid low fees transactions that will never be confirmed)
