### ISSUE TITLE
funds confirmed but balance not available in my wallet

### ISSUE THREAD

**Issue by learner5** [bitpay/copay#6016]
i have updated to bitpay 3.2.0 from one before that update and have bought BTC is confirmed but not available in my wallet please fix the app this is the transaction that i'm receiving the balance  77ccd88c49dc737828eca46e89384aac21cbff37db55a64ee89bcca16a93edc4  i was transferred  52 USD

**Comment by gabrielbazan7** [comment]
What do you mean by not available ?

**Comment by learner5** [comment]
balance not available in my wallet

**Comment by maytherman** [comment]
I have the same issue. Money has been taken from my bank account but nothing is in my wallet

**Comment by dabura667** [comment]
@learner5 the money received in transaction you have shown us is all spent. Did you send any money after receiving that transaction?

@maytherman I understand that Coinbase support is slow, which is why I personally never use them. But please be patient, as there is nothing we can do on our side, and your issue is to do solely with Coinbase, and is unrelated to the issues you keep responding to. Thank you for your patience.

**Comment by learner5** [comment]
i received 54.74 confirmed but it does not show up in my wallet  i have spent 10.59+2.10+12.50 after that  with a total of 25.19 and i have not spent nothing more  and just have 1 dollar available.

**Comment by dabura667** [comment]
The transaction you mentioned, received 54.38 USD:
https://insight.bitpay.com/tx/77ccd88c49dc737828eca46e89384aac21cbff37db55a64ee89bcca16a93edc4/%3C/0

Sent 10.50 USD (+ 0.93 USD fee):
https://insight.bitpay.com/tx/8c21c4e69e8a8cd24530bbb720747c0a5d2377dc3076769f147ad1a0ff55ceef/%3C/0

Then sent 25.61 USD (+ 0.94 USD fee): (You did not mention this transaction... why?)
https://insight.bitpay.com/tx/5618f94aa1484b6959b80317835e4756094243427e5edbf9018a23316e7243ce/%3C/0

Then sent 2.09 USD (+ 0.94 USD fee):
https://insight.bitpay.com/tx/b572536db724e4e3da827b6d879f28e4b936b4d88674a1b4d99e819473026aff/%3C/0

Then sent 12.43 USD (+ 0.94 USD fee):
https://insight.bitpay.com/tx/c68e60fe7c4f030325585a6b9f32b4f780dd0b8272490ae3386e1fda7712f220/%3C/0

```
+54.38 USD
-11.43 USD
-26.55 USD
-3.03 USD
-13.37 USD
==
0 USD
```

If you have 1 dollar available it is probably because you received 1 dollar from someone... because from the transactions I can see you should have 0 dollars, and not even 1...

All of the above transactions are confirmed in the blockchain.

Try sending us a screenshot.

Also, you can go into your wallet options screen from Settings >> (your wallet) >> Transaction History >> Clear Cache, and then your app will re-download the history again, and hopefully things will appear properly.
