### ISSUE TITLE
fondi insufficienti per inviare BTC

### ISSUE THREAD

**Issue by Guidosogliani62** [bitpay/copay#6027]
Good morning, I tried to transfer 0.352 BTC but a window tells me that the funds are not enough ...
I await your communications
Best regard
![mancanza fondi sogliani](https://cloud.githubusercontent.com/assets/28704921/26054900/c788cd92-396e-11e7-907d-94e7c8c2dba1.jpg)

**Comment by gabrielbazan7** [comment]
This happens when you have insufficient funds to pay the fee amount of the transaction you are trying to send. It could be possible that you have a ton of very small inputs that are no economical worthy to send. You can get an idea of your "usable" balance by trying to send all (using the send all feature) funds to other wallet.
