### ISSUE TITLE
Account not recognizing Coinbase account

### ISSUE THREAD

**Issue by Buddyzilla** [bitpay/copay#6061]
I connected my Coinbase account to Copay; however Copay doesn't recognize that. It says on Coinbase that I have it connected.

**Comment by gabrielbazan7** [comment]
Could you give us more detailed information about this issue ?

**Comment by Buddyzilla** [comment]
There is nothing more to say, I've gone through the process of connecting Coinbase to Copay but Copay still wants me to connect Coinbase even though it's already connected.

**Comment by cmgustavo** [comment]
Did you already receive the email from Coinbase that the account has been connected?

What version of Copay do you have installed? Platform (iOS, Android or desktop)? 

Thanks.

**Comment by Buddyzilla** [comment]
I got the email every time I tried and I'm using the Android version.

**Comment by cmgustavo** [comment]
This 's a known issue and we don't have a fix yet.
Some Android devices have an old or incompatible browser in order to handle custom URL's. Please, take a look at this thread to get more information and try to connect to Coinbase manually. https://github.com/bitpay/copay/issues/5891#issuecomment-297076251
