### ISSUE TITLE
Wallet Recover

### ISSUE THREAD

**Issue by mike1968mi** [bitpay/copay#6087]
Can I recover my wallet with the phrase if I don't have an internet connection?

**Comment by dabura667** [comment]
> Can you recover the private keys (the keys used for signing and authorizing transactions on the bitcoin network)?

Yes. Those keys are never stored outside your device, so you don't need an internet connection.

> Can your Copay app set up a new wallet without an internet connection?

Because the wallet does a lot more than just restoring your private keys on startup, a new wallet will fail on startup without an internet connection, because it won't be able to check balances or anything else without access to the blockchain.

**Comment by matiu** [comment]
Please stop openning tickets about the same issue. It has been answered in
detail in the previous issues you opened.

On May 21, 2017 1:19 PM, "Dabura667" <notifications@github.com> wrote:

Can you recover the private keys (the keys used for signing and authorizing
transactions on the bitcoin network)?

Yes. Those keys are never stored outside your device, so you don't need an
internet connection.

Can your Copay app set up a new wallet without an internet connection?

Because the wallet does a lot more than just restoring your private keys on
startup, a new wallet will fail on startup without an internet connection,
because it won't be able to check balances or anything else without access
to the blockchain.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6087#issuecomment-302946701>, or mute
the thread

**Comment by mike1968mi** [comment]
So I do need an internet connection to recover the wallet with the phrase so it IS stored on Copay servers so my Bitcoin must also be there as well. 

All I want is MY Bitcoin funds, that's all. I'm not asking for anything that does not belong to me. 

**By due process of law, my wallet funds must be returned to me from Copay.** You must give me access to the service you provided me with and use another form of verification. 

**### Copay breached their terms and services by using false statements about the service and misleading clients.** 

At the time of my deposit in to my Copay wallet Bitcoin was at $1,800 and is now over $2,000 and you must pay the amount I have lost on my investment as well.

**Comment by mike1968mi** [comment]
So I do need an internet connection to recover the wallet with the phrase
so it IS stored on Copay servers so my Bitcoin must also be there as well.

All I want is MY Bitcoin funds, that's all. I'm not asking for anything
that does not belong to me.


   - *By due process of law, my wallet funds must be returned to me from
   Copay.* You must give me access to the service you provided me with and
   use another form of verification.



   - * Copay breached their terms and services by using false statements
   about the service and misleading clients.*


At the time of my deposit in to my Copay wallet Bitcoin was at $1,800 and
is now over $2,000 and you must pay the amount I have lost on my investment
as well.




  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>
