### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by neotribe** [bitpay/copay#6099]
the problem is that I can not stand out anything. Although I have 0.01 btc in the account, it means the fees are not enough. That can not be.

**Comment by latifiwallen** [comment]
I have Bitcoins that were sent from my Blockchain account to my copay account and it is still pending after 5 days. How can I cancel this transaction?

**Comment by hoangthanhzz** [comment]
I wonder how to cancel the transaction , that affect the bitcoin ? Or lost bitcoin available!

**Comment by gabrielbazan7** [comment]
@neotribe This happens when you have insufficient funds to pay the fee amount of the transaction you are trying to send. It could be possible that you have a ton of very small inputs that are no economical worthy to send. You can get an idea of your "usable" balance by trying to send all (using the send all feature) funds to other wallet.

@latifiwallen Could you share the transaction id ? It seems that the transaction still pending because the fee associated to that transaction is too low. You can't not cancel a transaction, if the transaction do not get confirmed, should be dropped in ~ one week.

@hoangthanhzz  No, a bitcoin transaction which has already been broadcast to the network cannot be reversed. This is an important feature of the bitcoin protocol which prevents payment fraud. Take a look to https://bitcoin.org/en/faq#transactions

**Comment by latifiwallen** [comment]
I think that because of the low fee, that is the problem. Is there any way to add to the fee after the transaction has been sent?

**Comment by gabrielbazan7** [comment]
@latifiwallen yes there is a way, but is a little advance option, and it is not sure that it works, but you could try if you want. Please follow very carefully the instructions. Go to settings -> advanced -> turn on "use unconfirmed funds". Then go to settings -> Bitcoin Network Fee Policy -> click on "urgent". Then go to receive and copy your wallet address, make sure is the wallet where you are receiving the funds, for example with the name : Personal Wallet. Go to send and copy that address in the recipient label, then on the calculator view click on more options and then send max. Then on the confirm view choose the SAME wallet as the sender ( Personal Wallet ). And slide to send. This way you will be sending the funds to your own wallet, using the unconfirmed inputs of the last transaction with a bigger fee and helping them to get confirm.

**Comment by neotribe** [comment]
Thanks for the hint,but it doesn't work. I will delete copay and take another wallet. I lost now 40 dollars and thats not funny. With my other wallet i never had this problem...

**Comment by gabrielbazan7** [comment]
@neotribe you tried the send max option ?

**Comment by neotribe** [comment]
Yes, it says always there are not enough funds for fee...i have 0.02 btc and the urgent fee is 0.004....

I dont understand where the problem...

**Comment by latifiwallen** [comment]
I will try that. But I agree about not using copay! I have $365.00 worth of Bitcoin just pending!! THIS SUCKS!!

**Comment by latifiwallen** [comment]
I just tried your idea. Let's see how it works.

**Comment by latifiwallen** [comment]
IT WORKED!!! I don't know what Wahome you are BUT, YOU ARE A GENIUS.. I CAN NOT THANK YOU ENOUGH!!!!!!

**Comment by gabrielbazan7** [comment]
@latifiwallen GREAT!!!.

Remember that the sender always pays for the fee. In your case the low fee was sent by your blockchain wallet.

**Comment by gabrielbazan7** [comment]
@neotribe send me an screenshot of the confirm view when you try to use the send max option

**Comment by neotribe** [comment]
Here the pics

**Comment by latifiwallen** [comment]
The Move line shows were I used the max option.
