### ISSUE TITLE
My last transaction is not showing

### ISSUE THREAD

**Issue by mrgrady123** [bitpay/copay#6119]
Hello,

I received some money yesterday and its status was on **Receiving**, So I ignored it and when I woke up today, there was no transaction as **Receiving** or **Received**. I am too much confused and worried cause it was much amount of cash and have no clue where it went.

Please help me ASAP

**Comment by my100bucks** [comment]
I have the same problem for my last two transactions. Waiting for solution 😐

**Comment by mrgrady123** [comment]
you also use copay?

**Comment by my100bucks** [comment]
Yes. On IPhone

**Comment by my100bucks** [comment]
I'm issue #6115. I hope this get fixed soon

**Comment by JDonadio** [comment]
We'll take a look, thanks for report it.

**Comment by mrgrady123** [comment]
15 hours still nothing

**Comment by nobugz1222** [comment]
I'm having this same problem with my copay wallet.. I'm set to lose out on a lot of money if this isn't fixed. This is the first time I've used copay and they have transactions disappearing? Wtf

**Comment by gabrielbazan7** [comment]
You transaction was dropped due to low fee set by the sender. You should ask him to re send the transaction with a proper fee. You could have an idea of a proper fee on this site https://bitcoinfees.21.co/

**Comment by mrgrady123** [comment]
No but he is experienced and he has sent me many time but how that is possible, I have spoken to him today and he was saying that it will be received in one day or so, but he was thinking that it is unusual wait.

**Comment by my100bucks** [comment]
I'm issue #6115 they closed my issue without answer. It won't show on insight because insight has been having this issue for past two weeks. Also copay has been dropping and showing transactions for me. I believe there are more and more people having this issue but they don't know how to follow up. Please look at this and try to solve. I like this app but if this keeps happening I have to switch. Btw Gabriel said my transaction does not exist but I can see it on blackchain.info but insight is telling me the transaction does not exist. However it would show the transaction once in a while and again it will say it does not exist?! Please help resolving this issue for all of us

**Comment by my100bucks** [comment]
In addition this are people which I have been working with for more than a year and they are telling me that they are experiencing the same problem with few other copay users.  The transaction can't drop within first few hours!

**Comment by my100bucks** [comment]
go to blockchain.info and input your address the you used to receive and if you see the transaction there send the link here.

**Comment by JDonadio** [comment]
Should be ok now. Reopen if the problem remains.
