### ISSUE TITLE
Bip 148

### ISSUE THREAD

**Issue by ncsuwolfs** [bitpay/copay#6130]
Will copay support bip 148 is necessary?

**Comment by dabura667** [comment]
1. I think Bitpay will not suppory BIP148 as they have signed on to Barry's agreement.
2. If you want to support BIP148 you MUST run your own full node with BIP148 on it. The whole point of BIP148 is to say to the miners "you are not the boss of us, you are our servants"... but if you rely on Copay's server, you are letting Bitpay be the boss of you.

You can run your own Copay server with BIP148 on it.

**Comment by chrisrico** [comment]
>You can run your own Copay server with BIP148 on it.

Is there a guide for compiling Bitcore with BIP148?

**Comment by gabegattis** [comment]
We have no intention of supporting BIP 148

**Comment by tommyquite** [comment]
Damn, seems like I have to part ways with Copay, if they don't support UASF..

Any chance they will change their minds?

**Comment by dabura667** [comment]
> If they don't support the BIP148, what will happen if I keep my coins in a Copay wallet and BIP148 activates. I won't get coins on both sides of the chain?

No, you will have coins on both sides of the chain. The only difference is that if a utxo split happens you will only be able to send coins on the non-BIP148 side using copay.

If you don't have a utxo split occur (there's no way to tell unless you are running a BIP148 node and a non-BIP148 node.) then using Copay will essentially be sending coins on both chains simultaneously.

Wallets that "support BIP148" will be the opposite, you will be inadvertently spending coins on a chain you are not validating and neither is your wallet provider.

The only way to safely navigate your coins properly through a sustained hardfork is to run a full node of both sides of the fork.

I now have a BIP148 backed Copay wallet, a legacy Core backed Copay Wallet, and a BU backed Copay wallet just so I can double check the balances on each.

Electrum is easier to patch to match with BU / BIP148 so I am thinking of switching back to Electrum since their server side software is more compatible with full node software out of the box.

But assuming no new stupid hard forks appear, I won't need to track another chain...

*Looks at the Consensus 2017 nonsense frankenSegwitHardForkPreserveASICBoost + 2MB*

*Takes a deep sigh*

How many chains will I need to watch now?...

Anyone who says "watch only the chain you believe in" is not a pragmatist.
