### ISSUE TITLE
Advanced send

### ISSUE THREAD

**Issue by kemoantemo** [bitpay/copay#6138]
Sometimes i need to some advanced options in sending like i choose how much fees i want to enter and send a specific inputs not the auto choose by the wallet the first may added as advanced button when sending and the second added at more advanced button

**Comment by thephez** [comment]
Ditto this.  Especially with the current cost of fees, a manual option would be useful for transactions that do not need to be confirmed for longer periods of time.  I have some funds that I will probably have to build manual transactions for because even the economy fees are too large to warrant sending.
