### ISSUE TITLE
Issue with fees

### ISSUE THREAD

**Issue by trx314** [bitpay/copay#6166]
Hi,
I let my fee setting as "normal", therefore I was expecting to that my transactions would request around 350 sat/b .
However, when I look at the actual fee of the transaction I did yesterday, it says 86sat/b.
Result: the transaction has been stuck "unconfirmed" for 18hs.
Two questions:
1- regarding the setting of fees in copay, why did I do wrong? I don't understand the discrepancy between what is indicated in the app and the actual result.
2- regarding my stuck transaction, what can I do? The app does not allow to increase the fees, right?
Thanks

**Comment by trx314** [comment]
Forgot to put the transaction link.
Here it is:
https://blockchain.info/tx/31bb5ae6e410d4ccebcc7dd56f8512e0e0e894df854e612e7ab09840befbb36e

**Comment by M1bhai** [comment]
Hey bud 

It took 8 days and then just because bitcoin miners dropped the transaction fees to .0003 my transaction got mined... but for 8 days I kept seeIng my coins come back and it was bothering me because I could not send them... bottom line here is that I m sure your coins will come back soon. These guys here aren't much help. You can scroll down and see my issue they don't help at all actually. The problem is that this company "Copay" is located somewhere in a 3rd world county I think it's Argentina. They just don't care down there about anything. Your money, your life. It's all there you can see how for a week I reached out and they would kinda play games if you ask me. So bottom line here. Just in the future transfer the bitcoins straight from the seller to your hard storage don't even bother with this APP... but ya your coins have to come back.

**Comment by thephez** [comment]
@trx314 You are correct - Copay doesn't support fee bumping, so you are kind of stuck waiting for the transaction to clear (or for it to get dropped from the mempool).  An unfortunate side affect of the network congestion due to the block size issues.

@M1bhai Copay is just the unbranded version of the [Bitpay wallet](https://bitpay.com/wallet).  Bitpay is based in the US (Atlanta) and is one of the largest bitcoin payment processors out there.

**Comment by trx314** [comment]
@thephez thanks. Any idea on why it went with such a low fee despite I let the "normal" setting (supposed to send 350sat/b)?

**Comment by thephez** [comment]
@trx314 I am not sure why that would happen.  On Android, it displays the transaction fee amount (in both BTC and USD) before broadcasting so you can do a rough sanity check on it by assuming the transaction is ~250 bytes.  This could obviously be way off if the transaction contained a lot of inputs or outputs, but it should give you a ballpark idea of the minimum transaction fee (i.e. 350 S/byte * 250 bytes =  87,500 satoshis).

**Comment by rafakortez** [comment]
Got exactly the same issue, Transaction Stuck, App says .003, but the actual fee is 350 satoshis.
So probably my money will get stuck for days. 
I posted my problem today but no answer so far.
https://github.com/bitpay/copay/issues/6200

**Comment by rafakortez** [comment]
any follow up into this? funds eventually will come back after days?

**Comment by trx314** [comment]
I got my tax confirmed by a "private" miner. Costed $7 and after half an
hour the tx received the first confirmation. Search on bitcointalk forum,
in the technical support section.

**Comment by matiu** [comment]
Sorry  the delay:

> 1- regarding the setting of fees in copay, why did I do wrong? I don't understand the discrepancy between what is indicated in the app and the actual result.

We use bitcoin-core fee estimation. This algorithm reset itself if the server restart. I could had happen that you sent the TX while that was happening, we had made some changes on our backend to prevent this from happening again (i.e. to "warm up" the server after it restarts).

> 2- regarding my stuck transaction, what can I do? The app does not allow to increase the fees, right?

You can wait until it is dropped from the mempool (~3 days) or chain a TX will higher fee. We are working on a feature within copay to do the second option from the app, in a friendly manner.


Thanks
