### ISSUE TITLE
Fees extremely high ?

### ISSUE THREAD

**Issue by cryptony** [bitpay/copay#6170]
Hi I tried since yesterday to do a transaction with a friend and the copay fees set as normal are ridiculously hugh (32% of the amount) ... it is a bug, a joke, or a temporary situation? Please tell me lol

**Comment by dabura667** [comment]
>  it is a bug, a joke, or a temporary situation?

None of the above.

This is Bitcoin as of late. For a normal transaction $1.50 - $2 fees are common, and if your wallet contains a lot of utxos (you have no control over this, neither does Copay, only the people who send bitcoin to you control this number) you pay more.

The amount of money being sent has 0 to do with the fee.... so if you send $10000000 you are probably still very happy ($2 is very small compared to that amount) but if you're sending $5, then 40% fees for you, sorry.

**Comment by schwanzkopfhegel** [comment]
Well, I have Tested it also, and in my opinion the fees are very high.
I have 0.006 btc on my Wallet (13€) and want to pay 0.001 btc (a bit more than 2€), which does not work because of the fees. So the fee for one transaction would be over 0.005 btc (over 10€)!!!

This cant be realistic. Next time I buy a burger @fastfood restaurant I pay the hole loan from the employee before I start thinking buying the Burger.. 

Kind regards

**Comment by ninara** [comment]
I am having the same issue and it looks to me as a bug in the system. It is impossible that a message ning fee can be that hight.
I have 0.00227 BTC and no matter what amount I try to send, I always get - insufficient funds error.
This is crazy.
I have a Jaxx wallet and there I can see how much is the maximum annount I can send and send can see exactly how much is the mining fee in advance and it's never that high!!!
The Jaxx wallet automatically calculates the maximum amount that can be sent and leaves enough funds for the fees, so that the transaction can be made.
Here, when I click on the send max an mount I am not even shown what this ammout is. I only see .... and then I get - insufficient funds.
Can you please, fix this?
If I have 5usd in my bank card I sure as hell can use them all. Here, they are trapped in a wallet and I am seeing other people complaining about the same issue. Can someone please look into this. We need a solution for these extremely high fees and also for BitPay and Copay allowing users to use their funds.

**Comment by dabura667** [comment]
@ninara Tap "Send Max" on the menu top right.

**Comment by ninara** [comment]
Tried that - the app says the same - "Not enough funds for fee" 
even if I try to send 0.00001 BTC it still says - Not enough funds for fee...
I am perplexed.

**Comment by schwanzkopfhegel** [comment]
@nirnara same issue here..

**Comment by gabrielbazan7** [comment]
Hi take a look to Copay FAQ https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send

**Comment by Pal0720** [comment]
So is there a way now to reduce the charges? Maybe by once sending a large amount and then withdrawing?

**Comment by dabura667** [comment]
> So is there a way now to reduce the charges? Maybe by once sending a large amount and then withdrawing?

There's a way to reduce your future fees by making sure you don't receive a lot of money in small amounts.

ie. If you are a miner, don't get payouts in 0.0001 BTC every day, try to opt for getting 0.003 BTC every month instead.

This will decrease your eventual fees paid.

However, once you have bitcoins in your wallet, the amount of bytes of data needed to send that money is mostly set in stone, and fees are on a per byte basis.

Right now 300 satoshis per byte is the norm... but maybe in a few months that might go down to 20 satoshis per byte...

but that still won't change the fact that receiving one big amount is cheaper to send than receiving a ton of small tiny amounts.

**Comment by 55dmb** [comment]
This is irritating. I have a permanent $50 in my wallet that I can’t touch. Earlier I tried to send $40 in BTC out of $120 in BTC. Apparently an $80 difference is insufficient funds. Plus the fee to move money to the debit card is insane. I can’t take .005 out of my wallet ($50ish) because of BitPay’s quirks? Shadiness? Don’t know...don’t care, but I do know that’s ridiculous! Want to know how much the “max” amount of $50 is? $40 you say? Do I hear $35? All intelligent guesses...try 2 bucks. My guess is that BitPay does this now as a way of keeping customers from straying from BitPay, sort of obligating you to use their wallet or lose $50 - $100 dollars. Well, not lose, but be unable to access and move anywhere...ever. I’m printing the keys and cutting my losses - this angers me and if I actually tell you what I think then my comment will likely get deleted. Clearly the above responses demonstrate no interest in resolving this issue. I’m 👏 out !

**Comment by billtata11** [comment]
When I tried to send it out, It was mentioned that the fees is 14.4%.  Ridiculous!! Dont use copay!!

**Comment by 55dmb** [comment]
Yeah that bothers me less than being unable to send say $40 when you have $100 in your wallet. It’s like it requires a significant ‘extra’ to just sit in the wallet. I use them to scan my mnemonic now but spend and receive from a different program.

Sent from my iPhone

David M Browning
PhD Candidate (ABD) and Teaching Fellow
The Catholic University of America
(c): (970) 222-7914
(email 1): 55browning@cua.edu
(email 2): davidmbrowning@icloud.com

**Comment by ericrasor** [comment]
I just sent funds to my BitPay card $125 of BTC.  It took nearly 6 hours for the transaction to process.  By the time the funds were transferred the value had dropped to around $80 of BTC and the transaction fees exceeded the value so I was left with nothing.  Now my wallet will not let me transfer the remaining BTC that I have in my wallet to a card to save what value I have. (BADREQUEST: Invalid fee per KB) $800+ is now less than $500.  Not happy as I watch my $$$ disappear.

**Comment by cryptorobb** [comment]
Paying a 130 dollar invoice will cost me 53 dollars, I am gonna do it and never use bitpay again...

**Comment by cryptorobb** [comment]
![inkedphoto_2017-12-23_21-15-53_li](https://user-images.githubusercontent.com/34798907/34324427-6af55e70-e827-11e7-9f0a-9c68a7f83a8b.jpg)
Please tell me my eyes deceive me and it meant $5.39. I am going to pay, and this will be the last time I ever use bitpay. BitPay is ran by a bunch of thieves.

**Comment by 55dmb** [comment]
Not sure how I made it onto this thread, but agreed. I use electrum for desktop and Blockchain for iOS. BitPay really bothers me - everything is expensive now, but there’s expensive and then there’s highway robbery with a nice UI. Every time I try to use BitPay again I regret it. Even CoinDesk has mentioned that the company has a recurring “headache” with the fees.

Sent from my iPhone

David M Browning
PhD Candidate (ABD) and Teaching Fellow
The Catholic University of America
(c): (970) 222-7914
(email 1): 55browning@cua.edu
(email 2): davidmbrowning@icloud.com

**Comment by Cr250cra1** [comment]
DO NOT send money to copay wallets they are stealing your coin.. It wasn't allways like this STEER CLEAR; SCAM ALERT

**Comment by billtata11** [comment]
I also have experience sending $60 to usi tech from Coinbase , the fee was $35. 
I saw all wallet to wallet fee are crazy high. It only will give you profit if you trade big amount of cryptos! Or you should have wallet in your exchange/trading platform . Like Coinbase and Gdax. Other than that method , I guess we will waste so much money as fee

**Comment by 55dmb** [comment]
If you did then try using your 12 word mnemonic in a different wallet then just delete copay (you should be able to load them in a different one - try Blockchain info wallet or electrum; Note: bread only loads 12 word phrases specifically created by the bread wallet and won’t work with one created elsewhere)

Sent from my iPhone

David M Browning
PhD Candidate (ABD) and Teaching Fellow
The Catholic University of America
(c): (970) 222-7914
(email 1): 55browning@cua.edu
(email 2): davidmbrowning@icloud.com
