### ISSUE TITLE
Bitcoin Withdraw 

### ISSUE THREAD

**Issue by LazyboyCT** [bitpay/copay#6215]
Good day support, how do I calculate the fee when I want to deposit BTC to another account. I keep getting insufficient fund.

**Comment by JDonadio** [comment]
Please take a look [here](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send)

**Comment by LazyboyCT** [comment]
I read through it a few times now but what I don't undersrand is that when I transfer the full amount out it give me a total for Normal fees. I then go back and adjust my total (full amount minus fees) and I still get this error.

**Comment by JDonadio** [comment]
"Normal" fee ~$5 USD more-less. In addition your fee will be higher regarding your inputs count. If you have insufficient fee for funds then your inputs are small and the transaction fee requires a fee that is over your balance. You could try the send max option, maybe you are able to send something instead of nothing.

**Comment by dabura667** [comment]
I think what he's saying is:

1. Click send max
2. Copay says it will send 0.9 BTC with 0.1 BTC fee (just simplifying)
3. He exits out
4. He types in 0.9 BTC manually to send.
5. It gives him insufficient funds error.

I think the answer is: "everytime you try to send it asks the server to estimate the fee. This estimate varies slightly each time, so during the time between you clicking send max and you sending the manual amount, the fee estimation rose a little bit.
