### ISSUE TITLE
Fix wallet

### ISSUE THREAD

**Issue by mikeyb** [bitpay/copay#6249]
Not sure what happened, Copay used to be a usable wallet.

Now when I open it I am presented with what can only be described as a piece of crap shat out of a skunks smelly ass, eaten by a cow to be shit out again, then stepped on by a marathon runner to travel across a city under someones shoe to be finally scraped off onto a sidewalk to be eaten by a dog and brought home to be shit out again in someone backyard, then their house catches on fire and heats up the Copay shit wallet into a crisp turd that no one will ever want to touch again.

REVERT THE UI!!! OMG STAB MY EYES THIS IS THE WORST UX I HAVE EVER SEEN. WHO SIGNED OFF?  WHERE IS THE SETTING FOR "TURN POOP BACK INTO USABLE BTC WALLET"?

**Comment by binks0678** [comment]
I Googled copay is a piece of shit... this was the first thing that came up...i then created an account just to comment on this post.... this is the best thing I've read in a while.... yes copay is a complete pile of shit I have $150 worth of bitcoin stuck in there... cant spend it, can't send it, and can't withdraw it because the confirmation screen never loads.....i hope the creators of this worthless cramp have sons, beautiful articulate sons and they have there legs taken from them, I pray they know that pain
