### ISSUE TITLE
Incorrect Balance Display

### ISSUE THREAD

**Issue by zapient** [bitpay/copay#6255]
## Environment
I am using the read-only functionality (xPub) of the IOS app. I use a Trezor as my hardware wallet.

## Issue
Last night I transferred a portion of my balance but the Copay app displays that I sent my whole balance. Checking my Trezor, it shows that I did only transfer a portion and my remaining funds were accessible which were then transferred early this morning. 

Not quite sure why this transaction used my whole balance and then "split" to two different addresses but regardless I think the app should account for this and display the correct balance.

## Related
https://github.com/bitpay/copay/issues/6041 ???

**Comment by dabura667** [comment]
It's because Copay can only calculate the actual send amount properly if it knows that one of the two addresses being sent to is its own change address.

Copay does not perform address lookahead for change addresses, so if you send using another app, and that app generates change address 4, Copay will still only be looking at change addresses up to 3, and see the new transaction and assume change address 4 is not your address because it hasn't generated it yet.

(Copay only generates change addresses when IT is the app that performs the sending)

IMO there should be a one address lookahead window for change addresses just for this use case of "sent from other wallet, want that properly displayed on Copay as well"

**Comment by hortonelectric** [comment]
This has to be fixed. At this moment, xpub/0/0 shows as 'unused address' even though it has been used. Not only has it been used, but the change address is also not being detected as used, even though the transaction itself which is causing the balance to be incorrect is showing up in the transaction list with the correct amount. We will have to fix this ourselves, immediately, because there's no way we can release an app that is broken in this way to our customers, who are using the watch-only HW wallet feature.

**Comment by zapient** [comment]
Ive uninstalled the app due to the lack of this feature. Im happy to hear that you will be supporting this in the near future.

**Comment by hortonelectric** [comment]
I think it is a BUG, not a feature request, because Copay claims to support a HW Wallet, but then the balances are off and this actually means you cannot send money from the wallet. So, I will try to send a Pull Request to the CoPay team, it will be up to them whether they like my solution and implement it.

**Comment by matiu** [comment]
@hortonelectric the OP refers to read-only wallet, please open a new ticket and describe your issue in detail so we can help you.

@zapient ok.
