### ISSUE TITLE
Transferred $98.00 of BTC to Copay Wallet but have Only received $0.07

### ISSUE THREAD

**Issue by JKayaMon** [bitpay/copay#6278]
Hello All & Thank You for any help you may offer,

**I initiated a transfer of BTC (USD value of $98.00) From Poloniex To Copay wallet.**
**Poloniex Transfer Details:**
![poloniex-transfer to copay](https://user-images.githubusercontent.com/29584566/27357629-f8a6a708-55e0-11e7-8edc-36ee3f847b84.JPG)

**Insight Transfer Details:**
![insight-blockchain_details](https://user-images.githubusercontent.com/29584566/27357666-386cc19c-55e1-11e7-95b8-cc92ca9ebb06.png)

**Now after more than 6 hours I've Only received BTC (USD value of $0.07) to Copay Wallet.**
**Copay Receive Details:**
![copay-received_funds](https://user-images.githubusercontent.com/29584566/27357916-3758ac3e-55e2-11e7-8635-3a75fc5c9047.png)

**Copay Wallet Summary:**
![copay-wallet](https://user-images.githubusercontent.com/29584566/27357925-4460617e-55e2-11e7-91e1-70edd06c49f6.png)

**Would someone please be willing to help me understand what's happening and recover the missing balance of the transfer?**

**Many Thanks
J Kayamon**

**Comment by dabura667** [comment]
You did not withdraw Bitcoin.

You withdrew USDT, which is a colored coin managed on the Omni protocol (which is a protocol on top of, but separate from the bitcoin blockchain)

The reason you only received 7 cents is because, in order to send the embedded USDT coin, and make a valid bitcoin transaction, Poloniex must send a little BTC to make a valid bitcoin transaction.

You can check your Omniwallet balance here:

http://omnichest.info/

Copay does not support Omniwallet transactions, so you must contact Omniwallet developers to ask what you need to do to get your keys into their wallet.

Whatever you do, DO NOT USE COPAY TO SEND THAT 7 CENTS! If you do, your USDT coins will effectively disappear.

Also, next time, please pay attention to what you are withdrawing. If you want BTC You need to withdraw BTC not USDT, did it not seem strange to you to withdraw USD to a bitcoin address?

**Comment by dabura667** [comment]
http://omnichest.info/lookuptx.aspx?txid=40c5001d69513724c4c11fd59d99ec8f9e9a25db44af34f469d9d46e0bedd78b

Here's the transaction

**Comment by JKayaMon** [comment]
Hi Dabura667,
Thank you for the clarification and I'll definitely be much more careful with future withdrawal details.  I'm very new to the entire understanding of moving crypto from one place to another and didn't have the full picture before initiating the transfer.

Also "Many Thanks" in finding the Omniwallet Transaction.

My understanding is that I transferred the wrong type of coin (USDT - unsupported) to the Copay wallet, and now my funds are in an Omniwallet, correct?
That being the case, I need to contact Omniwallet to get 'My Own Keys' for 'My Own OmniWallet'?
As I'm sure I don't have one, would an Omniwallet have been created for me at the time of the transfer?

I imagine all that Omniwallet Dev would need is the Transaction link that you provided.
Does this sound right?


Many Thanks Again Dabura667,
JKayamon

**Comment by dabura667** [comment]
Just tell the omniwallet devs:

"I accidentally sent USDT to my Copay Bitcoin wallet. I have written down my 12 word phrase from Copay. Is there any way to import this phrase into an Omniwallet?" And they should be able to help you.

> Re: USDT disappearing

Omni is a standard that basically "colors" small amounts of bitcoin. So your 7 cents of bitcoin is representing 98 USDT. However, if a wallet that doesn't understand how to color bitcoins using Omni rules, by sending your 7 cents you will effectively wash the color off and the 98 USDT will cease to exist, and disappear.

Don't use your Copay wallet and contact Omniwallet devs as soon as possible.

Thanks.

**Comment by JKayaMon** [comment]
Thank you Dabura,
I did just as you said and now I'm fully recovered!!!

Thank you very much for helping me,
Please send me  your BTC address.
JKayamon

**Comment by dabura667** [comment]
134gia7LLxurwDyxj3bXUWnCLsWtMwBCEU

Youre welcome!

**Comment by dabura667** [comment]
Thanks for the tip! I will buy lunch with it.
