### ISSUE TITLE
Reguest: Support importing private keys

### ISSUE THREAD

**Issue by MuhammedZakir** [bitpay/copay#6344]
Why doesn't Copay support importing private keys? Bither support both generating a P2PKH address and importing P2PKH addresses. So why not Copay too? Also, can you add an option to send from a private key directly like Mycelium does? If it's about security/privacy issue(reusing address), then disable it by default and can be enabled in `Settings -> Advanced` (like ArcBit).

I prefer Copay over Bither now because of multiple wallets support. If you added this too, then it would be great!

Copay iOS v3.6.2
iOS v10.1.1

**Comment by dabura667** [comment]
Why doesn't Copay support importing private keys?

Because Copay is not made for a user that messes around with individual private keys. It was made for a new user that wants all the address and key management to be done automatically in the background.

If you want the feature, implement it yourself or pay someone else to do it for you. I'm sure they won't object.

I don't think the feature is worth anyone's time to make. If you need the feature so much, use Bither.

**Comment by MuhammedZakir** [comment]
If I knew how to implement it, I would have already done it. I wasn't complaining about it. I was wondering why they didn't implement and if there is any specific reason for it.

I already am using Bither for as my non-HD wallet. It would have been better if Copay could do too!

Btw, is Copay considering implementing signing/verifying messages? It has become a need for signed messages for some sites and also for other purposes. It will be great if it is added! Regardless, thanks!

**Comment by matiu** [comment]
> I already am using Bither for as my non-HD wallet. It would have been better if Copay could do too!

As @dabura667 suggested,  copay is focused on HD wallets. Adding individual private keys will break our backup procedures, so it is not something we plan to do.


> Btw, is Copay considering implementing signing/verifying messages? It has become a need for signed messages for some sites and also for other purposes. It will be great if it is added! 

Yes, we will add this soon.
