### ISSUE TITLE
No Balance in CoPay but shows in Coinbase

### ISSUE THREAD

**Issue by adamf00** [bitpay/copay#6352]
Just bought some BTC initiating the payment in CoPay to Coinbase.  The transaction shows in coinbase but had an error in CoPay.  There is an error on the transaction in CoPay: "Two-step verification code required to complete this request. Re-play the request with CB-2FA-Token header".  How do I do that?

**Comment by goferit** [comment]
First timer. Same issue.

**Comment by JDonadio** [comment]
Already fixed in the latest release and will work for new purchases. Sorry about that.
For new reports or updates please follow [this thread](https://github.com/bitpay/copay/issues/6189). Thanks in advance.

**Comment by adamf00** [comment]
So the coin is locked in online coinbase and can not be transferred to Copay without paying a transfer fee sending it to my Copay ID?

**Comment by adamf00** [comment]
Also I was using version 3.6.2 on apple laptop for this purchase.  So what is the latest version that  now works?

**Comment by spider-man13** [comment]
I have tried to resend my BTC from the coinbase website to my Copay wallet address, and it will not let me either. It says that "you have not enough funds, try with a smaller amount" but the BTC are shown in coinbase so I have the funds because they were never transferred to Copay. It seems like they are locked because of Copay. I also use the Google Chrome app version 3.6.2
