### ISSUE TITLE
Cannot connect Copay Wallet to Coinbase

### ISSUE THREAD

**Issue by maxmin88** [bitpay/copay#6396]
I went through the process to connect my wallet to Coinbase.  Both on Sunday and today I am getting a page not found error after submitting my credentials to Coinbase.  Coinbase is not connected to my Copay wallet....  Using Android app.

**Comment by Yagermeister** [comment]
I confirm the same error as maxmin88 with the Android app. HOWEVER, in the Coinbase website (not the Android app) under Settings > Security > Third-Party Applications, Copay is shown as successfully connected. The Android app never gets updated though.

**Comment by cmgustavo** [comment]
Seems to be an issue from some Android devices. Could not reproduce the error in our test lab. Please, check this thread to find out a manual solution: https://github.com/bitpay/copay/issues/5891

**Comment by maxmin88** [comment]
I tried the manual method in 5891 and it still didn't work.  Copied "code=XXXXXXXXXXX" into OAUTH and it still errored.  
I must have gotten 6 text messages with an authentication code.  Is your approach utilizing 2 step authentication?  I didn't see any place to enter the sms code..

**Comment by maxmin88** [comment]
I tried the link below and It still doesn’t work.  I have a standard OEM ROM (no changes) OnePlus 3T.

I also tried Gildera with the same error.

You really need to fix this.  It looks like a lot of people are having this problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cmgustavo** [comment]
Sorry about that, but we need more information in order to reproduce and fix it. We don't have the same phone, all our Android devices for testing purpose are working.

Just for rule out possible errors. Please, check if your mobile browser open this follow link:

[copay:glidera?code=xx](copay:glidera?code=xx)

If the previous link is not clickeable, copy it to your browser. It should try to open Copay in your phone (check the screen):

![img_0420](https://user-images.githubusercontent.com/237435/28317216-61139078-6b9c-11e7-835e-b52cc3dee931.png)

If it doesn't work, the main issue is related with some specific phones and the plugin that Copay uses to handle custom URLs: https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by cmgustavo** [comment]
Don't need to enter 2FA code in our app. Coinbase needs to validate the new device by email after enter 2FA code in their website.

**Comment by maxmin88** [comment]
These are the results I am getting.

First I uninstalled and reinstalled the CoPay app.  I reran the Coinbase authorization request.
[cid:image003.png@01D2FFA1.B8F44740]


Than I ran the url you suggested in Chrome URL entry box:
copay:glidera?code=xx                     and
copay://glidera?code=xx

Got this:
[cid:image006.png@01D2FFA1.B8F44740]

Chrome interpreted the request as a non-URL and ran a search.


This is my current phone setup.  It has a stock OEM ROM and is not rooted. The browser is stock Chrome:

[cid:image008.png@01D2FFA1.B8F44740]

I am a developer and will give you more info if you need it.

Robert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by maxmin88** [comment]
Also here is the info on Chrome if you need it.

[cid:image003.png@01D2FFA2.896491A0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jonnet97030** [comment]
I notice that the image shown to maxmin88 is from an iPhone. I have been playing around with Android 6.0 and 7.0 - I have a Samsung Galaxy S7 through T-Mobile running stock Android Nougat, the stock Samsung internet browser, Firefox, and Google Chrome, as well as Opera Mini and Dolphin. I tried it the normal way and the manual method linked to above - none of those browsers will open the copay protocol after authorizing them with coinbase. Since I do not have a different model phone, other versions of android before 6.0 or different network, I cannot make any conclusions, but I think the issue may be with a recent Android security update.

**Comment by TheCryptek** [comment]
Jonnet I can confirm it also doesn't work on the Samsung Galaxy grand (or go) prime running Android 5.1.1

**Comment by jweitz** [comment]
@cmgustavo,

Is there an update on this issue?  I am having similar issues on LGV20 connecting Copay v3.7.3 to the Coinbase service?  Any suggestions?

Best,
J2

**Comment by jonnet97030** [comment]
Unfortunately not. However, Coinbase does have its own app, and it 
functions pretty well. I've just settled into using both in tandem.

**Comment by jweitz** [comment]
So here's an absurd work around that I found.  I wanted a Private wallet and read some good things on Copay which is why I'm trying to link to an exchange.

- Launch Copay App via Android
- Go to Exchanges > Coinbase > Connect Coinbase Account
- Copy URL for Coinbase Authorization and open in Chrome Browser on a laptop
- Log in to Coinbase
- Before clicking Authorize, Open Chrome DevTools
- In Networking tab, clear data and start recording
- Click Authorize
- Return to networking tab and retrieve "code" from "copay:" app link
- Back on mobile device return to Copay App and return to Exchanges > Coinbase
- Click on Enter Code and paste in retrieved "code" from Chrome Browser

HTH

**Comment by taylormade2k** [comment]
I figured out a super simple solution to this.  All credit to Jweitz as without him I would not have found it.  You don't need to open a chrome browser or record anything on your pc.  All of this can be done from your phone.  The code is actually contained in the error message webpage.  It says coinbase?code=xxxxxxxx&state=secure_random.  Just copy everything in between the two equal signs.  That is the code!! Then go to the coinbase app and enter that into section that says 'enter code'.  I am not a programmer but this seems like it would be a simple fix for the developer.  At least they could offer the option to copy the code and direct them to paste it into the required section.  Thanks again Jweitz!!

**Comment by Eric31415** [comment]
I tried taylormade2k's solution above, but the connection went into an infinite loop. Not sure what to try next. I have a Galaxy Note4.

**Comment by Eric31415** [comment]
I figured out what to do: I couldn't copy everything between the two equal signs. I could only copy everything between the first equal sign and the next ampersand. When I did this and pasted it into the authorization prompt, it worked.

**Comment by ariazevedopt** [comment]
still the same issue, any solution worked for me
both on laptop and mobile app

**Comment by jaminroe** [comment]
Getting same issue on my Galaxy S8 in Chrome. Android 7.0

**Comment by jaminroe** [comment]
How do I find that error message. All I see is the _Authorizing..._ button not changing and redirecting me.
