### ISSUE TITLE
Bitcoin Segwit? What will happen to bitcoins stored in Copay when this happens?

### ISSUE THREAD

**Issue by Linusky17** [bitpay/copay#6422]
Bitcoin Segwit? What will happen to bitcoins stored in Copay when this happens? I think most people already know what would happen on August 1st, the most secure way is to store bitcoins in your own offline wallet with your own private key. But Copay confuses me because I do not see private key anywhere, I know you can extract it but is it safe to just keep bitcoins in Copay without doing anything else? Or should I get the private key?

**Comment by dabura667** [comment]
You're fine. Your 12 word backup phrase is your private key.

**Comment by Linusky17** [comment]
So I do not have to do anything for Segwit? But how is Copay going to store both new and old bitcoins at the same time?

**Comment by dabura667** [comment]
> store both new and old bitcoins

That's not what a Bitcoin wallet does... a bitcoin wallet ONLY stores keys. Your keys are your keys regardless of which blockchain you use them on.

In order to understand the ramifications of what happens when a contentious hardfork happens, you need to have a pretty full understanding of how bitcoin works at a technical level.

Here is an explanation of what will most likely happen.

1. You have 10 BTC before the fork.
2. A bunch of forking and chaos happens. If you don't do anything, you still have 10 BTC ON EVERY FORK.
3. Eventually, most of the forks die, and we all return to one fork... Copay will be on that fork (or move to it if necessary)
4. In the event that multiple forks will continue on forever, THEN you have to worry about which blockchain has which coins. As long as you don't touch anything, your 10 BTC will be on every fork. But once you start sending them around, there is a possibility that you receive money on one fork, but not the other... meaning your balance could change between forks, and you need a wallet that can manage multiple forks. Currently no wallet can. (Electrum has a new experimental feature that lets you SWITCH chains, but not manage both simultaneously)

The possibility of 4 happening is low.

However, the one thing to remember: DON'T PANIC. There might be people who try to trick you into thinking "OMG IF YOU DON'T IMPORT YOUR PRIVATE KEYS TO XYZ WITHIN 10 HOURS YOU WILL LOSE YOUR BITCOINS!" this is a lie, and most likely a scam to steal your keys and steal your bitcoins.

Calm down, wait for everything to blow over.

If you are too anxious about it, sell all your bitcoins now and buy them back once everything settles down.

**Comment by Linusky17** [comment]
Thank you for the explaination

**Comment by sushilraghav** [comment]
@Linusky17 @dabura667 @gabrielbazan7 @kleetus @saschad    For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
