### ISSUE TITLE
What will happen to BTC in different chains in Copay/BitPay in case of network split? Will app support all chains?

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6439]
Will Copay/BitPay app support BTC operations in all **network chains**?

**Comment by RussianSwiss** [comment]
Will Copay/BitPay app support BTC operations in all **network chains**?

**Comment by dabura667** [comment]
There's no way we can know if it works on all chains until those chains exist.

For instance, UAHF (aka Bitcoin ABC, aka Bitcoin Cash) has flip flopped on exactly what they're going to do like 10 times in the last week.

Can't tell you which wallets will support them, because no one even knows on a technical level what "they" are yet.

However, Copay's app connects to a single blockchain. So the answer is that they can only support one chain at a time.

Which chain Copay's backend will follow? Currently the only open source implementation of the Copay backend supports an old version of Bitcoin Core.

So I highly doubt they will support anything other than Core without extensive effort.

(Who knows, maybe they are secretly working on a bitcore-cash implementation. I have no clue)

**Comment by RussianSwiss** [comment]
Do you know any way to export **xprv** for any **xpub-generater** 555th address generated by app if one has mnemonics?

**Comment by dabura667** [comment]
You shouldn't need to do that.

The recovery phrase will work in other wallets.

**Comment by paOol** [comment]
I think what most people want clarity on is whether they'll be able to access UASF or BitcoinCash if they hold their funds in CoPay.

I think the answer is yes, but would be good to have a definite answer. @dabura667 's response made it a bit less clear. 

but in theory if XYZ wallet comes around and seamlessly offers sending through all possible chains, it should be possible to import your recovery phrase into that new wallet.

**Comment by dabura667** [comment]
To be more specific.

The current state of Copay and Bitpay app only support Bitcoin Core.

In the event that UASF or BIP91 is successful, Copay will follow it.

In the event that UASF or BIP91 has less than 33% of the hash power (upon activation) Copay will not follow UASF or BIP91.

Copay can also not currently support Bitcoin Cash. But when you send from Copay, there will be a chance that your transaction is mirrored on the Bitcoin Cash network, as Bitcoin Cash's replay protection is opt-in.

These explanations are based on the assumption that Bitpay's developers do nothing.

If they have plans, they will probably make a statement here eventually.

**Comment by dabura667** [comment]
But your recovery phrase is your key. So if another wallet supports Bitcoin Cash, import your phrase into that wallet.

**Comment by RussianSwiss** [comment]
Wallets working with other chains won't be available immediately. Also we don't want to give access to all our **xpub** addresses.

**Still is there a way to export xprv for i xpub address?**

**Comment by dabura667** [comment]
Yes. "Export" then decrypt with sjcl

**Comment by JDonadio** [comment]
Please follow https://github.com/bitpay/copay/issues/6557
