### ISSUE TITLE
Feasible for 2 people to have accounts on one phone app?

### ISSUE THREAD

**Issue by flrebroker** [bitpay/copay#6486]
Hello I've searched about my issue but do not see what I'm asking.  What I'm trying to do is get my wife and I's coins off of Coinbase before fork.  I have mine in my Copay android wallet.  Of course I have backed up seed.  Now my next idea was to create a new wallet for my wife on my phone app and then direct her to transfer her coins there.  However, now I have to ask her to write down her 12 word seed and hide.  This is probably going to freak her out.  So is the only way to not have a non-backed up wallet is to have all funds go in the original wallet?

In other words if I have 10 separate wallets on my phone app, then I need to hide all 10 seeds with their respective wallet names so I know which is which?

Also, to clarify, if I setup any other wallets on my phone app and the phone disappears tomorrow and I only have the original seed stored away all other wallets will be lost forever if not backed up?

I would have thought by default any and all wallets would be backed up and accessible under the original 12 word seed.  Am I using the wrong wallet if this is what I want to do?  Any suggestions on other wallets that would work better for me at this time?  Thanks. 

One other issue, I'm using fingerprint to access Copay.  If my wife wants to check her balance on my phone then I will need to setup her fingerprint with the phone?  Would both fingerprints work to access account?  Sorry for all the questions!

**Comment by JDonadio** [comment]
> Hello I've searched about my issue but do not see what I'm asking. What I'm trying to do is get my wife and I's coins off of Coinbase before fork. I have mine in my Copay android wallet. Of course I have backed up seed. Now my next idea was to create a new wallet for my wife on my phone app and then direct her to transfer her coins there. However, now I have to ask her to write down her 12 word seed and hide. This is probably going to freak her out. So is the only way to not have a non-backed up wallet is to have all funds go in the original wallet?

In order to keep your wallet safe and avoid any case like lost, steal, crash, etc, you `must`: 

* Follow the backup process
* Export the wallet as:
   * file/text
   * QR code

> In other words if I have 10 separate wallets on my phone app, then I need to hide all 10 seeds with their respective wallet names so I know which is which?

Yes

> Also, to clarify, if I setup any other wallets on my phone app and the phone disappears tomorrow and I only have the original seed stored away all other wallets will be lost forever if not backed up?

Yes

> I would have thought by default any and all wallets would be backed up and accessible under the original 12 word seed. Am I using the wrong wallet if this is what I want to do? Any suggestions on other wallets that would work better for me at this time? Thanks.

Each wallet can only be accessed with their own private key (12 words or any backup format)

> One other issue, I'm using fingerprint to access Copay. If my wife wants to check her balance on my phone then I will need to setup her fingerprint with the phone? Would both fingerprints work to access account? 

Copay and BitPay use the `native fingerprint service` from iOS and Android, so if any other person has set his fingerprint in your phone then will be able to unlock the app.

**Comment by dabura667** [comment]
You can actually use the same 12 word backup to generate two separate wallets by using the advanced wallet creation options.

1. Tap create new wallet
2. Pick a name for the wallet like wife wallet etc
3. Tap "advanced options"
4. Set "wallet key" to "specify phrase"
5. Type in your original wallet recovery phrase (the one you already have written down)
6. For "derivation path" type in m/44'/0'/1' instead of the default m/44'/0'/0' (so change the last 0 to 1 without accidentally deleting any of the apostrophes)
7. Don't touch any of the other advanced options on accident.
8. Tap create wallet

> What did this do?

This used a feature of BIP44 called "accounts" that other wallets use but Copay does not. That 0 you changed means "first account" changing it to 1 means "second account" (starting to count from 0)

Now, you can recover both of your wallets by the same phrase, but different accounts. If you recover with Copay just remember to change the derivation path when importing your wife's wallet.

However, if you don't want your wife to know your phrase, then either way you can not give her control of the "Wife wallet" since it will show her your phrase if she wishes, and if she is able to spend from it.

The accounts feature exists merely to separate transactions and make them not mingle with each other.
