### ISSUE TITLE
Another newbie question about private keys and paper wallets/copay

### ISSUE THREAD

**Issue by beatdigger** [bitpay/copay#6490]
Disclaimer I am new to all of this. Not really an issue just reaching out for basic understanding of private keys in my scenario.

I bought BTC and needed a wallet as a place to put it so I downloaded CoPay.
When I launched CoPay during some part of the process, it asked me to write down a 12 word phrase and guard it with my life as this was my one and only "private key". I did not understand what a private key was but I wrote it down anyway. 

Fast forward a few weeks, I moved my BTC into a paper wallet. 
When generating the paper wallet, I was given a new and different "private key" (a long alphanumeric number this time) and was also given similar instruction to guard it with my life etc... 

So I guess I'm just confused as to the difference of these keys. Do I even still need the first private key now that all my BTC is moved to a paper wallet with a new private key? When/how will these private keys come into play when i go to sell my coin in the future? Suppose I lost my 12 word key but still had my paper wallet, would I be screwed in that scenario?

**Comment by dabura667** [comment]
1. If you have ever given out, or shown an address to anyone from your Copay wallet, you should NEVER completely delete the backup phrase. I have had people say to me "oh, by the way, that money I owe you, I sent it to that one address you sent me 3 years ago. Thanks." (This was TOTALLY STUPID ON THEIR PART, but luckily I was able to piece together when I sent the address to them, and since all my old backups are labelled with dates I used them, it was easy to find)
2. Paper wallets are old. They use the WIF format of private keys. Copay is new (relatively) and uses the BIP39 phrase format of private keys. The 12 word phrase format made it easier to write down for safe keeping, as printers usually save copies of what they print and/or occasionally send images of what they print to the manufacturer for troubleshooting purposes. (You agree to this when installing the drivers usually) So people thought "hmm, maybe we should write these down by hand.. but 53 random characters are really hard to write down."

**Comment by beatdigger** [comment]
Is the 12 word passphrase specific to only CoPay? 
I was under the impression that the 12 word phrase somehow established my presence on the blockchain. Kind of like an account at a bank or something.
I'm looking at BTC as a long term investment. When the day comes to cash in.. will the 12 word phrase be needed if I'm just going from my paper wallet to an exchange like coinbase for example?

**Comment by gabrielbazan7** [comment]
No, Copay uses the BIP39 phrase format that is also used by other wallets too. Yes, to move the money you will need the private key from your paper wallet.

**Comment by beatdigger** [comment]
When would I ever need to use the 12 word key?
The only scenario I can possibly think of would be If maybe I lost my phone? 

Suppose I lost my phone with coPay and then got a new phone and decided to use Jaxx instead. Would the same 12 word phrase work on Jaxx to restore my funds? So am I to understand that the 12 word phrase is not tied to any specific wallet/app but rather to the blockchain??

**Comment by dabura667** [comment]
> So am I to understand that the 12 word phrase is not tied to any specific wallet/app but rather to the blockchain??

It's not tied to anything. It is your key. A "key" in cryptography is a very large number. The 12 word phrase is literally a large number encoded in words from a word list.

It's hard to wrap your head around... but you'll do yourself a favor if you stop trying to compare bitcoin to something you understand.

And yes, you can import Copay's phrase into Jaxx and vice versa and it will work.

You shouldn't do it, except for emergencies though. Sticking your key into any old app just exposes your key to the dangers all apps it has ever been in.

Copay is fairly safe (I know because I've checked every line of it myself) I have no clue how safe Jaxx is.

**Comment by beatdigger** [comment]
The only motivation for using Jaxx is that it can track/hold my Litecoin also. 
As I understand it, CoPay cannot.

**Comment by JDonadio** [comment]
Copay/BitPay app only supports BTC.
