### ISSUE TITLE
cheating in india by giving testing btc in copay wallet

### ISSUE THREAD

**Issue by balaji786** [bitpay/copay#6497]
Some one has cheated in copay wallet giving 12 testing btc n taken money as original in INR in delhi.Wallet Name HIM can u trace from which source it has been trf to that wallet.Two trxn 10 and 2 on Friday july28,2017.Location Delhi India.Pls help us in tracking the culprit.It has been serious threat to your wallet crediablity.Kindly disable this options from your wallet.

**Comment by JDonadio** [comment]
Hi @balaji786,

Each user is responsible for taking care of their funds. Both developers and BitPay themselves cannot access the funds of any wallet because the keys are stored in the devices, not in the cloud, not in our servers. Regarding the `testnet` network, is available only for testing purposes but to opearate inside the testnet network each participant of the transaction must have a testnet wallet. There is no way to share any amount from one net to another.

Unfortunately there is nothing we can do in this case.

**Comment by dabura667** [comment]
> Kindly disable this options from your wallet.

There are many wallets that offer testnet sending and receiving. Disabling it will just make the scammer use a different wallet app and do the same thing.

**Comment by yashbakshi27** [comment]
Hi @ balaji
Balaji please give me ur contact number. Mine is 9501092110. Were the two guys Ankit & Ashu..??
I also got scammed yesterday for 8 btc . Is there any way to nab the culprit now..??? They took INR 13,20,000 from me..!! its my hard earned money..!! Plz can some one help..???

**Comment by dabura667** [comment]
@matiu Perhaps we could modify Testnet wallets to not show Fiat amounts and constantly show a warning "This is not real Bitcoin"

**Comment by JDonadio** [comment]
Definitely we need to put focus on https://github.com/bitpay/copay/issues/4938
