### ISSUE TITLE
"Hot" wallet vs Cold wallet

### ISSUE THREAD

**Issue by tommyquite** [bitpay/copay#6530]
Hi,

I am thinking about moving some of my crypto to cold storage. But I am having a hard time grasping the ups and downs for both. 

I am currently using Hot desktop and Mobile wallets where I own my private keys. Copay and Electrum wallets. My seed is stored offline, in different parts, on different locations and password protected.

A few a few questions, to better understand the security risks of a "hot" wallet with the specifics i mentioned above:

1. Can a hacker or thief gain access to my wallet, or private keys, without the seed (stored offline) and my spending password? (assuming the hacker has full acces to my computer or phone)

2. Are the private keys stored somewhere on the mobile device or computer when im using a copay wallet? (I assume this must be the case for the wallet to work.. Or is the offline seed the only source of private keys?)

3. Can I use a copay hot wallet on top of my cold storage wallet, without having the "risks" of a hot wallet?

4. What exactly are the security benefits of a cold wallet vs a hot wallet (where you own your own private keys and store the seed offline, multiple locations and with pass protection)? Because I don't see much difference.. Except if indeed, a hacker can steal private keys from my device(s).

Some explanation is very much appreciated.

Thanks in advance!

Best Regards,

Tom

**Comment by dabura667** [comment]
1. A hacker needs either your seed OR your spending password and access to your device. If a hacker has full access to your device she can easily log your key strokes and find your spending password. The spending password can then be used to decrypt your seed and steal your bitcoins.
2. If you have a spending password active, the seed itself is encrypted with your spending password and stored on your PC/mobile's disk like any other file. (Mobile devices are better at protecting files of one app from other apps reading it than a PC or Mac) If you don't have a spending password, the seed is saved in plain text to a file on your disk.
3. What do you mean "on top of"? I think you are misunderstanding what a cold wallet is.
4. A cold wallet is a wallet (specifically, a private key or seed) that NEVER touches a device that has or ever will touch the internet. Copay can not generate or manage cold wallets, since it has no method of importing and exporting transaction data.

For example, you can buy a new computer, weld the LAN port shut and physically break any WIFI chips in the PC, boot up Tails OS (which is preinstalled with Electrum) and generate a seed there, copy down the master public key, and import the master public key to your online PC.

Then you use your online pc and master public key to generate transaction files, copy them to your offline pc, and sign them using Electrum and your seed, and move the signed transaction data to your online pc.

You seed has only ever touched the offline pc.

What you are calling "cold wallet" is just "writing down a backup of a hot wallet"

**Comment by tommyquite** [comment]
Thanks for your answers! 

I was actually referring to a Trezor or Nano ledger cold storage wallet.
And the security benefits of those vs a hot wallet in which you own your own private keys and store your seed offline with a passphrase protection. 

But my understanding from what you say is that: even tho your seed may be stored offline. Your private keys still exist on the device your using, and can therefor be stolen by hackers or thiefs. Where as in a cold wallet, the private keys and/or seed, are never on your device. And the cold storage device itself cannot be hacked, or is at least near to impossible to hack. Am I understanding correctly?

Also, in which directory does Copay store my private keys when I create a new wallet?

Thanks in advance!

**Comment by dabura667** [comment]
4. Yes.

5. The "passphrase" entered during creation / importing a wallet from seed, is like "the 13th word". You must mix your seed together with this passphrase to generate your wallet's master private key. The spending password which is asked every time you spend, literally takes your seed AND master private key and encrypts them both with your spending password, which means it looks like garbage without the spending password. The passphrase is meant to protect you in case someone finds your 12 word phrase (seed), because they need your passphrase (13 th word) they can't steal. But it doesn't protect you from a hacker getting your device files (your Copay stores both the seed AND the master private key generated from your seed and passphrase)

6. It depends. Chrome extensions store files in the chrome appdata directory under the app id's folder. The standalone binary has its own appdata folder. If you're on windows google "where is appdata folder?" And you can search in there.

**Comment by ketchupfles** [comment]
I still don't understand. What is seed? What is the "13th word"? As far is i know there are only 3 things to keep you safe. 12 phrase password for recovery that you get during the creation of your wallet, the spending password that you need to type in for every transaction and using multisig wallets. 

What about the following: 

I am using Copay. I've got a spending password. I am using Copay on my computer that has access to the internet and my mobile phone.

If someone hacks my computer and tracks what i type, can the person get access to my wallets?

**Comment by JDonadio** [comment]
The spending password is stored locally. You can use your wallet in your computer and mobile with different passwords.
