### ISSUE TITLE
Different balances on same wallet

### ISSUE THREAD

**Issue by alejoacostaa** [bitpay/copay#6532]
So I had approx 0.86 BTC on my copay wallet and then imported this same wallet onto electrum (the reasons for this don't matter) with the recovery 12 word seed, everything worked just fine.
I then sent a payment of 0.02031909 BTC from Electrum.

Now Copay shows my balance at 0.1219BTC and Electrum at 0.8479 (the correct one).

I imported the wallet in electrum with the Copay seed so shouldnt the balances between both be the same as it is literally the same wallet on different devices (Electrum on PC and Copay on Android)? anyone has any idea whats going on?

I have the feeling it has something to do with "change" addresses but I cant really figure out whats up.
Thanks!

PD: In case it comes in handy, transaction I did is:
https://www.blocktrail.com/BTC/tx/59e24bad73443cb03029f428a7e883cd23079eb3a8536da5f294026a04605065

**Comment by JDonadio** [comment]
The reason is, Copay cannot see the change address generated by Electrum so the amount used in the transaction (in this case about ~0.7) is the only "visible" part of the balance. Copay doesn't look-ahead to synchronize, you must run the scan addresses (manually) to get the correct balance after each transaction made from another wallet.

**Comment by alejoacostaa** [comment]
Great, thanks for the reply!

As expected, manually scanning for funds on the Copay app did the the trick.

Thanks again!

**Comment by pyaephyoswe** [comment]
pyaephyoswe569@gmail.com
