### ISSUE TITLE
problem with 12 words in spanish to restore wallet in other like as LEDGER and TREZOR 

### ISSUE THREAD

**Issue by Coin2Cop** [bitpay/copay#6537]
hi i made my backup but my wallet copay is in spanish, i need restore my seed in other devices but i cant because the other wallet dont recognize the spanish words.

im try made the equivalent based in this documents 

https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
https://github.com/bitcoin/bips/blob/master/bip-0039/spanish.txt

im try transalte the words 
and dont work too, thanks for your help 

dve

**Comment by dabura667** [comment]
Ledger and Trezor do not support Spanish phrases.

There is no way to convert.

1. Create a new wallet with Trezor or Ledger.
2. Write the new English phrase down on paper.
3. Send all your bitcoins to the Trezor or Ledger.

Even if you COULD use Spanish phrases, you shouldn't. It defeats the whole purpose of the device if you don't generate the phrase on the device.

**Comment by Coin2Cop** [comment]
I need this Spanish seed for extract my Bitcoin cash :(

**Comment by dabura667** [comment]
Electron Cash accepts Spanish phrases.

Be sure to select BIP39 when recovering.

**Comment by JDonadio** [comment]
@Coin2Cop feel free to continue the discussion if you have any problem. We could give you spanish assistance if you prefer. 

Thanks @dabura667 for your support.

**Comment by Coin2Cop** [comment]
Excuseme electron cash but in pc?

**Comment by dabura667** [comment]
http://electroncash.org/

**Comment by aderregibus** [comment]
Hello,

I'm having a similar issue.
I am trying to claim my BTG in Coinomi with the information I exported from my Copay wallet.
I've tried everything so far with no luck.

The main problem seems to be that the BIP39 recovery phrase is in spanish because my device was set to spanish when the wallet was created, while Coinomi only accepts english phrases.

My questions are:
(1) Can someone please explain to me why using the equivalent words in english does not work?
(2) Does someone know any way to claim my BTG given my situation?

Thank you.

**Comment by gabrielbazan7** [comment]
1) there is no equivalent words in english.
2) Use the recovery tool : https://bitpay.github.io/copay-recovery/. Remember to set the chain as btg/livenet
