### ISSUE TITLE
Assume wrong interpretation of transaction

### ISSUE THREAD

**Issue by andriytyurnikov** [bitpay/copay#6555]
See transaction `3613445da26b252ed3dd4265e799d22a4e0727aaea6b8d14d74bb8d70843820d`
https://insight.bitpay.com/tx/3613445da26b252ed3dd4265e799d22a4e0727aaea6b8d14d74bb8d70843820d

BitPay wallet says I've sent 3.144906 BTC
Exodus wallet says I've sent 2.89 BTC :)

**Comment by JDonadio** [comment]
Please attach your transaction detail screenshot so we can check it.

**Comment by andriytyurnikov** [comment]
<img width="400" alt="screen shot 2017-08-11 at 00 41 26" src="https://user-images.githubusercontent.com/3668/29193431-e8067e62-7e2d-11e7-8768-b1713945a747.png">

**Comment by andriytyurnikov** [comment]
Here goes exodus:
<img width="770" alt="screen shot 2017-08-11 at 00 42 52" src="https://user-images.githubusercontent.com/3668/29193476-1b133c5a-7e2e-11e7-823a-e400f09ebab3.png">

**Comment by andriytyurnikov** [comment]
Bug present on both OS X desktop and iOS Copay and BitPay apps.
wild guess - current code assumes only transactions that produced by wallet itself - and not all types of transactions that are valid

**Comment by dabura667** [comment]
Please Click the Rescan all addresses button.

You have been using the Copay recovery phrase in an external wallet (non-copay) which has been generating change addresses which Copay does not yet know about. 1PUZC64V79NFvkRKJqD8M9TWe3kbWt5jke is your change address, but Copay doesn't know that since Copay wasn't the wallet used to generate it.

**Comment by andriytyurnikov** [comment]
it worked, but still looks like an issue to me ;)

**Comment by dabura667** [comment]
I think it is a nice thing to have (constant change address look ahead) but the assumption of Copay should not be "let's assume they are using multiple wallet apps to manage the same keys." So I don't think this is an issue of much importance, since users shouldn't be entering their phrases willy nilly into a billion apps.

**Comment by JDonadio** [comment]
> let's assume they are using multiple wallet apps to manage the same keys.

That's right. Copay/BitPay wasn't designed for that purpose.

**Comment by andriytyurnikov** [comment]
Decision-making in software is a thing that keeps me awake all night sometimes. Just to make things clear: Incorrect balance in wallet app is a behavior by design, right? :)
P.S. If you have a document, where this trade-off was made *before* this issue was opened - please share a link, it would help me enormously in my research. 
Thank you so much for sharing results of your hard work.
