### ISSUE TITLE
Copay 

### ISSUE THREAD

**Issue by belayairina** [bitpay/copay#6561]
Здравствуйте!
Подскажите пожалуйста почему я не могу вывести 0.0056 BTC пишет не хвотает средств на комиссию, это сколько же должно быть на счету чтобы вывести?

**Comment by dabura667** [comment]
(Google Translated)

How many transactions have you received in the past?
Сколько транзакций вы получили в прошлом?

**Comment by belayairina** [comment]
Последний платёж или в общем?

**Comment by belayairina** [comment]
Раньше выводила и 0.001 и 0.0001 Copay пользуюсь с октября 2016? Сейчас в чём проблема?

**Comment by dabura667** [comment]
(Google Translated Russian below)

-----

In Bitcoin, the more times you receive money, the more fees you must pay.

For example: If you receive 10 BTC one time, you will pay a small fee to send 9.9 BTC. (Maybe like 0.00023 BTC)

BUT If you receive 0.1 BTC 100 times (= 10 BTC total), you will pay a large fee to send 9.9 BTC. (Maybe around near 0.015 BTC)

This is because every time you send Bitcoins, you must refer to a previous transaction where you received Bitcoins. This makes the transaction data bigger (in bytes) and since fees are relative to the data size, the bigger the size of the data, the bigger the fee is.

If you received 0.0056 BTC in 5 transactions of 0.001 and 6 transactions of 0.0001, then your fees should be around 0.0017 BTC to 0.0034 BTC to send all your money.

-----

В Биткойне, чем больше раз вы получаете деньги, тем больше вы платите.

Например: если вы получите 10 BTC один раз, вы заплатите небольшую плату за отправку 9.9 BTC. (Может быть, 0.00023 BTC)

НО Если вы получите 0.1 BTC 100 раз (= 10 BTC всего), вы заплатите большую комиссию за отправку 9.9 BTC. (Возможно, около 0,015 БТД)

Это связано с тем, что каждый раз, когда вы отправляете биткойны, вы должны ссылаться на предыдущую транзакцию, в которой вы получили биткойны. Это делает транзакционные данные большими (в байтах), а так как сборы относятся к размеру данных, чем больший размер данных, тем больше размер платы.

Если вы получили 0,0056 BTC в 5 транзакциях 0,001 и 6 транзакций 0,0001, тогда ваши сборы должны составлять около 0,0017 BTC до 0,0034 BTC, чтобы отправить все ваши деньги.

**Comment by aradell** [comment]
hello,i have a problem with copay and  I can not withdraw no amount .I have this message:spending this balance will need significant bitcoin network fees.

**Comment by JDonadio** [comment]
Hi @belayairina, unfortunately we can only give you support in `english` or `spanish`. Please consider the english so we can assist you better. Please re-open the ticket if the problem was not solved. Thanks @dabura667 for your support.

@aradell please follow [this](https://github.com/bitpay/copay/issues/6562#issuecomment-322762885)

**Comment by crimaru** [comment]
I have the same issues with COPAY - I understand that the fees have nothing to do with the amount of money but with the number of bits but how the hell are the minimum fees calculated to 25-29% of the total amount? I mean with example to transfer 15 USD you pay 4.5 ? really ? It's good that I just tested this amount and not more otherwise who knows how much I would have lost to get back some of my money. Bad experience so far ...
