### ISSUE TITLE
Amount too low to spend?

### ISSUE THREAD

**Issue by the3vil1** [bitpay/copay#6562]
Hi,
I have been receiving payments for some time now from nicehash and genesis mining. On August 12 I received 0.00201 BTC and received the notification "amount too low to spend". I have received smaller amounts in the past and just recently upgraded the app as well (iOS). I have read what this means but shouldn't this only be for very low anounts? (Lower than the transaction fee itself?) 
Thank you all!

**Comment by dabura667** [comment]
https://github.com/bitpay/bitcore-wallet-service/blob/d416284fc3311bc45d41fadad00fb693bb31eb70/lib/server.js#L2962

Basically, BWS tells your wallet that when a received transaction's feePerKb is lower than the super economy setting recommendation, it can not be used in a transaction (as your unconfirmed transaction will not likely confirm quickly regardless of your fee setting)

This should clear away once the transaction confirms.

I had mistakenly thought it meant that the utxo amount was less than the added fees for the extra input. That is not the case.

@matiu @JDonadio This error message is confusing. And should be "Fee too low to spend unconfirmed" and should only be shown if spending unconfirmed is enabled.

**Comment by the3vil1** [comment]
Thank you for the reply.

I have 6+ confirmations and the "too low to spend" notification remains. I also received another payment fron genesis-mining of 0.002016 BTC and the message is also tagged on that transaction "too low to spend"
Should we wait for more confirmations until the message to clear?
Thank you!

**Comment by dabura667** [comment]
@the3vil1 Does the "too low to spend" still display if you go to options and click "Clear History Cache" for the wallet? That should re-download your transaction history and the notification should go away...

**Comment by the3vil1** [comment]
After clearing the cache, other low amounts now have that notification next to them.

**Comment by the3vil1** [comment]
Status Update : I still have the "too low to spend" notification on my 0.001 & 0.002 amounts.

**Comment by matiu** [comment]
Actually, the meaning of the message is that the amount you are receiving is to low, and redeeming it (i.e. adding that incoming UTXO to a transaction) will probably cost you more that the value it self, due to the miner fees.

When you send a transaction, you compose the funds  you are sending from one or more incoming transactions  you have received in the past. For each incoming transaction you have received on the past, the cost of the miner fees increase. If the amount of the incoming transaction is "too low", it could not make economical sense to use it.

**Comment by dabura667** [comment]
@matiu Oh I just saw the code in WalletService.

The logic is flawed.

#6582

**Comment by ojuser** [comment]
Can someone please clarify what this error  "amount too low to spend" means? 

1) Do I need to change my payouts amount from my bitcoin network to Copay higher? 

My current pay level that I transfer to Copay is 0,01 BTC and after I have received these payments in Copay this error "amount too low to spend" appears next to my received pay.

I have already changed my Bitcoin Network Fee for SuperEconomy 264 satoshis/byte. 

2) What transfer / pay level is optimal compared to the Network / Copay fees?

3) Is there some other fees Copay takes when I start to make payments from my Copay wallet?

Thank you for your response already before hand! I am very confused and have just started bitcoin mining..

**Comment by 1alejo0** [comment]
I have 0.0074btc with the same Message. Too low to Spend. 

Is There any way to know what is the minimun  ammount required so as to be able to transfer it?

I am afraid to put more money into copay and not be able to take it out.

Is there a way to know the Miner fee before puting the money in?

If the Bitcoin network allowed to put the money in why does not allow me to take it out?

**Comment by b-mandl** [comment]
The warning message seems to be bogus as far as I can tell. I see it on a 0.006 BTC transaction in my wallet where I have a dozen or so other transactions, most ot them around 0.02 BTC. When I try to send the "max amount" from that wallet (with "super economy" fee setting) I get a total fee amount of around 0.004 BTC. 
To me it looks like the warning comes up if the fee for sending something from my wallet gets close to the amount where the warning appears. The warning would be correct if I would try to send a small amount from that wallet, but it is cleary wrong (or at lease very misleading) in may case becasue it is not true when I send a much higher amount than the one where the warning appears.
Can anyone confirm this observation/view?

**Comment by JDonadio** [comment]
This warning in incoming transactions is shown when the received amount is too low compared to current Bitcoin network fees.  When trying to redeem this amount in the future, it could happen that
the fee required by the Bitcoin network to include it into a transaction will be higher that the amount itself, making it economically inviable to use it.

**Comment by allthatmoney** [comment]
this really confuses me. how can 0.005717 in bitcoin which is 27.68 us dollars be too low compared to the network fee. i have priority checked in my system for fees. so how can it be that 27 dollars is not enough to cover the fees for an incoming transaction. i know i'm not getting charged more than my deposit when it's a 27 dollars deposit. i have2 already like this.

**Comment by allthatmoney** [comment]
so are you saying it could cost more than 27 dollars in the future to withdraw 27 dollars? this is blowing my mind. and when i receive this shouldn't the fee be paid at the sending end of it? does this mean the sender is not paying enough to send it to me? many times i'm sending it from an outside account that has the fee taken away from me when i send it. i have never had problems getting anything from 5 to 25 dollars in the past.

**Comment by allthatmoney** [comment]
![to low](https://user-images.githubusercontent.com/17850870/29985645-d6830ce4-8f2d-11e7-8aa0-6a3db2c9689a.png)
i just scrolled down my list and it looks like i have at least 50 of these now and they all range from 10 dollars to 28 dollars. i cleared the cash and nothing changed. am i going to have trouble withdrawing my bitcoins down the road for this? do i need to go back to a third party wallet and risk getting my money stolen? this is getting scary

**Comment by sherzinger** [comment]
Can confirm that this message makes no sense. I've got a ~20$ Tx which has this error message.

This issue should be opened again.

**Comment by allthatmoney** [comment]
i agree sherzinger,
 getting the link sent to you saying you might have trouble spending it later because your 25 to 30 dollar deposit is not enough to pay for your future trans fee is no explanation to our question. i'm sure everyone can find that explanation on our site on their own but it explains nothing. i have at least 40 of these that are over 20 dollars. this don't make any sense at all that 20 dollars might not cover the future transaction fee. i don't get any error messages like this in coinbase. it makes me worry that maybe a hacker is somehow doing something to our system and might be trying to figure out how to route our deposits to their own account in some way. i even cleaned my cash and it made no difference.

**Comment by sherzinger** [comment]
That's not a hacker.
Copays fee estimation algorithm is simply broken or the devs assume that we might pay 20$+ Tx fees in the future, which might or might not happen.

I'd argue though that this is rather unlikely, given that you can get into the next 4 blocks for roughly 25 cent according to https://bitcoinfees.21.co/ (at the moment I'm writing this)

**Comment by cynhen** [comment]
Any resolution?  Am I losing my money?

**Comment by b-mandl** [comment]
The “Amount too low to spend” message is misleading (to say the least)

 

What it actually means is “the standard transaction fee is close to that amount”

 

In other words: if you transfer coins from your wallet with standard fee setting you will pay approximately as much fees as the amount that is marked as “amount too low to be spent”. If you wanted to spend ONLY that amount the transaction fees would eat up most or all of it. 

 

That’s all! You will not lose any money!

 

 

If you can afford to wait for your transaction to complete you can user “super economic” or even custom fee setting.

 

I tried several times sending coins with custom fee set to 20 satoshi per byte (much less than the current 156 used with “super economy” fee setting) and the transaction was confirmed every time within 24 hours or less.

 

Hope this helps

 

Br

Bernhard

**Comment by cynhen** [comment]
Even though it says too low, I don't want to send it anywhere, just want it in my coinbase.  How can I just put it into my coinbase?  I thought it was supposed to go in automatically.

**Comment by Jamonz** [comment]
I am getting this message as well. Has there been any resolution? And is there a way of knowing how much the transaction fee is going to be beforehand?
![image](https://user-images.githubusercontent.com/12490357/34084518-caf5d1c8-e3e6-11e7-81c9-b799539887e2.png)

**Comment by cynhen** [comment]
Hi, what I've learned is that it's too low to spend but you can send it to
an exchange or another walletbwith no problem

**Comment by gbilawa** [comment]
I had this same issue and found a solution. Just setup a wallet at blockchain.info and import the funds from your Bitpay wallet.

**Comment by WaffleconeLover** [comment]
I had this same issue and found a solution. Just setup a wallet at blockchain.info and import the funds from your Bitpay wallet.

**Comment by allthatmoney** [comment]
i'm getting this message from 150.00 deposits. surly it will not cost
150.00to pay a fee for sending btc. i had thought about sending it out to
another wallet. i guess if it's to low to send you could send out a
thousand dollars at a tie to a different wallet rite? it sucks though that
you have to see this from 150 to 180 dollar deposits.

**Comment by dabura667** [comment]
Yes you will get this message for 150 because Copay has decided that 30% fee for sending is too high. Meaning Copay estimates $45 cost to send just that one.

But keep in mind that this $45 is calculated using Copay’s Insight backend, which recently attempted to switch to a new version with lower fee estimates, but ran in to technical problems so they are back to estimating fees 40% higher than everyone else.

By my estimates, $14 should get you in within a few blocks. So using Copay’s “30% of amount in fees is unspendable” that would mean $46 in bitcoin received should get this warning, not $150.

But to be honest, The best plan of action will be:

1. Wait for a month when lightning comes out on bitcoin mainnet.
2. Check the proper satoshi per byte fees on a reliable website (don’t trust Copay’s estimates)
3. Send all your bitcoin to the lightning wallet (which, as a bonus, will support segwit, you get a 50% discount even if you only use lightning wallet for on chain transactions.
4. Once it looks like places are accepting lightning, open some channels.

To be honest, most of the traffic in bitcoin is inter-exchange arbitrage. Since exchanges charge all fees to users, and users are sending 100 BTC at a time, us little people WILL ALWAYS LOSE.

If all exchanges opened lightning channels with other exchanges and traders used them to send between exchanges, the mempool would dry up and fees would be back to 1 satoshi/byte.

**Comment by allthatmoney** [comment]
i am also getting stalled deposits that say the sender did not pay enough
and it could take a long time to receive my bitcoin and it could even be
cancelled. if it gets cancelled does that mean the sender will get my
bitcoin sent back to them? if so they might be doing this on purpose so
they can get their payment back. we should have an option to pay the
blockchain extra so we can get our payment sent through. that would be
better than losing it at least to a scammer.

**Comment by Tuny1** [comment]
Hi!
On December the 29th I have made my first transaction, have bought and receive some satoshis on my brand new Copay Wallet.(฿0,0087 = u$s126,37 right now)... 
I was excited till I read a notification that says "Amount too low to spend" It also says "this amount in the transaction is too low compared to the fees of the bitcoin network, to spend these funds it is required to have an amount higher than the commission required by the Bitcoin network"
Till today, January the 9th, continious showing the same notification. Does it mean that my u$s126 will be stuck there forever? Is it normal? Which amount is suppoused to be enough? 
Thank you, ;-)

**Comment by allthatmoney** [comment]
if you ever have 126.00 in your account and it says amount to low to spend
then i think all you would have to do is add another deposit from your
wallet that would raise it higher than the fee and you will be able to use
it to withdraw or pay. some people think it is a joke when they say 200.00
is to low to spend but a couple weeks ago i was charged 200.00 to send a
215..00 payment in bitcoin.  i never checked the fee before in the past
because i always thought if it's there i'm going to have to pay it anyway
rite? but i check from now on and i also took every penny of my bitcoin and
transferred it into litecoin and ethereum and bitcoincash which all cost
about 15 to 18 cents to send even bigger amounts than the one that cost me
200.00. i was totally in shock after i sen i had just been charged 200.00
to send about 215.00 in bitcoin.
things that can make bitcoin fees go up are blockchain being busier than
usual, and also if you have been receiving micro payments like 50 cents
worth of bitcoin per day it backs up the charges and gets you when you make
a transaction. that was another think that got me that day was ii did not
realize it but i had been getting 35 cent deposits from the mcap coin
mining scam. they know  this is going to stick people with high bills but
they don't care because they are getting their cut all at once from
everyone in one gigantic payment every day. so if anyone is getting those
micro payments from the mcaps you better stop and figure out how to get
your bitcoins out.

**Comment by Tuny1** [comment]
Thank you so much for your replay, Allthatmoney. 
It was my first buy of BTC... and the last, ;-) 
From now on I will buy ETH or LTC, as you say. 
Well, sometimes we learn the hard way... 
Thank you again, and have a nice day!
