### ISSUE TITLE
Transaction not showing?

### ISSUE THREAD

**Issue by stepl5** [bitpay/copay#6607]
Hi,
I made a small transaction around an hour ago and is not showing in my wallet as pending or my blockchain? Could something have gone wrong? 
Thanks, 
Steve

**Comment by JDonadio** [comment]
For any transaction which is waiting for confirmation you have to check the fee, because it's the main reason for which it takes time to confirm. Sometimes even if your fee is "ok" the bitcoin network could has been congested in the broadcasted time, requiring a greater amount that the normal and your transaction could be hanging in the mempool for a while (even be dropped and returned to your wallet after ~1 week in the worst case).
