### ISSUE TITLE
Recovery Tool for Trezor shared wallets

### ISSUE THREAD

**Issue by AdvancedStyle** [bitpay/copay#6645]
I'm trying to understand how you would recover funds in a multi-sig shared Copay wallet, with all trezor signers, if copay.io disappears?

It appears the Copay Recovery Tool (https://github.com/bitpay/copay-recovery) does not support trezor?

So if copay services go away, your funds are stuck?

**Comment by JDonadio** [comment]
> It appears the Copay Recovery Tool (https://github.com/bitpay/copay-recovery) does not support trezor?

Yes. Unfortunately is not supported for now.

> So if copay services go away, your funds are stuck?

https://github.com/bitpay/copay/wiki/COPAY---FAQ#if-copayio-disappears-is-there-a-procedure-to-recover-my-funds

**Comment by AdvancedStyle** [comment]
> So if copay services go away, your funds are stuck?

https://github.com/bitpay/copay/wiki/COPAY---FAQ#if-copayio-disappears-is-there-a-procedure-to-recover-my-funds

This link is to the tool that you said won't work?

**Comment by JDonadio** [comment]
Yes you're right, in your case you'll not be able to recover the funds if that happends.

**Comment by blueknight02** [comment]
This is a HUGE problem for the many people that use your Copay service along with hardware wallets. They expect to have the upmost security, and now your saying that recovery is impossible. This issue should be stated in **bold** when referring people to use hardware wallets on Copay. It's a major security risk and quite unacceptable that this is the case.

**Comment by JDonadio** [comment]
JFYI: We are planning to support BCH within the app which actually support HW, so hopefully both of you guys will be able to claim your BCH soon.

**Comment by blueknight02** [comment]
That's very good news. Any idea on when that might be ready?

**Comment by JDonadio** [comment]
A good approach > next week.

**Comment by blueknight02** [comment]
It's been almost a month now, any idea on when this feature will be ready?

**Comment by Sabbe** [comment]
Indeed. An update on the HW supported BCH recovery would be GREAT. This is really really needed.

**Comment by matiu** [comment]
We are working on this this week. Please see https://github.com/trezor/connect/issues/83

**Comment by blueknight02** [comment]
Please also support Ledger devices, which enabled BCH recovery months ago

**Comment by johnvamo** [comment]
Hi,

Keep waiting for the solution of HW copayers....Thanks...

**Comment by matiu** [comment]
Just to be clear, are you all talking about BCH, right?

I want to clariry that It *is* possible to recover a trezor waller from the
trezor  backup works in Copay (btc)

**Comment by johnvamo** [comment]
Hi,

Yes, I am talking about claiming Bitcoin cash from a copay shared wallet integrated with Trezor. How is it possible to claim them? The recovery tool did not worked out. Thanks for your support.

**Comment by matiu** [comment]
@johnvamo got it. Thanks.

We are working to integrate BCH to Copay Trezor integration now, we hope to finish that in the next few days.

**Comment by johnvamo** [comment]
Thanks for your support.

**Comment by gabrielbazan7** [comment]
I'm waiting for Trezor team response to continue the work with this integration.
https://github.com/trezor/connect/issues/85

**Comment by Sabbe** [comment]
Any comment on the Ledger based wallet BCH recovery? Been waiting for ages.

**Comment by gabrielbazan7** [comment]
@Sabbe I'm also working on the Ledger integration. But the documentation is not clear. https://github.com/LedgerHQ/ledger-wallet-api/issues/13.

**Comment by Sabbe** [comment]
@gabrielbazan7 Do you need help in communicating with Ledger? I know them fairly well and could persuade to improve documentation asap. Tell me if that is needed.

**Comment by gabrielbazan7** [comment]
Yes please! Thanks

**Comment by blueknight02** [comment]
Any updates on this on Ledger integration? It's been months now, and with another hard fork looming I'm afraid it will never be resolved. I'll be changing wallet services and removing my high recommendations of Copay if so. @JDonadio @gabrielbazan7 @matiu

**Comment by johnvamo** [comment]
Hi,

"We are working to integrate BCH to Copay Trezor integration now, we hope to finish that in the next few days."

What about copay Trezor shared wallet to claim BCH...no tool possible yet ? 

Thanks for your support.

**Comment by Sabbe** [comment]
I'm trying to nudge the Ledger team now to help with this. Hopefully they will soon.

**Comment by Sabbe** [comment]
@gabrielbazan7 I got in touch with Ledger CTO, he promised to take a look at that soon.

**Comment by johnvamo** [comment]
@matiu Please give us any news about trezor integration please...

**Comment by chriswilmer** [comment]
@matiu : This is still unresolved right? It's a bit unsettling! The reason I loved Copay so much was precisely because of Copay+Trezor integration... and now I'm anxious about my Bitcoin Cash!

**Comment by gabrielbazan7** [comment]
We are working on it. We will let you know.

**Comment by JasonGreyman** [comment]
Waiting on 1.0 BCH for this problem as well, as I sent it to a SegWait-formatted address for my Trezor (starting with "3" in the BCH address).

**Comment by ledgeruser** [comment]
I'm using MultiSig shared Copay wallet with Ledger being used as signer #2.  My BCH balance is displayed on my phone (signer #1) but will not populate copay chrome app on computer as the second signer is the Ledger.  I can initiate the transfer of BCH from my phone but cannot sign with signer #2.  Frustrating that my BCH is essentially held hostage in Copay!

**Comment by Sabbe** [comment]
Hello @gabrielbazan7 can you update on the current status of the Ledger integration? Has Ledger improved things at their end? Their CTO promised to take a look at this.

**Comment by johnvamo** [comment]
I just got this message from Trezor: 

"BitPay has recently announced that it will discontinue its Copay bitcoin wallet Chrome app, due to Google’s decision about Chrome apps’ end-of-life in 2018. As a consequence, multisig wallets with TREZOR as a co-signer will no longer be available after this date.

If you stored your bitcoins on a multisig wallet with the help of Copay bitcoin wallet, we strongly recommend moving your funds to your TREZOR"

 and:

Hi John,I'm sorry but there is really nothing we can do about this, the ball is on Copay's side of the court right now. Please, contact them.I hope this was helpful. | Hi John,I'm sorry but there is really nothing we can do about this, the ball is on Copay's side of the court right now. Please, contact them.I hope this was helpful.
-- | --
Hi John,I'm sorry but there is really nothing we can do about this, the ball is on Copay's side of the court right now. Please, contact them.I hope this was helpful.

We need to claim our bitcoin cash before it is over copay support...please any good news...because the ones I am showing here are not. 

Thank you for your support till the end....

JOHN
  |

**Comment by matiu** [comment]
@ledgeruser @Sabbe no, there is no news from Ledger.

Please see the complete End-of-life statement at https://blog.bitpay.com/copay-chrome-end/


In order to claim your multisig BCH from trezor/ledger you can:
0- you will need to import for hw seed into Copay SOFTWARE wallet, therefore you should hard reset your hw wallet afterwards to have a private key that never was on a computer/phone.

1-  go you import, and enter the 24 words, select "from hardware wallet"

2- duplicate the wallet to BCH

3- sign an outoging TX

4- sign from the other software copayer.

**Comment by alypseak** [comment]
Thank you @matiu

**Comment by johnvamo** [comment]
Hello @matiu,

Thanks for your quick response.

I am not understanding your instructions.

When you mean software wallet...is the copay wallet where my multisignature funds are...right?

Then if I go to "import wallet"...I have separate options for the words seed and hardware wallet...so where to start from?
Duplicate the wallet to BCH...you mean select BCH?
Where do I sign for an outgoing TX?

Thanks for the clarifications you can give us.

JOHN

**Comment by matiu** [comment]
@johnvamo 

>When you mean software wallet...is the copay wallet where my multisignature funds are...right?

I mean you will need to sign the transaction with a software wallet (ie Copay on a desktop) and not use your Trezor/ledger. To do so, you will need to import the seed from your Trezor/Ledger in Copay.

> Then if I go to "import wallet"...I have separate options for the words seed and hardware wallet...so where to start from?

You need to enter the 24 backup words from Trezor / Leder.


> Duplicate the wallet to BCH...you mean select BCH?
no, import it using BTC, one it is imported, go to settings and duplicate it to BCH.

> Where do I sign for an outgoing TX?

In the software wallet you just imported. You dont need the Trezor/Ledger since the key was imported.


<img width="524" alt="bitpay_-_secure_bitcoin_wallet_and_recovery_tool_for_trezor_shared_wallets_ _issue__6645_ _bitpay_copay" src="https://user-images.githubusercontent.com/98844/33095218-a1c89fe8-cee1-11e7-8dbd-e3e860d7e844.png">

**Comment by johnvamo** [comment]
Hi @matiu,

I imported successfully my copay trezor wallet...but when duplicating...the multisignature wallet ( Fondo TV) is not elegible to be duplicated....why? the one that is elegible is a normal copay wallet...

I have done the process in just one  of the 2-2 copayers... 
 
![walletimportedtrezor](https://user-images.githubusercontent.com/27964280/33097522-7c76c55c-ced8-11e7-9a9f-13aa66015ade.png)

What is next then?

Thanks for your support.

JOHN

**Comment by johnvamo** [comment]
@matiu , I understand the recovery tool does not work for copay integrated with Hardwallets...

Look at the response from Trezor:
<img width="1018" alt="screen shot 2017-11-22 at 11 46 58 am" src="https://user-images.githubusercontent.com/27964280/33139321-edf86ee0-cf7a-11e7-98b2-8e7a0c828dfa.png">

I really need to go through this claim process...Thanks again for your support.

**Comment by chriswilmer** [comment]
@matiu : A step-by-step explanation of how to move BCH from a 2-of-2 Copay/Trezor wallet (even if it means importing the recovery seed) would be really really really helpful!

**Comment by johnvamo** [comment]
@matiu, 

Researching...I found it:

<img width="872" alt="screen shot 2017-11-22 at 10 08 53 pm" src="https://user-images.githubusercontent.com/27964280/33157687-dd15ff3c-cfd1-11e7-80f2-49860f2acb72.png">

My copay multisignature wallet is BIP48, thats why is nos eligible for duplicate for BCH...(only BIP44)

How to resolve it???

Thanks again...

Anyone has gone successfully claiming BCH as mentioned above?

**Comment by corebindallas** [comment]
Hi @matiu and other copay/bitpay staff

I am also in the same boat as everyone else which is really unfortunate. We understand this software is provided without warranty but we would still expect to have a mechanism for this process. 

As was mentioned here because of the derivation path we can not sweep our multi-sig BIP48 trezor wallets.

Is there anything we can do to get this resolved? it would be nice to also do this for the BTG fork at some point.

Even if the process is more complicated or requires us leveraging another application such as electrum we would be happy to give that a try with a little guidance.

**Comment by chriswilmer** [comment]
Could we use this? (would have to edit source code to allow 44 --> 48 for path derivation

https://iancoleman.io/bip39/

**Comment by johnvamo** [comment]
Any one here from Copay support???
Thank you...

**Comment by corebindallas** [comment]
Hi Please help resolve the issue with not being able to sweep the BIP48 derivation path multi sig trezor wallet or give us some guidance. This is totally lacking in professionalism that we arent even being given a response. If it is impossible please tell us why and tell us to go fly a kite at least.

**Comment by JDonadio** [comment]
Please see this comment: https://github.com/bitpay/copay/issues/6645#issuecomment-346151743

**Comment by matiu** [comment]
@johnvamo I was able to reproduce the error you are mentioning.


It is fixed on Chrome App version v3.9.9.  Please note you need Chrome App v3.9.9 in order to be able to duplicate BIP48 wallets, it won't work on other platforms.

v3.9.9 was already submitted to the Chrome store. It should be available soon for all users.


 So, the procedure to access BCH from a multisig software wallet is:


Please see the complete End-of-life statement at https://blog.bitpay.com/copay-chrome-end/

In order to claim your multisig BCH from trezor/ledger you can:


0- you will need to import for hw seed into Copay SOFTWARE wallet, therefore you should hard reset your hw wallet afterwards to have a private key that never was on a computer/phone.


1- Using Copay Chrome App Version v3.9.9; go you import, and enter the 24 words, select "from hardware wallet"

2- duplicate the wallet to BCH

3- sign an outgoing TX

4- sign from the other software copayer.

**Comment by johnvamo** [comment]
Hello @matiu,

I am glad to hear from you. I will try it...and tell you what happened. Thanks.

**Comment by johnvamo** [comment]
Hello @matiu,

I claimed successfully the bitcoin cash...

But, here some tips to get it correctly...

1.When I imported the wallet with the 24 words seed...I change the derivation path from m/44'/0'/0'  to **m/48'/0'/0'** otherwise the wallet is not shown...
2. Then I could duplicate the wallet...when sending from the copay wallet **important** to put before the address  "bitcoincash:" then the address.  

Reading:
https://www.yours.org/content/increasing-merchant-adoption-of-bitcoin-cash-e3167e2fa326/ 

I hope anyone with the same situation can solve it at last...

**Comment by johnvamo** [comment]
@matiu, 

I forgot to Thank you so much for your support.
Happy Christmas!

**Comment by corebindallas** [comment]
@matiu 
Thank you very much I can confirm the same as @johnvamo
It's important for the user to duplicate the derivation path as it is currently in their hardware + copay wallet. In my case I used a second account on the trezor so my path was **m/48'/0'/1'** also I wasn't able to add the wallet until I deleted the original wallet which uses the trezor seed the application complained.

Thank you all so much we appreciate all the hard work the product is amazing and I really hope the native applications will implement hardware seeds but with a little more transparency on how to recover them in the event copay vanishes (we hope not) or that one of these forks happens again (we also hope not) it's always nice to be able to access funds if it is normally possible.

**Comment by JasonGreyman** [comment]
If anyone like me sent BCH to a SegWit address on accident, it looks like BTC.com's guide here offers a solution for a 10% fee. I have not completed it yet, just passing on the info:

https://bch.btc.com/docs/help/bch_segwit_recovery

**Comment by chriswilmer** [comment]
My Chrome Copay "extension" is 3.9.9 but when I load the "app" and go to about it says the version is 3.9.2... also, I don't see the derivation path changing to m/48/0/0 when I click on hardware wallet in the import menu. How do I get the 3.9.9 "app"?

**Comment by johnvamo** [comment]
The version is the same for me 3.9.2 within the app - when you see in the extensions app window in chrome it says 3.9.9 ...it works...an the derivation has to be changed manually...
<img width="406" alt="screen shot 2017-12-08 at 12 01 03 pm" src="https://user-images.githubusercontent.com/27964280/33776512-9fc3b77e-dc0f-11e7-9e59-f1ddd5a67e73.png">

**Comment by chriswilmer** [comment]
Grr, I feel like I'm close. I followed the above steps and when I hit the "duplicate to BCH" button... it showed my BCH balance temporarily, but now it shows a BCH balance of 0 (and no transactions). It's not possible that the txn was spent because the 2nd co-signer is still not imported (still using the trezor). Not sure what's going on.

**Comment by chriswilmer** [comment]
Guys, what am I doing wrong? When Copay "checks the balance" of my Bitcoin Cash Wallet BEFORE I hit "duplicate" it shows a positive balance. AFTER I hit duplicate, it shows a zero balance and I can't spend anything. I've tried deleting the wallet and reimporting and it shows the same thing.

**Comment by chriswilmer** [comment]
Sorry to spam this thread, but I feel as though my situation has become somewhat urgent... now that I've typed my recovery phrase into Copay, the funds are no longer as secure, I was hoping to send them immediately to a new secure address... but now they are stuck in a low-security situation. Please help!

**Comment by chriswilmer** [comment]
OK, so, just to add a little more technical detail to what is going on, let me describe what I am doing. First of all, I *am* able to successfully recover BCH from a 1-of-1 wallet using the above procedure, works perfectly. For my 2-of-2 wallet, the BTC wallet shows the full transaction history, but after I click "duplicate to BCH" it does not show any transaction history, which is clearly a bug, because it should show all of the old transactions from before the split (there were many). So, it is somehow not duplicating to BCH correctly.

**Comment by chriswilmer** [comment]
UPDATE!!!! - I went into the settings for the wallets and manually clicked on "scan addresses for funds" and finally all of the Bitcoin Cash showed up. OK, trying to sign the txn now... what a stressful today. Sorry for flooding this thread! Maybe someone else will have the same problem.

**Comment by chriswilmer** [comment]
UPDATE2: Nope, still stuck. I can create a payment proposal with cosigner A, but for cosigner B I follow the exact same procedure, but when I hit the "duplicate BCH" button nothing happens. No Bitcoin Cash wallet is created... both wallets use the same 24 word recovery seed but each uses a different password. Help?

**Comment by johnvamo** [comment]
Both wallets use the same seed??? How is it possible?

**Comment by chriswilmer** [comment]
Well, the "password" is like a 25th word for the recovery seed. So, they each have the same first 24 words and then a different 25th word. Anyway, maybe it has caused some unintended behavior in this case. I am besides myself with anxiety right now.

**Comment by johnvamo** [comment]
Are you using trezor? In both wallets?

If yes, each trezor should have a different seed: 24 words



John Jairo Vásquez

**Comment by chriswilmer** [comment]
Yes, both wallets are using a trezor, but they were both initialized with the same 24 word seed.

**Comment by johnvamo** [comment]
Thats strange to me...as far as a know each wallet should have a unique private key (seed). otherwise, is the same wallet!

Are you using different computer for each wallet? are both copay wallets updated to version 3.9.9? 

Where both imported with the derivation path m/48/0/0 ?

**Comment by chriswilmer** [comment]
@johnvamo Yes, each wallet DOES have a unique private key because the private key is essentially:

 SHA256( recovery seed + password)

So if each wallet uses a different password, then the private keys are different. That's why the password is kind of like a 25th word for the recovery seed. Makes sense?

I'm still stuck though for reasons I don't understand.

**Comment by blueknight02** [comment]
@matiu I successfully imported the HW seed, but when duplicating the wallet to BCH, the BCH wallet says its "Incomplete." When I select it, it gives me a QR code to share with other copayers(as if I were just creating the wallet)

**Comment by ledgeruser** [comment]
I'm running into the same issue as blueknight02 above.  My BCH wallet is now stuck as "Incomplete" and when I click on it I am provided a QR Code to share with other copayer.  However my original copayer already has the wallet created and showing a balance.  Just the copayer affiliated with the Ledger still having issues.

**Comment by jojkaart** [comment]
@ledgeruser @blueknight02 You can use Electron Cash to import the wallet as well. You can even import all the keys in one wallet if you wish or use it in the multisig manner if you need to preserve multisig-security. Just give Electron the seed, click options to tell Electron it's a BIP39 wallet (don't use the 145 thing, that's for seeds specifically created for use with bcash). After this, proceed and make sure the derivation path is the correct one m/48/0/x for the ledger seed, where x is the account number you chose for copay to use.

We recently succesfully used this method to claim funds from an old multi-sig copay-ledger wallet.

**Comment by ledgeruser** [comment]
Am I the only one who still hasn't been able to get access to their BCH?  I'm not sure if I should trust Electron Cash with this (maybe if a step by step guide was made).  With Copayer 1 the BCH will not duplicate and displays a balance of zero but when I go into Settings-->Bitcoin Cash I can view my full balance.  Copayer 2 has full access to BCH with no issues.  Could really use some help here please!
