### ISSUE TITLE
Recebi um dinheiro em bitcons e não consigo transferir pra nenhuma outra carteira a não ser a do copay

### ISSUE THREAD

**Issue by macaco2205** [bitpay/copay#6713]
Recebi um dinheiro em bitcons e não consigo transferir pra nenhuma outra carteira a não ser a do copay, meu saldo está lá preso , abri uma carteira, configurei as configurações avançadas te stnet e tal mais não consigo transferir pra uma carteira que não seja configurada da mesma forma e pra nenhuma outra carteira de fora do copay , se puderem me ajudar são 4 btc...

**Comment by JDonadio** [comment]
@macaco2205 can you please provide your wallet id? also if you can attach some screenshot of your problem would be great

**Comment by macaco2205** [comment]
as I will attach an image here has no option to add an image, where where is my ID of the wallet I am new to it
The guy who sent the bitcoins asked to make a configuration in the account.
I checked the option - testNet
and also checked the option - only address wallet for audit purposes, the problem and that the bitcoins are stuck and can only be sent to wallets with the same configuration and when I send it to another wallet the message that my wallet is without funds or when I buy some gift card from amazon he says that there are no wallets available, if you can help me with this.

**Comment by macaco2205** [comment]
480cb622-8f20-4136-82dd-802c62028213

**Comment by Inkeliz** [comment]
Testnet not have any value. For sure you can't purchase any gift card from Amazon, because Amazon only accept the Bitcoin from Mainnet, the true Bitcoin.

Understand the Testnet like a “altcoin”, this is only for testing propose, they don’t have any value. You can't buy anything using the Bitcoins in the Testnet, look on [Wiki](https://en.bitcoin.it/wiki/Testnet):

> The testnet is an alternative Bitcoin block chain, to be used for testing. Testnet coins are separate and distinct from actual bitcoins, and are never supposed to have any value.

For the same reason, you can’t move the bitcoins to another wallet outside from Testnet. The Testnet Bitcoin can only be used inside the Testnet.

**Comment by JDonadio** [comment]
Thanks @Inkeliz for the clean information. @macaco2205 I hope your doubts have been clarified.
