### ISSUE TITLE
Coins still confirming 

### ISSUE THREAD

**Issue by boxur** [bitpay/copay#6752]
Why do I have 80$ With less than one confirmation still pending for 1 day now

**Comment by boxur** [comment]
Why can't I spend my coins also why do u take so many coins like this when sending a transaction like why do u hold my 80$ and only leave 1$ for immediate spending??

**Comment by boxur** [comment]
Have scanned address for coins same thing. It says 79$ with less than 1 confirmation and still not confirming

**Comment by boxur** [comment]
Also the transaction i sent 12 hrs ago keeps refreshing saying I "sent a few seconds ago" after it say sent "a few minutes ago" recurringly

**Comment by boxur** [comment]
Wallet id 735c55fb-53a0-468a-8847-5ea064679c35

**Comment by JDonadio** [comment]
Please read:

https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-creating-a-transaction-proposal-lock-my-balance-and-is-significantly-higher-than-the-proposal-amount

Note: if your transaction is pending for confirmation, the reason is a low fee (see the transaction size explanation in the first link)

If you provide your transaction id we can take a look and check what is going on.
