### ISSUE TITLE
BCH balance is 0

### ISSUE THREAD

**Issue by bektar** [bitpay/copay#6759]
I just installed the 3.8.1 beta on iOS and enabled support for bch. The bch wallets do not show any transactions and the balance is 0.

**Comment by JDonadio** [comment]
Please try scanning your wallet with https://bitpay.github.io/copay-recovery/ and tell us if you see your balance there. Ensure to select `bch/livenet` as main chain before scan.

**Comment by bektar** [comment]
It is a 3 out of 6 wallet and I only got easy access to 3 of the seeds. I will try to get hold of the other ones, but will probably take a few weeks

**Comment by JDonadio** [comment]
Obvious question: your wallet was created and had funds before 1 Aug ?

**Comment by bektar** [comment]
Yeah, one of the wallets haven’t had any transactions since late December though, but as far as I know that shouldn’t matter? The second wallet has been used regularly and is also empty of bch (should be a small amount on it, definitely > 0).

**Comment by JDonadio** [comment]
If you had BTC balance before 1 Aug your BCH balance should be there. Otherwise it would be zero by duplicating it.

**Comment by bektar** [comment]
I used the recovery tool on one of the wallets and managed to sweep it without issues. When i open copay there still are no transactions listed, not even the sweeping one is shown.

**Comment by allthatmoney** [comment]
how do you get the 3.8.1 beta  release? i don't have a bch option in my wallet?

**Comment by bektar** [comment]
@allthatmoney https://blog.bitpay.com/bitcoin-cash-wallet-beta/

I imported a third wallet and converted to bch, for this on the transactions actually shows up. It is only a 2 of 2 wallet. It fails to actually send though, the confirmation dialog doesn't display properly so can't click the button.

**Comment by allthatmoney** [comment]
thanks bektar but i figured out how to get my coins. i let the software do the search for me and it found my bitcoin cash for me and then i sent the coins to my trading platform at livecoin. they support bitcoin cash there and my deposit went rite in and is ready to trade or sell now. if anyone needs to know about livecoin you can go here https://livecoin.net/?from=Livecoin-Ub5t4keE
 and get an account with them and then click on the balance tab at the top after you log in. then find the bitcoin cash wallet in the list and click on the deposit button and it will give you a bitcoin cash address to send your bitcoin cash to. it works really well with no problems. i thought we had to collect our coins in copay but that is not the case. you can send them to anyplace that supports bitcoin cash and you will receive them. to me this seems a lot more simple than creating a third wallet or even adding to my copay wallet when it supports them since i only wanted to collect what was rightfully mine and sell them for bitcoins. i am very pleased now

**Comment by allthatmoney** [comment]
do not use the extractor. some one is getting our code words and emptying our copay wallets. they got mine and a friends wallet already. we got our bitcoin cash and then they came back and got our bitcoins. i repeat don't use the extractor. it's a hacker's tool

**Comment by allthatmoney** [comment]
hello, i thought i had gotten hacked but what happened is i forgot to change the chain bitcoin to bch and i searched and found my bitcoins. then i sent my bitcoins to a bitcoin cash address thinking they were bitcoin cash coins. is there any way to get these coins back since i have the bitcoin hash address they were sent  does anyone at all  know how to get these back? if not that software needs to be removed because i won't be the last to do this. why does it even have a bitcoin selection on it and why does it start on bitcoin selection?

**Comment by JDonadio** [comment]
We made some changes in the recovery tool to make more clear what chain are you scanning/sending the funds. If you are the owner of both seed wallets there is not problem if you send bch into a btc wallet or vice versa, all you have to do is scan the recipient wallet selecting the correct chain.

**Comment by allthatmoney** [comment]
no, i sent the bitcoin to livecoin trading exchange address. i guess it
will depend on if they are willing to help me or not. it was abut 10,000.00
dollars so they might keep it.

**Comment by matiu** [comment]
[ Removing comments not related to OP]

@bektar Please let us know any of the addresses holding the funds so we can check the wallet.

**Comment by bektar** [comment]
I actually managed to get a hold of the other seeds and used the recovery tool without any issues this weekend. Still no transactions shown in copay. Are you still interested in the addresses?

**Comment by matiu** [comment]
Hi, sorry you are having problems. Yes please, if possible send us one of the addresses that used to had funds and the walletId (my email es matias@bitpay.com). so we can check it on detail. The wallet's transactions should be listed.

**Comment by bektar** [comment]
I was able to get it to display the transactions by doing the following:

    Settings -> [[select wallet]] -> More Options -> Wallet Addresses -> Scan addresses for funds

I'll send a couple of the addresses to you by mail anyway.
