### ISSUE TITLE
Money not in wallet

### ISSUE THREAD

**Issue by yhindy** [bitpay/copay#6770]
I bought some coin on coin base and on coin base it says transaction went through but on copay it says replay the request with cb-2fa token. What do I do?

**Comment by matiu** [comment]
Ping @cmgustavo

**Comment by cmgustavo** [comment]
Hi @yhindy , I 'm sorry you are having issue with our Coinbase integration. Could you confirm that your bitcoins are in your Coinbase account thought their website? It happens because Copay can't create a bitcoin transaction using the Coinbase API without the correct permissions. This is a known issue and will be fixed in the next release.

**Comment by yhindy** [comment]
In my BTC wallet on Coinbase, it says that the coins are there. Will my coins show up in a copay after the update?

**Comment by yhindy** [comment]
@cmgustavo

**Comment by cmgustavo** [comment]
Transactions that already got an error, have to be completed manually creating a normal transaction from your Coinbase account (website) to your Copay wallet.

After the update you should logout and re-connect Coinbase from Copay. This is due to a change in token permissions from Coinbase that solves the 2FA issue. Please, stay tuned to any update of Copay and sorry again for problems caused
