### ISSUE TITLE
BCH multisig (can't create transaction)

### ISSUE THREAD

**Issue by idoganov** [bitpay/copay#6810]
When I create a transaction with multisig address (2-3) after entering the address of the recipient and the amount at the next stage, an error occurs. The commission is not calculated and there is no possibility to send the transaction.

**Comment by JDonadio** [comment]
Could you attach some screenshots so we can investigate it? thanks

**Comment by idoganov** [comment]
![scr](https://user-images.githubusercontent.com/28714128/31046977-03711270-a60b-11e7-80d5-fc6ffe53a164.jpg)

**Comment by JDonadio** [comment]
Hi, the issue is caused by the "old" format for BCH addresses. 

Please read this article: https://support.bitpay.com/hc/en-us/articles/115004671663

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using https://bitpay.github.io/address-translator/
