### ISSUE TITLE
Please change title of app and clarify BCH as a separate currency.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#6825]
Currently, Copay is registered as "A Bitcoin Wallet" which is misleading. Currently Copay now supports currencies other than Bitcoin, so "A Cryptocurrency Wallet" or "A Multi-currency Wallet" should be more appropriate.

Calling Copay "A Bitcoin Wallet" and adding an option for wallet creation that shows Bitcoin Cash as "just a parameter change, no biggie" rather than "Choose your Currency" (clearly stating Bitcoin Cash is a separate currency) can land Bitpay in hot water legally in many countries, as it could be interpreted as trying to pass off Bitcoin Cash as Bitcoin.

I'm not trying to say "Bitcoin is the real Bitcoin and Bitcoin Cash is not" but rather "These are separate currencies, and should be portrayed as such. Otherwise Bitpay is liable for criminal charges in many countries (if any lawyer cared to bring it up)"

For instance, the current UI would be very helpful to a scammer that was trying to sell someone Bitcoin Cash at a higher price by showing them Bitcoin's price. When the same scam was reported by people being tricked into buying Testnet coins, your reaction was to change the UI enough to make it obvious that Testnet coins were different and removed the fiat price display to remove confusion...

Then the following days you add Bitcoin Cash as if it were Bitcoin, saying "oh, this is just the same thing, but you're just changing the "Coin" parameter, nothing to see here."

**Comment by fortran77** [comment]
This type of proposal should be based on technical merit, not on made up nonsense like the "criminal charges" assertion.

**Comment by dabura667** [comment]
> technical merit

UX decisions are almost never made on technical merit... in fact most UX decisions are made at the cost of technical merit. Thanks for your input though.

This is a UX problem. And in the worst case scenario, a legal problem. Bitpay is a company that is officially sponsoring this software, so they are an easy target for litigation. The legal comment was just a kind reminder, as it seems their legal team is asleep at the wheel, or fired due to massive layoffs before Bitmain threw them a lifevest in exchange for their souls.

Ok, that last part was a jab.

but still, this UX is confusing, and I have actually had a user who bought 1 BCH from someone for $5000. The wallet they used was Bitpay wallet.

Bitpay is losing people money and helping scammers with their new UI.

Sorry if your political affiliations are blinding you from seeing the horrible UI, @fortran77

**Comment by matiu** [comment]
We are not changing the name. Copay supports Bitcoin, Bitcoin Cash, and Bitcoin Testnet. "Bitcoin Wallet" is an appropriate description.

**Comment by dabura667** [comment]
Testnet is a network for testing bitcoin.

Bitcoin Cash is an altcoin specifically made to attack Bitcoin.

There’s a difference.

**Comment by matiu** [comment]
> Bitcoin Cash is an altcoin specifically made to attack Bitcoin.

We appreciate all points of view, but we will not have that discussion here. 

We see Bitcoin Cash as a legit cryptocurrency, providing alternative ways to scale Bitcoin.  In the future, it may disappear, or overtake Bitcoin core; or they could both coexist. We think that now, the best service to our users is to support both in our wallet.

**Comment by jameswalpole** [comment]
To the technical questions here about UX confusion: BCH and BTC are clearly labelled on wallets in the app, and the team is working on designs to further distinguish these two assets visually. In addition, anyone who wants to use the BCH support option must knowingly enable it in their wallet settings. These changes and the [BCH address formatting](https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests) are designed to avoid any user confusion between chains

**Comment by junderw** [comment]
> is working on designs to further distinguish these two assets visually

This should be higher priority. There have been multiple accounts of users being sold BCH for a "discounted price" based off BTC price, then they complain to the exchanges where they try to "sell their Bitcoin"

When asked which wallet they used (we were curious whether there was some fraud app showing Bitcoin Cash as Bitcoin) they said Copay.

Electron Cash is an app that only Cash users will seek out to use Cash, Electrum does not support Cash.

Copay is the first app that originally supported Bitcoin to after-the-fact support Cash in parallel and do it in such a way that users are being tricked into buying BCH for BTC prices. (The customer said in their ticket "I thought, because it says "bitcoin wallet app" on the appstore, it only deals with bitcoins")

So I agree that this issue shouldn't be politicized a la @matiu 's comment, I think that the current UI was very distasteful. I will not assume malice, but will hope that moving forward Copay can protect users from this kind of fraud in the UI/UX decisions it makes.

Thank you.
