### ISSUE TITLE
Lost one of the 12-word seed on multi sig

### ISSUE THREAD

**Issue by Azverin** [bitpay/copay#6835]
I have a multi sig wallet and lost one of the devices, which remained one of the combinations of 12 words, please help to restore the ability to work with a wallet, becuse I have an unspent funds

**Comment by JDonadio** [comment]
Hi there,

If your multi-sig wallet is `2-2` there is nothing to do. 
If your multi-sig wallet is `x-2` with x >= 3, all you have to do is use the [recovery tool](https://bitpay.github.io/copay-recovery/) and use all the exported backup format available for you. In this case the 12 words will not work because the exported format have the public key ring for all of the copayers.

Hope that helps.

**Comment by parkermor** [comment]
@Azverin 
I can recover the lost words of your wallet if you want need help send me email : anywalletrecovery@gmail.com
