### ISSUE TITLE
copay.exe version 3.8.2 from github is marked by Avast for having: FileRepMalware

### ISSUE THREAD

**Issue by Miner01-PC** [bitpay/copay#6851]
copay.exe version 3.8.2 from github is marked by Avast for having: FileRepMalware

**Comment by dabura667** [comment]
Did you check the signature?

Checking the signature will tell us that The exe file that triggered the malware detection is actually Copay’s exe and not some exe that a virus on your computer tricked you into downloading.

Please check the signature, then rescan and tell us if the result is the same.

**Comment by Miner01-PC** [comment]
How do I check the signature?

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay/issues/6471#issuecomment-333117704

**Comment by dabura667** [comment]
1. Download Gpg4win from this site: https://www.gpg4win.org/download.html
2. Once you download the exe file, type in the Windows search "Powershell" and run powershell
3. Type in `Get-FileHash YOURFULLFILEPATHHERE | Format-List` (You can enter the full file path by typing in "Get-FileHash" then space, then drag and drop the exe file on your powershell window and the file path will show... then type space, then `| Format-List`
4. It should show something like: Algorithm, Hash, Path
5. Make sure the algorithm says SHA256 and the Path matches the file... then check that the hash you get matches the hash on gpg4win below the download button, just to be sure, I'll write it here too: `SHA256: 2565bf6faf8defb8fa61b0b1a30f0e68e2ca5ceb3177d08516e00ca1620252bf`
6. Install gpg4win
7. Run Kleopatra (installed with gpg4win)
8. click "Decrypt/verify files"
9. Open the sig file (make sure the exe file is in the same folder, and that it is the same filename just without .sig on it)
10. It might show yellow or red (Because you haven't "trusted their key" yet, but that's complicated), but that's not important, check that it says "Valid signature" or not. And it should show the key ID as 0x1112CFA1. (This is copay's binary signing keys)

If it says valid signature, the exe file is definitely the one that Copay uploaded.

**Comment by dabura667** [comment]
Windows is so complicated. The how-to for linux is

1. Open terminal
2. `gpg --verify Copay.exe.sig Copay.exe`
