### ISSUE TITLE
[important] Deadalnix' Bech32 address proposal

### ISSUE THREAD

**Issue by DesWurstes** [bitpay/copay#6899]
Would you remove your new address format starting with `C` and add the Bech32 format (described here: https://github.com/Bitcoin-UAHF/spec/pull/21) if some wallets start using it? It's more useful. Some discussion at the end of https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-October/thread.html

**Comment by monsterbitar** [comment]
Starting with... C?
I have a multisig cash wallet where the address starts with H. I also have issues using it, since some places don't recognize it as a valid address. I know the issue is on the other part not recognizing it, since they are the ones making assumptions that aren't valid in my case, but still.

I'd be happy with getting regular bitcoin-styled addresses as an option, and the Bech32 seems like a good thing as well; though it will likely be plagued by the same inter-compatibility issues for months to come.

**Comment by matiu** [comment]
@DesWurstes definitely yes. If there is a new standard for Cash, we will adopt it.

Here is a small description of the address conventions we use:
https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

In order to move forward we *needed* to differentiate bitcoin and bitcoin cash addresses, otherwise our users will be extremely confused.

@monsterbitar p2sh addresses (for multisig wallets, in case of Copay) for cash start with "H", p2pkh, with "C". 

You can translate the addresses to the other version using https://bitpay.github.io/address-translator/

**Comment by priestc** [comment]
I want to put it on record that I think bech32 addresses for BCH is a bad idea. I much prefer a version byte change. With that said, I would also support keeping everything the way it is. Segwit Bitcoin is moving to bech32 addresses anyways, so eventually "1" addresses will be unique to BCH.

**Comment by DesWurstes** [comment]
@matiu So you'll implement the Jan 14 Bech32 address format?

**Comment by DesWurstes** [comment]
OK, may I assume that you won't?

**Comment by monsterbitar** [comment]
Assume they will; though expect it to possibly happen later than Jan 14.
