### ISSUE TITLE
Help with mutisign wallet.

### ISSUE THREAD

**Issue by tsomoney** [bitpay/copay#6934]
We have a 3 of 5 copay wallet,

for the upcoming BTG and BT1 BT2 hard fork, how do we get our coins?

For private wallet is simple, just the private key, but how about mult-sign wallet?

Thanks

**Comment by JDonadio** [comment]
Hi there,

In respect of the upcoming Bitcoin  network Segwit2X fork, what will happen around mid November 2017, we are evaluating the best options for our wallet users and the best way for the apps will react to the fork.

In Copay and Bitpay wallets, the users, and only the users, hold theirs private keys, therefore it will be always up to the user to decide exactly what path to take, and when and how to move theirs funds.

We are committed to maximize our user's funds security and value. In the coming weeks, we will provide more details about Copay and Bitpay app plans for the fork.

**Comment by kirksu** [comment]
To elaborate on the question:
I have a copay 3 of 6 wallet with BTC in it. After the hard fork that creates B2X (Segwit2X) later this month, will I be able to access the B2X from my wallet? If the answer is yes, how can I access it?
When the hard fork a few months ago created BCC (BitcoinCash), I was unable to access the BCC from my copay 3 of 6 wallet because one of the 6 seeds had been lost. I want to avoid a similar situation after the Segwit2x fork.  Also, if there is a way to access the aforementioned BCC with only 5 of the 6 seeds available, I would be very appreciative to know it.  I posted this same question under issue #7015 a few moments ago, before finding this string.  Sorry for the duplicate post.  This seems like a better place for the post.

**Comment by matiu** [comment]
@kirksu deleted you  comment, please do not post the same comment many times.

**Comment by kirksu** [comment]
Thank you, I was just looking for the way to do it myself.  Sorry for the duplicate.
