### ISSUE TITLE
Where are my btc ?

### ISSUE THREAD

**Issue by drago23456** [bitpay/copay#7011]

**Comment by JDonadio** [comment]
Explain your issue because I have nothing to start.

**Comment by drago23456** [comment]
I had 33 € and i couldent use it but no i have nothing wtf

**Comment by JDonadio** [comment]
Are you waiting for an incoming transaction?
Are you trying to send a transaction?
Can you attach a screenshot?

**Comment by drago23456** [comment]
No,No                  ![btc](https://user-images.githubusercontent.com/33255577/32225433-7f08c1ce-be45-11e7-811e-7d0cba8e4742.PNG)

**Comment by drago23456** [comment]
I have to go to work but i swear i had yesterday 33€ and no my wallet is empty

**Comment by JDonadio** [comment]
Go to settings > wallet > more opts > wallet information, copy and paste the wallet id

**Comment by drago23456** [comment]
nothing is listed in my transactions
so i dont know where it is

**Comment by drago23456** [comment]
d8746da0-9bb0-4d10-bc8b-e5e880263e5d

**Comment by JDonadio** [comment]
Your wallet status:

* Balance
  Total: 0.00000000 btc (0.00000000 btc locked)
  Confirmed: 0.00000000 btc (0.00000000 btc locked)
  Available: 0.00000000 btc (0.00000000 btc confirmed / 0.00000000 btc unconfirmed)

* Tx history
  [Sun Oct 22 2017 12:49:52 GMT-0300] ca5482fd93d38701c7fcb467ef4ce714b37f343a5b51788eddbe2d6027484e5c => sent 0.00237900 btc (fee/kb 0.00146571 btc) (1337 confirmations)

Your [last transaction](https://insight.bitpay.com/tx/ca5482fd93d38701c7fcb467ef4ce714b37f343a5b51788eddbe2d6027484e5c) was sent 9 days ago and your wallet remains empty since then.

**Comment by JDonadio** [comment]
@drago23456 the email is just for notification. You are the owner of your keys and only you can sign and broadcast transactions, not me or anyone of BitPay. The keys are stored in your device so if you didn't move these funds maybe was another person with access to your device.
