### ISSUE TITLE
Copay connection to Coinbase not working 

### ISSUE THREAD

**Issue by TheHCA** [bitpay/copay#7022]
Yesterday I got copay and Coinbase and linked the accounts. In Coinbase I set up my payments and bought 0.005 BTC. 

I want to keep the bitcoin in my copay wallet though and copay is showing as 0.00 BTC which I’ve seen is because the wallets are separate.

When I try buying bitcoin using the Coinbase integration in Copay (so it will go into my Copay wallet and can skip the transfer fee), I get an “Error: No payment method available to buy” and I can’t see my previous purchase activity in Copay. 

I’ve had a look at other tickets for this error with no resolutions working for me.

**Comment by cmgustavo** [comment]
Hi @TheHCA , 

That 's correct, Copay and Coinbase are different wallets.

Coinbase integration only supports buy/sell from US bank account. If you have an US bank account, this error could be related to some types of payment that Coinbase doesn't support from third party applications (API). We are working to provide more information from Coinbase in Copay side in order to understand why it fails.

Hope that helps. Thanks.

**Comment by TheHCA** [comment]
Ahh, my bank account is UK which probably explains why I’m getting this error. 

Is my only option then to transfer my bitcoins via a standard send between the wallets?
Also, are there plans in the near future to expand this feature to non-US accounts?

**Comment by cmgustavo** [comment]
I am afraid that you have no other option that send manually from Coinbase to Copay. 

We have plans to add "EUR" in the near future, but I don't know about UK. 

Thanks for report.
