### ISSUE TITLE
Android build - cordova-custom-config: Error loading dependencies (Cannot find module 'tostr') - attempting to resolve

### ISSUE THREAD

**Issue by xelawafsTemp** [bitpay/copay#7048]
Environment:

**copay version: 3.8.2
node version: v8.4.0
npm version: 5.5.1
cordova version: 7.0.1**

`npm run start:android` fails with the following error:

```
> copay@3.8.2 build:android /app/copay/android
> cordova prepare android && cordova build android --debug

cordova-custom-config: Error loading dependencies (Cannot find module 'tostr') - attempting to resolve
cordova-custom-config: npm dependencies missing - installing
cordova-custom-config: Installed npm dependencies
cordova-custom-config: Running restoreBackups.js
cordova-custom-config: Error loading dependencies (Cannot find module 'tostr') - attempting to resolve
cordova-custom-config: npm dependencies already installed
npm WARN invalid config loglevel="notice"

> copay@3.8.2 run:android /app/copay/android
> cordova run android --device

cordova-custom-config: Error loading dependencies (Cannot find module 'tostr') - attempting to resolve
```

I've looked around and [this issue](https://github.com/dpa99c/cordova-custom-config/issues/89) indicates a race condition may be involved between Cordova hooks. A quick fix was to first run `npm install tostr`. Is this a know/fixed issue?

What can I do to run `npm run start:android` without it breaking?

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.
