### ISSUE TITLE
my wallets not letting my balance go

### ISSUE THREAD

**Issue by brenz16** [bitpay/copay#7112]
I can't sent the bitcoins I have in my wallet back to my blockchain why's that?

**Comment by brenz16** [comment]
Here's a pics

**Comment by brenz16** [comment]
1MHpv1fn7nLeDowh6Xc3cY5Rf4aaJeiUKb my wallet id

**Comment by JDonadio** [comment]
Please explain your issue because we don't know what is happening with your wallet.

**Comment by brenz16** [comment]
![copay wallet error](https://user-images.githubusercontent.com/33578627/32694048-752e4110-c79b-11e7-9110-f8371972d4af.png)

**Comment by brenz16** [comment]
I have been trying to send the remaining balance in my wallet but it won't let me

**Comment by brenz16** [comment]
![copay wallet error2](https://user-images.githubusercontent.com/33578627/32694112-451a58a0-c79c-11e7-998a-9e42ffa0c429.png)
![copay wallet error3](https://user-images.githubusercontent.com/33578627/32694113-4993c772-c79c-11e7-8dfd-429ffce6b9e2.png)

**Comment by brenz16** [comment]
its been trying to send for two days now

**Comment by JDonadio** [comment]
Right now the bitcoin network is congested due a huge  amount of transactions in the mempool. Unfortunately there is nothing to do, just wait.

The amount what you're trying to send is too low, so will not be economically viable spend it because of fees.

Please check our [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ) section, could be very helpful.
