### ISSUE TITLE
Previously confirmed transaction now unconfirmed. And transfer to exchange in limbo, no confirmations

### ISSUE THREAD

**Issue by remsky** [bitpay/copay#7121]
Transferred in an amount of BTC, 80+ confirmations to copay. Sent half of it to exchange, still says "Sending, a few seconds ago" even though it's been 8 hours. 

Fine, congestion. Not great, but it happens. But the other half of my balance is now saying Unconfirmed and that I have a 0 BTC confirmed balance.

**Comment by DingusShiba** [comment]
I actually have the same thing going on, and my balance switches per refresh. Won't settle on a balance, thus errors are thrown when trying to transfer.

**Comment by remsky** [comment]
It's been 12 hours now, still no confirmations on the outbound, still has my **previously confirmed balance as unavailable**

What's going on. People are waiting for this transfer, what do I tell them.

**Comment by JDonadio** [comment]
@remsky please explain your issue in detail and provide the transaction ids.

**Comment by remsky** [comment]
2c6b94ee6ef138c02bfda6978357dd1033f476afa7d1797cb9b830b4fc1555ca

Transaction into my copay, was confirmed. Sent half of it away on the transaction I'll include below.  It's still unconfirmed and saying it's too low to send (set on normal priority), but whatever. 

The remainder of the balance, which hasn't been sent anywhere, is unavailable in Copay now. It won't let me send it or even see it as confirmed

**Comment by remsky** [comment]
d3b83cc837a298f1cbe8ee7cfe5db4b183f16767d8ba9d137c158bcf5a8c3eb2

Outbound unconfirmed congested transaction ^

**Comment by remsky** [comment]
@JDonadio

**Comment by swirve001** [comment]
I am having a similar problem.  I sent a transaction to an exchange, and it is stuck in seemingly permanent limbo.  Half the transaction seems to be acting like it's using unconfirmed funds, though all previous transactions with the wallet were confirmed long ago. Transaction information:

https://insight.bitpay.com/tx/21d7d0cc2d81b7912c0b0c64d89c2ad44e04a3a8e029db431ff184d30b439646

The "0.49867622" amount also is identical to the amount in my wallet that now says unconfirmed funds not able to be spent.  I can't tell if that is the source of the problem, or if it's because that part has sort of gone through.  In Blockchain Explorer:

https://blockchain.info/tx/21d7d0cc2d81b7912c0b0c64d89c2ad44e04a3a8e029db431ff184d30b439646

I see this "Estimated BTC Transacted | 0.49867622 BTC"

I have no idea what's going on except that the transaction lists as unconfirmed, and is thus not available in either my wallet or at the recipient address.

**Comment by remsky** [comment]
24 hours now, no explanation

**Comment by mazamats** [comment]
Same thing here, in my case it looks like the transactions are never even getting broadcasted to the network.

Several transactions that I've sent with Normal/Priority fees won't even show up on any block explorer. They're been hanging there for days.

**Comment by JDonadio** [comment]
@remsky 

This transaction is confirmed: https://insight.bitpay.com/tx/2c6b94ee6ef138c02bfda6978357dd1033f476afa7d1797cb9b830b4fc1555ca

This transaction is confirmed as well: https://insight.bitpay.com/tx/d3b83cc837a298f1cbe8ee7cfe5db4b183f16767d8ba9d137c158bcf5a8c3eb2

**Comment by JDonadio** [comment]
@swirve001 your transaction was confirmed

**Comment by JDonadio** [comment]
The bitcoin network congestion is out of our control, we (and any wallet software) can do anything.
