### ISSUE TITLE
Gone BCH

### ISSUE THREAD

**Issue by levmuza** [bitpay/copay#7124]
Translated from a paper wallet bitcoin, which has not had a transaction from July 2017, however, the BCH shows a zero balance. How to be now? Transferred through the scan private key.

**Comment by Jacobbubble** [comment]
Just a guess, but I think Copay may have "sweeped" the wallet instead of "imported".
"Translated" isn't a thing.

If that's true, your BCH would still be on the private key you scanned off the paper wallet. Just use Copay's recovery tool with your paper wallet https://bitpay.github.io/copay-recovery/.

Select bch/livenet, and put in the details.

**Comment by levmuza** [comment]
Thanks for the reply... does this Mean that all means to return to a paper wallet?

**Comment by levmuza** [comment]
That is, I want to understand: is it possible with this tool to return back to a paper wallet of all funds?

**Comment by JDonadio** [comment]
Hi @levmuza, as @Jacobbubble said we have only a sweep process (not import) for paper wallets. You must find a software that support that process to claim your BCH.
