### ISSUE TITLE
Same wallet, different derivation strategy

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#7125]
I have a 2 of 2 wallet, one using a normal mnemonic setup, one using a trezor.

The same wallet is labeled as having different derivation strategies. In Bitpay, the wallet says it's using BIP44, but in Copay the same wallet (with a hardware key) is labeled as using BIP48.

This interferes with the automatic Bitcoin Cash sync. I can get the bitcoin cash wallet with the mnemonic setup into both Bitpay and Copay by exporting from Bitpay and importing into Copay, but I cannot spend the bitcoin cash because the wallet that's connected to the hardware wallet is listed under "Non eligible BTC wallets".

Furthermore, I cannot use the recommended recovery tool because hardware wallets are not supported.
<img width="806" alt="screen shot 2017-11-12 at 01 46 20" src="https://user-images.githubusercontent.com/6015223/32697737-1a7a2198-c74c-11e7-8232-b60cb4fdd5c1.png">

**Comment by Jacobbubble** [comment]
@matiu Do you know where I can look to try to solve this? 

The issue that I see even if I fixed this manually is that it doesn't look easy to restore the wallet I have in copay onto a different version of copay since I don't have the shared wallet url to originally establish a connection between the two multisig parties/wallets.

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.
