### ISSUE TITLE
Retrieve Bitcoin Gold from multisig wallet

### ISSUE THREAD

**Issue by insanely-raw** [bitpay/copay#7140]
For users with a mutlisig wallet in Copay, how do we retrieve our Bitcoin Gold?

**Comment by Gamboster** [comment]
Hello @insanely-raw 
At the moment there is no way to claim Bitcoin Gold. In the next release of Copay, we will enable a way to obtain the xPriv key. Then, you can import it into a wallet that allows you to see your Bitcoin Gold

**Comment by insanely-raw** [comment]
Yes, but my question was about multi-signature wallets. Or am I missing something?

**Comment by morrisonbrett** [comment]
Will you incorporate the claiming into the [recovery tool](https://bitpay.github.io/copay-recovery/) as well?

**Comment by JDonadio** [comment]
It is already merged in the recovery tool. Ensure to select `btg/livenet` as main chain before the scan.

**Comment by martyzigman** [comment]
GREAT NEWS!  I was able to load Bitcoin Gold from my Copay / MultiSig Wallet pretty easy.  Here is what I did:

1) After emptying all my bitcoin to another wallet, I then felt safe to proceed.
2) I downloaded Version 3.2.1 of ElectrumG from here: https://bitcoingold.org/electrumg/
3) I created a new Mult-Sig wallet.  In my case, it was 2 of 3 signatures.
4) I shared that I had my own seeds so that it would prompt me for more information.
5) I copied my 12-word phrase and went options to indicate BIP39
6) When the tool prompted me, I manually changed the BTG derivation path to M/44'/0'/0'
7) Repeat this process for the other two signatures (supply the 12-word phrase).
8) The wallet needed to be encrypted with a new password.  Standard practice.

Within 5 minutes of the scan, all the Bitcoin Gold was there.  I was able to successfully sign a transaction in ElectrumG and transmit.  

I followed a very similar practice to extract all the Bitcoin SV from the same wallet.
