### ISSUE TITLE
Recovery of BCH sent to BTC wallet - recovery tool not responding

### ISSUE THREAD

**Issue by aslakandersen** [bitpay/copay#7151]
Hi,

I have sent an amount of Bitcoin cash to my Bitcoin wallet from kraken by mistake.
Recovery tool that is listen in FAQ is not responding after I start searching.

Transaction ID: daf226a2d294dae229902b2a81816be894e17044f5cb71f74d90e3b0d9ba2d89
Description: 1NuWRzKQsEeGmvz1DEbJe5K6YHNBZZsAbP
Can anyone help?

**Comment by aslakandersen** [comment]
Wallet iD: d57496db-a329-446c-bc4a-247b8ad2f0cb

**Comment by 010rafa** [comment]
i have the same problem

**Comment by aslakandersen** [comment]
I have tried to open a wallet in Bitcoin cash using the 12 word phrase but that is already a wallet in copay. Is it safe to delete bitcoin wallet and then import it into a bitcoin cash wallet? Will i lose the history by deleting? Please advise

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

**Comment by aslakandersen** [comment]
Thanks  @JDonadio, but I have followed this process as indicated in the title and its not working, maybe I'm doing something wrong.
Should i first delete the wallet to make it work?

![skjermbilde1](https://user-images.githubusercontent.com/33651655/32791090-719aa842-c960-11e7-86ea-c60c9bbc7169.JPG)

I am certain the password phrase is correct, the rest is left as is, but nothing happens. What is wrong here? My input or the preparation?

**Comment by aslakandersen** [comment]
@JDonadio I have sent the bitcoin cash after restoring it. thanks for the help. onto the new challenge :)
https://bch-insight.bitpay.com/tx/68a90858b2a8ba3e8e19864aec3c406eac7eabeb52d4cd72d91a3610c4409609

It wont confirm, and I guess that is because of the 0.01446407 which were bitcoin but that is now sent to another wallet. 

What is happening?

**Comment by JDonadio** [comment]
Unfortunately not, was designed to `recover and move all your funds`

**Comment by aslakandersen** [comment]
@JDonadio ok, I dont understand why that amount showed up because I transferred them out of that address two days ago. 
what should I do to move forward then to get the BCH to be available again?

**Comment by 010rafa** [comment]
Are the recovey phrase the 12 words ? Cause it doesnt  work ?




Op di 14 nov. 2017 om 20:41 schreef aslakandersen <notifications@github.com>

**Comment by aslakandersen** [comment]
@010rafa It worked, but now I got a "false" amount of bitcoin from that adress which i moved to another wallet, probably because that transaction for some reason had 1 confirmation

**Comment by Panther992** [comment]
Do you need to recover lost cryptocurrency [Bitcoins, Ethereum, etc]? contact support@blackwebs.org or (508)556-9312 to help you recover all . I almost committed suicide when I lost about $370,000 to some hypnotic scammers. They helped me to recovered every cents. Tell him you're from Ella at Federal Naval Credit.

**Comment by davidoles1905** [comment]
Do you need help on how to recover your stolen or lost bitcoins from an investment scammer or merchant. Kindly reach out to W E B H U B G H O S T via  G M A I L C OM. Get the peace of mind you deserve

**Comment by davidoles1905** [comment]
I lost a great deal of investement in bitcoin a few weeks back when I was trying to take a bold step in the bitcon market. I was partnering witha poopular bitcoin investement website who have been able to convince me through third parties. at first didnt think there was something to worry about as my first $100 investement made me $150 within 24hours. To me that was very impresssive and I then when ahead to invest 2BTC which was about $23,600 at the time. One thin I learn it that I didnt lose my money due to bitcoin volatility< I lost it becaus eof some unscrupulous  element across the internet that targeted a single mother like me, for their personal gain. Thanks to my friend who recommended the services of a Data retriever hacker who could recover lost/sent bitcoin using advanced methods which I can testify to based on first hand experience. If there is anyone out tere in a similar situation and wants a fast solutuon then contact emai ...  WEBHUBGHOST  @ gmail com 
Thank me later
