### ISSUE TITLE
Bitcoin Cash - Multi Sig Issue with Ledger Nano/Copay

### ISSUE THREAD

**Issue by blockpool** [bitpay/copay#7179]
We have a 3 of 3 multi sig wallet and have a BCH balance that needs to be moved out of the Copay wallet. 2 of the 3 users can sign the transaction but the 3rd had imported the wallet into a ledger nano. He cannot now see the transaction to sign because of a BIP issue between Ledger and Copay. Is there any solution to this? @JDonadio

**Comment by blockpool** [comment]
On a separate note, can a multi-sig cosigner remove themselves voluntarily from a multi-sign wallet? Above issue is still unresolved btw

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.
