### ISSUE TITLE
Co-Pay Wallet said receiving funds yesterday and now nothing is there on the receivers end.  

### ISSUE THREAD

**Issue by david2254** [bitpay/copay#7189]
My friend opened a wallet the other day. I sent him 0.250885 BTC. The funds left my wallet and it showed up on his end as receiving (but unconfirmed). The next day it shows none of the funds or transaction history on his end. 

The transaction history does not show on my end either. 

My friend did receive an email of "received funds" in the above amount from Co-pay. 

From what I understand the funds are in neither of our wallets as well as no record. Please advise.

**Comment by david2254** [comment]
As well: When I click on the transaction to track it on Insight the top of the screen simply says "transaction not found". Very lost right now.

**Comment by matiu** [comment]
Are the funds back to your balance? If not, can you send me one of your wallet addresses to matias@bitpay.com so we can investigate further?

thanks.

**Comment by david2254** [comment]
Hey Matiu I received a random amount back to my wallet (not from any specific address, also does not show up in my transactions) not matching nearly the full amount of  0.250885 BTC. At a minimum its about 400 - 500$ off at this point.

**Comment by matiu** [comment]
Sorry, I dont understand the issue. What you mean be "I received a random amount back to my wallet "

Also "At a minimum its about 400 - 500$ off at this point." $ equivalence change as bitcoin price varies, you should check the BTC amount only.

**Comment by david2254** [comment]
Hi Matias,

Thank you for reaching out. I was trying to explain to you I received back
a amount when I wrote you of exactly 0.2 BTC.

The 0.2 that came in after the lost transaction we are discussing, it did
not have a sender or show up in my transaction history. I simply open my
wallet and that amount was just there.

I figured it was PART of the overall amount of 0.250885.

**Comment by david2254** [comment]
Listen essentially there is 0.5 Bitcoin that was hacked from me. Are you
going to be able to fix this or can I please let everyone know to stop
using co pay immediately. I don't want to see more people lose funds so
helplessly

**Comment by JDonadio** [comment]
Did you provide the info what matiu request you?

**Comment by david2254** [comment]
Several times.

**Comment by david2254** [comment]
Is there anything being done. I have sent Matiu countless emails detailing the information over and over again and eventually he has stopped responding to me. Please help fix co-pay so others don't get hacked out of there money. 
please advise.

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
Any solutions??

**Comment by david2254** [comment]
Still no word. A HACK ON COPAY IT MUST HAVE BEEN!

You guys are the laziest developers and you should not have a platform or product that simply steals money. Shame on you guys. I will do everything in my power to make sure CO PAY and BITPAY fail in a terribe way. It is what you guys deserve after this awful fiasco.

**Comment by david2254** [comment]
Did they close my issue are you kidding me.

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
