### ISSUE TITLE
How should I reset Speding Password  on Copay app

### ISSUE THREAD

**Issue by Natsukimistu** [bitpay/copay#7218]
I forgot my spending password , How should I reset ?

I use to open app by TouchID so No problem to open app but if i want to send to BTC to other address , I set up password before , I forgot.
I would like to reset password, How should I do?

**Comment by mr10008** [comment]
Here are instructions from the support:

Since your spending password is not managed by BitPay but created and stored client-side, there is no way to reset it.

However, if you have backed up your spending password-protected wallet, you can delete it and then restore it from your backup to get access to the unencrypted funds.

You can import your wallet to another device by using the 12 word backup phrase for your wallet.

If you haven't backed up your wallet, please first go to Settings > Your Wallet Name > Backup. Be sure to write down the 12 word backup phrase and save it securely (we do not recommend emailing it to yourself unless it is encrypted).

To import the wallet on another device, you can click the + next to Wallets and then choose Import wallet. Enter the 12 word phrase and you will now have access to the wallet from both devices.

Please see the following article for steps on how to restore the wallet from a backup:

https://support.bitpay.com/hc/en-us/articles/115003028346-How-do-I-move-my-wallet-from-Copay-to-BitPay-
