### ISSUE TITLE
Your wallet is not rejestred Bitcore Wallet Service?

### ISSUE THREAD

**Issue by pawelk2** [bitpay/copay#7252]
Hello,
Today I saw in my wallet that Your wallet is not rejestred Bitcore Wallet Service.
What is going on? I have MyBitcoinZ wallet

**Comment by Teigwaren** [comment]
Hi,
same here. My BitcoinZ was not registered. I pressed the button to try to recreate it from local storage, now its empty and my passphrase is not accepted, because there is no access to the wallet on the server.
When I apparently got connection to it there was an Errormessage like "Wallet already in MyBitcoinZ".
Its still down to 0

I hope there is a solution
King regards
