### ISSUE TITLE
Segwit implementation

### ISSUE THREAD

**Issue by Schknheit** [bitpay/copay#7288]
Why its taking so long to implement segwit? Theres a really need to charge for 220sat/b while the mempool is confirming easily 151-160? (https://bitcoinfees.earn.com/). And why the payment system uses a default 200sat/b fee or even 220sat/b? I would love to hear the explanation.

**Comment by junderw** [comment]
Copay and Bitpay wallets are estimating higher than all other wallets because their fee estimation backend is based on an old version of Bitcoin that can not see witness data for segwit transactions... due to this, all segwit transactions look like they are paying over 60% more fees per byte than they actually are... since the old Bitcoin Core fee estimations were completely based on fees in the past blocks, this exacerbates the problem.

They could lower fees by 45% by just swapping their backend for a version of Bitcoin Core that understands segwit witness data.

They could lower fees by another 40-60% by implementing Segwit.

They could lower fees by another 30-40% by using estimatesmartfee instead of estimatefee from Bitcoin Core.

Copay is unusable without setting custom fees manually by looking at another website for fee estimates.

**Comment by Schknheit** [comment]
Nice to see an answer and finally understanding the point. So they are waiting Core to implement segwit and then implement in bitpay wallet?

**Comment by dabura667** [comment]
Nope.

Bitcoin Core has already implemented and released everything.

Just need to wait for Bitpay to swap everything out.

**Comment by Schknheit** [comment]
Why don't they do it already then? I mean, I read their milestone to v3.0.0 and theres no Segwit implementation there. About core, yes, they havent implemented a ui for it yet(?).

**Comment by dabura667** [comment]
Copay doesn’t use Core for wallet functions.

I am talking about verifying segwit transactions properly. That has been in Core since a looooong time ago.

**Comment by Schknheit** [comment]
I'm not understanding anymore. But back to my main point which was explained by @junderw, why don't they just implement segwit in Bitpay? I mean, the fees are ridiculous.

**Comment by Schknheit** [comment]
Good to see their complete silence. Horrible service, hope your BCash bandwagon die soon. Nice move Shitpay, good luck in the long run, fuckers.

**Comment by JDonadio** [comment]
Follow https://github.com/bitpay/copay/issues/4020
