### ISSUE TITLE
Insufficient Funds for Fee, preventing me from moving my money

### ISSUE THREAD

**Issue by JacobHeymann** [bitpay/copay#7302]
I posted yesterday and the post was closed after someone said
"You can set a custom fee tapping on the fee option at confirming time.
https://github.com/bitpay/copay/wiki/COPAY---FAQ 
which doesnt help, as any fee amount 10-300 sat/byte gives the same error. I have $85 of bitcoin on bitpay, and am furious that the only option I have on this app is to purchase more. I can't sell, send, or pay my bitcoin, it is stuck. What do I do, and who do I need to talk to to fix this app right now?

**Comment by JacobHeymann** [comment]
Update:

In order to sell or send, you have to leave an amount in bitpay to pay for the fee, which changes by the amount being moved. I had to sacrifice $10 or so in order for the money I needed to go through, but it did go through. Issue, cleared, just poor UI and high fees.

**Comment by JDonadio** [comment]
That's because you have a lot of small inputs, and if you check the info in the FAQ section you know what is going on. Try using the send max option, in the amount page tap the menu (3 dots at top-right) and select the send max option. If that option don't help you, I'm afraid your funds are not available to spend because it is not economical viable.
