### ISSUE TITLE
Money lost

### ISSUE THREAD

**Issue by Lexi27** [bitpay/copay#7307]
I got a new phone and put in the recovery phrase and there was a red error saying that it could not recreate it. I checked everything, tried recreated it many times and it would not work. So I went to my old phone and clicked on 'Personal wallet' and it said This wallet is not registered ... tap to recreate. So I taped it and all the money was gone. I am now able to recreate the wallet on the new phone but both phones say that I have 0 BTZ in them. How do I get the fund back?

**Comment by avibrazil** [comment]
Can you see the list of transactions and the specific transactions that show the money leaving your wallet ?

If you can’t see this, it means it’s not your wallet.

Try to IMPORT a wallet instead of CREATING.

There are 3 things that define an HD wallet:
ⓐ the phrase
ⓑ the phrase password, or the absence of a password
ⓒ the derivation path, which is usually m/44'/0'/0' or m/44'/0'/1'

Make sure you are importing an existing wallet with these 3 pieces of information. A phrase with password gives you one HD wallet while the same phrase without a password or with another password gives you a valid different wallet.

Having said that, it doesn’t look like you’ve lost your money. Just keep trying different combinations. Good luck

**Comment by Lexi27** [comment]
There are no transactions of it leaving. It seems like it copied over my wallet with a new one. 
I have tried importing a wallet and creating one. 
Now, it works, I can import my wallet but the wallet is empty. It is the phrase without a password. 
Thanks for the help.

**Comment by Lexi27** [comment]
When I import my wallet again, it says your wallet is already installed, and it has nothing in it.

**Comment by avibrazil** [comment]
Lexi, I’m sensible to kind of user problems.

I can provide offline help (phone, chat etc) if you promise to write here what was the outcome and what you did to fix it, so other users can learn.

If you want this, contact me on avibrazil at GMail or chat here: https://chat.whatsapp.com/IKrUJ4syFyh5R2GGwHaDeM

**Comment by gabrielbazan7** [comment]
BTCZ is not supported by Copay or BitPay. Check this: https://github.com/bitcoinz-pod/bitcoinz-wallet/releases or https://play.google.com/store/apps/details?id=com.btczcom.btcz
Post your issues here: https://github.com/bitcoinz-pod/bitcoinz-wallet/issues
