### ISSUE TITLE
seed phrase in Italian

### ISSUE THREAD

**Issue by lucadgtrip** [bitpay/copay#7367]
I don't seem to find a way to use the 12 words in italian I got from Copay to restore the private keys on another wallet.
Are these not supported other than on copay?

**Comment by JDonadio** [comment]
You have to find another software that support BIP39

**Comment by oliverlag** [comment]
Hi! 
actually my copay wallet is in italian and my passphrase was in italian too. 
I tried different (most popular btc wallet that support bip39) in the google store but I wasn't able to restore the wallet using my passphrase.  All the wallet were considering only english words in my passphrase. 
Btw I was able to restore my wallet on a different smartphone and with copay. 
Just for testing I setup my copay in Eng, I created a new wallet, set up a new passphrase (this time was in ENG) and I tried to restore the wall with one of the previous btc wallet I found in the store.. this time it was working fine. 
I guess the problem is only with the Italian language of the passphrase. Can you investigate on this? 

Thanks

**Comment by oliverlag** [comment]
Hi.. no update on this?
Thanks
