### ISSUE TITLE
Connection with Coinbase doesn't show in Copay

### ISSUE THREAD

**Issue by Dutchie86** [bitpay/copay#7370]
I have a Copay app and a Coinbase account and app. I have connected my Copay app to Coinbase through the regular steps. I got to a screen where I could authorize Copay to acces my Coinbase account. On that page it says that after the authorization I wil get redirected to copay://coinbase. So I fill in the page, type in a 2 step verification code I got texted to me and click on the blue button 'Authorize'. I almost instantly get an e-mail from Coinbase that the Copay app is connected to my Coinbase account. However,  I don't get redirected to copay://coinbase. 

When I check my Copay app it doesn't show any connection to Coinbase. Like before, I get to a screen with 3 options: 1. Connect Coinbase account. 2. Sign up for Coinbase. 3. Enter code (right top corner). Since I have already signed up and thought I had connected (I got the e-mail!) I choose 'Enter code'. It says Enter OAuth Code. But I have no clue what code to enter?! Is this a code I should get if I would have gotten redirected to copay://coinbase after the authorization. Or should I enter another code?

Can someone help me? 

I use a Samsung Galaxy A3 2016 and never changed the basic settings of my phone.

**Comment by birdhunter51** [comment]
I have the same problem exactly.  Samsung Note 4 T-mobile

**Comment by cmgustavo** [comment]
Hi @Dutchie86 , thanks for reporting your issue as well detailed. Unfortunately, it 's a known issue for some Android version and devices, that could not handle a custom URL scheme (like `copay://coinbase`) as expected. After Coinbase authorize to Copay to access your account, the website (coinbase.com) tries to redirect to Copay with this URL: `copay://coinbase?code=xxx` where code is the **OAuth Code** required by Copay in order to establish the connection.

Please, check this workaround that I hope it helps: https://github.com/bitpay/copay/issues/6396#issuecomment-330036165
or 
https://github.com/bitpay/copay/issues/5891#issuecomment-297076251

**Comment by jaminroe** [comment]
Same here. Brand New account and install on my Galaxy S8 with Android 7.0

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
