### ISSUE TITLE
Unconfirmed transaction afters 12hours what to do ?

### ISSUE THREAD

**Issue by Martin1970nl** [bitpay/copay#7380]
Hi..

I have a Unconfirmed transaction after 12 hours of waiting.. when i push the button view the blockchain
It say the transaction is not found.. 

How is it possible and what can i do about it..

Greats and thanks martin

**Comment by AleSmaz** [comment]
I have the same problem

**Comment by Ashotsochi** [comment]
тоже самое

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.

**Comment by AleSmaz** [comment]
the problem is that it continually tries to send the btc but it is not
successful and I do not have my btc available. can you stop?

Il 08 Dic 2017 14:32, "Javier Donadío" <notifications@github.com> ha
scritto:

You can open the view, copy the url (before the insight page did load
completely) and use the transaction id in any other block explorer to check
their status. Sorry about that, we must fix our public insight to show the
transactions properly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7380#issuecomment-350263831>, or mute
the thread
