### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kenysha25** [bitpay/copay#7391]
http://prntscr.com/hkly7j When i have click on green area i get this http://prntscr.com/hklyes Is this a bug or something I do not know about?

**Comment by Kenysha25** [comment]
helloooooo

**Comment by BGalliotti** [comment]
Hello,

The error you are experiencing has been fixed in an updated version of the BitPay wallet. 

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**

Once you've updated the app, please follow the instructions in [this help article](https://support.bitpay.com/hc/en-us/articles/115005559826) to pay a BitPay invoice.

Thanks for reaching out!
