### ISSUE TITLE
Transferring of bitcoin

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#7415]
Can I transfer the amount of Btc I have in copay into other wallet ? Is it safe to do now ?

**Comment by JDonadio** [comment]
I don't understand your question

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by QuestBit** [comment]
I mean can I transfer the bitcoin that I have from copay wallet to another wallet ? BecAuse earlier round when I transfer out, the transaction was not found.

**Comment by QuestBit** [comment]
Earlier I had the issue of transaction not found when I sent out 2 bitcoin. Now can I send out bitcoin from copay wallet ? Is the issue has been rectified ?

**Comment by QuestBit** [comment]
Hi there. Can anyone reply ?

**Comment by carlosgfranco** [comment]
hi questbit, was your issue solved? it's happening to many people. See https://github.com/bitpay/copay/issues/7807

**Comment by QuestBit** [comment]
I can see the transaction now. But the recipient has not received the bitcoin sent from copay wallet. Still waiting

**Comment by carlosgfranco** [comment]
can you share the TX ID? perhaps it doesn't have enough confirmations (requires minimum 6 for it to commit in the network)

**Comment by QuestBit** [comment]
https://insight.bitpay.com/tx/4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080

It’s been a month now. There’s confirmation but the bitcoin has not transferred to the recipient. First time we are facing this issue. I’ve contacted blockchain support as well yesterday. Waiting for their reply.

**Comment by carlosgfranco** [comment]
@QuestBit mmm, 7545 confirmations, indeed. Checking the tree chart, those 2BTC have jumped a few addresses (https://blockchain.info/tree/306381779). I hope the funds didn't go to an incorrect address

**Comment by QuestBit** [comment]
That’s the thing I don’t get it. It has confirmations. The address is correct. The funny thing is the bitcoin was not received by the recipient. It’s all started when there was an error saying transaction not found. Sigh.

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
