### ISSUE TITLE
Ledger Hardware Wallets

### ISSUE THREAD

**Issue by enigma0x7** [bitpay/copay#7421]
Is there a reason that ledger hardware wallet is not going to be an option in the apps besides the discontinued chrome app.

I would really love the ability to use Copay from my cellphone (Untrusted Device) and sign the transaction with my Ledger (Trusted Device) by connecting it to my phones USB port. This way I can send funds to the exchanges securely when I am not at home and do not have to rely on a 3rd party person to sign off.

Copay seems like a useful tool but is limited without hardware wallet integration. I just can't see myself using it with this limitation.

**Comment by JDonadio** [comment]
We are not planing to support HW for now. Please check this out: https://blog.bitpay.com/copay-chrome-end/

**Comment by arnuschky** [comment]
Would you mind elaborating a bit on the reasoning behind this decision? Is this due to a major technical limitation? Support load? Dev effort?

Is there any plan to cooperate with Ledger to get this working again? Can we somehow help?

We're depending on Copay's integration as it's the only way to use multi-sig with Ledger wallets. 
(Admittedly, not really your problem but Ledgers.)

**Comment by skddc** [comment]
> Would you mind elaborating a bit on the reasoning behind this decision? Is this due to a major technical limitation? Support load? Dev effort?

Same question here, and actually this issue was opened for that exact question:

> Is there a reason that ledger hardware wallet is not going to be an option in the apps besides the discontinued chrome app.

Seems like I'm not the only one wondering why it would only work in the Chrome app, when Trezor wallet itself e.g. works on the same bitcore stack, from a normal browser app. Is there a reason Trezor bridge/connect can't be implemented for the desktop versions?

I guess Android would require a Cordova plugin for USB Host access and more custom code. Possible, but probably more work than just using what's in the Chrome app and changing it to use Trezor bridge I would guess.

As there are so many open issues being opened about this feature, why not keep one of those and add information about where a potential contributor could start with this? I can't believe secure wallet support is an unwanted feature per se, but maybe I'm missing something here.
