### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by nicomaza005** [bitpay/copay#7437]
Hola, send a transaction and says "sending" when I want to see the string of blocks says "Transaction not found" lost my btc or what?

https://insight.bitpay.com/tx/d9e0df6637dc0502d3076d3ad3ba7e5db803162434d289d40c2ebdef1eaaff9f

Thanks

**Comment by carlosgfranco** [comment]
hi nicomaza005, was you issue solved? Same thing happened to us: https://github.com/bitpay/copay/issues/7807

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.

**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.

Thanks.
