### ISSUE TITLE
iphone copay, cannot set BTC unit to bits

### ISSUE THREAD

**Issue by Sipke82** [bitpay/copay#7449]
Hi,

Using copay on a iphone7 , i cannot set the BTC unit to bits.

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by Gamboster** [comment]
Please, do not send your funds as indicated by @inlerfect . He is a scammer taking advantage of the situation. Copay developers will never ask you to send your funds in that way.

**Comment by JDonadio** [comment]
The unit `bits` was removed, only BTC is available.
