### ISSUE TITLE
iphone notifications do not work

### ISSUE THREAD

**Issue by Sipke82** [bitpay/copay#7451]
Hi,

Using copay on a iphone 7 with iOS 11, notifications of do NOT work.

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.
