### ISSUE TITLE
The amount was not received from the exchange to the cold wallet

### ISSUE THREAD

**Issue by Mikle10** [bitpay/copay#7462]
Hello!
The last transaction was not received from the exchange.
The wallet address is correct.
amount 3680.00000000	
fee 0.30000000	
net amont 3679.70000000	Complete		
Txid: 081ee5a8acf6fd370c0b229d4d5affd749ec0f556a3740f81329597def43455f	
wallet: t1emdzciNFoWpAH7mojEkfWSciTNQN49bvn
Please advise

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by Gamboster** [comment]
Please, do not send your funds as indicated by @inlerfect . He is a scammer taking advantage of the situation. Copay developers will never ask you to send your funds in that way.
