### ISSUE TITLE
Can't send money - the app doesn't accept a custom fee that I have set.

### ISSUE THREAD

**Issue by patrykzz** [bitpay/copay#7483]
As in the title.
I used the windows app (both copay and bitpay) as some people here advised me to. I currently have 0.00055 BTC (around 9$) and I wanted to send that amount but the app does not let me to send it with my custom fee. Any fee amount I set that is less than the 'super economy' option does not work. Correct me if I'm wrong, but if I have $9 and a fee of 100satoshis/b costs around $4,8 in bitcoin then shouldn't it be possible to send it? (No fee works, not 1s/b, not 250s/b)
![bez tytulu](https://user-images.githubusercontent.com/1649516/34009658-0764b19a-e10a-11e7-9350-266d342c7f0d.png)

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
