### ISSUE TITLE
False reception

### ISSUE THREAD

**Issue by Doublef1000** [bitpay/copay#7485]
Hi today i sent 100 usd and 1776 tethers to my copay wallet and it only received 0.05 and 0.09 usd can someone please help me

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
