### ISSUE TITLE
 Btc sent without commission

### ISSUE THREAD

**Issue by LitionGeek** [bitpay/copay#7489]
Hello, i From Argentina. I hope this goes here.. 
Yesterday I sent Btc to my Bittrex and Poloniex account, I'm new to this, and I did not have much btc, which I put very low commission, now I'm worried, that this will not arrive. A bittrex arrived but it is in confirmation. I really do not know what to do, I do not think you can cancel the shipment. Or could the sent thing arrive later? Regards... Sorry my english is not very good, I am using a translator... Wallet(Copay)

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by Gamboster** [comment]
Hola @LitionGeek actualmente la red de bitcoin se encuentra congestionada, por lo que enviar transacciones con poco fee puede ocasionar que se demore días en confirmar, o incluso que se caigan de la mempool. Si una transacción tiene un fee muy bajo y no es confirmado nunca, usualmente suele caerse a las 2 semanas desde la creación. Si esto sucede los fondos deberían volver a estar disponibles en tu wallet.
Recomendamos usar los fee sugeridos por la wallet para enviar fondos con relativa urgencia.
