### ISSUE TITLE
I have 120 dollars stuck

### ISSUE THREAD

**Issue by LMSVieira** [bitpay/copay#7495]
Insufficient funds for transaction with 120 dollars in wallet for 3 weeks even with custom satoshi setting even if i try 1 sat/byte

**Comment by militant13** [comment]
Bitpay is a scam I’m convinced never had a problem until them

**Comment by LMSVieira** [comment]
What to do?

**Comment by militant13** [comment]
Email them hope they notice

**Comment by militant13** [comment]
I filed complaints against them you should as well

**Comment by militant13** [comment]
I sent transaction with 30% in fees it’s not even showing up on Blockchain but the wallet claims it sent

**Comment by militant13** [comment]
BITPAY is really bullshit

**Comment by patrykzz** [comment]
I have the exact same problem. I hope someone will finally sue their asses for what they are doing right now. No custom fee works.

**Comment by LMSVieira** [comment]
Bullshit i say also

**Comment by militant13** [comment]
Bitpay is scamming please report to better business bureau as they already have investigation open on them

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
