### ISSUE TITLE
BTC to BCH didn’t work

### ISSUE THREAD

**Issue by jpgemini87** [bitpay/copay#7497]
Hey guys, i followed the steps, backed up wallet, exported and imported wallet into BTC through an exodus address change but i don’t see any BCH, it’s been about 24hrs 

Any help please? Thank you

**Comment by Gamboster** [comment]
Are you sure you had BTC (in that wallet that you are importing) pre hardfork from 1st of August?

If what you did was import a BTC wallet, which had funds before August 1, then you should have your BCHs. Please go to: Settings -> Bitcoin Cash -> Duplicate for BCH

**Comment by JDonadio** [comment]
If you have your original wallet in copay, go to settings > bitcoin cash > duplicate (see if it has balance). If your wallet is old (marked as Non BIP44) you'll need to use the recovery tool in order to scan your wallet. Set the main chain as `bch/livenet` and fill the rest of fields.

https://bitpay.github.io/copay-recovery/
