### ISSUE TITLE
Sent transaction show up then disappear back and forth

### ISSUE THREAD

**Issue by telexqwerty** [bitpay/copay#7498]
I made a transaction.
Then it show up as “sending a few second ago”
Then later I go back and check, I don’t see the transation anymore.
Then a little later I see it show up as “sending a few second ago”.
And my balance is not stable. It keeps changing back and forth!!!
Is there any current issue with the Copay app?
Is there any way to fix it?

**Comment by telexqwerty** [comment]
I believe it’s going around in Copay server and has never been sent out to the network. It’s been 2 days already. Why is that?
I use the receiver address to check on blockchain, no tx yet.

**Comment by bearwhalebandit** [comment]
Many people have the same issue and copay is s the staying silent. I lost a 1000 dollars this way support ticket still unanswered from a week ago

**Comment by omietrice** [comment]
Yep me too, I posted on Reddit and got marked as trolling to the bottom of the list..

**Comment by bearwhalebandit** [comment]
Hi can you post the link to Bitcoin talk? Also maybe you can link my thread as well

**Comment by telexqwerty** [comment]
Here is my thread on Bitcointalk

https://bitcointalk.org/index.php?topic=2592780.0

**Comment by telexqwerty** [comment]
Could you please also link your thread? Hopefully we can have more people seeing the issue and they have a way to fix it.

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by luckykcc17** [comment]
I sent a little bit of btc this morning, transaction showed up in recent history and now record is gone, along with my bitcoin. Balance is zero wtih no record of transaction. I do have the Bitpay email confirming that transaction was sent.....please see attachment. WHAT IS GOING ON [HERE? 
![bitpay - sent transaction - 12 21 17](https://user-images.githubusercontent.com/34752144/34271841-03f419c2-e65c-11e7-8558-7589a01c3742.jpg)

**Comment by rosdi** [comment]
@luckykcc17 , BTC transaction fees are sky high at the moment... DO NOT send small payments (less than 0.1 btc).. otherwise most of those bitcoins will be absorbed by miners as transfer fees.

Even 0.01 btc is not worth to be transferred at the moment.

**Comment by luckykcc17** [comment]
Thank you Rosdi....it is happening again with a legit transaction. Sent $58 USD with an $11 USD fee and doing **exactly** what the author of this this thread stated. Doesn't even show up on blockchain, which means only one thing....that Bitpay has not even broadcasted the transaction and so they have out bitcoins, which is such crap.

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
Does anyone has an answer of what's going on?

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
