### ISSUE TITLE
Bitcoin shipping and disappeared blockchain transaction and bitcoin

### ISSUE THREAD

**Issue by juanote81** [bitpay/copay#7502]
Today I transferred 157 dollars in bitcoin and there was never confirmation now it says in copay sending but I check in blockchain and it tells me transaction not found

**Comment by militant13** [comment]
Bitpay is doing the same for me I’ve been waiting for almost 2 weeks not even a reply from support

**Comment by omietrice** [comment]
Yeah they aren't answering.

**Comment by juanote81** [comment]
Transaction TX f8d1d4fb024db780d4228ff077592fb692bb77308a4aa91b43d0092c3a6ed4f6

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
