### ISSUE TITLE
Payment Round Trip

### ISSUE THREAD

**Issue by aodunaiy** [bitpay/copay#7507]
I inadvertently sent a payment to the originating wallet address.

After 24hrs, the transaction is invalid (when viewed on the blockchain), yet my payment is pending from my wallet. When will it revert to cancelled?

The problem is that all other held coins on the same block (within my wallet) are now not available for use. Please help.

**Comment by aodunaiy** [comment]
Can I have an update on this please?

**Comment by aodunaiy** [comment]
Now quite worrying, as the round trip transaction has disappeared from my wallet transaction list, yet I have some bitcoins that remains inaccessible.

Is there a copay support team that one can actually reach?

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by aodunaiy** [comment]
Is this for real? Months after the problem...

My only recommendation to anyone reading this is to avoid bitpay /copay 
like the plague.

On 23 April 2018 3:13:18 pm BGalliotti <notifications@github.com> wrote:
Hello,
Are you still experiencing this issue?
We look forward to hearing from you.
Regards—

**Comment by BGalliotti** [comment]
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.

We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
