### ISSUE TITLE
Recovery phrase doesn't work

### ISSUE THREAD

**Issue by Tomic18** [bitpay/copay#7513]
I have my 12 word recovery phrase and it says that the phrase is invalid

**Comment by interfect** [comment]
The last word in the phrase serves as a sort of checksum, I believe, so that mistakes in copying or entering the word list can be detected. It sounds like such a mistake has occurred: either when typing the words in you replaced a word with a similar word, or when writing the words down initially they were not transcribed correctly.

The easiest thing to do is to try again and double check your typing.

If that fails, look at the word list at https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt and see if any of the words you have written down isn't on the list, or could have been a mistake when the correct word was another similar word on the list.

If you don't see anything obvious, it is possible I believe to brute force all single word changes in your seed to try and recover the correct key. You need special software for this.

Unfortunately if you do not have a correct 12-word recovery phrase and you do not have a working wallet with the coins in it, the coins are lost forever.

**Comment by gabrielbazan7** [comment]
Check if all the words are in this list https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by DevilishBooster** [comment]
I am also having this issue. I think I first set up my wallet back in June of this year, and I wrote down the recovery phrase. However, looking at that link you posted, @gabrielbazan7 , the first word of my recovery phrase isn't included. Is it possible that some words were removed from the list? I didn't have that much in my wallet, but I figured I'd try recovering it anyway.

**Comment by DevilishBooster** [comment]
Nevermind. Apparently I'm an idiot and wrote the correct word... but with a couple extra letters. I have recovered my wallet now.

**Comment by korison** [comment]
@Tomic18 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
