### ISSUE TITLE
transaction must be canceled but still hangs, need help

### ISSUE THREAD

**Issue by FrankyPol** [bitpay/copay#7518]
when I try to make a money transfer, this transfer freezes, and in its place there appears another transfer which I did for a long time, but it was canceled because of the small commission of the network.
I think for some reason, the purse believes that my new transfer are old money transfer and do not want to spend them
P.S. I am making new transfer already with a large commission, but they are all canceled, and the miners do not accept them

https://blockchain.info/tx/7c504933f04a9d200cc1adc59c34ef81f8552591d7bc211967f669fd2961b789
That is my problem transaction which must be canceled after 72 hours but it continue hangs. Please help.

**Comment by militant13** [comment]
Bitpay wallet is retarded it traps your money good lol ugh a lot of us have same problem if you find solution please share

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
