### ISSUE TITLE
Copay iOS Bitcoin Cash issue

### ISSUE THREAD

**Issue by shayanb** [bitpay/copay#7523]
On my iOS Copay I have multiple Bitcoin wallets. in Settings ->Bitcoin Cash, it shows 3 wallets that are convertible to Bitcoin Cash wallets (had balance before August 2017). Now when I convert 1, the balance it shows on the main page is not the same as it shows on the setting page. Also it behaves stranger when I want to convert the second wallet, which will ask for my spending password (normal behaviour) and shows the loading popup view and then nothing. I cannot convert the second wallet to bitcoin cash. it just does not do anything.

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service. 


Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.


Thanks.
