### ISSUE TITLE
Bitcoin see transaction but not on blockkchain 

### ISSUE THREAD

**Issue by Hdd612** [bitpay/copay#7529]
Can i please get some help i sent money i can see the transaction but its nothing on the blockchain and is unconfirmed can you please just send my bitcoin back to my wallet

**Comment by Hdd612** [comment]
I been waiting for days also

**Comment by militant13** [comment]
I’ve been waiting for 2 weeeks

**Comment by Hdd612** [comment]
[](url)
![screenshot_2017-12-19-16-00-28](https://user-images.githubusercontent.com/34670952/34178673-011d0eac-e4d6-11e7-8792-ce98db7e2ae2.png)

**Comment by Hdd612** [comment]
Receives my money but i can't pay it out to my address been like this forever

**Comment by BGalliotti** [comment]
Hello,

Since the wallet is not backed up you will not be able to send bitcoins.

While backing up your wallet, do not forget to write down the 12-word recovery phrase, this is the only way to recover your wallet. Bitpay/Copay has no control over it.

We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
