### ISSUE TITLE
Transaction stuck due to low fees

### ISSUE THREAD

**Issue by Jordimr33** [bitpay/copay#7534]
I have the following transaction stuck:
https://blockchain.info/tx/ba70061c3ade76b6dc50163ee03183d29484ceb9bd770490f6cf0255f5c5b4e7

It's a transaction for 0.99 btc, but somehow it is showing as two parts, on of the 0.99, and one for 0.53 for a total of 1.52. My questions:

Can I expect it to be processed, in spite of the low fee? It's been over 3 days now.

Why is this holding 1.53 btc from my wallet, and not just 0.99?

Can I make other transactions while this resolves, or should I stay put until this money shows again on my wallet? 

I need to make an urgent payment, so all help appreciated.

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by Jordimr33** [comment]
Thank you. Any help from the copay team or anyone that has had a similar issue much appreciated.

**Comment by militant13** [comment]
Brother bitpay team is not going to help you I’ve had problem for weeks others months.. the best you can do is try to send coins once you see them back in your wallet at a higher fee and hope it gets sent

**Comment by militant13** [comment]
I feel your paid man smh I reported them to better business bureau and already got a reponse they are opening a investigation the more people that complain the more fire power they will have

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.

Since this thread did not have any responses in a while we will be closing it.

**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.
