### ISSUE TITLE
Bitcoins missing since one month

### ISSUE THREAD

**Issue by yycc6** [bitpay/copay#7535]
I send 3 bitcoins in my wallet created in Copay and then the next day my bitcoins diappear and only 0.47 Bitcoin is left in my wallet, I have contacted the support service right away, now one month has passed, several peoples answered my request with some standard responses, and my bitcoins are still missing. Is it true that copay secure our bitcoins?

**Comment by militant13** [comment]
No please report to bbb.org

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by BGalliotti** [comment]
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.

**Comment by korison** [comment]
@yycc6 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
