### ISSUE TITLE
Bitpay trying to silence me

### ISSUE THREAD

**Issue by militant13** [bitpay/copay#7544]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!

BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by dabura667** [comment]
I am not affiliated with Bitpay in any way... but Bitpay doesn't hold your bitcoins. They can't "give you your money back" since they NEVER HAD IT IN THE FIRST PLACE.

I understand it is frustrating when you lose a lot of money due to your own error... it is difficult to admit, and you want to blame someone/something else.

None of your "issues" explain anything clearly. You are just yelling and making threats. No one can help you with just "give me my money back"...

I repeat. Bitpay never held your money to begin with.

**Comment by militant13** [comment]
If you are not affiliated with bitpay or can help me or someone else with this issue eat a dick and shut the fuck up thanks.. 

Looked into it with a QR code scanner, it turns out that they write the invoice number into the OP_RETURN of the tx. Greatly increasing the tx fee 10 fold.... explain this dickhead

**Comment by militant13** [comment]
Know what you are talking about before you speak your ignorance is distasteful

**Comment by dabura667** [comment]
> they write the invoice number into the OP_RETURN of the tx

That's not how this wallet works at all.

Are you even using Copay? Are you sure you didn't get tricked into downloading some virus called Gopay or something?

**Comment by militant13** [comment]
This is BITPAY WALLET

**Comment by JDonadio** [comment]
Inappropriate language
