### ISSUE TITLE
Amount too low to spend on $22 transaction?

### ISSUE THREAD

**Issue by festivemonkey** [bitpay/copay#7557]
I transferred $22.95 of bitcoin to my BitPay wallet and I'm getting a message that says the amount is too low to spend. The transfer was made at 3pm and it's been over four hours. The transaction also has 6+ confirmations so I don't believe it is due to it not being confirmed.

Here's a screenshot of the transaction:
![img_2748](https://user-images.githubusercontent.com/34696651/34185421-2fb4ad2a-e4f3-11e7-95ce-2b763286ddf7.PNG)

Is the network fee really $22?!
I've tried many solutions online such as clearing the transaction cache and updating the app to no avail.

Any help would be amazing. Thank you in advance.

**Comment by JDonadio** [comment]
That warning is because the total amount to send (or received) is almost the same amount compared with the normal network fee policy, so it's not economically recommended. You can check the actual fees here: https://bitcoinfees.earn.com/ and set a custom value in the confirm page, taping on the fee section.
