### ISSUE TITLE
descriptiob bad request

### ISSUE THREAD

**Issue by elmero2** [bitpay/copay#7625]
hello there

i have the problem that i can not send any bits to any adress. got the  deposit 17 hours ago so it is not pending or anything like that. when i click on send the Description BADREQUEST appears and nothing else happens. why can i not send my coins and what can i do?
im using it on a windows phone

**Comment by BitMari** [comment]
Is the message Bad request could not send payment ?  I have had two seperate reports of that error. On android and on ios , whats going on?

**Comment by romul86** [comment]
Android


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: BitMari <notifications@github.com> Дата: 23.12.17  22:00  (GMT+03:00) Кому: bitpay/copay <copay@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: Re: [bitpay/copay] descriptiob bad request (#7625) 
Is the message Bad request could not send payment ?  I have had two seperate reports of that error. On android and on ios , whats going on?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitpay/copay","title":"bitpay/copay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitpay/copay"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BitMari in #7625: Is the message Bad request could not send payment ?  I have had two seperate reports of that error. On android and on ios , whats going on?"}],"action":{"name":"View Issue","url":"https://github.com/bitpay/copay/issues/7625#issuecomment-353742576"}}}

**Comment by romul86** [comment]
Hi, elermo
NO, ANDROID


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: elmero2 <notifications@github.com> Дата: 23.12.17  19:47  (GMT+03:00) Кому: bitpay/copay <copay@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [bitpay/copay] descriptiob bad request (#7625) 
hello there
i have the problem that i can not send any bits to any adress. got the  deposit 17 hours ago so it is not pending or anything like that. when i click on send the Description BADREQUEST appears and nothing else happens. why can i not send my coins and what can i do?

im using it on a windows phone

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitpay/copay","title":"bitpay/copay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitpay/copay"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"descriptiob bad request (#7625)"}],"action":{"name":"View Issue","url":"https://github.com/bitpay/copay/issues/7625"}}}

**Comment by elmero2** [comment]
im using it on my windows phone. nothing more than bad request
not could not send or anythig else

**Comment by romul86** [comment]
http://cryptofest.online/stream



Отправлено со смартфона Samsung Galaxy.

**Comment by elmero2** [comment]
How should a russian video help me bro?
 is there anxthing i can do to use my coins

**Comment by gabrielbazan7** [comment]
Hi. You still having this issue ?

**Comment by romul86** [comment]
https://blockchain.info/ru/tx/402f8c6e4497c8d8b6ffe1a735ba51d343caee4edaffe3fa41ba482922373db0



Отправлено со смартфона Samsung Galaxy.
