### ISSUE TITLE
Does the latest Copay client on Windows support sweep?

### ISSUE THREAD

**Issue by jasmreid** [bitpay/copay#7707]
It seems the latest version of the Copay wallet does not support "sweep". None of the menu items discussed in other threads here work the same in the current version (3.9.1) on Windows.
I created a new BCH Wallet in the Copay application to receive the BCH coin I have after the hard fork. I backed it up.
When I hit Send the only options are Buy Bitcoin and Show Bitcoin address.  Nowhere I could find is there an opportunity to enter a private key to get the wallet to sweep the BCH chain to find funds. Any clues??

**Comment by BGalliotti** [comment]
Hello,

The error you are experiencing has been fixed in an updated version of the BitPay wallet. 

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**

Once you've updated the app, please follow the instructions in [this help article](https://support.bitpay.com/hc/en-us/articles/115005559826) to pay a BitPay invoice.

Thanks for reaching out!
