### ISSUE TITLE
BTC sending problem

### ISSUE THREAD

**Issue by ceaoguz** [bitpay/copay#7716]
I try to send my BTC to binance but its not happened. Just write 'sending' in my wallet. The amount of fee is gone also. Anybody help me please!

**Comment by ceaoguz** [comment]
Is there any way to cancel that sending?

**Comment by luckykcc17** [comment]
I am having same issue.....sent bitcoin with Economy fee which always works fine and it is stuck in sending for about 8 hours now. When I search blockchain with sent address, no transaction shows up so this means that Bitpay has not even broadcasted the transaction.  Bitcoin amount is gone from my wallet, the transaction doesn't even show up in my history...I have to "scan for funds" in order to have it appear but it disappears again if I close Bitpay. THIS IS NOT A BITCOIN NETWORK ISSUE!!! THIS IS A BITPAY ISSUE!!!

**Comment by ceaoguz** [comment]
When i try to send with economy, i took error message. i tried so many time. The error messege like that 
'Error at confirm
Insufficient funds for fee'
Do u know how i fix that error?

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
