### ISSUE TITLE
After syncing my BCH in Copay, I see a dozen transactions in my wallet

### ISSUE THREAD

**Issue by BitcoinBarrons** [bitpay/copay#7729]
Where did my BCH come from and go to? Who would have access to my unaccesable BCH Wallet?

*** Finally, today, After syncing my BCH in Copay, I see a dozen transactions in my wallet. Why are there SO many deposits and withdraws in my BCH wallet over the 3 month period of May-July, when I haven't even had access to it until today Jan 2, 2018?

![screen shot 2018-01-02 at 4 23 25 pm](https://user-images.githubusercontent.com/33402911/34500807-48a5d376-efda-11e7-8ed6-5d0c386596f9.png)
![screen shot 2018-01-02 at 4 23 52 pm](https://user-images.githubusercontent.com/33402911/34500808-48b6c1cc-efda-11e7-8955-17473ffd07ed.png)
![screen shot 2018-01-02 at 4 24 03 pm](https://user-images.githubusercontent.com/33402911/34500809-48c544f4-efda-11e7-96d7-2a135776b8bb.png)
![screen shot 2018-01-02 at 4 24 16 pm](https://user-images.githubusercontent.com/33402911/34500810-48d0f862-efda-11e7-929c-7293d9525bcc.png)
<img width="259" alt="screen shot 2018-01-02 at 4 24 29 pm" src="https://user-images.githubusercontent.com/33402911/34500811-48e0c9b8-efda-11e7-9d05-0ad5b618c2ea.png">

**Comment by Gamboster** [comment]
Hello @BitcoinBarrons. Sorry for the delay.

The only people with access to your funds are those who have access to your private key, of which only you are responsible.

That BCH wallet from where did you import it? If it was duplicated from your BTC wallet, you will have the same pre fork transactions. Since BCH is a copy of the BTC chain until August 1, 2017
