### ISSUE TITLE
 The history of transmitting BTC has disappeared. No transactions are found either.

### ISSUE THREAD

**Issue by yuichitada** [bitpay/copay#7737]
I sent money to the address my remittee provided.

Address: 1EgACKEib1D7yaXZW4CZrb9SwmYuCwjUkQ
Amount: 0.01467 BTC
Transfer fee: 0.0001 BTC
Sent time: 01/03/2018 10:19 pm

For a while, it was displayed as being being sent in the copay history, but the history during transmission has disappeared after about 4 hours have elapsed.

It is described in the email from wallet-service@bitcore.io
Even if you check [See it the block block], no transactions are found.
URL: https://insight.bitpay.com/tx/46a58299a3d7b2a84a72370d43e4082d0954350701cd3289664326ac57c497ea

Why? Is there no way to recover it?

**Comment by luckykcc17** [comment]
Same exact issue here....

I made 2 bitcoin transactions yesterday with the economy fee...first confirm was received instantly and fully confirmed (6+) within an 40 minutes. The second transaction sent about 30 minutes later is still "sending". I received an email from Bitpay for both transactions confirming that they were sent (please see attachment) but the second one over 24 hours later has not even been broadcast to a block, as I have searched the address on numerous block search websites and the transaction doesn't exist.

WHAT IS GOING ON HERE WITH BITPAY????

The fees Bitpay charges are WAY higher then any other wallet I use, but there seems to always be an issue. My other wallets with cheaper fees have NEVER had any issues like this.

Bitpay doesn't seem to want to address any issues that users are experiencing even though they have our bitcoin somewhere in their system because they have not even broadcasted the bitcoin to be sent.

PLEASE SOMEONE EXPLAIN TO ME WHAT IS HAPPENING??
![bitpay email - wallet sent confirm](https://user-images.githubusercontent.com/34752144/34544377-fab70236-f0b3-11e7-9366-6a8ad1e59974.jpg)

**Comment by Keensyst** [comment]
Because they are a rip off

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
