### ISSUE TITLE
Bitpay/copay

### ISSUE THREAD

**Issue by jalalalami** [bitpay/copay#7785]
I bought an amazon giftcard & i recieved an error message after the took my payment so now no bitcoins & no gift card

**Comment by Gamboster** [comment]
Hello @jalalalami  Sorry for the delay and the problems related to Amazon integration.
If for some reason your Amazon Gift Card is not getting the code to redeem it, please contact to the bitpay help center: https://help.bitpay.com/requestHelp, select the BitPay payment/transaction and describe your issue providing the invoice id or transaction id for your Amazon Gift Card purchase. Also you can send an email to help@bitpay.com.

If you have a screenshot or the text of the error that you received, you could mention it to better identify.
I will close this issue since the means to solve these problems are those that I mentioned before.
