### ISSUE TITLE
"Transaction not found" (Low transaction fee)

### ISSUE THREAD

**Issue by 2pacisALIVEE** [bitpay/copay#7790]
https://insight.bitpay.com/tx/c773aa4621c58a1190902479f243e01591980cf66adccc6511aa27c8733c4313

This Scares the shit out of me, I wonder how long it might take for the transaction to get through, and if it will get through at all? Can I do something to speed up the process? (I have one week to get it through)

![fullsizerender](https://user-images.githubusercontent.com/35273402/34739215-e5ea1d8a-f57b-11e7-9d69-df9119376e40.jpg)

**Comment by 2pacisALIVEE** [comment]
Anyone know? Or did my money just disappear?

Just read a lot of people saying their money is gone?

**Comment by yasminsalim** [comment]
https://insight.bitpay.com/tx/13fb4495be34eaec6a3d21dfb82dd1579c147ec1751e39efafff1a4b3713e939

This transaction was made on 03/01/2018 from my bitpay wallet.

Until today, it's unconfirmed on blockchain.

This transaction not display on my bitpay wallet history & on bitpay insight page. (Transaction not found).

I did sent many emails to bitpay support team regarding this issue but not getting any response from them.

I want my money. Otherwise i am going to report BBB regarding this scam.

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807

**Comment by 2pacisALIVEE** [comment]
Thanks, Copay send the money back because it didn't go through! Really good service! If you have the same problem it might just take awhile for it to get through, or it will be sent back to your wallet!

Thanks for all the support!
