### ISSUE TITLE
Moved funds don't appear on wallet

### ISSUE THREAD

**Issue by VSBIT** [bitpay/copay#7799]
Transaction ID: https://insight.bitpay.com/tx/521c3c7914f4ccfa8e123b84314cb0908596b2a2accba72865bfaccad05b2f46

**Comment by yasminsalim** [comment]
https://insight.bitpay.com/tx/13fb4495be34eaec6a3d21dfb82dd1579c147ec1751e39efafff1a4b3713e939

This transaction was made on 03/01/2018 from my bitpay wallet.

Until today, it's unconfirmed on blockchain.

This transaction not display on my bitpay wallet history & on bitpay insight page. (Transaction not found).

I did sent many emails to bitpay support team regarding this issue but not getting any response from them.

I want my money. Otherwise i am going to report BBB regarding this scam.

**Comment by matt77unltd** [comment]
Honestly I can't still believe what is happening, mine too is missing a fund of $600 sent on the 24th DEC. 2017 till now is no where to be found in my wallet after displaying receiving payment for more than 2 weeks

**Comment by VSBIT** [comment]
Dear BitPay support - please help!!!

**Comment by luckykcc17** [comment]
BitPay.....you are opening new offices in San Francisco and NYC but your service is terrible. This is crazy and I do not understand how you spend money in two most expensive cities in the USA instead of hiring support.

**Comment by VSBIT** [comment]
Dear BitPay Support. - please help to resolve this situation.

**Comment by VSBIT** [comment]
Is there anybody who will help? Support simply does not answer ((
