### ISSUE TITLE
Who can help me to recover my Bitcoin?

### ISSUE THREAD

**Issue by lds2004** [bitpay/copay#7839]
I send my Bitcoin to myself Address.And the fees Is so high.Now this transaction has 1 confirm.Can I cancel this transaction？

**Comment by mr10008** [comment]
If there is already 1 confirmation it means it's getting through, more confirmations will come soon.
Not possible to cancel it.

**Comment by MSJDH2U** [comment]
I sent 50 btc never received them,sent 5000$  don't know who it went to sure not I and four other transactions never received anyone of them,two through to a server who sends direct to PayPal yet nothing and I am aa very active member in the tester groupsI have quite a built account log yet. It is steady refusing to allow any type collection to pay, I even buy USD and usdt,if it's out there I am buying imnready to withdraw through a trader institute these online guys are having a ball with the actual work we do to earn them money then so many just walk away not believing it's real because of these type issues. I even registered with social security so I could claim and report for case of being Frauded so many have went to jail from earnings and no collection yet taxes still expect to be paid on year earnings period from the agency that I watched online, just to think of going to jail over money never seen that some coin account just decides lock your money away from you still you claimed it or it would not be there,my dad needs his doctor bills paid how can I retrieve anything to help my dad survive.Better to actually get to live before he dies I work hard to earn this I need help my dad someone help me

**Comment by nics40** [comment]
Yep fucking copay stoles my bitcoin to $1000 and I tryed getting a fucking atm card now my coins is in a wAllet just sitting there and never do I gettin g answers for my lost fuck copay scam fucks

**Comment by harrisondel** [comment]
@MSJDH2U 
@nics40 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
