### ISSUE TITLE
retrait des BTC impossible

### ISSUE THREAD

**Issue by muyakaboyi** [bitpay/copay#7840]
Bonjour,

Je tente depuis des heures de transférer des BTC de mon portefeuilles copay vers binance mais riens ne fonctionne. tout est figé à la page de la confirmation du paiement alors que les frais sont vérifiés. 
le seul message qui tourne est création de la transaction mais ça ne bouge plus après. 

impossible de retirer quoi que ce soit et c'est depuis des heures et des heures

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
