### ISSUE TITLE
Disappeared coins on Copay wallet 

### ISSUE THREAD

**Issue by Afoulous84** [bitpay/copay#7869]
Hello,
I have made a transaction in my copay wallet but haven’t received the money despite that it shows the coins were sent from my wallet.

**Comment by mr10008** [comment]
Check the transaction on http://blockchain.info/

**Comment by Afoulous84** [comment]
$100 just disappeared. I haven’t received it or still in my wallet. Please help me get my money back.
Thanks

Aziz

**Comment by mr10008** [comment]
Try to restore the wallet using Mycelium wallet with the Copay seed. Then see if the transactions and balance shows up properly.

**Comment by Afoulous84** [comment]
I downloaded the new wallet but I don’t know how to do it with copay seed.
Thanks 

Aziz

**Comment by vuduy67215** [comment]
Vào 08-02-2018 0:40, "Afoulous84" <notifications@github.com> đã viết:

> I downloaded the new wallet but I don’t know how to do it with copay seed.
> Thanks
>
> Aziz
>

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
