### ISSUE TITLE
Not receive 

### ISSUE THREAD

**Issue by kirtikmavani** [bitpay/copay#7881]
Dear Sir/Mam,

I have sent BTC from Copay.io Wallet to Zebpay Wallet but accidentally i have sent BTC to my BCH Zebpay wallet address.

So requesting you to help me to retrieve the fund.

Txn Hash: d719694ff8b08f9a0aedf3f17e2d0d123754810be4ff9143bc9e98c299e94b44

Your support in this meter will highly appreciated.

Thank You.

**Comment by JDonadio** [comment]
We have no control over any wallet, because each private key is generated and stored in the device itself so we cannot make refunds or so regarding erroneous transactions.

Regarding the BTC > BCH transaction, **for Copay wallets** you can use the [recovery tool](https://bitpay.github.io/copay-recovery/) and scan your _BCH Wallet_ selecting the _btc/livenet_ chain in order to find your BTC coins in your BCH Wallet.

If your wallet doesn't belong to Copay or BitPay, you must contact to the support team and ask they how to recover that funds.

**Comment by Keensyst** [comment]
I'll help ya, we'll get yours back and 100 to boot if they piss me off

**Comment by kirtikmavani** [comment]
Dear Sir,

How can i contact to support team as i am not technical.

**Comment by JDonadio** [comment]
Open the `Zebpay wallet` website or so and try to find a contact email or link.
