### ISSUE TITLE
No wallets available to use Shapeshift...

### ISSUE THREAD

**Issue by AntonOta** [bitpay/copay#7904]
Getting this error once I click Start In the Shapeshift tab of Bitpay. What can I do to fix this?

**Comment by Gamboster** [comment]
In order to use Shapeshift, you must have created at least one BTC wallet (livenet) and one BCH wallet. The general fee configuration, in Normal.
Also, you must have sufficient funds to perform the minimum trade for Shapeshift in the wallet from which you want to make the purchase.

**Comment by Lancelight** [comment]
This is caused by ineptness on the part of Bitpay devs (including the actual design of requiring 3 tx's to fill a card:  priv wallet -> bitpay wallet -> card wallet).  Since the geniuses at BP dont know what a "Max Amount" button or "Calculate Fees" button is for,  you WILL receive this error when you try to add more BTC to a card than you actually have in the wallet due to the ABSURD fees they add to BTC transactions which causes you to put more than your wallet could support.  So rather than saying "Insufficient amount",  it will say "No wallets Available".  If you back it off by 1 penny,  you'll then be presented with "Insufficient Amount" errors until eventually you get a workable amount through TRIAL AND ERROR.

The amount of ineptness in this design and implementation is so mind boggling that I'm utterly amazed that it works at all.
