### ISSUE TITLE
Still will not send coins

### ISSUE THREAD

**Issue by bakd247** [bitpay/copay#7918]
This wallet has had way more than enough for a transaction fee and a transaction for over 6 months and no matter what I set it to...the thing will not create a transaction...claiming insufficient funds with over $50 in a single address....
wallet has no problems receiving coins...and every other wallet in the world will send coins to this wallet but this wallet will not send...

**Comment by Gamboster** [comment]
How are you wanting to send your money? The problem here is that the fees of the bitcoin network are very high these days.

What you could do is the following:
Go to Settings -> Bitcoin Network Fee Policity -> Set "Super economy" by default.

Then go to Send tab, and once on the "Enter amount" screen, click on the top right (In the 3 dots) -> Send max amount.

Maybe that way you can optimize your Tx and it works.

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
