### ISSUE TITLE
Just Lost Wallet/$76 worth of Bitcoin

### ISSUE THREAD

**Issue by kmkrause** [bitpay/copay#7933]
Hello,
I'm new to Bitcoin/Copay.  I decided to signup at coinbase  deposited $80. I read you needed a wallet. I decided on copay. Transferred the funds to my wallet. Everything processed smoothly and my copay wallet showed $76. I then went to the merchant and tried to pay. A spend password popped up. i couldn't remember the password. I may have mixed it up with my coinbase password instead.

 I then did a little digging online and read that  I could delete copay from my Android phone and reinstall it using the 12 word phrase to by pass/reset spending password.  I did that. Now if I restore using only the phrase it creates a "Personal Wallet" with no funds in it.  

 If I try and restore wallet with 12 word phrase and try and guess the recovery phrase password (Under Advanced Options) I get an error saying 
"Could not access the wallet at the server
Please Check
The password of the recovery phrase (if Set)
The derivation path
The wallet service URL
Is there any way I can recover my wallet/funds I do know the 12 word phrase. and I thought that would have all I would have needed.   

Thanks for any help fixing this.

**Comment by jidanni** [comment]
Maybe also try your 12 words in a different project's wallet?

**Comment by kmkrause** [comment]
I have, It say success but still shows "personal Wallet" with no bitcoins in it.

**Comment by jidanni** [comment]
I'm talking about e.g., https://github.com/spesmilo/electrum .

**Comment by jidanni** [comment]
Homepage: https://electrum.org/

**Comment by kmkrause** [comment]
Yes that's the one I used as well as bitpay. Putting in my 12 words only creates a empty wallet.
Thank you for your help.

**Comment by paOol** [comment]
you can investigate by going to coinbase, 
and looking up the transaction ID of the deposit into CoPay.

then check the address it was sent to (your copay address) on a blockexplorer like blockchair.com and you'll see whether the funds are there still or not.

they probably are, and I think you likely copied the 12 word phrase incorrectly or added a space or missing a character somewhere.

**Comment by kmkrause** [comment]
I don't think the 12 words are wrong. I typed it in when setting up copay on my Android phone. The next step requires you to select the words in order to proceed. Each word is correctly spelled with one space between them.  I can see my transaction ID and do have my wallet address.  I will try the website mentioned. What is put into the search bar?

When creating the copay wallet after the 12 words were giving to me I was instructed to create a password.. If I can remember that password would it keep the 12 word phrase from working?

**Comment by kmkrause** [comment]
I just put in what i think was my old wallet ID (I emailed to myself) on the above mentioned website and it shows. 
Last seen receiving: 2018-01-25 01:14
Total received: 0.00621076 BTC

**Comment by kmkrause** [comment]
When adding another wallet using the 12 words I get "wallet All Ready In Bitpay"  so it seems the 12 words work...it's just the funds that use to be on it is gone.

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
