### ISSUE TITLE
Sent BCH to wrong address 

### ISSUE THREAD

**Issue by chasemw08** [bitpay/copay#7944]
Sent BCH from coinbase to copay app BTC wallet on accident. Is there any way I can recover those funds?

**Comment by crazyjay0516** [comment]
were did u send them

**Comment by chasemw08** [comment]
To a legacy address on Copay

**Comment by nics40** [comment]
Been trying to get back my bitcoin that I sent to a wrong address and still can not get back my bitcoin copay is just holding in a wallet that will not refund me my bitcoin that was worth over $1000. Copay is a scammer

**Comment by Gamboster** [comment]
@chasemw08 
If you sent BCH by mistake to one of the addresses of your BTC wallet. What you can do is go to: Settings -> Bitcoin Cash -> Select the wallet to which you sent BCH and click on "Duplicate for BCH"

**Comment by Gamboster** [comment]
@nics40 What is the issue that you opened to report your error?
You are responsible for your funds, because no one other than you has access to your private keys. We can not take charge for an error that you commit. But as much as possible, we try to help.
If your problem was the same as the one that reported here, you can try to solve it with the my previous comment.
Please, do not generate spam in the tickets of others.

**Comment by nics40** [comment]
Then why can’t u guys reverse the transaction for me.   Its nobody’s wallet it’s in cause it’s just sitting there deducting cause the value of bitcoin.  So I going keep doing this until I get my bitcoin back. Hahahahahaha

**Comment by chasemw08** [comment]
@Gamboster thank you so very much!
