### ISSUE TITLE
No recibi gif card comprada con btc

### ISSUE THREAD

**Issue by william8411** [bitpay/copay#7947]
Saludos por favor quisiera su atención y ayuda compre una gif card y no recibí el código de la gif card pero si me descontaron el dinero de mi cuenta que debo hacer ?? donde puedo ver mi codigo de gif card? Ayudenme no quisiera perder mi dinero

**Comment by Gamboster** [comment]
Hola @william8411 Disculpa la demora. Por favor, lee este link y sigue los pasos para que Bitpay revise tu problema https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)

**Comment by 2028meme** [comment]
Buenas noches quisiera me ayudaran. Esta mañana compre una gift card de 64.20 por copay y me salía error y error y al verificar en mi mi billetera me sale descontada o sea que cobraron los bitcoin. Cómo
Haría para visualizar el código de la gift card porque no me sale por ningún lado. Gracias

**Comment by cmgustavo** [comment]
Hola @2028meme , podrías darnos un poco más de información al respecto? Capturas de pantalla también ayudarían a entender y ver el problema.

Desde qué dispositivo hiciste la compra? Tienes el TxId?
