### ISSUE TITLE
Recieve QR code in ALL CAPS, not accepted in bitcoin.com wallet; compliancy issues

### ISSUE THREAD

**Issue by 94b42c29dd** [bitpay/copay#7953]
When someone with a bitcoin.com wallet scans the qr code it's not accepted because the QR code is in all caps (when using bitcoin cash) (e.g. BITCOINCASH:3JS8S... instead of bitcoincash:3js8s...). also when sharing the address using the sharebutton it doesn't use the "bitcoincash:" prefix, which also isn't accepted in the bitcoin.com fork of this wallet and is not compliant with the Cashaddr format, just like the all caps qr code. This all causes a very bad user experience. Hopefully it can be fixed.

Using v3.14 on android.

**Comment by Gamboster** [comment]
Hello @94b42c29dd 

If the bitcoin.com wallet does not recognize the QR code just because it is in uppercase, then it is a bitcoin.com wallet error, you should report the error there.

bitcoin.com should be able to receive BCH addresses:
- Uppercase with and without prefix
- In lowercase with and without prefix.

Note: Addresses with a mix between uppercase and lowercase are not allowed

https://github.com/Bitcoin-UAHF/spec/blob/master/cashaddr.md#uppercaselowercase

As you can see, in the QR is recommended to use uppercase to use alphanumbic encodding. The QR code of Copay is correctly implemented.

Regarding the sharing function, we will review it to see if it works correctly. Alternatively you can use the copy to clipboard function that Copay has, by clicking on the QR code or the address you are trying to pass.
