### ISSUE TITLE
Can’t transfer bitcoin

### ISSUE THREAD

**Issue by beadgrl1** [bitpay/copay#7989]
I can’t send my bitcoin to another address. Says insufficient funds. But I have .43000 bitcoin.

**Comment by vuduy67215** [comment]
bitpay/copay
reply@reply.github.com


Vào 05-02-2018 22:22, "beadgrl1" <notifications@github.com> đã viết:

I can’t send my bitcoin to another address. Says insufficient funds. But I
have .43000 bitcoin.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7989>, or mute the thread

**Comment by vuduy67215** [comment]
Vào 05-02-2018 23:22, "phim hay" <vuduy67215@gmail.com> đã viết:

bitpay/copay reply+022084576ff8bfdbfdcd414c372565
d205c98e0d6ef7611592cf00000001169038ca92a169ce118ca7df@reply.github.com


Vào 05-02-2018 22:22, "beadgrl1" <notifications@github.com> đã viết:

I can’t send my bitcoin to another address. Says insufficient funds. But I
have .43000 bitcoin.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7989>, or mute the thread

**Comment by beadgrl1** [comment]
What does this mean?

**Comment by yavaev05** [comment]
Кому хотели лередать Bitcoin

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-05 20:47 GMT+03:00 beadgrl1 <notifications@github.com>:

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)

**Comment by vuduy67215** [comment]
Vào 07-02-2018 8:29, "Jason Dreyzehner" <notifications@github.com> đã viết:
