### ISSUE TITLE
Sent bitcoins from coin mama 

### ISSUE THREAD

**Issue by patriots1121** [bitpay/copay#7990]
To copay and says order complete on coin mama and it is still not in my copay account

**Comment by Gamboster** [comment]
Hi @patriots1121 , if you are sure that you sent BTC or BCH to a copay wallet address, then the funds should be there. If they are not, then you should create a ticket to "coin moma" and ask about the status of your transaction.
Anyway, you can send the transaction id, or the address to wich you sent, to verify it.

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
