### ISSUE TITLE
Selling bitcoins

### ISSUE THREAD

**Issue by kevita7** [bitpay/copay#7993]
I sold some of my bitcoins on Friday, it shows it was transferred out of my account but when I check the status it just gives me an error message

**Comment by Gamboster** [comment]
Hello @kevita7,
Could you indicate your problem better? Where do you want to check the "status"? And what does the error say?

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)

**Comment by kevita7** [comment]
I go to coinbase hit the activity and the last transaction shows how much I sold & it shows & error next to it? So how do I found out where my money is?

**Comment by bitjson** [comment]
We are not able to provide support for Coinbase.com. Please visit their support site here: https://support.coinbase.com/
