### ISSUE TITLE
Bitcoin Not Received in my Copay Wallet.

### ISSUE THREAD

**Issue by cryptobulls17** [bitpay/copay#7997]
Dear Sir/Mam,

my one of transaction is not yet credited in my Copay Wallet.

you can also refer it : https://blockchain.info/address/3PGuNkffqdRkwQaGfKKawug8W4NYfztPba

Transaction Details.

Date: 2018-02-06 15:16 
TXID: 0c9eb0d8952f1af842921722bf62a9671a89ff4859d12a6ef758a067a1f0033e 
BTC Amount: 0.02517519 
BTC Address;

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)
