### ISSUE TITLE
Bitcoin not received in copay and bitpay wallet!

### ISSUE THREAD

**Issue by SiddSen** [bitpay/copay#8002]
Bitcoin not received in copay wallet but shows up on Blockchain. 

Blockchain website: https://blockchain.info/address/1MeHHf8AqqCFwgQCYZ7BcqM8gLZ462cpdW

Please help ASAP

**Comment by bitjson** [comment]
Hello, thank you for submitting an issue on Copay’s GitHub repo. After a quick review, I believe this is a one-off issue, and not a development work item, so I’m closing it for now. Please let me know if it should be reopened.

Copay is an open source project, and this issue tracker helps us organize bugs reports and feature requests. While we often try to provide end-user support on GitHub, if your issue is primarily a question or a support request, you’ll get a more complete and timely response by [asking the community on Stack Exchange](https://bitcoin.stackexchange.com/questions/tagged/copay).

We recommend you search for your question on Stack Exchange. If it hasn’t been asked before, you can submit it yourself.

### [Get help with Copay on Stack Exchange &rarr;](https://bitcoin.stackexchange.com/questions/tagged/copay)

**Comment by vuduy67215** [comment]
Vào 07-02-2018 4:45, "SiddSen" <notifications@github.com> đã viết:
