### ISSUE TITLE
Remove Windows Phone support

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#8086]
https://www.cnet.com/news/windows-10-mobile-features-hardware-death-sentence-microsoft/
https://gizmodo.com/windows-phone-which-was-already-dead-gets-another-sta-1823145178

**Comment by randolf** [comment]
I remember someone years ago using a Windows CE phone, but they eventually moved to an Android phone because it kept crashing and didn't have enough apps.  I wasn't even aware that Microsoft had a Windows 10 phone, and I guess it's not a surprise that Microsoft is abandoning it since I don't know anyone who even has one -- of the people I know, I'd estimate ~80% are using Android, and ~20% are using iPhones.  I also know a handful of people who use pre-Android BlackBerry phones (including me), but even though this is insignificant it's still more than the 0 people I know who use Windows phones.

I just don't see it being worth the effort to bother making apps for Windows phones, especially given that even Microsoft has decided to give up on this market too.
