### ISSUE TITLE
I cant complete my backup process

### ISSUE THREAD

**Issue by Hit-Boy** [bitpay/copay#8121]
After entering spending password, i always return to "Are u being watched?" page, what i should do to fix it?

**Comment by Gamboster** [comment]
You have to be sure that you are entering the password correctly. The one you set when creating the wallet. If you put it wrong, you'll go back to the "Are you being watched?".
We are aware that this part of the app must be improved, so that the user knows what is happening. In a future release we will improve it.

**Comment by mlane0703** [comment]
I'm having the same problem. Except I continued to create the wallet w/o the password or back up bc it wouldn't let me create it. After creating the wallet I had funds transferred to it and the funds have been locked up for almost 2 months now. I've sent email after email trying to get help and the funds are still locked... I'm pissed.  For ppl who don't know anything about a bitpay wallet.. and the password and back up.... this app is a trap. Ive since created a different wallet.. used the same password  I tried to create the 1st wallet and had no issues... So I don't understand how he's saying u have to enter it correctly. But anyways,  now that funds are in that wallet w/ no password.. it's like there lost. The app prevents u from backing up the wallet or setting up a password bc any action must have a spending password... even tho it never let me create one... 
It feels like a complete SCAM.  like the app was created for this purpose... I'm pissed and my advise to u is DON'T continue w/ a bitpay wallet. U have a STRONG chance of losing ur $$$$%!!!

**Comment by dabura667** [comment]
could you be more specific?

The problem can’t be fixed if the developers can’t reproduce the problem.

Your current description of events doesn’t make sense to me, and trying to create a new wallet and break it in the same way doesn’t work. The wallet doesn’t break.

What OS are you using? What version? What build? Which manufacturer? Do you have custom keyboards installed? Do you have autofill enabled on some keyboard level app?

There are literally millions of conditions that could have caused the issue.

Imagine this: you install a cool app for your keyboard that autofills stuff for you, but it doesn’t work well with Copay and accidentally filled in a password from a different app, and you just hit enter... then for some reason the same app doesn’t recognize the autofill when spending (only when setting up initially)

Etc etc

Instantly assuming malice on Copay’s part or assuming it’s Copay’s fault to begin with is not constructive. You are just making it less likely that they will want to help you.

I understand you are frustrated. But you learned a lesson:

1. Before using a new wallet, send a small amount in, like 10 dollars.
2. Make sure you make a backup.
3. Erase the wallet and make sure you can restore the backup.
4. After you restore the backup, make sure you can send by sending the $10 back to your original wallet.
5. If all goes well, send your money into the new wallet.

At the very least, you learned a lesson. But if you have your 12 word phrase written down you SHOULD be able to bypass the “spending password” function.

**Comment by Hit-Boy** [comment]
Thank u for help, i was just writing pay password instead of my account password, because it was written that i should write exactly pay

**Comment by Belkodon** [comment]
SAME HERE.
---------------
I NEVER SET A COPAY WALLET SPENDING PASSWORD 
---------------
I installed the COPAY WALET APP on my iPhone in december 2017.
Back then I didn´t have problems to send or receive BTC or any currency.

I activated the "touch ID security" ( for login & spending )

I never looked at the "12 word recovery phrases",
since I could do that at anytime later, ...

NOW THERE IS A "SPENDING PASSWORD" OPTION
WHICH IS SUDDENLY ACTIVATED – NOT BY ME ! ! !

THE FACT THAT IT´S ACTIVATED PREVENTS ME FROM BEING ABLE :

    TO SEND MY BTC
    TO LOOK AT THE "12 WORDS BACKUP PHRASE"

WTF !
----------------
IS THERE A WAY TO DOWNGRADE TO AN OLDER VERSION OF COPAY WALLET ?
( IN ORDER TO GET RID OF BEING ASKED FOR A PASSWORD THAT I NEVER SET ? )
WHY CAN´T I JUST ACTIVATE GOOGLE AUTHENTICATOR FOR COPAY ?
TO GET AROUND ... ( entering passwords is so obsolescent )
----------------

<img width="445" alt="bildschirmfoto 2018-03-19 um 16 51 33" src="https://user-images.githubusercontent.com/7950439/37609587-c0070a8a-2b9d-11e8-98ef-a0c03cc56e43.png">
<img width="462" alt="bildschirmfoto 2018-03-19 um 16 51 55" src="https://user-images.githubusercontent.com/7950439/37609588-c050cb0c-2b9d-11e8-8838-823c31891536.png">

**Comment by AgentZ86** [comment]
Yes same problem here. New bitpay download to windows 10 pc desktop. Windows 10 home. never gets me to a passphrase screen EVER. Only asks to setup backup or ignore for later. Then from there takes me to password screen which I assumed was to create a password not to enter a password that is already created. 

I short I never created a password and selected to setup backup later. Assuming that the password screen I was at was for creation of the password and not to enter the password I typed one in. This just takes me back to the "are you being watched screen". After watching youtube vids on setup and what it's suppose to look like. I see that there was suppose to be a passphrase screen first which I am suppose to print, screen shot or write down. Then from there it should go to being watched etc. then create a password. This never actually happened. It went from the backup suggestions to being watched to enter password. I have the password that I thought it was trying to create when entering password but I'm not sure that it really created any and is dead on arrival. I skipped backup and then figured I could transfer some bitcoin and use the app without a password since I didn't set on up and didn't understand that the password it's asking for is actually NOT creating password login but actually looking for an actual password. Either way I transferred some bitcoin to a DOA app and now it's stuck in limbo without any spend access. I do indeed have the password that I was creating or thought it was asking to create but in fact the creation of a password never actually completed either nor any initial backup. The entire process seems to have failed without ever showing a passphrase group of words that I've seen on youtube screens during this process.

**Comment by AgentZ86** [comment]
Ok I understand something a little better now. I installed on another desktop pc to get familiar with the screens I'm suppose to see. As suspected the screen to select to create backup appears, then create password, then from there is a passphrase screen in which you much copy or write down those passphrase in order to complete the backup or bitcoin wallet creation. However on my first attempt on my other machine I was not given these screens nor passphrase to complete so I pressed the back button to take me back to the skip screens to create wallet later. I believe this is what caused the problem when the passphrase was not showing in order to complete the process. 
And yet it did create a bitcoin wallet in order to send funds to it but those funds are unusable do to the lack of passphrase and completion of the password process.

**Comment by Belkodon** [comment]
THE DILEMMA :
THE COPAY WALLET APP IS AN EXAMPLE OF "BAD PROGRAMMING".
EITHER IT´S A LACK OF CONECPTIONAL LOGIC OR IT´S PLANNED TO FUNCTION LIKE A TRAP.

HOW CAN IT HAPPEN, THAT A SOFTWARE SHUTS OUT THE USER AFTER ANY UPGRADE ?

WTF ?!-***

**THE PROGRAMMERS OF THE COPAY APP HAVE ROBBED ME. AND THAT´S A FACT.**
-----------------
AND SINCE COPAY IS PROBABLY NOT PROGRAMMED BY ANY COMPANY IN THE USA OR EUROPE,
THERE IS NO CHANCE OF GETTING BACK THE CONTROL OVER MY BTC WITHIN THE APP. 
---------------
 I PROBALY NEED A HACKER WHO CAN RE-PROGRAMM THE COPAY APP AND REMOVE THE STUPID PASSWORD POPUP THAT HAS BEEN INTEGRATED...

**Comment by gabrielbazan7** [comment]
The spending password is the password you set at creation time (also you can do it later) to encrypt your wallet. You need to remember this password to have access to your funds. 

![bitpay_-_secure_bitcoin_wallet_and_slack_-_bitpay_and_wallet-settings_html_ _copay](https://user-images.githubusercontent.com/10999037/37731081-00f9e2c8-2d20-11e8-8cce-2a9f2a325ebe.png)

![bitpay_-_secure_bitcoin_wallet_and_slack_-_bitpay_and_wallet-settings_html_ _copay](https://user-images.githubusercontent.com/10999037/37731097-07a8457e-2d20-11e8-8487-bcbe84006cf8.png)

**Comment by fedyakahaw** [comment]
Same thing here ! I have never programed any spending code as the app said I was able to make this later. Now I'm trying to send BTC and it asks me to enter the spending code. I tried to set it up via settings, same thing : warning screen (make sure you're not being watched) then it asks me to enter the code that I've never programmed.

**Comment by richardsj** [comment]
Bump - no idea why this issue (cannot enter encryption password) is closed as it's still very much a bug on IOS (total show-stopper, multi-sig wallet, enter encrypt password takes you back to "Are you Being Watched").

@Hit-Boy

**Comment by richardsj** [comment]
This is a brand new wallet - so it's the "Backup Wallet" option after creating it.  There is no previous password to enter, it just ignores the first one you use.  Here's a [video of the bug in action
](https://imgur.com/gallery/TrjO3XF)

**Comment by BGalliotti** [comment]
Hello @richardsj 
Thanks for reaching out to us.

You do not need a password to backup the wallet. 
If you are being asked for a password when trying to back the wallet up, that means you have previously set it up.

Please send the steps you do to get there.


Please let us know if you have any additional questions.
Kind regards.
