### ISSUE TITLE
Bug or Intended?

### ISSUE THREAD

**Issue by sadpandas** [bitpay/copay#8158]
I used lastpass to generate a password but it didn't end up saving so I went to backup my wallet to restart the process of all over again and I cant because I didn't backup my wallet before I made the password. My BTC is lost now unless there is a fix coming for this, Its forced on and I'm unable to deactivate it. Shouldn't it be off until I backed up? There wasn't a warning before i made the password that I wouldn't be able to backup if the password was forgotten

![screenshot_20180305-000559 488](https://user-images.githubusercontent.com/37060576/36962082-55c76216-200b-11e8-95ab-76382833c928.png)

Also when I try to access the back up via fingerprint It's just a blank page.

**Comment by gabrielbazan7** [comment]
Hi, the spending password is the password you set at creation time to encrypt the wallet. You need to remember this password in order to access to your funds. Unfortunately there is nothing we can do for your since your spending password is not managed by BitPay but created and stored client-side, there is no way to reset it.
