### ISSUE TITLE
Problem for send btc  -  you haven't wallet avaliable

### ISSUE THREAD

**Issue by jordaoofc** [bitpay/copay#8248]
![image](https://user-images.githubusercontent.com/37426176/37498939-d17dfe64-289f-11e8-8a6d-8572aada9dc1.png)

I have a Copay wallet and I have problems sending btc, I have the necessary amount but when I put the link of the wallet that I want to send it is as in the image above, saying that there are no wallets available. But I have a maid and with balance, she receives payments but does not send. Can someone help me? I'm in the last version of the app

![image](https://user-images.githubusercontent.com/37426176/37498963-f882a2d0-289f-11e8-9fe9-7f17eb97e8c5.png)

![image](https://user-images.githubusercontent.com/37426176/37498967-0233a428-28a0-11e8-8bc0-39ec23efcb25.png)

**Comment by Gamboster** [comment]
Hi,@jordaoofc The wallet you have created is a "Testnet" wallet, you can check it by its symbol, different from a normal wallet. This type of wallet, only receives testnet coins. They have no real value, since they are used by developers to test.
If you want to send money to wallets "livenet" (With BTC that has value), you can not do it from a wallet testnet.

**Comment by jordaoofc** [comment]
os btc que recebi são valores enviados de uma carteira normal, agora não consigo mais usar? Os btc que estão nessa carteira são valores enviados por uma carteira normal

168/5000
the btc I received are values sent from a normal wallet, now I can not use them anymore? The btc that are in this portfolio are values sent by a normal wallet

**Comment by Gamboster** [comment]
You can not send BTC testnet from a normal wallet (livenet). The wallet from which it was sent, must also be testnet.
