### ISSUE TITLE
Bitcoin Cash Support

### ISSUE THREAD

**Issue by elchupanibre44** [bitpay/copay#8266]
Hello,

I have accidentally sent BCH to my Bitpay BTC wallet from Coinbase (I know I'm so stupid..). I was able to use the Bitcoin Cash Support to locate the exact BCH amount in my BTC wallet, but duplicating my wallet does not transfer the BCH over. I still end up with 0 BCH. Am I missing a step? Any help would be greatly appreciated!

Thank you!

**Comment by matiu** [comment]
Could you  try to 'scan address for funds' in settings > more options > wallet addresses? 

If that does not work, let us know.

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.

**Comment by corn91791** [comment]
No don’t let it go through

Christopher Roberson 

On Apr 26, 2018, at 10:56 AM, BGalliotti <notifications@github.com> wrote:

Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
