### ISSUE TITLE
BCH transaction not found

### ISSUE THREAD

**Issue by udai001** [bitpay/copay#8317]
BCH sent 4 days ago does not appear in transaction as remittance. Help me

**Comment by matiu** [comment]
Can you share details of the transaction? (TXID, or addresses)

**Comment by BGalliotti** [comment]
Hello,

We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.

**Regarding your BCH transaction please follow #8586**

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you still need support, open a new issue, we will be happy to help you.
Thanks
