### ISSUE TITLE
12 Word recovery seed invalid

### ISSUE THREAD

**Issue by fmrco366** [bitpay/copay#8363]
My daughters Samsung phone reset itself and she lost all her contacts&apps.  I’m trying to retore her copay wallet with 12word recovery seed but i get a message saying could not import: wallet recovery invalid.  I know these are the 12 words, and the correct order.  Is there a way I can find the old wallets File/text info to copy and paste in the new wallet to recover,  if the phone reset itself?  I’m not familiar with Android/Samsung OS or where to look for it.

**Comment by bitjson** [comment]
Be careful not to share the seed with anyone.

Often, when users have trouble restoring from the 12 word backup, it's because one of the words is misspelled. You can find the full word list (for English) here: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

Also be sure you're not capitalizing any letters or adding a period at the end.

**Comment by fmrco366** [comment]
Thank You.  It was because the first word was capitalized. D’Oh!  It worked after correcting.  Thanks again

**Comment by bitjson** [comment]
Great! Glad to hear you were able to restore the wallet.
