### ISSUE TITLE
Use Ledger with Copay Wallet

### ISSUE THREAD

**Issue by NinaCrypto** [bitpay/copay#8439]
Hello 
How can I use Ledger Nano S with Copay Wallet? (instructions on Ledger website are not updated and can't find a way to connect with nano s)
Thanks

**Comment by Gamboster** [comment]
Hello @NinaCrypto . Currently Copay does not support hardware wallets. It is a decision we made because Google published that the chrome apps will not continue to have support (The hardware wallets compatibility with Copay was done through chome app). As you can read here: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Regards.
