### ISSUE TITLE
HOW TO GET ENCRYPT PASSWORD

### ISSUE THREAD

**Issue by romerobd** [bitpay/copay#8474]
I’m trying to sell bitcoin using coinbase and when I confirm it’s asking me for an ENCRYPT PASSWORD, which I’ve never had to enter on past transactions.  How do I retrieve this password or disable this setting?

**Comment by BGalliotti** [comment]
Hello,
Since your spending password is not managed by BitPay (it is created and stored client-side), there is no way to reset it.

However, if you have [backed up](https://www.youtube.com/watch?v=U23E-dZEuYs) your wallet by writing down the 12 word recovery phrase, you can delete the wallet and then restore the wallet from your backup to get access to your funds without the need to enter your spending password.

The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device. To restore your wallet if your device is lost or stolen, you must save the 12-word backup phrase that you receive when you create a wallet. BitPay will not be able to recover your funds.

Please reach out if you have any additional questions or concerns.
Regards.

**Comment by Batsoma** [comment]
i have the issue and I tried to add bitpay wallet on different mobile using 12 word backup with no success
saying 12 word is invalid

**Comment by BGalliotti** [comment]
Hello @Batsoma,

Thanks for reaching out to us.

Please refer to #8532 to the IMPORT and follow those steps meticulously.
If you have any questions, please post them in that thread.


Kind regards.

**Comment by Batsoma** [comment]
I have a serious problem with my wallet
I am trying to send funds and wallet asking for encrypt password and it
says it’s wrong password although I am sure from my password

I didn’t backup for my wallet I just have only first 12 backup when I
created wallet
Kindly ur support please
I am still have to access to wallet
I can get information do u need

**Comment by BGalliotti** [comment]
Hello @Batsoma,

Thanks for reaching out to us.
If you have the 12-word passphrase, it should not be a problem to recover the wallet.
Please refer to #8532 tand follow the steps described there.

The 12 word passphrase has nothing to do with the encrypt password, so in case you have the 12-word passphrase, go ahead and recover the wallet.
Bear in mind if you do not have the 12-word passphrase, there is no way to recover the wallet.
**There is no account or password for the BitPay wallet. Please see https://support.bitpay.com/hc/en-us/articles/115002989283-Why-don-t-I-have-an-online-account-for-my-BitPay-wallet-.**

**BitPay does not store your private keys or have access to your funds. The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device. To restore your wallet if your device is lost or stolen, you must save the 12-word backup phrase that you receive when you create a wallet. BitPay will not be able to recover your funds.**

**Unfortunately, without the 12-word recovery phrase, you will not be able to recover the wallet and there is no way for us to help with that.**

**As a recommendation for the future, backup your wallet right after creating it and write down the 12-word phrase, store it in a safe place and do not share it with anybody.**

Uninstalling the app without backing your wallet up, will lead to losing your wallet and money.

If there is any other question or concern please let us know.



 

Please let us know if you have any additional questions.
Kind regards.

**Comment by Batsoma** [comment]
I have first 12 word passphrase when I created bitpay wallet
I tried to do restore bitpay using 12 wordphrase which I have on different
device but I got error “ invalid passphrase”
I am sure from enrypted password I don’t know why it’s wrong
Please help me I have money on this wallet

**Comment by BGalliotti** [comment]
Hello @Batsoma 

Thanks for reaching out to us.

Unless you have created the wallet with a very old version of the app, you do not need the password.

So please, go ahead and try the recovery process without entering any password.

Please let us know if you have any additional questions.
Kind regards.

**Comment by josephgitts** [comment]
Hi admin am trying to put my 12 words which I wrote it down,am using bitpay this is what it  say :error wrong number of recovery words :13

**Comment by BGalliotti** [comment]
Hello @josephgitts ,

Thanks for reaching out to us.

Very likely you are entering some space, probably after the last word.

Please refer to #8532 there are a clear explanation and things that you can check.

Please let us know if you have any additional questions.
Kind regards.

**Comment by acs51** [comment]
When I set up Bitpay, it never asked me to set up an encrypt password, now I can't send any funds because it's asking me for an encrypt password which I don't have!!!

**Comment by BGalliotti** [comment]
Hello @acs51 

Thanks for reaching out to us.

What you are posing is not possible. If you are being asked for a password, that means you have set up a password. 

The only thing you can do to recover the wallet is to try to remember that password. Take into account, there are no special requirements for the password, such as uppercase, lowercase, symbols, etc.

Please let us know if you have any additional questions.
Kind regards.

**Comment by metanurb21** [comment]
This obviously is an issue if enough people are reporting it. I too just tried transferring some BTC to my card and it asks for an Encrypted Password. I meticulously recorded ALL information from the setup process, Usernames, Email, Passwords, Backup phrase, Spending password and nowhere was there  ever a mention of an encrypted password to transfer funds. So what now? I guess another canned response that doesn't help one bit.

**Comment by corn91791** [comment]
OK I understand that but what if somebody has the access to all my stuff and they’re blocking me from getting my stuff is there taking it for me at the same time

On Jul 28, 2018, at 2:00 PM, Dave Stewart <notifications@github.com> wrote:

This obviously is an issue if enough people are reporting it. I too just tried transferring some BTC to my card and it asks for an Encrypted Password. I meticulously recorded ALL information from the setup process, Usernames, Email, Passwords, Backup phrase, Spending password and nowhere was there ever a mention of an encrypted password to transfer funds. So what now? I guess another canned response that doesn't help one bit.

**Comment by BGalliotti** [comment]
Hello @metanurb21  

Spending password and encrypt password are the same thing, so please go ahead and enter your spending password if you are asked for an encrypt password.

Also, since you have all the backup data, you can safely remove the wallet and recover it using the backup phrase. To do so please refer to #8532 

@corn91791 
> OK I understand that but what if somebody has the access to all my stuff and they’re blocking me from getting my stuff is there taking it for me at the same time

If you have the passphrase, nobody can deny you the access to the wallet, they could use it simultaneously but never block you.
If someone else has the passphrase, they are in control of the funds and probably they will steal the funds all at once. 

Please let us know if you have any additional questions.
Kind regards.

**Comment by edueter** [comment]
Hi admin, listen

I've just installed the wallet on my iPhone and the thing is I copied a password from a passwd management app that I use but the paste was temporary and I couldn't save it.
I got nothing since this is a brand new wallet (first time user), not even a backup (since it asks for the passwd). Is there an way to reset the whole thing with no need to recover the pass? thanks.

**Comment by edueter** [comment]
@edueter ok, solved it myself. Reinstall the app and just begin with an new e-mail address

**Comment by IcePrincess1405** [comment]
Okay so I am having a similar issue. I didn't set a password and somehow one of my is requiring a wallet. Also if I were ever asked to put a password on something I will be using on a daily basis such as bitpay wallet or a bank account for that matter the possibilities are limited to about five (I know not very wise). These passwords are programmed into my muscles so there is no way I would have screwed it up. I understand Bitpay's position as well; because nothing is stored in their end asking them to recover btc does not make sense. I get that and I believe that they believe that the customer has definitely set a password. However, I see this to be a bit of a common theme. Unless everyone is lying about setting a password or forgetting about it I think we may have to explore this a little bit. My question is, is the encrypted password stored somewhere in the user's device if that is the device used to create the wallet and "set the password"?

**Comment by richardsuns** [comment]
@romerobd 
if you couldn't restore your wallet, i can bruteforce and crack your ENCRYPT PASSWORD.
i have recovered another wallet with ENCRYPT PASSWORD problem
