### ISSUE TITLE
Created wallet on desktop & now can't get wallet updates

### ISSUE THREAD

**Issue by Cluelesss** [bitpay/copay#8492]
Was working fine on my Win 7 desktop (sent/rcvd txns), made a deposit which has 10 confirmations on Blockchain and a confirmation email from Bitcore.io that it was successfully rcvd by my wallet address.  But, it's not showing up in my wallet.  The desktop app isn't responding properly: clicking on "Advanced" in the Settings tab (along with a couple of other functions) doesn't do anything and some of the icons are broken.  

I should also probably mention that I set up the app in a rush and didn't note my Wallet ID or create a passphrase (smart, I know).  It seems like the only thing I *can* do it right click and "Reload app".  I'm just worried that without the Wallet ID/passphrase, I might blow up my wallet given my current luck.  Any ideas if this, or something else, might work to safely refresh my wallet.

**Comment by BGalliotti** [comment]
Hello,
In order to properly address your issue please send us your wallet ID so we can check it out.

- Regarding the wallet, please send us screenshots of what is going on,  steps for the error to come up.

**Please do no uninstall the app, as you have no backup of your wallet.**
**Do not try any destructive solutions like reinstalling windows or things like that.**

The basic steps here would be:
- Try to make the wallet work (Windows Safe mode, compatibility options or whatever makes it work)
  Please be careful when doing so.
- Back up the wallet.

We look forward to hearing from you.
Regards.

**Comment by Cluelesss** [comment]
As of right now, I can't get to my Wallet ID, because when I go to Settings and try to click on Advanced, nothing happens.  My wallet also doesn't appear here (although it does on the Home page).  The icons are missing also.

![copay-wallet-settings-2](https://user-images.githubusercontent.com/38709658/39283050-3db76c3c-48da-11e8-800e-98b7ebc3bf23.gif)

The Home page at least displays my current balance:

![copay-wallet-1](https://user-images.githubusercontent.com/38709658/39283108-9dc14062-48da-11e8-902f-2644deb0ebf4.gif)

Was considering to "Restart App" via right clicking, but don't want to loose anything as I just made a confirmed transfer into the Wallet that isn't showing up.
