### ISSUE TITLE
Wallet busy error

### ISSUE THREAD

**Issue by SasaWebUp** [bitpay/copay#8549]
What is going on with copay wallet?
I am getting number of problems in last couple of days. Latest one is wallet_busy error. Please fix ASAP. This is becoming outrageus and obscure.

**Comment by thor12341** [comment]
me too. WALLET_BUSY: Wallet is busy, try later

**Comment by Kafkamorph** [comment]
Same. Not the first time. This client is unreliable.

**Comment by SasaWebUp** [comment]
Agreed. Now I can not use my btc wallet due to their inefficency to provide
stable wallet. Complete joke.

**Comment by FaSSt3r** [comment]
It is already fix, at least for me :)

**Comment by BGalliotti** [comment]
Hello everyone,

We apologize for the inconveniences this issue may have caused to you.

Yesterday we have experienced an outage that lasted several hours.

The service is now up and running, anyways due to yesterday's event, many people are trying to perform transactions/operations and that might be causing congestion.

Please be patient.

Thank you all, best regards.
