### ISSUE TITLE
Recovery phrase not working - funds gone

### ISSUE THREAD

**Issue by InigoMontpiya** [bitpay/copay#8656]
Hi there,

My old phone broke a while back and when I got a new one and entered my recovery phrase I get an empty wallet. 

I know I have the correct recovery phrase as I have it written down in two separate locations. However the wallet has no funds and no transactions despite a weekly deposit into my wallet. 

Please help!

**Comment by BGalliotti** [comment]
Hello @InigoMontpiya  ,

Thanks for reaching out to us.
We are sorry you have had this bad experience.
**Please make sure you do not have another wallet, and you are restoring the desired wallet.**

**Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you need any further assistance, please let us know.

Kind Regards.

**Comment by InigoMontpiya** [comment]
Hi @BGalliotti,

I have tried this and still get zero funds. I cannot access the original app I had it on as the old phone is completely dead. 

I do not understand how I can have the recovery phrase yet get no funds in my wallet. Have I done something wrong and somehow emptied my wallet?  

My understanding was that as long as I have my recovery phrase I can always access my wallet across multiple devices so I was not concerned when my mobile broke. 

Any further help appreciated

**Comment by BGalliotti** [comment]
Hello @InigoMontpiya 

Thanks for reaching out to us.
You probably haven't done something wrong, the thing is, if your wallet is showing no funds, it's because it does have no funds.

However you can check the following:

-  Make sure the wallet you have recovered is the wallet that should have funds, check if you do not have another wallet.

- **Is your wallet a BCH wallet?** in such case please follow #8586 

If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by Richie202a** [comment]
@InigoMontpiya 
were you able to recover your seed phrase, if not i can help: anywalletrecovery@gmail.com
