### ISSUE TITLE
I can't buy Amazon.com Gift Cards (Error in payment protocol. Invalid URL)

### ISSUE THREAD

**Issue by miguelangel2801** [bitpay/copay#8660]
Hi, Copay team

Since few weeks ago I've getting this error message when I try to buy an Amazon's Gift Card:

_Error in payment protocol._ 

_Invalid URL_

I have two BTC wallets with positive balance greater than 5USD. 

I've tried uninstalling the app from my smartphone but it didn't work.

Also, I've bought Amazon's gift cards twice. So, I have no idea about why is happening this now.

Please, I need help.

Regards.

**Comment by shane1900** [comment]
Same issue here.  Happens when I select my BTC account and the error appears (amazon checkout).

iPhone 6s, 11.4 ios.

v4.4.0

Wallet ID d54e4670-c886-4314-92bf-904b5393a9e6


![img_f24878ee997e-1](https://user-images.githubusercontent.com/13156874/41677744-75a5a9c4-7486-11e8-80b9-4135ff17f1b7.jpeg)

**Comment by BGalliotti** [comment]
@miguelangel2801 @shane1900 

Please try again. Let us know if you have any problems.

**Comment by shane1900** [comment]
Works thank you.

**Comment by BGalliotti** [comment]
Awesome! 
@shane1900 

We are glad it is working. 

Open a new thread if you have more questions or concerns.
