### ISSUE TITLE
Old copay account 

### ISSUE THREAD

**Issue by joehayes13** [bitpay/copay#8668]
I had copay on my phone when it crashed (no money in it not a big deal) 
My pool just paid out 1 btc to this wallet address (big deal). 
How do I get that wallet active again? If i can't how do i get that transfer sent back to the pool or moved over to my new wallet?

**Comment by corn91791** [comment]
No don’t let people tack my money

**Comment by BGalliotti** [comment]
Hello  @joehayes13 

Thanks for reaching out to us.
In order to recover your wallet, you need your 12-word passphrase.

Please follow #8532 for all the instructions on how to do that.

If you have more questions regarding your recovery, please post there.

If you any more questions, please open a new thread, and we will give you support.

Kind regards.
