### ISSUE TITLE
Recover 4-3 multisig wallet

### ISSUE THREAD

**Issue by minergarage** [bitpay/copay#8736]
Hi, I have set my copay account with multiple user setting with multiple verification required. 
Unfortunately, two of the members have does not have access to the phone anymore and their private key.  Since the account was made with 4 user with 3 user verification needed, we can not change the setting nor verify any of the setting. 
Is there anything we can do to restore this account?  Or is it lost forever?

**Comment by BGalliotti** [comment]
Hello @minergarage 

Thanks for reaching out to us.

Since your wallet is a 4-3 and two of the users have lost their wallets, unless they have their 12-word backup phrases, they cannot recover the wallets. At least one of them should have the passphrase, otherwise, nothing can be done to recover those wallets.

Please let us know if you have any additional questions.
Kind regards.
