### ISSUE TITLE
Unconfirmed funds / late confirmation

### ISSUE THREAD

**Issue by Edmund2000** [bitpay/copay#8803]
I was sent some amount of bitcoins and it's been unconfirmed for hours now

**Comment by BGalliotti** [comment]
Hello @Edmund2000 

Thanks for reaching out to us.


Please be patient, a transaction can take a while to be confirmed depending on many factors.
However if somebody sent you funds, the only thing you can do is wait.
On our end, there is nothing to be done as well.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Edmund2000** [comment]
How long does it take for a fund to be confirmed

**Comment by BGalliotti** [comment]
@Edmund2000 ,

There is no average time for a transaction confirmation.

When bitcoin network traffic is high, many users’ transactions will delayed. Please see https://blog.bitpay.com/transaction-delays.

If your transaction was not confirmed yet, please allow some time for it to receive a confirmation. You can check the status on any blockchain explorer (https://blockchain.info or https://insight.bitpay.com for example) by looking up the transaction ID or sending or receiving bitcoin address.

If the transaction receives a confirmation, your Wallet should update automatically.
If the transaction does not confirm, the bitcoin will be spendable again from the sender's bitcoin wallet. Note that this may take up to 30 days.

The transaction(s) may have been transmitted, but was then 'pruned' from the mempool (the current database of pending, unconfirmed bitcoin transactions) due to including too low of a mining fee. 
The sender's wallet (or bitcoin service) may also be rebroadcasting the transaction in order to get it to confirm at a lower fee.

The website https://bitcoinfees.21.co/ is a useful tool to determine the recommended minimum fee for a transaction to receive timely confirmation. If you sent a transaction with a lower fee, this website will show the estimated time that it will take to confirm.

Generally, as more transactions are added to the network with higher fees than the one yours was sent with, the algorithms of the specialized computers which confirm bitcoin transactions (“miners”) choose those new transactions to confirm, prioritizing these ahead of lower-fee transactions, as they are worth more to the miners to process.

However, any unconfirmed transactions should eventually either: show up (your Wallet will update automatically once the transaction receives a confirmation) or their funds will be available in the originating wallet (for any transaction that never confirms).

If your transaction has not been confirmed yet, please allow some time for it to go through once it has received a confirmation.
