### ISSUE TITLE
I havent received  the full amount

### ISSUE THREAD

**Issue by andrew458k** [bitpay/copay#8840]
Hi,

A person sent me 0.03 btc to my copay address but I havent received the full amount, only 0.0005 btc
this is a screenshot from the sender account in blockchain:
![capture last](https://user-images.githubusercontent.com/40810493/42249498-d8d4b062-7f2b-11e8-9fba-934f7b4b76da.jpg)
and this is from my address in copay:
![kk](https://user-images.githubusercontent.com/40810493/42249523-ffb43d74-7f2b-11e8-8cd0-2e653664ec3f.png)
anyone can help me please?

**Comment by BGalliotti** [comment]
Hello @andrew458k 

Thanks for reaching out to us.

**Please send us your wallet and transaction ID:**

 - BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.
- Transaction ID (text, not a picture): 
Open the Bitpay/Copay app > tap on the desrired wallet > tap on the desired transaction >Tap on the transaction ID, that will copy it to the clipboard so you can paste it.

**We look forward to hearing from you.**

Kind regards.

**Comment by andrew458k** [comment]
transaction ID: 85bebf4b6f2a9ea88b120d173756d6aa28747bfae7a9109871c9c7687bfb2ead

wallet ID: 7d90ef73-b812-4163-bbc5-e15a0367324d

the sender used a wallet from blockchain
and I use copay

**Comment by BGalliotti** [comment]
Hello @andrew458k 

Thanks for the information provided.
You cannot receive more or less than what was sent.

This is the transaction: https://live.blockcypher.com/btc/tx/85bebf4b6f2a9ea88b120d173756d6aa28747bfae7a9109871c9c7687bfb2ead/

As you can see, the amount received is **0.00050000 btc**
Here is your wallet report showing the transaction:

```
* Wallet info

* Tx history
  [Wed Jul 04 2018 07:45:51 GMT-0300] 9f0304294c7c0abfa3bc3aa2f58d9a6a2b3376c005000970639c8b087cb00b92 => sent 0.00058338 btc (fee/kb 0.00009935 btc) (22 confirmations)
  [Tue Jul 03 2018 17:28:02 GMT-0300] 85bebf4b6f2a9ea88b120d173756d6aa28747bfae7a9109871c9c7687bfb2ead <= received 0.00050000 btc (fee/kb 0.00005022 btc) (98 confirmations)
  [Mon Jul 02 2018 15:18:15 GMT-0300] 

```

So, what you received, is what was sent.

Please let us know if you have any additional questions.
Kind regards.

**Comment by andrew458k** [comment]
But the screenshot from the blockchain account shows a transaction of 0.03 BTC to my wallet?

**Comment by andrew458k** [comment]
But the screenshot from the blockchain account shows a transaction of 0.03 BTC to my wallet?

**Comment by BGalliotti** [comment]
Hello @andrew458k 

Thanks for reaching out to us.

Please be patient as we have many tickets to solve.

This is the address that the screenshot shows **1BSWAJA5fDGvNDxUkkGDiiRm2P5fwCWUTi** 

Supposedly the sender sent 0.0305113 BTC to that address, which is your wallet's address, right?
It turns out that address has only two transactions associated to it:

- 9f0304294c7c0abfa3bc3aa2f58d9a6a2b3376c005000970639c8b087cb00b92
- 85bebf4b6f2a9ea88b120d173756d6aa28747bfae7a9109871c9c7687bfb2ead

which are the same transactions shown in the wallet report.

That can be seen here: https://live.blockcypher.com/btc/address/1BSWAJA5fDGvNDxUkkGDiiRm2P5fwCWUTi/

So, there are two possible scenarios:
1) The transaction has not been broadcast yet
2) Something on that screenshot is fake

Please reach the sender and ask him for the transaction ID, not any screenshot. Then check the transaction on any blockchain explorer and make sure the amount is the one you are expecting.

Please let us know if you have any additional questions.
Kind regards.

**Comment by andrew458k** [comment]
"1. The transaction has not been broadcast yet"
 can you explain more please?
its been 20 hours since the transaction was sent

**Comment by BGalliotti** [comment]
Hello @andrew458k 

> "1. The transaction has not been broadcast yet"

This is just a "hypothetical" case.

When you send funds, the transaction is broadcasted or "sent" to the bitcoin network. When the bitcoin network confirms the transaction, after 6 confirmations it is considered completed.

When the transaction is completed it is properly sent, in most cases received (sometimes it could take a while) and irreversible.

It basically works like this: Sender > Bitcoin Network > Receiver

We say it is "hypothetical" since it is a possibility but not very likely. 
Usually, if it says "sent" means it has been broadcast. It could be the case that it said "sent" and had not been broadcast yet, we don't know how that website works internally.

We recommend you to talk to the sender and double check the transaction.

**Comment by andrew458k** [comment]
thank you, it was the sender who was trying to scam me by editing the screenshot
Thank you.

**Comment by BGalliotti** [comment]
Hello @andrew458k ,

What a shame, we are sorry about your bad experience.
As a recommendation, always ask for the transaction ID.

If you have any additional questions, please open a new issue, we will be closing this one.
Best regards.
