### ISSUE TITLE
Confirmed transaction but it doesn't show in my co-pay BCH wallet

### ISSUE THREAD

**Issue by umpire109** [bitpay/copay#8863]
I have recently sent BCH from my Ausutralian company to my Copay BCH wallet , but it doesn't show in my desktop Copay application. 

How can I prove this???

**Comment by BGalliotti** [comment]
Hello @umpire109 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by umpire109** [comment]
Hi
Thank you for your response,
mainly I'm using my desk top computer with Copay app. my Computer is NEC
LaVie with Windows 10.
my mobile is Iphone 6s but I only download the App yesterday.

Current version of my Copay app is v4.40
[image: IMG_0612.JPG]
​
[image: IMG_0611.JPG]
​

2018年7月11日(水) 23:13 BGalliotti <notifications@github.com>:

**Comment by BGalliotti** [comment]
Hello @umpire109 
Thanks for reaching out to us.

We need the information requested in order to proceed with the issue.

Please send us:
- Transaction hash
- wallet ID

In the meantime:

**Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

**Bear in mind**
- If you have imported the wallet using the same passphrase for every device, then you should see the same funds. In any other case, NO.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by umpire109** [comment]
Hi Ben,

So how do I duplicate the found on Copay App with the address you sent me?
Iv tried so many way but I couldn’t work it out. I’m sorry I’m only beginner with this app.



iPhoneから送信

2018/07/12 23:24、BGalliotti <notifications@github.com>のメール:

**Comment by BGalliotti** [comment]
Hello @umpire109 

Thanks for reaching out to us.
We have answered you on the Bitpay support. 

Please answer to us there so we can keep this question clear.

We are going to close this issue and the post the solution.
Kind regards.
