### ISSUE TITLE
Address derivation changed / how to increase gap?

### ISSUE THREAD

**Issue by got3nks** [bitpay/copay#8895]
We are recovering an old wallet created on a very old (around 2 years ago) Bitcore-Wallet-Service server.

Once I click on "Tap to recreate" on the new Bitcore-Wallet-Service instance (linked to Bitcore v5), no funds are found while I'm 100% sure there are funds (if I switch back to the old BWS server URL in the Copay Wallet Server URL configuration I can see the funds).

Has the address derivation scheme changed on newer versions (maybe beacuse of Segwit adoption, while we have funds on legacy addresses)? 

And how do I increase the 40 addresses gap while scanning for active addresses?

**Comment by BGalliotti** [comment]
Hello @got3nks 

Thanks for reaching out to us.

As I understand, the derivation has not changed and we have not adopted segwit yet.
We can suggest you create a new wallet, and since you are able to see the funds, move them to the new wallet.

Please let us know if you have any additional questions.
Kind regards.

**Comment by got3nks** [comment]
I'm migrating to the new Bitcore Wallet Service to recover the Bitcoin Cash in those addresses.

Please help.

**Comment by BGalliotti** [comment]
Hello @got3nks 

Thanks for reaching out to us.

> I'm migrating to the new Bitcore Wallet Service to recover the Bitcoin Cash in those addresses.

**How can you help you?**

Please let us know if you have any additional questions.
Kind regards.
