### ISSUE TITLE
Unable to add contact - Segwit address no supported - Feature request

### ISSUE THREAD

**Issue by alannallama** [bitpay/copay#8903]
I go into address book, add contact, and put in the name, email, and bitcoin address, but the 'save' button is deactivated. What am I doing wrong?

**Comment by BGalliotti** [comment]
Hello @alannallama 

Thanks for reaching out to us.

Please check the email field is correct, with no spaces, and the bitcoin address shows a green tick.


Please let us know if you have any additional questions.
Kind regards.

**Comment by alannallama** [comment]
Hi @BGalliotti - There are no leading or trailing spaces. The bitcoin address is 100% correct, but it's showing a red cross. I have sent to this address twice today from other wallets with no problems. I triple checked it. This happens when trying to add a different contact with a different address as well: red cross and button deactivated.

![copayaddress](https://user-images.githubusercontent.com/5498878/43178024-6e83cdce-901f-11e8-9908-dc65e599410b.jpg)

**Comment by alannallama** [comment]
Hmmm... it seems like maybe you don't allow segwit addresses? If so it would be useful to have an error message saying as much, or a link to documentation there or something.

**Comment by BGalliotti** [comment]
Hello @alannallama 

Thanks for reaching out to us.

Effectively we do not work with segwit addresses. 
Thanks for your contribution, we will put it on our feature request list.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Kirvx** [comment]
Hi @BGalliotti !

I hope this "feature request" will be one of the priorities for your friendly team, as Copay 4.6 is going to be a very serious wallet, after years of develops, redesign, new ideas, new functionalities.
All users should benefit of the lowers miner fees that segwit introduces, even if segwit caused drama in the bitcoin community.

With segwit support, I'm sure you will have less support requests caused by miner fees in the next bull run @BGalliotti 

And I'm sure BitPay can restore the nice reputation it had before S2X (funny how a community can forget all the contributions BitPay gave to Bitcoin adoption).

Regards!

@matiu

**Comment by BGalliotti** [comment]
Hello @Kirvx 
Thanks for your contribution and feedback.

Many users are requesting the Segwit support. Unfortunately, the decision is not up to the development team.

We all hope this will become a reality in the future, we will keep you posted in regards to this topic.

Thank you for your interest and support @Kirvx 
Best regards.

**Comment by alannallama** [comment]
I understand segwit support might not be possible right now, but how about a meaningful error message so people at least know why they can't add the address?
