### ISSUE TITLE
Insufficient funds for Network fee (BitPay Debit Card Top Up)

### ISSUE THREAD

**Issue by cotilloe** [bitpay/copay#9314]
I have been using the BitPay Debit Card for several months now, regularly and have loaded many transactions in the past. However, upon upgrading to the Windows Store BitPay Client, I cannot load funds any more. 

I visit the BitPay website, login to my account and choose add funds. The box pops up, I enter the amount and then I copy the URL (it won't ever open directly). Once I copy it and open the wallet, the payment request is already there, at the top. I click it and it tells me that their is insufficient funds in my wallet to cove the network fee. 

The issue is that this is not true. I looked at the details on the invoice pop-up on the BitPay website and the amount to add + transaction fee were lower than my available balance. It should have been a simple thing, as it always has been in the past. 

I even tried several amounts for lower values, to no avail. I can have 3-4 times the amount needed to cover the deposit amount and transaction fees but still get the error. 

There is no override here at all. The one thing I did notice, is that in the wallet, after it gives the error, the screen behind shows the amount to send and beneath that it says network fee suggested by merchant. there is nothing listed there except for ---, but the total being sent, displayed at the top is equal to the total, including the network fee from the BitPay Invoice.

I have uninstalled the Windows Store Wallet 3 times now, but when I reinstall it, it is magically full of my info, I never have to put they back up phrase in again, which is disturbing. So, basically, I would imagine a fresh install would most likely solve my issue, however how do i get rid of BitPay off of the computer the manual way?

Thanks

**Comment by BGalliotti** [comment]
Hello @cotilloe 
Thanks for reaching out to us.

> I have been using the BitPay Debit Card for several months now, regularly and have loaded many transactions in the past. However, upon upgrading to the Windows Store BitPay Client, I cannot load funds any more.

There was an issue to load the BitPay card on the first Windows Electron versions, very likely this is due to that issue.

> I visit the BitPay website, login to my account and choose add funds. The box pops up, I enter the amount and then I copy the URL (it won't ever open directly). Once I copy it and open the wallet, the payment request is already there, at the top. I click it and it tells me that their is insufficient funds in my wallet to cove the network fee.
The issue is that this is not true. I looked at the details on the invoice pop-up on the BitPay website and the amount to add + transaction fee were lower than my available balance. It should have been a simple thing, as it always has been in the past.

This issue might be derived from the BitPay card pairing issue mentioned above. 
Another possibility is that you had funds but some of the funds were not confirmed. You can send unconfirmed funds (when the required feature is enabled) but you cannot make payments or load the card with unconfirmed funds.

Please update the app and try again. You can find the app [here](https://www.microsoft.com/en-us/p/bitpay-for-windows/9nbr15sk4zjv?activetab=pivot%3Aoverviewtab).

Once updated, import your wallet pair the card and refresh the wallet cache.

**Please open up your BitPay app and try the following steps:**

- Wallet > Preferences (top right corner icon) > Transaction History > Clear cache
- Wallet > Preferences (top right corner icon) > Wallet Addresses > Scan addresses for funds

Then try loading funds to the card again.

**If all the above was not working,**please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
