### ISSUE TITLE
Recovery phrase password deprecation

### ISSUE THREAD

**Issue by yunesj** [bitpay/copay#9328]
Would you please explain why the recovery phrase password was deprecated in commit https://github.com/bitpay/copay/commit/52bbb357d041916141443a0b7f063d4ea6fa7ba1#diff-d9807a0f419163dc65c8d1ab9b0c30f2 ?

How long will importing a recovery phrase with a password be supported?

Thanks!

**Comment by matiu** [comment]
Hi,

While the feature is quite interesting for the advanced users, the recovery phrase password turned out to be too complicated for normal users, because it was easily confused with the recovery words and the storage-encrypting password. That is why we decided to remove it, even from "advanced" settings.


There are no plans to remove it from importing, to support old users. Also, our recovery tool  (https://bitpay.github.io/copay-recovery/) supports it.

**Comment by yunesj** [comment]
I think this feature is necessary for the following important use case.

It is necessary to provide trusted others with a way to recover a user's funds. It is also occasionally necessary to move funds to a new account, e.g., when there is a compromised wallet or chain split.

It was formerly possible to securely provide (e.g., offline via SSS) trusted others one long password, which could unlock any recovery phrase used now or in the future. Without this feature, it seems a user has to securely redistribute (i.e., offline with SSS) a new recovery phrase every time there is a compromised wallet or chain split.

Don't you think deprecating this feature makes secure backup and recovery extremely difficult? Is there another method that is a suitable replacement for this removed feature?

**Comment by yunesj** [comment]
Thanks for recognizing the value of the feature and assigning the ticket. However, the ticket is "closed", so I worry it won't be noticed. Would you please reopen it?

Thanks!

**Comment by yunesj** [comment]
@BGalliotti @cmgustavo The recent security vulnerability called for migrating all funds to new wallets, which as we discussed, is facilitated by this deprecated feature. Could you please re-enable it, or at least re-open this ticket?
