### ISSUE TITLE
BIP44 Second account m/44'/0'/1' can not be created/imported.

### ISSUE THREAD

**Issue by insiderq** [bitpay/copay#9371]
I am trying to import my Blockchain.info passphrase into Copay wallet.
I was able to do that with my first m/44'/0'/0' account. 
BUT, when i try to access my second m/44'/0'/1' account copay doesn’t let me do that. 
1 - if i try to create a new one with custom seed and custom derivation m/44'/0'/1' it says “key already associated”
2 - if i try to import this wallet with custom seed and custom derivation m/44'/0'/1' it says “could not accessthe wallet at the server, please check ...” like the wallet never existed on the server.

**Comment by matiu** [comment]
Hi, atm, only account 0 if supported. We plan to support bip44 accounts in
the near future, but it wont work now.

**Comment by jesskie** [comment]
That's my second wallet.I have imported the old one that's been hack by kazacktan national.

**Comment by matiu** [comment]
You can use our recovery tool to access other accounts.

**Comment by jesskie** [comment]
Tns

**Comment by jesskie** [comment]
Can u help me fixed it I've already recovered my old wallet

**Comment by jesskie** [comment]
Just messeged what I'm going to do

**Comment by BGalliotti** [comment]
Hello @jesskie 
Thanks for reaching out to us.

If your issue is related to the first one posted on this thread, please, post it explaining clearly what the issue is and bringing all the relevant information so we can properly address it, otherwise, please open a new issue [here](https://github.com/bitpay/copay/issues).

Kind regards.
