### ISSUE TITLE
Cash Account Integration

### ISSUE THREAD

**Issue by monsterbitar** [bitpay/copay#9401]
I am currently working on a specification for on-chain aliases that look like this: James#577821; to help convey payment information in a more convenient manner, particulary in verbal contexts.

The specification has undergone reasonable peer-review so far (by wallet developers, token developers, coinbase engineeers) but more feedback is always welcome.

Here's a link to the draft spec: https://gitlab.com/cash-accounts/specification/blob/master/SPECIFICATION.md

**Comment by imaginaryusername** [comment]
Will definitely love to see copay get in on the effort, and also work out a general BIP47 implementation.

**Comment by matiu** [comment]
We will integrate cash account only when we have a reusable address schema in place. We are currently studying whether BIP47 or Stealth address (or something else) will fix better with our wallet and users.

thanks for CashAddr! is a great step forward and we would love to have it in Copay. Closing this since we are using issues mainly for bug reports.
