### ISSUE TITLE
i can' t trasfer btc from my wallet to others

### ISSUE THREAD

**Issue by cristian8315** [bitpay/copay#9431]
i can't send my btc from my copay wallet to others, only in my copay wallet . Why???
id wallet 52e4dd15-f33b-40b2-a1bd-d0be5b173ded

thank you

**Comment by cristian8315** [comment]
> i can't send my btc from my copay wallet to others, only in my copay wallet . Why???
> id wallet 52e4dd15-f33b-40b2-a1bd-d0be5b173ded
> 
> thank you
![qqqq](https://user-images.githubusercontent.com/46249022/50541563-d8ba2580-0ba8-11e9-8d8a-7b1f75c09136.PNG)

**Comment by cristian8315** [comment]
why i can't found copay APP in Android store?

**Comment by BGalliotti** [comment]
Hello 

Thanks for reaching out to us.

> i can't send my btc from my copay wallet to others, only in my copay wallet . Why???

Are you still experiencing the issue?

> why i can't found copay APP in Android store?

Due to Google policies, the Copay app is no longer being distributed on their store, but on GitHub. You can find it **[here](https://github.com/bitpay/copay/releases)**.

Please let us know if you have any additional questions.

Kind regards.

**Comment by BGalliotti** [comment]
Hello @cristian8315 

**We have not heard from you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
