### ISSUE TITLE
Splash screen says unlock app

### ISSUE THREAD

**Issue by edgsys** [bitpay/copay#9449]
Can't open copay app screen says unlock app and scan again then fingerprint icon. Pls help.

**Comment by BGalliotti** [comment]
Hello @edgsys 
Thanks for reaching out to us.

> Can't open copay app screen says unlock app and scan again then fingerprint icon. Pls help.

We do not quite understand what your issue is.

- Do you have a PIN? (are you prompted to enter a PIN when opening the wallet)
- What happens if you scan your finger?
- In case the scan is successful, what happens after that?

Hello 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: On Android go to the system settings, Apps and look for Copay and check the app info.
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.

**We look forward to hearing from you.**
