### ISSUE TITLE
Network 403 error

### ISSUE THREAD

**Issue by norival1992** [bitpay/copay#9471]
I dont know what happen on my wallet it always said  403 red color (403 error i think it is forbidden error)
i tried to tap many times, but always failed.

Here is screenshot : http://prntscr.com/m7xy43 & http://prntscr.com/m7xy8a

I withdrawed around $450 to my wallet yesterday. Bad thing, today i cant use it to create my customers order.

**Comment by BGalliotti** [comment]
Hello @norival1992 

We are sorry you have had this bad experience.
We understand your situation, unfortunately, this error is due to your **Internet connection**.

Depending on which country you are, **CloudFlare,** our Content Delivery Network provider, might be blocking your request.

Please check out the following links for a list of countries that ban/prohibit/limit the use of cryptocurrencies:

- [Countries where the cryptocurrencies are banned](https://bitnewstoday.com/market/bitcoin/countries-where-the-cryptocurrencies-are-banned-busted-for-bitcoin/)
- [Bitcoin bans](http://bitcoinbans.com/).

*Note: these links are external resources not related to BitPay and we are not responsible nor for the content neither for its accuracy.*

If you are in a country that bans cryptocurrencies, do not panic, your funds are still in your wallet.

In case you are not located in any of the countries which ban cryptocurrencies, the only thing you can do is try a different connection. You might be behind a proxy server, or accessing through an IP that is somehow being rejected by the server.

**We can suggest you try:**

- Accessing the internet through a different network connection (friends, neighbors, work..).
- Using your mobile broadband connection (3G/4G/5G/..) instead of Wifi
- If you did not experience this issue before, please think about what might have changed (you have changed your Internet service provider/connection, your mobile/cable company, etc).
- Reach your internet service provider/phone/cable company technical support, and tell them about your problem, they should give you a solution.
- In case you are using a firewall or any internet traffic filtering software, make sure it is not blocking your connections. 

**If you still need to manage your funds, you can try using a third party wallet**

1) Choose a wallet app and install it. We do not have any suggestions and do not know exactly which wallets might work, however, you can check this [article](https://support.bitpay.com/hc/en-us/articles/115005701523-Which-wallets-work-for-a-BitPay-payment-Which-wallets-are-compatible-) to have an idea.
2) Import your wallet in the wallet app.

Here are some recommendations when importing the wallet:

- Look for importing/restoring/recovering options on the wallet app.
- You will need the wallet 12-word recovery phrase.
- Depending on the wallet, it may take a while for the funds to show up, this is normal.

**If you are experiencing an issue, here are some things that you can check:**

- Are you sure that the recovery phrase was written in the correct order?
- Did you use all lowercase letters and no punctuation?
- Did you add a password to your recovery phrase?
- [Do you have the QR code or text/file backup?](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-)
- Did you separate each word with a single space (no commas or any other punctuation)?

Also make sure:
**- Your phone is not using capitals for the first letter of the words**

**- You are not typing spaces:**

- before the first word
- more than one space between words
- After the last word

Please also ensure that your words are all contained in the following list of possible words:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
For other languages click [here](https://github.com/bitcoin/bips/blob/master/bip-0039).

3) Manage your funds.

**If you cannot access your wallet, you can still recover your funds by moving them to another wallet.**

Here is our recovery tool https://bitpay.github.io/copay-recovery/

Read this [article](https://blog.bitpay.com/bitcoin-cash-recovery/) to know how to use it.

Feel free to get back to us in case you have any questions or concerns.
Thank you for your interest and support.
