### ISSUE TITLE
transaction not recieved 

### ISSUE THREAD

**Issue by badmog** [bitpay/copay#9576]
transaction:
25b8eecf6314c659d3fce298aca1d97a13d3ebd1ab93da1cbab00ecdb454c826
wallet add : 1GBsrdKxxBXnzUqDqxJX7L5VnBgpnzRhMo

please resolve issue 

transaction confirmed from sender . blockchain confirmed

i have updated and imported my copay to new bitpay wallet  please deposit the new wallet with the missed funds sent previously to  copay wallet to my updated bitpay wallet updated wallet bitpay : 1MM8r2i93YWx4HxAM9qoDuuuhyHKFFbJqU old copay wallet : 163Fb5yXgRjcCyJfV9WvH7RfhTmHKZLrzQ

please resolve the issue of the missing transaction of 0.03280000
transaction:
25b8eecf6314c659d3fce298aca1d97a13d3ebd1ab93da1cbab00ecdb454c826

**Comment by badmog** [comment]
transaction confirmed from sender . blockchain confirmed

**Comment by badmog** [comment]
i have updated and imported my copay to new bitpay wallet please deposit the new wallet with the missed funds sent previously to copay wallet to my updated bitpay wallet 

updated wallet bitpay : 1MM8r2i93YWx4HxAM9qoDuuuhyHKFFbJqU

old copay wallet : 
163Fb5yXgRjcCyJfV9WvH7RfhTmHKZLrzQ

**Comment by badmog** [comment]
please resolve the issue of the missing transaction of 0.03280000
transaction:
25b8eecf6314c659d3fce298aca1d97a13d3ebd1ab93da1cbab00ecdb454c826

**Comment by BGalliotti** [comment]
Hello @badmog 
Thanks for reaching out to us.

We have checked the transaction and none of the destination addresses on that transaction belong to your wallet, then you will not see those funds in your wallet.

Please reach the sender if you were expecting to receive funds from them.

Let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @badmog 
Thanks for reaching out to us.

> i cant understand that . i just copied the bitcoin address and pasted it to the address space how comes it not my address ??!!

You must have used a different wallet as the destination addresses do not even belong to any BitPay wallet.
Your wallet can only generate addresses that belong to it, no wallet can generate addresses that don't belong to them or that belong to another wallet (otherwise we would be using other people's money).

> where did the funds go then ? 

There is no way to know that, anyone can see the addresses where the funds were sent on the transaction but there is no personal data bound to them.

> cant you order payment request or reverse the funds ?!

No, bitcoin transactions are not reversible. 
There is nothing we can do to request or claim payment.

This is a human-error case. Next time, to receive funds:

- Open the Copay/Bitpay app
- Select the wallet where you want to receive funds
- Tap **Receive**
- Scan the QR code or tap it to copy the address.

Please let us know if you have any additional questions.
Kind regards.
