### ISSUE TITLE
Copay support (waiting for confirmation)

### ISSUE THREAD

**Issue by alexbk718** [bitpay/copay#9617]
my transaction says received (receiving) for over 7 hours now. Is copay having some sort of issues??

**Comment by alexbk718** [comment]
usually confirmation is quick... never had an issue

**Comment by BGalliotti** [comment]
Hello @alexbk718 

Thank you for reaching out to us.

If you are receiving funds, unless they are coming from another Copay wallet, the problem is not on the Copay side.

To make sure what is going on, [check the transaction on the blockchain](https://insight.bitcore.io/).

If the transaction is confirmed and not showing up on your wallet, please [refresh](https://github.com/bitpay/copay/issues/8806).


Please let us know if you have any additional questions.
Kind regards.
