### ISSUE TITLE
Transaction not confirmed

### ISSUE THREAD

**Issue by lavachepourpre** [bitpay/copay#9626]
Hello. This is the first time for me a transaction takes  so long, 
7 hours now. This is : 6c4f0124c17cee0dc0b5ae1fcc76bf1958dfaf1adc06bb8203b07b20946c1385
I can wait but it blocks my entire wallet. What could I do ? Just wait ?

**Comment by fmonts** [comment]
I don't see that transaction: https://live.blockcypher.com/btc/tx/6c4f0124c17cee0dc0b5ae1fcc76bf1958dfaf1adc06bb8203b07b20946c1385

**Comment by fmonts** [comment]
found on blockchain.com, probably some nodes have already dropped it, anyway it has only 32 sat/B, as you can see right now to have a transaction confirmed you need at least 70/80+:
https://jochen-hoenicke.de/queue/#0,2d

you should always check the fee before doing a transaction, in the latest days the fees have increased a lot and the copay algorithm doesn't work very well

**Comment by BGalliotti** [comment]
Hello @lavachepourpre 
Thank you for reaching out to us.

The transaction has taken longer than usual due to the bitcoin network congestion.
When bitcoin price rises as it did it 1 week ago now, you might expect delays like yours and high fees. 

To learn more about this read this [post](https://github.com/bitpay/copay/issues/8803#issuecomment-398775441).

Kind regards.
