### ISSUE TITLE
help copay

### ISSUE THREAD

**Issue by apavee** [bitpay/copay#9634]
the following 2 transactions did not have a confirmation since 3 hours 

i have a copay wallet 

what should i do? 

b27188e473bbca3cd900796e64896da6ccfd419c5ad18422e63a30984f27849e
646807a8ba294c55a5ccef1f4b08e395656d013800fc1f9e1fb8a5b18a47e523

thanks

**Comment by BGalliotti** [comment]
Hello  @apavee 
Thank you for reaching out to us.

Both transactions are properly confirmed.
The transactions have taken longer than usual due to the bitcoin network congestion.
When bitcoin price rises as it did it 1 week ago now, you might expect delays like yours and high fees. 

To learn more about this read this [post](https://github.com/bitpay/copay/issues/8803#issuecomment-398775441).

Kind regards.
