### ISSUE TITLE
Could not update wallet: Network error.

### ISSUE THREAD

**Issue by tracyramone** [bitpay/copay#9637]
Hi,
I'm getting "Could not update wallet: Network error."
I have tried both scanning addresses and clearing cache.
I'm using v5.7.1 on Win10 (64-bit).
Please help.
Thanks

**Comment by BGalliotti** [comment]
Hello @tracyramone 
Thank you for reaching out to us.

Thank you for reaching out about the Network Error you are experiencing in your BitPay Wallet.  **Unfortunately, this error is usually due to your internet connection.** Your device may be using a proxy server or VPN, which may be rejected by BitPay’s server. 

We suggest you try the below to troubleshoot:

- Access the internet through a different network connection.
- Use mobile broadband connections (such as 3G/4G/5G) instead of wifi, or use wifi instead of mobile broadband. 
- Reach out to your internet service provider’s technical support.
- Make sure that any internet traffic filtering software (such as antivirus, firewall, or internet suites) is not blocking your connection.

Please let us know if you have any additional questions.
Kind regards.
