### ISSUE TITLE
Refund to copay wallet

### ISSUE THREAD

**Issue by yankeefan233** [bitpay/copay#9657]
Hello, i have recieved a refund from https://paybis.com to my copay wallet and they say there is a delay to see my payment in my account, any help please

**Comment by BGalliotti** [comment]
Hello @yankeefan233  
Thank you for reaching out to us.

As they have they have told you, told you there will be a delay, you may expect long delays due to Bitcoin network congestion.
You can check the transaction status on [insight](https://insight.bitcore.io/).
If the transaction was confirmed and the wallet was not showing it, please **[refresh the wallet](https://github.com/bitpay/copay/issues/8806#issuecomment-399074701)**.

To know why some transactions take a while to be confirmed,  please refer to [8712](https://github.com/bitpay/copay/issues/8712#issuecomment-392816250)

Please let us know if you have any additional questions.
Kind regards.
